"""Category: Advanced — advanced and low-level tweaks."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Advanced", win_default="7,8,10,11")
CATEGORY = "Advanced"

TWEAKS = validate_module("advanced", [
    T("adv-001", "Disable Meltdown Mitigation",
      "Disables the Meltdown mitigation for the CPU.",
      actions=[("cmd", "reg add HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management /v FeatureSettingsOverrideMask /t REG_DWORD /d 3 /f")],
      revert=[("cmd", "reg add HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management /v FeatureSettingsOverrideMask /t REG_DWORD /d 0 /f")],
      why="Removes the mitigation overhead on CPUs that are not realistically attacked on a gaming machine.",
      changes="Disables Meltdown/Spectre mitigations.",
      risk="safe", impact="moderate", recommended="optional", admin=True,
      tags=["meltdown", "spectre", "mitigation"]),
    T("adv-002", "Set Large System Cache",
      "Gives the system cache priority for file work.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "LargeSystemCache", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "LargeSystemCache", 0, "DWORD")],
      why="Larger cache helps file-heavy workloads at the cost of some memory for apps.",
      changes="Enables LargeSystemCache.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["cache", "memory", "system"]),
    T("adv-003", "Disable Insecure Guest Fallback",
      "Disables SMB guest fallback.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters", "AllowInsecureGuestAuth", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters", "AllowInsecureGuestAuth", 1, "DWORD")],
      why="Blocks insecure guest SMB fallback and its negotiation overhead.",
      changes="Disables SMB guest fallback.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["smb", "guest", "security"]),
    T("adv-004", "Disable Auto-Logging Metadata",
      "Guidance on NTFS metadata journaling.",
      actions=[("guidance", "Do not disable NTFS journaling on your OS drive — it protects against corruption. It is not a meaningful game performance cost.")],
      revert=[("guidance", "No change to revert.")],
      why="NTFS journaling is cheap and important for data safety.",
      changes="Shows NTFS guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["ntfs", "journal", "filesystem"]),
    T("adv-005", "Enable Write Caching",
      "Guidance on disk write caching.",
      actions=[("guidance", "Keep 'Enable write caching on the device' enabled in Disk Manager for NVMe/SSD drives — disabling it costs write performance for no gaming benefit.")],
      revert=[("guidance", "No change to revert.")],
      why="Write caching is essential to SSD performance.",
      changes="Shows write-cache guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["cache", "write", "disk"]),
    T("adv-006", "Set Processor Scheduling to Programs",
      "Prioritizes programs over background services.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\PriorityControl", "Win32PrioritySeparation", 26, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\PriorityControl", "Win32PrioritySeparation", 2, "DWORD")],
      why="Keeps foreground programs above background services in the scheduler.",
      changes="Sets Win32PrioritySeparation to 26.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["priority", "scheduler", "programs"]),
    T("adv-007", "Disable Credential Manager",
      "Disables the credential manager service.",
      actions=[("sc", "disable", "VaultSvc")],
      revert=[("sc", "enable", "VaultSvc")],
      why="Stops credential vault polling for users who rely on apps storing secrets elsewhere.",
      changes="Disables the Credential Manager service.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["credentials", "vault", "service"]),
    T("adv-008", "Disable Print Job History",
      "Disables print job history tracking.",
      actions=[("guidance", "In Print Management or via the spooler, disable 'log print jobs' audit settings if you do not need a print trail.")],
      revert=[("guidance", "Re-enable print job history.")],
      why="Reduces printer subsystem auditing overhead.",
      changes="Shows print-history guidance.",
      risk="safe", impact="very low", recommended="optional",
      tags=["print", "history", "audit"]),
    T("adv-009", "Disable Font Cache Service",
      "Disables the font cache service.",
      actions=[("sc", "disable", "FontCache")],
      revert=[("sc", "enable", "FontCache")],
      why="Saves a small resident service, but font rendering will re-cache.",
      changes="Disables FontCache.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["font", "cache", "service"]),
    T("adv-010", "Disable Indexing of Game Drives",
      "Guidance on drive indexing.",
      actions=[("guidance", "Remove game drives from Windows Search indexing (Settings > Search > Searching Windows) — indexing huge game folders causes periodic disk churn.")],
      revert=[("guidance", "Re-add the drive to indexing.")],
      why="Indexing re-scans changed files and spikes disk I/O.",
      changes="Shows indexing guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["index", "search", "disk"]),
    T("adv-011", "Disable Busy Wait Timer",
      "Guidance on the timer queue.",
      actions=[("guidance", "Do not force the system timer below 15.6ms manually. The timer queue is managed by apps; forcing it system-wide wastes CPU in idle loops.")],
      revert=[("guidance", "No change to revert.")],
      why="Manual timer forcing increases idle power and CPU wake-ups.",
      changes="Shows timer guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["timer", "queue", "idle"]),
    T("adv-012", "Disable Memory Compression",
      "Turns off memory compression.",
      actions=[("cmd", "powershell -NoProfile -Command \"Disable-MMAgent -MemoryCompression\"")],
      revert=[("cmd", "powershell -NoProfile -Command \"Enable-MMAgent -MemoryCompression\"")],
      why="Removes the compression CPU overhead on systems with ample RAM.",
      changes="Disables memory compression.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["memory", "compression", "ram"]),
])
