"""Category: AMD — Radeon driver and AMD Software guidance."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("AMD", win_default="7,8,10,11")
CATEGORY = "AMD"

TWEAKS = validate_module("amd", [
    T("amd-001", "Enable Radeon Anti-Lag",
      "Guidance to enable Radeon Anti-Lag in supported games.",
      actions=[("guidance", "Enable 'Radeon Anti-Lag' in AMD Software > Gaming for supported titles. It limits CPU render queue ahead, reducing input latency. Use Anti-Lag 2 where the game supports it.")],
      revert=[("guidance", "Disable Radeon Anti-Lag.")],
      why="Anti-Lag reduces the CPU/GPU queue gap that adds latency.",
      changes="Shows Anti-Lag guidance.",
      risk="safe", impact="high", recommended="recommended",
      when={"gpu": ["amd"]},
      tags=["antilag", "latency", "radeon"]),
    T("amd-002", "Enable Radeon Chill",
      "Guidance to cap FPS with Radeon Chill.",
      actions=[("guidance", "Set a min/max FPS cap with Radeon Chill in AMD Software. A stable cap just below your refresh rate avoids frame-time spikes from uncapped rates.")],
      revert=[("guidance", "Disable Radeon Chill.")],
      why="An FPS cap keeps frame times consistent instead of spiking.",
      changes="Shows Radeon Chill guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["amd"]},
      tags=["chill", "fpscap", "frametime"]),
    T("amd-003", "Image Sharpening Guidance",
      "Guidance on Radeon Image Sharpening.",
      actions=[("guidance", "Radeon Image Sharpening adds a sharpening pass. Use it sparingly (0-50%) — high values add visible artifacts and a small GPU cost.")],
      revert=[("guidance", "Disable Image Sharpening.")],
      why="Sharpening is a GPU post-pass; excess strength wastes performance.",
      changes="Shows image-sharpening guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["amd"]},
      tags=["sharpening", "image", "gpu"]),
    T("amd-004", "Disable FreeSync if Stuttering",
      "Guidance for FreeSync and VRR issues.",
      actions=[("guidance", "If a game stutters at low FPS, disable FreeSync (or cap above the FreeSync low range). Below the sync floor, FreeSync behaves like V-Sync and adds latency.")],
      revert=[("guidance", "Re-enable FreeSync.")],
      why="Running below the FreeSync range reintroduces tearing/VSync behavior.",
      changes="Shows FreeSync guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["amd"]},
      tags=["freesync", "vrr", "stutter"]),
    T("amd-005", "Driver Update via AMD Software",
      "Guidance to keep Radeon drivers current.",
      actions=[("guidance", "Update drivers through AMD Software (or the Adrenalin installer with 'Factory Reset' checked) to apply a clean driver state.")],
      revert=[("guidance", "Roll back the driver.")],
      why="Adrenalin releases fix new-game bugs and add tuning features.",
      changes="Shows driver-update guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["amd"]},
      tags=["driver", "adrenalin", "update"]),
    T("amd-006", "Disable Radeon Overlay",
      "Guidance to disable the in-game Radeon overlay.",
      actions=[("guidance", "In AMD Software, disable the in-game overlay if you do not use it. It adds a presentation hook over every game.")],
      revert=[("guidance", "Re-enable the overlay.")],
      why="The overlay hooks game presentation and can add a frame of cost.",
      changes="Shows overlay guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["amd"]},
      tags=["overlay", "radeon", "hook"]),
    T("amd-007", "Smart Access Memory Check",
      "Guidance to verify SAM is enabled.",
      actions=[("guidance", "Verify 'Smart Access Memory' (Resizable BAR) is on in AMD Software and that the motherboard BIOS has 'Above 4G decoding' and 'ReBAR' enabled. SAM lifts GPU memory efficiency.")],
      revert=[("guidance", "Disable SAM.")],
      why="SAM lets the CPU read the full GPU VRAM, raising effective bandwidth.",
      changes="Shows SAM guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["amd"], "intel_cpu": False},
      tags=["sam", "rebar", "vram"]),
    T("amd-008", "Radeon Boost Guidance",
      "Guidance on Radeon Boost dynamic resolution.",
      actions=[("guidance", "Radeon Boost lowers resolution during fast motion. Enable it only if you do not notice the resolution drop in competitive play.")],
      revert=[("guidance", "Disable Radeon Boost.")],
      why="Dynamic resolution changes can be distracting and alter image clarity mid-combat.",
      changes="Shows Radeon Boost guidance.",
      risk="safe", impact="low", recommended="optional",
      when={"gpu": ["amd"]},
      tags=["boost", "resolution", "dynamic"]),
    T("amd-009", "Surface Format Optimization",
      "Guidance on AMD surface format optimization.",
      actions=[("guidance", "Leave 'Surface Format Optimization' enabled in game profiles unless a specific title glitches — it reorders surface formats for faster rendering.")],
      revert=[("guidance", "Disable the per-game optimization.")],
      why="Surface format reordering reduces bandwidth on some engines.",
      changes="Shows surface-format guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["amd"]},
      tags=["surface", "format", "bandwidth"]),
    T("amd-010", "Tessellation Level Cap",
      "Guidance on capping tessellation in AMD profiles.",
      actions=[("guidance", "Set 'Tessellation Mode' to 'Override application settings' with a 16x cap if old titles over-tessellate, which tanks FPS on high-poly terrain.")],
      revert=[("guidance", "Restore 'AMD optimized' tessellation.")],
      why="Excessive tessellation spends GPU triangles on invisible detail.",
      changes="Shows tessellation guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["amd"]},
      tags=["tessellation", "geometry", "gpu"]),
    T("amd-011", "Shader Cache Management",
      "Guidance on the AMD shader cache size.",
      actions=[("guidance", "AMD Software lets you set shader cache size. Use 'AMD Optimized' or a larger cache on an SSD to avoid shader recompilation stutter in DX12 titles.")],
      revert=[("guidance", "Reset the shader cache size.")],
      why="A warm shader cache prevents compile hitches during gameplay.",
      changes="Shows shader-cache guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["amd"]},
      tags=["shaders", "cache", "compile"]),
    T("amd-012", "Disable Background Recording",
      "Guidance to stop Radeon ReLive background recording.",
      actions=[("guidance", "Turn off 'Instant Replay' and 'Record Desktop' in AMD Software > Recording when you are not capturing. The encoder keeps running otherwise.")],
      revert=[("guidance", "Re-enable Instant Replay.")],
      why="Constant background encoding consumes the video engine and bandwidth.",
      changes="Shows ReLive guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["amd"]},
      tags=["relive", "recording", "encode"]),
    T("amd-013", "Reset AMD Software Settings",
      "Guidance to reset Radeon settings.",
      actions=[("guidance", "If a game misbehaves, reset the game profile or 'Factory Reset' the settings in AMD Software to clear stale per-game overrides.")],
      revert=[("guidance", "No change to revert.")],
      why="Stale per-game profiles override global performance settings.",
      changes="Shows settings-reset guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["amd"]},
      tags=["reset", "settings", "profile"]),
    T("amd-014", "Radeon Super Resolution",
      "Guidance on RSR upscaling for unsupported games.",
      actions=[("guidance", "If a game lacks FSR, enable Radeon Super Resolution and render below native resolution — the driver upscales the output. Cap FPS to avoid upscale shimmer.")],
      revert=[("guidance", "Disable RSR.")],
      why="Driver-level upscaling frees GPU budget on unsupported titles.",
      changes="Shows RSR guidance.",
      risk="safe", impact="moderate", recommended="optional",
      when={"gpu": ["amd"]},
      tags=["rsr", "upscale", "fsr"]),
])
