"""Category: Audio — sound stack latency and behaviour optimizations."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Audio", win_default="7,8,10,11")
CATEGORY = "Audio"

TWEAKS = validate_module("audio", [
    T("audio-001", "Mute System Startup Sound",
      "Disables the Windows startup chime.",
      actions=[("reg", "HKCU", r"AppEvents\Schemes\Apps\.Default\SystemStart\.Default", "", "", "STRING")],
      revert=[("reg", "HKCU", r"AppEvents\Schemes\Apps\.Default\SystemStart\.Default", "", "startup", "STRING")],
      why="Removes the chime and its audio initialization burst on every boot.",
      changes="Mutes the startup sound.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["sound", "startup", "chime"]),
    T("audio-002", "Mute Notification Sounds",
      "Silences default notification sounds.",
      actions=[("reg", "HKCU", r"AppEvents\Schemes\Apps\.Default\Notification.Default\.Default", "", "", "STRING")],
      revert=[("reg", "HKCU", r"AppEvents\Schemes\Apps\.Default\Notification.Default\.Default", "", r"%SystemRoot%\Media\Windows Notify System Generic.wav", "EXPAND_STRING")],
      why="Removes audio pipeline work and distractions from background notifications.",
      changes="Clears the default notification sound file.",
      risk="safe", impact="low", recommended="recommended",
      tags=["sound", "notifications", "mute"]),
    T("audio-003", "High Priority Audio MMCSS Task",
      "Raises the MMCSS 'Audio' class scheduling priority.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Audio", "Priority", 4, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Audio", "Priority", 2, "DWORD")],
      why="Higher audio thread priority reduces audio processing jitter.",
      changes="Sets Audio task priority to 4.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["mmcss", "audio", "priority"]),
    T("audio-004", "High Priority Playback MMCSS Task",
      "Raises the MMCSS 'Playback' class scheduling priority.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Playback", "Priority", 4, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Playback", "Priority", 2, "DWORD")],
      why="Keeps audio playback threads responsive under CPU load.",
      changes="Sets Playback task priority to 4.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["mmcss", "playback", "priority"]),
    T("audio-005", "Audio Services Automatic",
      "Sets the Windows Audio and AudioEndpointBuilder services to automatic.",
      actions=[
          ("svc", "AudioSrv", "auto"),
          ("svc", "AudioEndpointBuilder", "auto"),
      ],
      revert=[
          ("svc", "AudioSrv", "manual"),
          ("svc", "AudioEndpointBuilder", "manual"),
      ],
      why="Ensures the audio stack is fully initialized before games launch.",
      changes="Sets audio services to automatic startup.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["audio", "service", "startup"]),
    T("audio-006", "Disable Spatial Audio",
      "Guidance to disable Windows Sonic spatial audio.",
      actions=[("guidance", "Open Sound settings for your output device and set 'Spatial sound' to 'Off'. Spatial processing adds a small CPU and latency cost with most game headsets.")],
      revert=[("guidance", "Re-enable spatial sound if wanted.")],
      why="Spatial audio processing adds overhead; most competitive players prefer raw stereo.",
      changes="Shows spatial audio guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["spatial", "sonic", "audio"]),
    T("audio-007", "Enable Exclusive Mode",
      "Guidance to enable audio exclusive mode for lower latency.",
      actions=[("guidance", "In Sound > device Properties > Advanced, enable 'Allow applications to take exclusive control of this device' and 'Give exclusive mode applications priority'. This lets games bypass the mixer pipeline.")],
      revert=[("guidance", "Disable exclusive mode.")],
      why="Exclusive mode skips the shared-mode mixer, cutting audio latency.",
      changes="Shows exclusive-mode guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["exclusive", "latency", "audio"]),
    T("audio-008", "Disable Audio Enhancements",
      "Guidance to turn off sound enhancements.",
      actions=[("guidance", "In Sound > device Properties > Enhancements, enable 'Disable all enhancements'. Loudness equalization and effects add DSP latency.")],
      revert=[("guidance", "Re-enable enhancements.")],
      why="DSP effects add buffering between the game and your ears.",
      changes="Shows enhancements guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["enhancements", "dsp", "audio"]),
    T("audio-009", "Set 48 kHz Default Format",
      "Guidance to set the audio format to 48 kHz.",
      actions=[("guidance", "In Sound > device Properties > Advanced set the default format to 48 kHz (or your headset's native rate). Avoid higher rates that force unnecessary resampling.")],
      revert=[("guidance", "Restore the previous format.")],
      why="48 kHz matches most game audio content, avoiding resampling work.",
      changes="Shows default-format guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["format", "khz", "resample"]),
    T("audio-010", "Disable Audio Device Power Savings",
      "Guidance to prevent the audio device from sleeping.",
      actions=[("guidance", "In Device Manager > Sound, video and game controllers > device > Power Management, uncheck 'Allow the computer to turn off this device' to stop audio dropouts.")],
      revert=[("guidance", "Re-enable device power management.")],
      why="Audio devices that sleep cause the first-sound-after-idle crackle.",
      changes="Shows audio power guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["power", "sleep", "audio"]),
    T("audio-011", "Disable 'Start Audio Service on Demand'",
      "Keeps the audio service warm at all times.",
      actions=[("guidance", "If you use audio-heavy apps, keep the Windows Audio service running (it already is in the applied audio tweaks) rather than triggering it on demand at game launch.")],
      revert=[("guidance", "No change to revert.")],
      why="On-demand audio start can stutter the first game launch of the session.",
      changes="Shows audio-on-demand guidance.",
      risk="safe", impact="very low", recommended="optional",
      tags=["service", "ondemand", "audio"]),
    T("audio-012", "Audio Latency Report",
      "Checks the audio output devices and default format.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-CimInstance Win32_SoundDevice | Format-Table Name,Status -AutoSize\"")],
      revert=[("guidance", "Read-only report.")],
      why="Confirms your intended device is the default and error-free.",
      changes="Shows the audio device report.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["report", "device", "audio"]),
])
