"""Category: Background — background apps and idle processing."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Background", win_default="10,11")
CATEGORY = "Background"

TWEAKS = validate_module("background", [
    T("bg-001", "Block Background Apps",
      "Stops background apps from running when not focused.",
      actions=[
          ("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\AppPrivacy", "LetAppsRunInBackground", 2, "DWORD"),
      ],
      revert=[
          ("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\AppPrivacy", "LetAppsRunInBackground", 0, "DWORD"),
      ],
      why="Background apps poll, sync and wake CPUs while you play.",
      changes="Blocks background app execution.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["background", "apps", "policy"]),
    T("bg-002", "Disable Background Intelligence Transfers",
      "Disables BITS background transfers.",
      actions=[("sc", "disable", "BITS")],
      revert=[("sc", "enable", "BITS")],
      why="BITS downloads updates silently in the background, spiking network/disk.",
      changes="Disables BITS.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["bits", "transfer", "network"]),
    T("bg-003", "Pause Windows Update During Play",
      "Guidance to pause updates.",
      actions=[("guidance", "Pause Windows updates (Settings > Windows Update > Pause) before long sessions. Update staging can consume disk, network and CPU mid-game.")],
      revert=[("guidance", "Resume Windows updates.")],
      why="Update download+install is a common mid-game resource spike.",
      changes="Shows update-pause guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["update", "pause", "background"]),
    T("bg-004", "Disable Background Printing",
      "Guidance for print spooler background work.",
      actions=[("guidance", "With no printer attached, the spooler is idle but present. The service tweak disables it; otherwise ignore it.")],
      revert=[("guidance", "No change to revert.")],
      why="An idle spooler has negligible cost; the tweak is for security.",
      changes="Shows spooler guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["spooler", "background", "printer"]),
    T("bg-005", "Reduce Disk Prefetch Churn",
      "Guidance to limit background disk scanning.",
      actions=[("guidance", "Exclude game folders from Defender real-time scans (Windows Security > Virus & threat protection > Exclusions) to stop constant game-file scanning.")],
      revert=[("guidance", "Remove the exclusions.")],
      why="Real-time antivirus scanning of large game folders hits disk and CPU.",
      changes="Shows Defender-exclusion guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["defender", "exclusion", "disk"]),
    T("bg-006", "Disable Cloud Sync for Game Folders",
      "Guidance on OneDrive and game folders.",
      actions=[("guidance", "Never put game install folders under OneDrive/Desktop. Cloud sync rewrites files while the game reads them, causing hitches and corruption.")],
      revert=[("guidance", "No change to revert.")],
      why="Cloud-backed folders reintroduce sync latency to every file read.",
      changes="Shows OneDrive-folder guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["onedrive", "sync", "folders"]),
    T("bg-007", "Disable SmartScreen",
      "Disables SmartScreen for apps and files.",
      actions=[
          ("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer", "SmartScreenEnabled", "Off", "STRING"),
      ],
      revert=[
          ("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer", "SmartScreenEnabled", "RequireAdmin", "STRING"),
      ],
      why="Skips the reputation check that adds a delay to app launches.",
      changes="Disables SmartScreen.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["smartscreen", "security", "launch"]),
    T("bg-008", "Disable Sync for Non-Store Apps",
      "Guidance to stop app sync backgrounding.",
      actions=[("guidance", "In Settings > Accounts > Windows backup, disable sync for non-essential settings/apps to remove its background polling.")],
      revert=[("guidance", "Re-enable sync.")],
      why="Settings sync polls the cloud at sign-in and periodically.",
      changes="Shows sync guidance.",
      risk="safe", impact="very low", recommended="optional",
      tags=["sync", "backup", "settings"]),
    T("bg-009", "Disable Tips and Suggestions",
      "Disables Windows tips background suggestions.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SoftLandingEnabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SoftLandingEnabled", 1, "DWORD")],
      why="Removes the background tip/suggestion polling.",
      changes="Disables tips and suggestions.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["tips", "suggestions", "background"]),
    T("bg-010", "Disable Automatic Update Reboots",
      "Guidance to control update reboot timing.",
      actions=[("guidance", "Set 'Active hours' in Windows Update so the system does not reboot mid-session, and disable automatic restarts during game time.")],
      revert=[("guidance", "Restore default active hours.")],
      why="An auto-reboot mid-match loses progress and settings.",
      changes="Shows active-hours guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["reboot", "update", "activehours"]),
])
