"""Category: BIOS — motherboard firmware guidance."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("BIOS", win_default="7,8,10,11")
CATEGORY = "BIOS"

TWEAKS = validate_module("bios", [
    T("bios-001", "Check BIOS Version",
      "Shows the current BIOS version.",
      actions=[("cmd", "powershell -NoProfile -Command Get-CimInstance Win32_BIOS | Select-Object SMBIOSBIOSVersion,ReleaseDate,Manufacturer")],
      revert=[("guidance", "No change to revert.")],
      why="Confirms the firmware level before updating.",
      changes="Reports the BIOS version.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["bios", "version", "firmware"]),
    T("bios-002", "Enable XMP/EXPO",
      "Guidance to enable memory overclock profiles.",
      actions=[("guidance", "In BIOS, enable XMP (Intel) or EXPO (AMD) for your RAM to run at its rated speed. Most memory ships at JEDEC defaults (2133-4800MT/s) until XMP is on.")],
      revert=[("guidance", "Disable XMP/EXPO.")],
      why="JEDEC-default memory silently caps CPU performance.",
      changes="Shows XMP guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["xmp", "expo", "memory"]),
    T("bios-003", "Enable Resizable BAR",
      "Guidance to enable ReBAR.",
      actions=[("guidance", "In BIOS, enable 'Above 4G Decoding' and 'Resizable BAR' (ReBAR). AMD SAM is the same feature. ReBAR helps modern GPUs and is required for Intel Arc full performance.")],
      revert=[("guidance", "Disable ReBAR.")],
      why="ReBAR lets the CPU access the full GPU VRAM.",
      changes="Shows ReBAR guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["rebar", "sam", "vram"]),
    T("bios-004", "Enable UEFI Only",
      "Guidance to use UEFI instead of legacy BIOS.",
      actions=[("guidance", "Boot in UEFI mode (disable CSM) for Secure Boot and faster boot. Reinstalling Windows is required if the disk is in legacy MBR layout.")],
      revert=[("guidance", "Re-enable CSM.")],
      why="UEFI boots faster and enables modern security features.",
      changes="Shows UEFI guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["uefi", "csm", "secureboot"]),
    T("bios-005", "Set Custom Fan Curves",
      "Guidance for fan curve tuning.",
      actions=[("guidance", "Set an aggressive fan curve for the CPU and GPU in BIOS/software so cooling ramps before thermal throttle, not after.")],
      revert=[("guidance", "Restore the default fan curve.")],
      why="Responsive fans prevent the thermal dips that cause frame-time spikes.",
      changes="Shows fan-curve guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["fan", "curve", "cooling"]),
    T("bios-006", "Enable TPM",
      "Guidance to enable the TPM.",
      actions=[("guidance", "Enable 'Intel PTT' (Intel) or 'AMD fTPM' in BIOS. TPM 2.0 is required for Windows 11, BitLocker and some anti-cheat (e.g. Vanguard).")],
      revert=[("guidance", "Disable the TPM.")],
      why="A missing TPM blocks Windows 11 and game anti-cheat.",
      changes="Shows TPM guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["tpm", "firmware", "security"]),
    T("bios-007", "Disable Fast Boot",
      "Guidance to disable BIOS fast boot for stability.",
      actions=[("guidance", "If USB devices do not wake reliably or drives are missed, disable 'Fast Boot' in the BIOS — it skips initialization some devices need.")],
      revert=[("guidance", "Re-enable Fast Boot.")],
      why="Fast Boot skips peripheral init that some hardware requires.",
      changes="Shows fast-boot guidance.",
      risk="safe", impact="very low", recommended="optional",
      tags=["fastboot", "bios", "usb"]),
    T("bios-008", "Update BIOS",
      "Guidance to update the motherboard firmware.",
      actions=[("guidance", "Update the BIOS via the vendor's USB-flash tool (never inside Windows on some boards). Updates fix memory training, ReBAR and CPU microcode bugs.")],
      revert=[("guidance", "Roll back the BIOS.")],
      why="BIOS updates fix the memory and boost bugs no OS tweak can.",
      changes="Shows BIOS-update guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["bios", "update", "firmware"]),
    T("bios-009", "Disable Integrated GPU",
      "Guidance to disable the iGPU on desktops.",
      actions=[("guidance", "On desktops with a discrete GPU, disable the iGPU in BIOS (or set primary display to the discrete card) to free memory bandwidth.")],
      revert=[("guidance", "Re-enable the iGPU.")],
      why="A live iGPU splits some frame timing on specific boards.",
      changes="Shows iGPU guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["igpu", "discrete", "display"]),
    T("bios-010", "Enable Virtualization",
      "Guidance to enable SVM/VT-x.",
      actions=[("guidance", "Enable 'SVM' (AMD) or 'Intel VT-x' in BIOS. Required for WSL2, Windows Sandbox, and some anti-cheat that checks virtualization.")],
      revert=[("guidance", "Disable virtualization.")],
      why="Virtualization must be on for VBS-based anti-cheat and hypervisor tools.",
      changes="Shows virtualization guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["virtualization", "svm", "vtx"]),
    T("bios-011", "Reset CMOS",
      "Guidance to reset the BIOS to defaults.",
      actions=[("guidance", "If the PC fails to POST after BIOS changes, clear CMOS (motherboard jumper/button or remove the battery for 30 seconds) to restore safe defaults.")],
      revert=[("guidance", "No change to revert.")],
      why="A CMOS reset recovers from failed memory or CPU settings.",
      changes="Shows CMOS-reset guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["cmos", "reset", "post"]),
    T("bios-012", "Memory Training Note",
      "Guidance on first-boot memory training.",
      actions=[("guidance", "New RAM (or an XMP profile change) triggers memory training: the first few boots may be slow. Let it complete; it is normal and does not persist.")],
      revert=[("guidance", "No change to revert.")],
      why="Training iterations stabilize timings; interrupting them can fail POST.",
      changes="Shows memory-training guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["memory", "training", "xmp"]),
])
