"""Category: CPU — processor scheduling, boost, power and mitigation settings."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("CPU", win_default="7,8,10,11")

CATEGORY = "CPU"

TWEAKS = validate_module("cpu", [
    T(
        "cpu-001", "High Performance Power Plan",
        "Activates the built-in High Performance Windows power plan.",
        actions=[("powerscheme", "setactive", "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c")],
        revert=[("powerscheme", "setactive", "381b4222-f694-41f0-9685-ff5bb260df2e")],
        why="Prevents the scheduler from aggressively down-clocking the CPU, which reduces frame-time spikes in CPU-bound games.",
        changes="Sets the active power scheme to High Performance.",
        risk="safe", impact="high", recommended="recommended", admin=True,
        tags=["power", "plan", "cpu", "clockspeed", "boost"],
    ),
    T(
        "cpu-002", "Ultimate Performance Power Plan",
        "Creates and activates the Ultimate Performance power plan (where available).",
        actions=[("powerscheme", "setactive", "e9a42b02-d5df-448d-aa00-03f14749eb61")],
        revert=[("powerscheme", "setactive", "381b4222-f694-41f0-9685-ff5bb260df2e")],
        why="Removes remaining power throttling paths on desktop PCs; strongest gains on modern CPUs.",
        changes="Activates the Ultimate Performance scheme.",
        risk="low", impact="extreme", recommended="recommended", admin=True,
        win="10,11", tags=["power", "plan", "ultimate", "cpu"],
    ),
    T(
        "cpu-005", "Aggressive Performance Boost Mode",
        "Sets the processor performance boost mode to Aggressive.",
        actions=[("power", "boost_mode", 2)],
        revert=[("power", "boost_mode", 0)],
        why="Allows single-core boost to run higher more often — important for frame consistency in CPU-heavy shooters.",
        changes="Changes the boost mode policy on AC power.",
        risk="low", impact="high", recommended="recommended", admin=True,
        tags=["boost", "boostmode", "turbo"],
    ),
    T(
        "cpu-007", "Disable CPU Core Parking (Power Scheme)",
        "Sets processor core parking min cores to 0 and min core percentage to 0.",
        actions=[
            ("cmd", "powercfg /setacvalueindex SCHEME_CURRENT 0cc5b647-c1df-4637-891a-dec35c318583 0cc5b647-c1df-4637-891a-dec35c318583 0"),
            ("cmd", "powercfg /setacvalueindex SCHEME_CURRENT 0cc5b647-c1df-4637-891a-dec35c318583 0cc5b647-c1df-4637-891a-dec35c318583 0"),
        ],
        revert=[
            ("cmd", "powercfg /setacvalueindex SCHEME_CURRENT 0cc5b647-c1df-4637-891a-dec35c318583 0cc5b647-c1df-4637-891a-dec35c318583 100"),
        ],
        why="Core parking can briefly leave a waking core unavailable; unparking keeps all cores ready for the scheduler.",
        changes="Removes core-parking thresholds from the active power scheme.",
        risk="low", impact="moderate", recommended="recommended", admin=True,
        win="7,8,10", tags=["parking", "core", "scheduler"],
    ),
    T(
        "cpu-008", "Disable CPU Core Parking (Registry override)",
        "Disables core parking through the processor performance core parking min cores value.",
        actions=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Processor", "CapParkedCores", 1, "DWORD")],
        revert=[("regdel", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Processor", "CapParkedCores")],
        why="Registry-level parking cap of 1 core prevents Windows from deep-parking cores.",
        changes="Adds CapParkedCores=1 to the processor control key.",
        risk="low", impact="moderate", recommended="optional", admin=True,
        win="7,8,10", tags=["parking", "registry"],
    ),
    T(
        "cpu-009", "Disable CPU Idle States (C-States)",
        "Forces the processor to stay in C0/C1 by disabling deeper idle states via registry.",
        actions=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Processor\\Power", "CStateEnabled", 0, "DWORD")],
        revert=[("regdel", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Processor\\Power", "CStateEnabled")],
        why="Deeper C-states add wake latency. Disabling them can smooth frame times at the cost of idle power.",
        changes="Disables deeper C-states through the processor power control key.",
        risk="moderate", impact="high", recommended="optional", admin=True, confirm=True,
        tags=["cstate", "idle", "latency"],
    ),
    T(
        "cpu-010", "Disable HPET Device",
        "Disables the High Precision Event Timer device in Device Manager.",
        actions=[("cmd", "bcdedit /set useplatformclock false")],
        revert=[("cmd", "bcdedit /deletevalue useplatformclock")],
        why="A faulty HPET can introduce timer latency; letting the CPU use its own TSC-based timers is usually faster.",
        changes="Disables the platform clock so the OS uses TSC-derived time.",
        risk="moderate", impact="high", recommended="optional", admin=True, confirm=True,
        win="7,8,10,11", tags=["hpet", "timer", "latency"],
    ),
    T(
        "cpu-011", "Disabled Dynamic Tick",
        "Disables the Windows dynamic tick which lets the timer be stopped in idle.",
        actions=[("cmd", "bcdedit /set disabledynamictick yes")],
        revert=[("cmd", "bcdedit /set disabledynamictick no")],
        why="With dynamic tick, timer interrupts fire irregularly. Disabling it can improve frame pacing.",
        changes="Sets the dynamic tick boot option to disabled.",
        risk="low", impact="moderate", recommended="recommended", admin=True,
        tags=["tick", "timer", "interrupt"],
    ),
    T(
        "cpu-012", "Reduced Timer Slack",
        "Removes the default 50 ms timer slack added by Windows to batch timer callbacks.",
        actions=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\kernel", "TimerSlack", 0, "DWORD")],
        revert=[("regdel", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\kernel", "TimerSlack")],
        why="Less timer slack means Windows wakes more promptly, tightening frame pacing.",
        changes="Sets kernel TimerSlack to 0.",
        risk="low", impact="moderate", recommended="recommended", admin=True,
        tags=["timer", "slack", "latency"],
    ),
    T(
        "cpu-013", "MMCSS Gaming Priority",
        "Configures the Multimedia Class Scheduler Gaming priority for pro audio/game classes.",
        actions=[
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile", "SystemResponsiveness", 0, "DWORD"),
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile", "NetworkThrottlingIndex", 0xffffffff, "DWORD"),
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "GPU Priority", 8, "DWORD"),
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "Priority", 6, "DWORD"),
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "Scheduling Category", "High", "STRING"),
        ],
        revert=[
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile", "SystemResponsiveness", 20, "DWORD"),
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile", "NetworkThrottlingIndex", 10, "DWORD"),
            ("regdel", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "GPU Priority"),
            ("regdel", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "Priority"),
            ("regdel", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "Scheduling Category"),
        ],
        why="Reserves less CPU time for system responsiveness and boosts the Games MMCSS class priority for lower input latency.",
        changes="Adjusts Multimedia Class Scheduler settings for the Games class.",
        risk="low", impact="high", recommended="recommended", admin=True,
        tags=["mmcss", "priority", "latency", "scheduler"],
    ),
    T(
        "cpu-014", "Processor Performance Increase Threshold",
        "Sets the processor performance increase threshold to a low value so boosts engage quickly.",
        actions=[("power", "perf_increase_threshold", 10)],
        revert=[("power", "perf_increase_threshold", 90)],
        why="A lower threshold makes the CPU boost sooner, reducing on-demand stall under sudden game load.",
        changes="Lowers the AC performance increase threshold to 10%.",
        risk="safe", impact="moderate", recommended="recommended", admin=True,
        tags=["boost", "threshold", "responsiveness"],
    ),
    T(
        "cpu-015", "Processor Performance Decrease Threshold",
        "Sets the processor performance decrease threshold to 100 so cores stop throttling only when truly idle.",
        actions=[("power", "perf_decrease_threshold", 100)],
        revert=[("power", "perf_decrease_threshold", 10)],
        why="Keeps clocks high while frames are still being produced instead of dropping clocks early.",
        changes="Raises the AC performance decrease threshold to 100%.",
        risk="safe", impact="low", recommended="recommended", admin=True,
        tags=["threshold", "clockspeed", "drop"],
    ),
    T(
        "cpu-016", "Win32 Priority Separation 26",
        "Lowers Windows' default 2-second foreground boost factor to reduce priority instability.",
        actions=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\PriorityControl", "Win32PrioritySeparation", 26, "DWORD")],
        revert=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\PriorityControl", "Win32PrioritySeparation", 2, "DWORD")],
        why="Priority separation 26 keeps foreground boost short so game threads keep consistent priority.",
        changes="Sets Win32PrioritySeparation to 26 (short boost, variable quantum).",
        risk="moderate", impact="moderate", recommended="optional", admin=True,
        tags=["priority", "foreground", "quantum"],
    ),
    T(
        "cpu-018", "Hardware Scheduling (GPU) Off for Old CPUs",
        "Turns off hardware-accelerated GPU scheduling to avoid scheduling stalls on older CPUs.",
        actions=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers", "HwSchMode", 2, "DWORD")],
        revert=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers", "HwSchMode", 1, "DWORD")],
        why="On some platforms HAGS adds overhead; disabling it returns scheduling to the driver on aging CPUs.",
        changes="Sets HwSchMode to 2 (off).",
        risk="low", impact="moderate", recommended="optional", admin=True,
        when={"cpu_cores": {"<=": 6}},
        tags=["hags", "scheduling", "gpu"],
    ),
    T(
        "cpu-019", "Processor Minimum Performance State 100%",
        "Locks the AC processor minimum performance state to 100% so the CPU never down-clocks to its lowest P-state.",
        actions=[("power", "processor_min", 100)],
        revert=[("power", "processor_min", 5)],
        why="A 100% performance floor keeps all cores ready at high clock, removing the up-clock ramp delay when a burst of work arrives.",
        changes="Sets the AC processor performance floor to 100%.",
        risk="low", impact="moderate", recommended="recommended", admin=True,
        tags=["power", "pstate", "clockspeed", "floor"],
    ),
    T(
        "cpu-020", "Processor Maximum Performance State 100%",
        "Ensures the AC processor maximum performance state stays at 100% so Windows never caps the CPU clock.",
        actions=[("power", "processor_max", 100)],
        revert=[("power", "processor_max", 100)],
        why="Some power plans cap the maximum state below 100%, which silently limits boost; this removes that ceiling.",
        changes="Sets the AC processor maximum performance state to 100%.",
        risk="safe", impact="low", recommended="recommended", admin=True,
        tags=["power", "pstate", "clockspeed", "ceiling"],
    ),
    T(
        "cpu-021", "Performance Increase Policy: Rocket",
        "Switches the processor performance increase policy to Rocket, which raises several cores together under load.",
        actions=[("power", "perf_increase_policy", 2)],
        revert=[("power", "perf_increase_policy", 1)],
        why="Rocket policy ramps the whole core package more aggressively than the default Ideal policy, cutting response latency in games.",
        changes="Sets the AC performance increase policy to Rocket.",
        risk="low", impact="moderate", recommended="recommended", admin=True,
        tags=["power", "policy", "boost", "responsiveness"],
    ),
    T(
        "cpu-022", "Performance Decrease Policy: Rocket",
        "Sets the processor performance decrease policy to Rocket so the clock only drops when the whole package is idle.",
        actions=[("power", "perf_decrease_policy", 2)],
        revert=[("power", "perf_decrease_policy", 1)],
        why="Rocket decrease keeps clocks high while any core is active, avoiding premature down-clocking between frame spikes.",
        changes="Sets the AC performance decrease policy to Rocket.",
        risk="low", impact="low", recommended="recommended", admin=True,
        tags=["power", "policy", "clockspeed", "scheduler"],
    ),
    T(
        "cpu-023", "Processor Boost Policy 100%",
        "Sets the processor performance boost policy ceiling to 100% so boost is allowed across all cores when the thermal budget permits.",
        actions=[("power", "boost_policy", 100)],
        revert=[("power", "boost_policy", 100)],
        why="A 100% boost policy ensures the CPU can reach its full multi-core boost instead of capping below the ceiling.",
        changes="Sets the AC processor boost policy to 100%.",
        risk="safe", impact="low", recommended="recommended", admin=True,
        tags=["power", "boost", "boostpolicy", "cpu"],
    ),
    T(
        "cpu-024", "Maximum Energy Performance Preference",
        "Sets the Energy Performance Preference (EPP) to 0, biasing efficiency cores toward maximum performance over power saving.",
        actions=[("power", "epp", 0)],
        revert=[("power", "epp", 50)],
        why="On newer Intel CPUs the efficiency cores use EPP to decide how aggressively to down-clock; 0 keeps them performance-oriented.",
        changes="Sets the AC energy performance preference to 0.",
        risk="low", impact="moderate", recommended="optional", admin=True,
        win="10,11", tags=["power", "epp", "efficiency", "clockspeed"],
    ),
    T(
        "cpu-025", "Disable Processor Idle Entry",
        "Disables the processor idle state entry so the CPU stops cycling into C-states on AC power.",
        actions=[("power", "idle_disable", 1)],
        revert=[("power", "idle_disable", 0)],
        why="Disabling idle entry keeps the CPU in a ready state, trimming the wake latency that C-state cycling can add.",
        changes="Disables processor idle entry on AC power.",
        risk="moderate", impact="high", recommended="optional", admin=True, confirm=True,
        tags=["power", "cstate", "idle", "latency"],
    ),
    T(
        "cpu-026", "Aggressive Idle Time Check",
        "Shortens the processor idle time check so the CPU resumes full performance faster after an idle period.",
        actions=[("power", "time_check", 10)],
        revert=[("power", "time_check", 20)],
        why="A shorter idle time check means the OS re-evaluates load sooner, reducing the delay before clocks ramp back up.",
        changes="Sets the AC processor idle time check to 10.",
        risk="low", impact="moderate", recommended="optional", admin=True,
        tags=["power", "idle", "responsiveness", "clockspeed"],
    ),
    T(
        "cpu-027", "Core Parking Minimum Cores 0",
        "Sets the processor core parking minimum cores to 0 so Windows is never forced to keep cores parked.",
        actions=[("power", "parking_min", 0)],
        revert=[("power", "parking_min", 100)],
        why="Zeroing the forced parking minimum lets every core stay available to the scheduler, avoiding park/wake stalls.",
        changes="Sets the AC core parking minimum cores to 0%.",
        risk="low", impact="moderate", recommended="recommended", admin=True,
        tags=["power", "parking", "core", "scheduler"],
    ),
    T(
        "cpu-028", "Core Parking Maximum Cores 100%",
        "Sets the processor core parking maximum cores to 100% so Windows may keep all cores unparked.",
        actions=[("power", "parking_max", 100)],
        revert=[("power", "parking_max", 0)],
        why="A 100% parking ceiling stops the OS from parking a large share of cores, keeping the full thread pool hot.",
        changes="Sets the AC core parking maximum cores to 100%.",
        risk="low", impact="moderate", recommended="recommended", admin=True,
        tags=["power", "parking", "core", "scheduler"],
    ),
    T(
        "cpu-029", "Faster Performance Increase Time",
        "Lowers the processor performance increase time so the CPU ramps clocks almost immediately under load.",
        actions=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PERFINCTIME 1")],
        revert=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PERFINCTIME 3")],
        why="The default 3 ms increase time adds a small ramp delay; 1 ms makes boost feel instant in CPU-bound moments.",
        changes="Sets the AC performance increase time to 1 ms.",
        risk="safe", impact="moderate", recommended="recommended", admin=True,
        tags=["powercfg", "ramp", "boost", "clockspeed"],
    ),
    T(
        "cpu-030", "Longer Performance Decrease Time",
        "Raises the processor performance decrease time so clocks stay elevated longer before throttling back.",
        actions=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PERFDECTIME 10")],
        revert=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PERFDECTIME 3")],
        why="Holding high clocks a little longer avoids the clock-drop bounce between frames in uneven workloads.",
        changes="Sets the AC performance decrease time to 10 ms.",
        risk="safe", impact="low", recommended="recommended", admin=True,
        tags=["powercfg", "clockspeed", "ramp", "stability"],
    ),
    T(
        "cpu-031", "Delayed Idle Promote Hysteresis",
        "Raises the idle promote hysteresis so cores stay in shallow idle states instead of sinking into deep C-states.",
        actions=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR IDLEPROMOTE 100")],
        revert=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR IDLEPROMOTE 60")],
        why="A higher promote threshold keeps wake costs low when the workload is bursty, reducing C-state wake latency.",
        changes="Sets the AC idle promote hysteresis to 100.",
        risk="low", impact="moderate", recommended="optional", admin=True,
        tags=["powercfg", "cstate", "idle", "latency"],
    ),
    T(
        "cpu-032", "Immediate Idle Demote",
        "Lowers the idle demote hysteresis so cores leave deep idle states at the first sign of load.",
        actions=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR IDLEDEMOTE 0")],
        revert=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR IDLEDEMOTE 60")],
        why="A demote threshold of 0 wakes parked or sleeping cores faster, cutting the stall when work suddenly arrives.",
        changes="Sets the AC idle demote hysteresis to 0.",
        risk="low", impact="moderate", recommended="optional", admin=True,
        tags=["powercfg", "idle", "wake", "latency"],
    ),
    T(
        "cpu-033", "Disable Intel Processor Power Driver",
        "Disables the Intelppm processor power-management driver so Intel CPUs run without driver-driven P-state throttling.",
        actions=[("svc", "intelppm", "disabled"), ("svcstop", "intelppm")],
        revert=[("svc", "intelppm", "auto"), ("svcstart", "intelppm")],
        why="Bypassing Intelppm can keep clocks at the base frequency instead of dropping under aggressive power rules (may increase heat and noise).",
        changes="Disables and stops the intelppm driver service.",
        risk="moderate", impact="high", recommended="experimental", admin=True, confirm=True,
        win="7,8,10", tags=["service", "intelppm", "power", "clockspeed"],
    ),
    T(
        "cpu-034", "Disable AMD Processor Power Driver",
        "Disables the AmdPPM processor power-management driver so AMD CPUs run without driver-driven P-state throttling.",
        actions=[("svc", "AmdPPM", "disabled"), ("svcstop", "AmdPPM")],
        revert=[("svc", "AmdPPM", "auto"), ("svcstart", "AmdPPM")],
        why="Bypassing AmdPPM can prevent aggressive down-clocking on desktop Ryzen parts, at the cost of idle power.",
        changes="Disables and stops the AmdPPM driver service.",
        risk="moderate", impact="high", recommended="experimental", admin=True, confirm=True,
        win="7,8,10", tags=["service", "amdppm", "power", "clockspeed"],
    ),
    T(
        "cpu-035", "Disable Telemetry Service",
        "Disables and stops the Connected User Experiences and Telemetry (DiagTrack) service to cut background CPU use.",
        actions=[("svc", "DiagTrack", "disabled"), ("svcstop", "DiagTrack")],
        revert=[("svc", "DiagTrack", "auto"), ("svcstart", "DiagTrack")],
        why="DiagTrack periodically uploads telemetry in the background; disabling it frees CPU cycles and reduces disk activity.",
        changes="Disables and stops DiagTrack.",
        risk="safe", impact="low", recommended="optional", admin=True,
        win="10,11", tags=["service", "telemetry", "background", "cpu"],
    ),
    T(
        "cpu-036", "Disable Windows Search Indexer",
        "Disables and stops the Windows Search service to stop background indexer CPU and disk churn.",
        actions=[("svc", "WSearch", "disabled"), ("svcstop", "WSearch")],
        revert=[("svc", "WSearch", "delayed"), ("svcstart", "WSearch")],
        why="The indexer periodically rescans files; disabling it keeps CPU and I/O available for active work (search results lose live indexing).",
        changes="Disables and stops WSearch.",
        risk="safe", impact="low", recommended="optional", admin=True,
        tags=["service", "search", "indexer", "cpu"],
    ),
    T(
        "cpu-037", "Disable Program Compatibility Assistant",
        "Disables and stops the Program Compatibility Assistant service so it no longer watches applications in the background.",
        actions=[("svc", "PcaSvc", "disabled"), ("svcstop", "PcaSvc")],
        revert=[("svc", "PcaSvc", "auto"), ("svcstart", "PcaSvc")],
        why="PcaSvc hooks process starts to detect compatibility issues; disabling it removes that constant CPU overhead.",
        changes="Disables and stops PcaSvc.",
        risk="low", impact="low", recommended="optional", admin=True,
        tags=["service", "compatibility", "background", "cpu"],
    ),
    T(
        "cpu-038", "Disable Error Reporting Service",
        "Disables and stops the Windows Error Reporting service so crash dumps and reports are not processed in the background.",
        actions=[("svc", "WerSvc", "disabled"), ("svcstop", "WerSvc")],
        revert=[("svc", "WerSvc", "manual"), ("svcstart", "WerSvc")],
        why="WerSvc spins up to capture and upload crash data; disabling it removes that burst of CPU and disk work.",
        changes="Disables and stops WerSvc.",
        risk="safe", impact="low", recommended="optional", admin=True,
        tags=["service", "error", "reporting", "cpu"],
    ),
    T(
        "cpu-039", "Disable WAP Push Service",
        "Disables and stops the Device Management WAP Push service, a background mobile-messaging worker.",
        actions=[("svc", "dmwappushservice", "disabled"), ("svcstop", "dmwappushservice")],
        revert=[("svc", "dmwappushservice", "auto"), ("svcstart", "dmwappushservice")],
        why="dmwappushservice listens for WAP push notifications on every boot; disabling it trims an idle background worker.",
        changes="Disables and stops dmwappushservice.",
        risk="safe", impact="low", recommended="optional", admin=True,
        win="10,11", tags=["service", "wap", "background", "cpu"],
    ),
    T(
        "cpu-040", "Enable x2APIC",
        "Enables the x2APIC boot option so modern CPUs use the extended interrupt controller mode.",
        actions=[("cmd", "bcdedit /set x2apicpolicy enable")],
        revert=[("cmd", "bcdedit /deletevalue x2apicpolicy")],
        why="x2APIC scales interrupt handling across many logical processors, cutting APIC contention on multicore systems.",
        changes="Sets the x2apicpolicy boot option to enable.",
        risk="moderate", impact="moderate", recommended="optional", admin=True, confirm=True,
        tags=["bcdedit", "apic", "interrupt", "multicore"],
    ),
    T(
        "cpu-041", "Force Platform Tick Timer",
        "Forces Windows to use the platform clock for its tick timer instead of the variable TSC.",
        actions=[("cmd", "bcdedit /set useplatformtick yes")],
        revert=[("cmd", "bcdedit /deletevalue useplatformtick")],
        why="On systems with unstable TSCs, a fixed platform tick keeps timer intervals even and frame pacing consistent.",
        changes="Sets the useplatformtick boot option to yes.",
        risk="moderate", impact="moderate", recommended="optional", admin=True, confirm=True,
        tags=["bcdedit", "timer", "tick", "latency"],
    ),
    T(
        "cpu-042", "Enhanced TSC Synchronization",
        "Selects the enhanced TSC synchronization policy for better cross-core time consistency on multi-socket systems.",
        actions=[("cmd", "bcdedit /set tscsyncpolicy enhanced")],
        revert=[("cmd", "bcdedit /deletevalue tscsyncpolicy")],
        why="Enhanced TSC sync aligns the timestamp counters across logical processors, which keeps perf counters and timing accurate.",
        changes="Sets the tscsyncpolicy boot option to enhanced.",
        risk="moderate", impact="moderate", recommended="optional", admin=True, confirm=True,
        tags=["bcdedit", "tsc", "timer", "multicore"],
    ),
    T(
        "cpu-043", "Reserve Low Memory for Drivers",
        "Adds the avoidlowmemory boot option so kernel drivers load above 2 GB, avoiding driver allocation churn.",
        actions=[("cmd", "bcdedit /set avoidlowmemory 0x8000000")],
        revert=[("cmd", "bcdedit /deletevalue avoidlowmemory")],
        why="Keeping driver allocations out of the low 2 GB region reduces memory-map pressure on heavily loaded systems.",
        changes="Sets avoidlowmemory to 0x8000000 (2 GB).",
        risk="moderate", impact="low", recommended="optional", admin=True, confirm=True,
        win="7,8,10", tags=["bcdedit", "memory", "driver", "kernel"],
    ),
    T(
        "cpu-044", "Disable Emergency Management Services",
        "Disables the Emergency Management Services serial-redirect boot feature to reduce boot-time overhead.",
        actions=[("cmd", "bcdedit /set ems no")],
        revert=[("cmd", "bcdedit /deletevalue ems")],
        why="EMS listens on serial ports during boot; disabling it removes that component for a faster, cleaner bootstrap.",
        changes="Sets the ems boot option to no.",
        risk="safe", impact="low", recommended="optional", admin=True, confirm=True,
        tags=["bcdedit", "ems", "boot", "serial"],
    ),
    T(
        "cpu-045", "Disable Windows Power Throttling",
        "Turns off Windows Power Throttling globally so background processes are not duty-cycled to save energy.",
        actions=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Power\\PowerThrottling", "PowerThrottlingOff", 1, "DWORD")],
        revert=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Power\\PowerThrottling", "PowerThrottlingOff", 0, "DWORD")],
        why="Power Throttling duty-cycles background threads to conserve battery; disabling it keeps work finishing promptly on AC.",
        changes="Sets PowerThrottlingOff=1 in the PowerThrottling control key.",
        risk="low", impact="moderate", recommended="recommended", admin=True, confirm=True,
        win="10,11", tags=["registry", "throttling", "background", "cpu"],
    ),
    T(
        "cpu-046", "MMCSS Latency Class Boost",
        "Raises the Multimedia Class Scheduler Latency class priority so latency-sensitive tasks are scheduled ahead of background work.",
        actions=[
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Latency", "Priority", 6, "DWORD"),
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Latency", "Scheduling Category", "High", "STRING"),
        ],
        revert=[
            ("regdel", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Latency", "Priority"),
            ("regdel", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Latency", "Scheduling Category"),
        ],
        why="The MMCSS Latency class is used by low-latency audio and input apps; a High scheduling category keeps their deadlines met.",
        changes="Boosts the MMCSS Latency class priority and scheduling category.",
        risk="low", impact="moderate", recommended="optional", admin=True,
        tags=["mmcss", "latency", "priority", "scheduler"],
    ),
    T(
        "cpu-047", "MMCSS Games I/O Priority",
        "Raises the Games MMCSS class SuperFetch I/O priority so game reads are served ahead of background I/O.",
        actions=[("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "SFIO Priority", 7, "DWORD")],
        revert=[("regdel", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "SFIO Priority")],
        why="A higher SFIO Priority lets game file reads bypass the disk scheduler's background queue, smoothing level loads and streaming.",
        changes="Sets the Games MMCSS class SFIO Priority to 7.",
        risk="low", impact="moderate", recommended="recommended", admin=True,
        tags=["mmcss", "games", "io", "priority"],
    ),
])
