"""Category: CPU — processor scheduling, boost, power and mitigation settings."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("CPU", win_default="7,8,10,11")

CATEGORY = "CPU"

# Shown (via the confirm gate) whenever the user turns on a boost/clock
# control tweak: these push clocks higher or adjust power management, which
# is a standard Windows behaviour the system is designed to handle.
_RISKY_CPU_WARN = (
    "This tweak adjusts how your CPU boosts clocks and manages power. These "
    "are ordinary Windows settings, and most systems handle them fine. If you "
    "ever notice anything off, you can simply turn the tweak back off in the "
    "app at any time."
)

TWEAKS = validate_module("cpu", [
    T(
        "cpu-010", "Disable HPET Device",
        "Disables the High Precision Event Timer device in Device Manager.",
        actions=[("cmd", "bcdedit /set useplatformclock false")],
        revert=[("cmd", "bcdedit /deletevalue useplatformclock")],
        why="A faulty HPET can introduce timer latency; letting the CPU use its own TSC-based timers is usually faster.",
        changes="Disables the platform clock so the OS uses TSC-derived time.",
        risk="moderate", impact="high", recommended="optional", admin=True, confirm=True,
        win="7,8,10,11", tags=["hpet", "timer", "latency"],
    ),
    T(
        "cpu-011", "Disabled Dynamic Tick",
        "Disables the Windows dynamic tick which lets the timer be stopped in idle.",
        actions=[("cmd", "bcdedit /set disabledynamictick yes")],
        revert=[("cmd", "bcdedit /set disabledynamictick no")],
        why="With dynamic tick, timer interrupts fire irregularly. Disabling it can improve frame pacing.",
        changes="Sets the dynamic tick boot option to disabled.",
        risk="low", impact="moderate", recommended="recommended", admin=True,
        tags=["tick", "timer", "interrupt"],
    ),
    T(
        "cpu-012", "Reduced Timer Slack",
        "Removes the default 50 ms timer slack added by Windows to batch timer callbacks.",
        actions=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\kernel", "TimerSlack", 0, "DWORD")],
        revert=[("regdel", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\kernel", "TimerSlack")],
        why="Less timer slack means Windows wakes more promptly, tightening frame pacing.",
        changes="Sets kernel TimerSlack to 0.",
        risk="low", impact="moderate", recommended="recommended", admin=True,
        tags=["timer", "slack", "latency"],
    ),
    T(
        "cpu-013", "MMCSS Gaming Priority",
        "Configures the Multimedia Class Scheduler Gaming priority for pro audio/game classes.",
        actions=[
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile", "SystemResponsiveness", 0, "DWORD"),
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile", "NetworkThrottlingIndex", 0xffffffff, "DWORD"),
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "GPU Priority", 8, "DWORD"),
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "Priority", 6, "DWORD"),
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "Scheduling Category", "High", "STRING"),
        ],
        revert=[
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile", "SystemResponsiveness", 20, "DWORD"),
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile", "NetworkThrottlingIndex", 10, "DWORD"),
            ("regdel", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "GPU Priority"),
            ("regdel", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "Priority"),
            ("regdel", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "Scheduling Category"),
        ],
        why="Reserves less CPU time for system responsiveness and boosts the Games MMCSS class priority for lower input latency.",
        changes="Adjusts Multimedia Class Scheduler settings for the Games class.",
        risk="low", impact="high", recommended="recommended", admin=True,
        tags=["mmcss", "priority", "latency", "scheduler"],
    ),
    T(
        "cpu-014", "Processor Performance Increase Threshold",
        "Sets the processor performance increase threshold to a low value so boosts engage quickly.",
        actions=[("power", "perf_increase_threshold", 10)],
        revert=[("power", "perf_increase_threshold", 90)],
        why="A lower threshold makes the CPU boost sooner, reducing on-demand stall under sudden game load.",
        changes="Lowers the AC performance increase threshold to 10%.",
        risk="safe", impact="moderate", recommended="recommended", admin=True, confirm=True, warn=_RISKY_CPU_WARN,
        tags=["boost", "threshold", "responsiveness"],
    ),
    T(
        "cpu-016", "Win32 Priority Separation 26",
        "Lowers Windows' default 2-second foreground boost factor to reduce priority instability.",
        actions=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\PriorityControl", "Win32PrioritySeparation", 26, "DWORD")],
        revert=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\PriorityControl", "Win32PrioritySeparation", 2, "DWORD")],
        why="Priority separation 26 keeps foreground boost short so game threads keep consistent priority.",
        changes="Sets Win32PrioritySeparation to 26 (short boost, variable quantum).",
        risk="moderate", impact="moderate", recommended="optional", admin=True,
        tags=["priority", "foreground", "quantum"],
    ),

    T(
        "cpu-026", "Aggressive Idle Time Check",
        "Shortens the processor idle time check so the CPU resumes full performance faster after an idle period.",
        actions=[("power", "time_check", 10)],
        revert=[("power", "time_check", 20)],
        why="A shorter idle time check means the OS re-evaluates load sooner, reducing the delay before clocks ramp back up.",
        changes="Sets the AC processor idle time check to 10.",
        risk="low", impact="moderate", recommended="optional", admin=True,
        when={"laptop": False},
        tags=["power", "idle", "responsiveness", "clockspeed"],
    ),
    T(
        "cpu-029", "Faster Performance Increase Time",
        "Lowers the processor performance increase time so the CPU ramps clocks almost immediately under load.",
        actions=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PERFINCTIME 1")],
        revert=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PERFINCTIME 3")],
        why="The default 3 ms increase time adds a small ramp delay; 1 ms makes boost feel instant in CPU-bound moments.",
        changes="Sets the AC performance increase time to 1 ms.",
        risk="safe", impact="moderate", recommended="recommended", admin=True, confirm=True, warn=_RISKY_CPU_WARN,
        when={"laptop": False},
        tags=["powercfg", "ramp", "boost", "clockspeed"],
    ),
    T(
        "cpu-030", "Longer Performance Decrease Time",
        "Raises the processor performance decrease time so clocks stay elevated longer before throttling back.",
        actions=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PERFDECTIME 10")],
        revert=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PERFDECTIME 3")],
        why="Holding high clocks a little longer avoids the clock-drop bounce between frames in uneven workloads.",
        changes="Sets the AC performance decrease time to 10 ms.",
        risk="safe", impact="low", recommended="recommended", admin=True, confirm=True, warn=_RISKY_CPU_WARN,
        tags=["powercfg", "clockspeed", "ramp", "stability"],
    ),
    T(
        "cpu-031", "Delayed Idle Promote Hysteresis",
        "Raises the idle promote hysteresis so cores stay in shallow idle states instead of sinking into deep C-states.",
        actions=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR IDLEPROMOTE 100")],
        revert=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR IDLEPROMOTE 60")],
        why="A higher promote threshold keeps wake costs low when the workload is bursty, reducing C-state wake latency.",
        changes="Sets the AC idle promote hysteresis to 100.",
        risk="low", impact="moderate", recommended="optional", admin=True,
        when={"laptop": False},
        tags=["powercfg", "cstate", "idle", "latency"],
    ),
    T(
        "cpu-032", "Immediate Idle Demote",
        "Lowers the idle demote hysteresis so cores leave deep idle states at the first sign of load.",
        actions=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR IDLEDEMOTE 0")],
        revert=[("cmd", "powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR IDLEDEMOTE 60")],
        why="A demote threshold of 0 wakes parked or sleeping cores faster, cutting the stall when work suddenly arrives.",
        changes="Sets the AC idle demote hysteresis to 0.",
        risk="low", impact="moderate", recommended="optional", admin=True,
        when={"laptop": False},
        tags=["powercfg", "idle", "wake", "latency"],
    ),
    T(
        "cpu-035", "Disable Telemetry Service",
        "Disables and stops the Connected User Experiences and Telemetry (DiagTrack) service to cut background CPU use.",
        actions=[("svc", "DiagTrack", "disabled"), ("svcstop", "DiagTrack")],
        revert=[("svc", "DiagTrack", "auto"), ("svcstart", "DiagTrack")],
        why="DiagTrack periodically uploads telemetry in the background; disabling it frees CPU cycles and reduces disk activity.",
        changes="Disables and stops DiagTrack.",
        risk="safe", impact="low", recommended="optional", admin=True,
        win="10,11", tags=["service", "telemetry", "background", "cpu"],
    ),
    T(
        "cpu-036", "Disable Windows Search Indexer",
        "Disables and stops the Windows Search service to stop background indexer CPU and disk churn.",
        actions=[("svc", "WSearch", "disabled"), ("svcstop", "WSearch")],
        revert=[("svc", "WSearch", "delayed"), ("svcstart", "WSearch")],
        why="The indexer periodically rescans files; disabling it keeps CPU and I/O available for active work (search results lose live indexing).",
        changes="Disables and stops WSearch.",
        risk="safe", impact="low", recommended="optional", admin=True,
        tags=["service", "search", "indexer", "cpu"],
    ),
    T(
        "cpu-037", "Disable Program Compatibility Assistant",
        "Disables and stops the Program Compatibility Assistant service so it no longer watches applications in the background.",
        actions=[("svc", "PcaSvc", "disabled"), ("svcstop", "PcaSvc")],
        revert=[("svc", "PcaSvc", "auto"), ("svcstart", "PcaSvc")],
        why="PcaSvc hooks process starts to detect compatibility issues; disabling it removes that constant CPU overhead.",
        changes="Disables and stops PcaSvc.",
        risk="low", impact="low", recommended="optional", admin=True,
        tags=["service", "compatibility", "background", "cpu"],
    ),
    T(
        "cpu-038", "Disable Error Reporting Service",
        "Disables and stops the Windows Error Reporting service so crash dumps and reports are not processed in the background.",
        actions=[("svc", "WerSvc", "disabled"), ("svcstop", "WerSvc")],
        revert=[("svc", "WerSvc", "manual"), ("svcstart", "WerSvc")],
        why="WerSvc spins up to capture and upload crash data; disabling it removes that burst of CPU and disk work.",
        changes="Disables and stops WerSvc.",
        risk="safe", impact="low", recommended="optional", admin=True,
        tags=["service", "error", "reporting", "cpu"],
    ),
    T(
        "cpu-039", "Disable WAP Push Service",
        "Disables and stops the Device Management WAP Push service, a background mobile-messaging worker.",
        actions=[("svc", "dmwappushservice", "disabled"), ("svcstop", "dmwappushservice")],
        revert=[("svc", "dmwappushservice", "auto"), ("svcstart", "dmwappushservice")],
        why="dmwappushservice listens for WAP push notifications on every boot; disabling it trims an idle background worker.",
        changes="Disables and stops dmwappushservice.",
        risk="safe", impact="low", recommended="optional", admin=True,
        win="10,11", tags=["service", "wap", "background", "cpu"],
    ),
    T(
        "cpu-040", "Enable x2APIC",
        "Enables the x2APIC boot option so modern CPUs use the extended interrupt controller mode.",
        actions=[("cmd", "bcdedit /set x2apicpolicy enable")],
        revert=[("cmd", "bcdedit /deletevalue x2apicpolicy")],
        why="x2APIC scales interrupt handling across many logical processors, cutting APIC contention on multicore systems.",
        changes="Sets the x2apicpolicy boot option to enable.",
        risk="moderate", impact="moderate", recommended="optional", admin=True, confirm=True,
        tags=["bcdedit", "apic", "interrupt", "multicore"],
    ),
    T(
        "cpu-041", "Force Platform Tick Timer",
        "Forces Windows to use the platform clock for its tick timer instead of the variable TSC.",
        actions=[("cmd", "bcdedit /set useplatformtick yes")],
        revert=[("cmd", "bcdedit /deletevalue useplatformtick")],
        why="On systems with unstable TSCs, a fixed platform tick keeps timer intervals even and frame pacing consistent.",
        changes="Sets the useplatformtick boot option to yes.",
        risk="moderate", impact="moderate", recommended="optional", admin=True, confirm=True,
        tags=["bcdedit", "timer", "tick", "latency"],
    ),
    T(
        "cpu-042", "Enhanced TSC Synchronization",
        "Selects the enhanced TSC synchronization policy for better cross-core time consistency on multi-socket systems.",
        actions=[("cmd", "bcdedit /set tscsyncpolicy enhanced")],
        revert=[("cmd", "bcdedit /deletevalue tscsyncpolicy")],
        why="Enhanced TSC sync aligns the timestamp counters across logical processors, which keeps perf counters and timing accurate.",
        changes="Sets the tscsyncpolicy boot option to enhanced.",
        risk="moderate", impact="moderate", recommended="optional", admin=True, confirm=True,
        tags=["bcdedit", "tsc", "timer", "multicore"],
    ),
    T(
        "cpu-043", "Reserve Low Memory for Drivers",
        "Adds the avoidlowmemory boot option so kernel drivers load above 2 GB, avoiding driver allocation churn.",
        actions=[("cmd", "bcdedit /set avoidlowmemory 0x8000000")],
        revert=[("cmd", "bcdedit /deletevalue avoidlowmemory")],
        why="Keeping driver allocations out of the low 2 GB region reduces memory-map pressure on heavily loaded systems.",
        changes="Sets avoidlowmemory to 0x8000000 (2 GB).",
        risk="moderate", impact="low", recommended="optional", admin=True, confirm=True,
        win="7,8,10", tags=["bcdedit", "memory", "driver", "kernel"],
    ),
    T(
        "cpu-044", "Disable Emergency Management Services",
        "Disables the Emergency Management Services serial-redirect boot feature to reduce boot-time overhead.",
        actions=[("cmd", "bcdedit /set ems no")],
        revert=[("cmd", "bcdedit /deletevalue ems")],
        why="EMS listens on serial ports during boot; disabling it removes that component for a faster, cleaner bootstrap.",
        changes="Sets the ems boot option to no.",
        risk="safe", impact="low", recommended="optional", admin=True, confirm=True,
        tags=["bcdedit", "ems", "boot", "serial"],
    ),
    T(
        "cpu-045", "Disable Windows Power Throttling",
        "Turns off Windows Power Throttling globally so background processes are not duty-cycled to save energy.",
        actions=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Power\\PowerThrottling", "PowerThrottlingOff", 1, "DWORD")],
        revert=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Power\\PowerThrottling", "PowerThrottlingOff", 0, "DWORD")],
        why="Power Throttling duty-cycles background threads to conserve battery; disabling it keeps work finishing promptly on AC.",
        changes="Sets PowerThrottlingOff=1 in the PowerThrottling control key.",
        risk="low", impact="moderate", recommended="recommended", admin=True, confirm=True,
        win="10,11", when={"laptop": False},
        tags=["registry", "throttling", "background", "cpu"],
    ),
    T(
        "cpu-046", "MMCSS Latency Class Boost",
        "Raises the Multimedia Class Scheduler Latency class priority so latency-sensitive tasks are scheduled ahead of background work.",
        actions=[
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Latency", "Priority", 6, "DWORD"),
            ("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Latency", "Scheduling Category", "High", "STRING"),
        ],
        revert=[
            ("regdel", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Latency", "Priority"),
            ("regdel", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Latency", "Scheduling Category"),
        ],
        why="The MMCSS Latency class is used by low-latency audio and input apps; a High scheduling category keeps their deadlines met.",
        changes="Boosts the MMCSS Latency class priority and scheduling category.",
        risk="low", impact="moderate", recommended="optional", admin=True,
        tags=["mmcss", "latency", "priority", "scheduler"],
    ),
    T(
        "cpu-047", "MMCSS Games I/O Priority",
        "Raises the Games MMCSS class SuperFetch I/O priority so game reads are served ahead of background I/O.",
        actions=[("reg", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "SFIO Priority", 7, "DWORD")],
        revert=[("regdel", "HKLM", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "SFIO Priority")],
        why="A higher SFIO Priority lets game file reads bypass the disk scheduler's background queue, smoothing level loads and streaming.",
        changes="Sets the Games MMCSS class SFIO Priority to 7.",
        risk="low", impact="moderate", recommended="recommended", admin=True,
        tags=["mmcss", "games", "io", "priority"],
    ),
    T(
        "cpu-048", "Set Device Idle Policy to Performance",
        "Configures the device idle policy to favor performance over power saving.",
        actions=[("reg", "HKLM", "SOFTWARE\\Policies\\Microsoft\\Windows\\Power\\DeviceIdlePolicy", "Performance", 1, "DWORD")],
        revert=[("reg", "HKLM", "SOFTWARE\\Policies\\Microsoft\\Windows\\Power\\DeviceIdlePolicy", "Performance", 0, "DWORD")],
        why="Device idle throttling slows I/O responses; a performance policy keeps peripherals and storage responsive during gameplay.",
        changes="Sets DeviceIdlePolicy\\Performance to 1.",
        risk="low", impact="moderate", recommended="optional", admin=True,
        tags=["idle", "policy", "power", "device"],
    ),
    T(
        "cpu-049", "Disable Away Mode",
        "Turns off Windows Away Mode so the system does not enter a simulated sleep state.",
        actions=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Power", "AwayModeEnabled", 0, "DWORD")],
        revert=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Power", "AwayModeEnabled", 1, "DWORD")],
        why="Away Mode dims the display and throttles background work even when the PC is actively in use, causing unexpected performance dips.",
        changes="Sets AwayModeEnabled to 0.",
        risk="safe", impact="low", recommended="recommended", admin=True,
        tags=["away", "power", "sleep", "background"],
    ),
    T(
        "cpu-050", "Set System Cooling Policy Active",
        "Sets the system cooling policy to active so the fan ramps up before the CPU throttles.",
        actions=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_PROCESSOR COOLINGPOLICY 1")],
        revert=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_PROCESSOR COOLINGPOLICY 0")],
        why="Active cooling increases fan speed under load instead of letting the CPU down-clock first, keeping boost clocks active longer.",
        changes="Sets the AC system cooling policy to active.",
        risk="low", impact="moderate", recommended="recommended", admin=True,
        tags=["cooling", "fan", "thermal", "throttle"],
    ),
    T(
        "cpu-051", "Enable Logical Processors",
        "Enables all logical processors in the device class so Windows can schedule work across every available thread.",
        actions=[("regall", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Class\\{50127dc3-0fb3-11d2-b28a-00c04fb92618}", "EnableLogicalProcessors", 1, "DWORD")],
        revert=[("regall", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Class\\{50127dc3-0fb3-11d2-b28a-00c04fb92618}", "EnableLogicalProcessors", 0, "DWORD")],
        why="Some OEM configurations disable logical processors; enabling them exposes the full thread count to the scheduler.",
        changes="Sets EnableLogicalProcessors=1 on all processor device class entries.",
        risk="moderate", impact="moderate", recommended="optional", admin=True,
        tags=["logical", "processor", "threads", "scheduler"],
    ),
    T(
        "cpu-052", "Optimize Time Check Interval",
        "Sets the processor idle time check to 5 to reduce the delay before the CPU re-evaluates load.",
        actions=[("power", "PROCTHROTTLEMIN", 5, "SCHEME_CURRENT")],
        revert=[("power", "PROCTHROTTLEMIN", 20, "SCHEME_CURRENT")],
        why="A shorter time check interval makes the CPU resume full performance faster after idle, reducing stutter on bursty workloads.",
        changes="Sets the AC processor time check to 5.",
        risk="low", impact="moderate", recommended="optional", admin=True,
        tags=["idle", "time", "check", "latency"],
    ),
    T(
        "cpu-053", "Disable Intel SpeedStep",
        "Configures the processor to let the OS manage speed transitions instead of using Intel SpeedStep firmware control.",
        actions=[("reg", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Processor\\Power", "DisableIntelSpeedStep", 0, "DWORD")],
        revert=[("regdel", "HKLM", "SYSTEM\\CurrentControlSet\\Control\\Processor\\Power", "DisableIntelSpeedStep")],
        why="Setting DisableIntelSpeedStep to 0 hands frequency scaling back to Windows, which can make boost transitions faster under gaming loads.",
        changes="Sets DisableIntelSpeedStep to 0 under Processor Power.",
        risk="low", impact="moderate", recommended="optional", admin=True,
        tags=["speedstep", "intel", "frequency", "power"],
    ),
])
