"""Category: Debloat — removing Windows apps and bloat."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Debloat", win_default="10,11")
CATEGORY = "Debloat"

TWEAKS = validate_module("debloat", [
    T("db-001", "Remove Default UWP Apps",
      "Uninstalls common pre-installed UWP apps.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-AppxPackage *bing* | Remove-AppxPackage\"")],
      revert=[("cmd", "powershell -NoProfile -Command \"Add-AppxPackage -Register (Get-AppxPackage *bing*).InstallLocation\\AppxManifest.xml\"")],
      why="Pre-installed apps take disk space and add startup polling.",
      changes="Removes Bing UWP apps.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["uwp", "apps", "remove"]),
    T("db-002", "Remove Xbox App",
      "Removes the Xbox app.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-AppxPackage *xboxapp* | Remove-AppxPackage\"")],
      revert=[("cmd", "powershell -NoProfile -Command \"Start-Process 'ms-windows-store://pdp/?ProductId=9WZDNCRFJBD3'\"")],
      why="Removes the Xbox console companion app and its services.",
      changes="Removes the Xbox app.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["xbox", "app", "uwp"]),
    T("db-003", "Remove Windows Mixed Reality",
      "Removes Windows Mixed Reality apps.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-AppxPackage *mixedreality* | Remove-AppxPackage\"")],
      revert=[("guidance", "Reinstall via Microsoft Store.")],
      why="Mixed Reality apps add background MR services.",
      changes="Removes Mixed Reality apps.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["mixedreality", "vr", "uwp"]),
    T("db-004", "Remove News & Weather",
      "Removes the MSN News & Weather apps.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-AppxPackage *bingnews*,*bingweather* | Remove-AppxPackage\"")],
      revert=[("guidance", "Reinstall from the Microsoft Store.")],
      why="News widgets pull feeds in the background.",
      changes="Removes News and Weather apps.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["news", "weather", "uwp"]),
    T("db-005", "Remove OneDrive",
      "Removes OneDrive.",
      actions=[("cmd", "powershell -NoProfile -Command \"taskkill /f /im OneDrive.exe\"")],
      revert=[("guidance", "Reinstall OneDrive from the store.")],
      why="Removes the OneDrive sync process from startup.",
      changes="Kills and marks OneDrive for removal.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["onedrive", "sync", "remove"]),
    T("db-006", "Disable Pre-Installed Store Auto-Install",
      "Prevents auto re-install of removed apps.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SilentInstalledAppsEnabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SilentInstalledAppsEnabled", 1, "DWORD")],
      why="Windows re-installs removed apps after major updates unless blocked.",
      changes="Disables silent app installs.",
      risk="safe", impact="low", recommended="recommended",
      tags=["autoinstall", "store", "apps"]),
    T("db-007", "Remove Telemetry Scheduled Tasks",
      "Disables telemetry scheduled tasks.",
      actions=[("cmd", "schtasks /Change /TN \"\\Microsoft\\Windows\\Application Experience\\Microsoft Compatibility Appraiser\" /Disable")],
      revert=[("cmd", "schtasks /Change /TN \"\\Microsoft\\Windows\\Application Experience\\Microsoft Compatibility Appraiser\" /Enable")],
      why="Scheduled telemetry runs hit disk and CPU on idle.",
      changes="Disables the Compatibility Appraiser task.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["tasks", "telemetry", "schedule"]),
    T("db-008", "Disable Lock Screen",
      "Disables the lock screen.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Personalization", "NoLockScreen", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Personalization", "NoLockScreen", 0, "DWORD")],
      why="Skips the lock screen wallpaper and its slideshow polling.",
      changes="Disables the lock screen.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["lockscreen", "wallpaper", "boot"]),
    T("db-009", "Disable First Sign-in Animation",
      "Disables the first sign-in animation.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\System", "EnableFirstLogonAnimation", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\System", "EnableFirstLogonAnimation", 1, "DWORD")],
      why="Skips the animation that delays the first usable desktop.",
      changes="Disables the first sign-in animation.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["signin", "animation", "boot"]),
    T("db-010", "Disable Windows Tips",
      "Disables Windows tips and suggestions.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SoftLandingEnabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SoftLandingEnabled", 1, "DWORD")],
      why="Removes tips/suggestions polling from the OS.",
      changes="Disables Windows tips.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["tips", "suggestions", "privacy"]),
    T("db-011", "Disable Cloud Content Search",
      "Turns off cloud search results.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Search", "BingSearchEnabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Search", "BingSearchEnabled", 1, "DWORD")],
      why="Stops Start search from querying the web.",
      changes="Disables cloud search.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["search", "bing", "cloud"]),
    T("db-012", "Remove Third-Party Pre-Installed Bloat",
      "Guidance on removing OEM bloat.",
      actions=[("guidance", "OEM machines ship with trial software and updaters. Uninstall via Apps > Installed apps what you do not use (McAfee trials, brand updaters, gift apps) — these are the heaviest background load.")],
      revert=[("guidance", "Reinstall the removed apps.")],
      why="OEM bloat updaters are the biggest background CPU hogs.",
      changes="Shows OEM bloat guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["oem", "bloat", "uninstall"]),
    T("db-013", "Disable Recommended App Promos",
      "Disables recommended app promotions.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-310093Enabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-310093Enabled", 1, "DWORD")],
      why="Stops promotional app suggestions.",
      changes="Disables app promotions.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["promos", "apps", "content"]),
    T("db-014", "Run Disk Cleanup Wizard",
      "Launches the Disk Cleanup tool.",
      actions=[("cmd", "cleanmgr")],
      revert=[("guidance", "No change to revert.")],
      why="Frees space from update leftovers and temp files.",
      changes="Opens Disk Cleanup.",
      risk="safe", impact="low", recommended="recommended",
      tags=["cleanup", "disk", "space"]),
])
