"""Category: Debloat — removing Windows apps and bloat."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Debloat", win_default="10,11")
CATEGORY = "Debloat"

TWEAKS = validate_module("debloat", [
    T("db-001", "Remove Default UWP Apps",
      "Uninstalls common pre-installed UWP apps.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-AppxPackage *bing* | Remove-AppxPackage\"")],
      revert=[("cmd", "powershell -NoProfile -Command \"Add-AppxPackage -Register (Get-AppxPackage *bing*).InstallLocation\\AppxManifest.xml\"")],
      why="Pre-installed apps take disk space and add startup polling.",
      changes="Removes Bing UWP apps.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["uwp", "apps", "remove"]),
    T("db-002", "Remove Xbox App",
      "Removes the Xbox app.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-AppxPackage *xboxapp* | Remove-AppxPackage\"")],
      revert=[("cmd", "powershell -NoProfile -Command \"Start-Process 'ms-windows-store://pdp/?ProductId=9WZDNCRFJBD3'\"")],
      why="Removes the Xbox console companion app and its services.",
      changes="Removes the Xbox app.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["xbox", "app", "uwp"]),
    T("db-003", "Remove Windows Mixed Reality",
      "Removes Windows Mixed Reality apps.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-AppxPackage *mixedreality* | Remove-AppxPackage\"")],
      revert=[("guidance", "Reinstall via Microsoft Store.")],
      why="Mixed Reality apps add background MR services.",
      changes="Removes Mixed Reality apps.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["mixedreality", "vr", "uwp"]),
    T("db-004", "Remove News & Weather",
      "Removes the MSN News & Weather apps.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-AppxPackage *bingnews*,*bingweather* | Remove-AppxPackage\"")],
      revert=[("guidance", "Reinstall from the Microsoft Store.")],
      why="News widgets pull feeds in the background.",
      changes="Removes News and Weather apps.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["news", "weather", "uwp"]),
    T("db-005", "Remove OneDrive",
      "Removes OneDrive.",
      actions=[("cmd", "powershell -NoProfile -Command \"taskkill /f /im OneDrive.exe\"")],
      revert=[("guidance", "Reinstall OneDrive from the store.")],
      why="Removes the OneDrive sync process from startup.",
      changes="Kills and marks OneDrive for removal.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["onedrive", "sync", "remove"]),
    T("db-006", "Disable Pre-Installed Store Auto-Install",
      "Prevents auto re-install of removed apps.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SilentInstalledAppsEnabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SilentInstalledAppsEnabled", 1, "DWORD")],
      why="Windows re-installs removed apps after major updates unless blocked.",
      changes="Disables silent app installs.",
      risk="safe", impact="low", recommended="recommended",
      tags=["autoinstall", "store", "apps"]),

    T("db-012", "Remove Third-Party Pre-Installed Bloat",
      "Guidance on removing OEM bloat.",
      actions=[("guidance", "OEM machines ship with trial software and updaters. Uninstall via Apps > Installed apps what you do not use (McAfee trials, brand updaters, gift apps) — these are the heaviest background load.")],
      revert=[("guidance", "Reinstall the removed apps.")],
      why="OEM bloat updaters are the biggest background CPU hogs.",
      changes="Shows OEM bloat guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["oem", "bloat", "uninstall"]),

    T("db-014", "Run Disk Cleanup Wizard",
      "Launches the Disk Cleanup tool.",
      actions=[("cmd", "cleanmgr")],
      revert=[("guidance", "No change to revert.")],
      why="Frees space from update leftovers and temp files.",
      changes="Opens Disk Cleanup.",
      risk="safe", impact="low", recommended="recommended",
      tags=["cleanup", "disk", "space"]),
    T("db-015", "Disable OneDrive",
      "Disables OneDrive file synchronization via Group Policy.",
      actions=[("cmd", "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\OneDrive\" /v DisableFileSyncNGSC /t REG_DWORD /d 1 /f")],
      revert=[("cmd", "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\OneDrive\" /v DisableFileSyncNGSC /t REG_DWORD /d 0 /f")],
      why="OneDrive syncs files in the background, consuming disk I/O and network bandwidth.",
      changes="Sets DisableFileSyncNGSC to 1 to block OneDrive sync.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["onedrive", "sync", "policy"]),
    T("db-016", "Uninstall Cortana",
      "Removes the Cortana app package from all user accounts.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-AppxPackage -allusers Microsoft.549981C3F5F10 | Remove-AppxPackage\"")],
      revert=[("cmd", "powershell -NoProfile -Command \"Add-AppxPackage -Register 'C:\\Program Files\\WindowsApps\\Microsoft.549981C3F5F10_*\\AppxManifest.xml' -DisableDevelopmentMode\"")],
      why="Cortana runs background processes that listen for voice commands and index data.",
      changes="Removes the Cortana UWP package for all users.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["cortana", "assistant", "uwp"]),
    T("db-017", "Disable Widgets",
      "Disables the Widgets board via Group Policy.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Widgets", "AllowWidgets", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Widgets", "AllowWidgets", 1, "DWORD")],
      why="The Widgets board pulls news, weather, and ads in a background WebView process.",
      changes="Sets AllowWidgets to 0 to hide the Widgets board.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["widgets", "news", "ui"]),
    T("db-018", "Disable Windows Copilot",
      "Disables the Windows Copilot sidebar via Group Policy.",
      actions=[("reg", "HKCU", r"Software\Policies\Microsoft\Windows\WindowsCopilot", "TurnOffWindowsCopilot", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Policies\Microsoft\Windows\WindowsCopilot", "TurnOffWindowsCopilot", 0, "DWORD")],
      why="Copilot adds an AI sidebar that polls network and runs background services.",
      changes="Sets TurnOffWindowsCopilot to 1 to disable the feature.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["copilot", "ai", "sidebar"]),
    T("db-019", "Disable Chat Icon",
      "Hides the Chat icon from the taskbar.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Explorer", "HideChatButton", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Explorer", "HideChatButton", 0, "DWORD")],
      why="The Chat icon launches Microsoft Teams background processes on click.",
      changes="Sets HideChatButton to 1 to remove the Chat icon.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["chat", "teams", "taskbar"]),
    T("db-020", "Disable Windows Spotlight",
      "Disables Windows Spotlight lock screen and desktop features.",
      actions=[("reg", "HKCU", r"SOFTWARE\Policies\Microsoft\Windows\CloudContent", "DisableWindowsSpotlightFeatures", 1, "DWORD")],
      revert=[("reg", "HKCU", r"SOFTWARE\Policies\Microsoft\Windows\CloudContent", "DisableWindowsSpotlightFeatures", 0, "DWORD")],
      why="Spotlight downloads and rotates lock screen images from Microsoft servers.",
      changes="Disables all Windows Spotlight features.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["spotlight", "lockscreen", "cloud"]),
])
