"""Category: Diagnostics — system health and diagnosis tools."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Diagnostics", win_default="7,8,10,11")
CATEGORY = "Diagnostics"

TWEAKS = validate_module("diagnostics", [
    T("diag-001", "Open System Information",
      "Opens the System Information tool.",
      actions=[("cmd", "start msinfo32")],
      revert=[("guidance", "Close the window.")],
      why="Shows hardware, BIOS and driver versions at a glance.",
      changes="Opens System Information.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["msinfo", "hardware", "info"]),
    T("diag-002", "Open DirectX Diagnostic",
      "Opens the DirectX Diagnostic Tool.",
      actions=[("cmd", "start dxdiag")],
      revert=[("guidance", "Close the window.")],
      why="Reports the GPU, driver and feature levels for DX questions.",
      changes="Opens dxdiag.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["dxdiag", "gpu", "feature"]),
    T("diag-003", "Check Disk Health",
      "Queries drive health via Storage Health.",
      actions=[("cmd", "powershell -NoProfile -Command Get-PhysicalDisk | Select-Object FriendlyName,HealthStatus,MediaType,OperationalStatus")],
      revert=[("guidance", "No change to revert.")],
      why="Warns you about failing drives before they stall games.",
      changes="Reports physical disk health.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["disk", "health", "ssd"]),
    T("diag-004", "Recent System Errors",
      "Shows recent critical system errors.",
      actions=[("cmd", "wevtutil qe System /c:8 /rd:true /f:text /q:*[System[(Level=1 or Level=2)]]")],
      revert=[("guidance", "No change to revert.")],
      why="Critical/error events reveal drivers crashing or hardware problems.",
      changes="Queries recent error events.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["events", "errors", "eventlog"]),
    T("diag-005", "CPU Information",
      "Shows CPU model, cores and logical processors.",
      actions=[("cmd", "powershell -NoProfile -Command Get-CimInstance Win32_Processor | Select-Object Name,NumberOfCores,NumberOfLogicalProcessors")],
      revert=[("guidance", "No change to revert.")],
      why="Confirms the CPU before core/thread related tuning.",
      changes="Reports CPU information.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["cpu", "cores", "threads"]),
    T("diag-006", "Memory Information",
      "Shows installed RAM and speed.",
      actions=[("cmd", "powershell -NoProfile -Command Get-CimInstance Win32_PhysicalMemory | Select-Object Capacity,Speed,Manufacturer")],
      revert=[("guidance", "No change to revert.")],
      why="Confirms RAM amount and speed before XMP/memory tweaks.",
      changes="Reports physical memory details.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["ram", "memory", "speed"]),
    T("diag-007", "Driver Problem Devices",
      "Lists devices with driver problems.",
      actions=[("cmd", "pnputil /enum-devices /problem")],
      revert=[("guidance", "No change to revert.")],
      why="Problem devices can cause DPC spikes and input issues.",
      changes="Enumerates devices with problems.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["devices", "drivers", "problems"]),
    T("diag-008", "Boot Time",
      "Shows the last boot time.",
      actions=[("cmd", "powershell -NoProfile -Command (Get-CimInstance Win32_OperatingSystem).LastBootUpTime")],
      revert=[("guidance", "No change to revert.")],
      why="Long uptime hides memory leaks; a recent boot is a good baseline.",
      changes="Reports last boot time.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["boot", "uptime", "info"]),
    T("diag-009", "Network Latency Test",
      "Pings a public host to check baseline latency.",
      actions=[("cmd", "ping -n 4 1.1.1.1")],
      revert=[("guidance", "No change to revert.")],
      why="Baseline latency separates ISP issues from local ones.",
      changes="Pings 1.1.1.1.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["ping", "network", "latency"]),
    T("diag-010", "Battery Report",
      "Generates a battery health report.",
      actions=[("cmd", "powercfg /batteryreport")],
      revert=[("guidance", "Delete the report file.")],
      why="Reveals battery wear that limits laptop performance.",
      changes="Writes batteryreport.html.",
      risk="safe", impact="very low", recommended="recommended",
      when={"laptop": True},
      tags=["battery", "report", "health"]),
    T("diag-011", "Check Windows Version",
      "Shows the installed Windows version and build.",
      actions=[("cmd", "ver")],
      revert=[("guidance", "No change to revert.")],
      why="Build numbers matter for which tweaks apply.",
      changes="Prints the Windows version.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["windows", "version", "build"]),
    T("diag-012", "Check Driver Date via System Info",
      "Shows the GPU driver date from System Information.",
      actions=[("cmd", "powershell -NoProfile -Command Get-CimInstance Win32_VideoController | Select-Object Name,DriverVersion,DriverDate")],
      revert=[("guidance", "No change to revert.")],
      why="An old GPU driver explains many performance gaps.",
      changes="Reports the video driver version.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["gpu", "driver", "version"]),
    T("diag-013", "LatencyMon Guidance",
      "Guidance on measuring DPC latency.",
      actions=[("guidance", "Install LatencyMon, let it run 5 minutes while a game is open, and check the 'Interrupt to process latency' values. Green = drivers healthy.")],
      revert=[("guidance", "Close LatencyMon.")],
      why="DPC spikes manifest as audio crackle and stutter.",
      changes="Shows LatencyMon guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["latencymon", "dpc", "audio"]),
    T("diag-014", "Startup Impact Check",
      "Shows last-boot startup app impact.",
      actions=[("cmd", "powershell -NoProfile -Command Get-CimInstance Win32_StartupCommand | Select-Object Name,Command,Location")],
      revert=[("guidance", "No change to revert.")],
      why="Identifies startup commands that delay sign-in.",
      changes="Lists startup commands.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["startup", "impact", "commands"]),
])
