"""Category: DirectX — runtime checks and DirectX behaviour."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("DirectX", win_default="7,8,10,11")
CATEGORY = "DirectX"
_ALL_GPU = {"gpu": ["nvidia", "amd", "intel"]}

TWEAKS = validate_module("directx", [
    T("dx-001", "Run DirectX Diagnostic",
      "Launches dxdiag to dump the graphics stack.",
      actions=[("cmd", "start dxdiag")],
      revert=[("guidance", "Close the dxdiag window.")],
      why="A dxdiag report shows driver, display and DirectX feature level details useful before tuning.",
      changes="Opens the DirectX Diagnostic Tool.",
      risk="safe", impact="very low", recommended="recommended",
      when=_ALL_GPU,
      tags=["dxdiag", "diagnostics", "gpu"]),
    T("dx-002", "Update DirectX Runtime",
      "Guidance for the DirectX end-user runtime.",
      actions=[("guidance", "DirectX 12 ships with Windows. Older titles may need the DirectX End-User Runtime (dxsetup) from Microsoft's download page — install it once for maximum DX9-11 compatibility.")],
      revert=[("guidance", "No change to revert.")],
      why="The redistributable closes gaps in legacy DX9-11 DLL coverage.",
      changes="Shows DirectX runtime guidance.",
      risk="safe", impact="low", recommended="recommended",
      when=_ALL_GPU,
      tags=["runtime", "redistributable", "dx9"]),
    T("dx-003", "Check DirectX 12 Support",
      "Reports whether the GPU supports feature level 12.",
      actions=[("cmd", "dxdiag /whql:off /t %TEMP%\\dxdiag.txt")],
      revert=[("guidance", "No change to revert.")],
      why="Feature level 12.x gates modern effects in DX12 games.",
      changes="Writes a dxdiag report to the temp folder.",
      risk="safe", impact="very low", recommended="recommended",
      when=_ALL_GPU,
      tags=["dx12", "featurelevel", "gpu"]),
    T("dx-004", "Verify Feature Level in Games",
      "Guidance to check per-game feature-level requirements.",
      actions=[("guidance", "Modern DX12 games report their required feature level. If a game won't start, confirm your GPU meets it via dxdiag's 'Feature Levels' row.")],
      revert=[("guidance", "No change to revert.")],
      why="Avoids chasing settings on a GPU that lacks the required features.",
      changes="Shows feature-level guidance.",
      risk="safe", impact="low", recommended="recommended",
      when=_ALL_GPU,
      tags=["featurelevel", "dx12", "compat"]),
    T("dx-005", "Shader Compilation Guidance",
      "Guidance on DX12 shader compilation hitches.",
      actions=[("guidance", "DX12 games often compile shaders at first run, causing stutter. Precompile by loading the game, or install the driver's shader cache so subsequent runs are smooth.")],
      revert=[("guidance", "No change to revert.")],
      why="DX12 shifts shader compilation to the CPU at runtime unless cached.",
      changes="Shows shader-compilation guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when=_ALL_GPU,
      tags=["shaders", "stutter", "compile"]),
    T("dx-006", "Async Compute Note",
      "Guidance on async compute behaviour in DX12.",
      actions=[("guidance", "DX12 exposes async compute. Leave game settings at their default; forcing it on hardware that lacks dedicated async queues can reduce FPS.")],
      revert=[("guidance", "No change to revert.")],
      why="Async compute should be game-managed, not globally forced.",
      changes="Shows async-compute guidance.",
      risk="safe", impact="low", recommended="recommended",
      when=_ALL_GPU,
      tags=["asynccompute", "gpu", "dx12"]),
    T("dx-007", "Ray Tracing Overhead Note",
      "Guidance for ray-tracing cost in DX12 titles.",
      actions=[("guidance", "DXR ray tracing costs a lot of GPU budget. On mid-range GPUs use 'RT at low quality' or disable it for consistent frame times.")],
      revert=[("guidance", "No change to revert.")],
      why="Unbounded RT budget causes severe 1% low frame times.",
      changes="Shows ray-tracing guidance.",
      risk="safe", impact="low", recommended="recommended",
      when=_ALL_GPU,
      tags=["raytracing", "dxr", "performance"]),
    T("dx-008", "Mesh Shader Note",
      "Guidance on mesh shader workloads in DX12.",
      actions=[("guidance", "Mesh shaders (feature level 12.2 GPUs) speed up geometry-heavy scenes. There is no global toggle; verify your GPU supports them in dxdiag.")],
      revert=[("guidance", "No change to revert.")],
      why="Mesh shaders replace the old vertex pipeline on supported hardware.",
      changes="Shows mesh-shader guidance.",
      risk="safe", impact="low", recommended="recommended",
      when=_ALL_GPU,
      tags=["meshshaders", "geometry", "dx12"]),
    T("dx-009", "D3D9 Windowed Optimizations",
      "Guidance for legacy DX9 games in windowed mode.",
      actions=[("guidance", "Legacy DX9 titles run a compatibility layer. If they stutter windowed, try exclusive fullscreen, or force 'Borderless' if the game offers it.")],
      revert=[("guidance", "No change to revert.")],
      why="Legacy presentation paths are slowest in windowed mode.",
      changes="Shows DX9 windowed guidance.",
      risk="safe", impact="low", recommended="recommended",
      when=_ALL_GPU,
      tags=["dx9", "legacy", "windowed"]),
    T("dx-010", "Update GPU Drivers for DX12",
      "Guidance to keep DX12 drivers current.",
      actions=[("guidance", "DX12 features are driver-dependent. Update to the latest stable GPU driver from NVIDIA/AMD/Intel before judging a DX12 game's performance.")],
      revert=[("guidance", "No change to revert.")],
      why="New DX12 titles frequently rely on the latest driver fixes.",
      changes="Shows driver-update guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when=_ALL_GPU,
      tags=["driver", "dx12", "update"]),
])
