"""Category: DirectX 12 — modern graphics pipeline notes and toggles."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("DirectX 12", win_default="10,11")
CATEGORY = "DirectX 12"

TWEAKS = validate_module("dx12", [
    T("dx12-002", "DirectStorage Enable",
      "Guidance to enable DirectStorage on supported systems.",
      actions=[("guidance", "DirectStorage needs an NVMe SSD, DX12 GPU and driver support. Enable 'GPU decompression' in supported games to offload asset loading.")],
      revert=[("guidance", "Disable DirectStorage in the game.")],
      why="GPU decompression cuts loading and texture streaming stalls.",
      changes="Shows DirectStorage guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["directstorage", "nvme", "streaming"]),
    T("dx12-003", "Reduce CPU Overhead",
      "Guidance on lowering DX12 CPU cost.",
      actions=[("guidance", "DX12 has higher fixed CPU cost from many threads. Keep HAGS on, set the game to 'high' thread priority if supported, and close browser tabs before DX12 titles.")],
      revert=[("guidance", "No change to revert.")],
      why="DX12 scales with cores; a busy desktop starves its worker threads.",
      changes="Shows DX12 CPU guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["cpu", "overhead", "threads"]),
    T("dx12-004", "Shader Caching for DX12",
      "Guidance for per-game DX12 shader caches.",
      actions=[("guidance", "Let games build their own DX12 shader cache on first launch. Do not clear it mid-session — that reintroduces stutter until it rebuilds.")],
      revert=[("guidance", "No change to revert.")],
      why="A warm DX12 shader cache is the difference between smooth and stuttery runs.",
      changes="Shows shader-cache guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["shaders", "cache", "stutter"]),
    T("dx12-005", "Work Graphs Note",
      "Guidance on DX12 Work Graphs technology.",
      actions=[("guidance", "Work Graphs (a 2020s DX12 feature) let the GPU schedule its own work. No user toggle exists; it activates per-game. Just keep the GPU driver current.")],
      revert=[("guidance", "No change to revert.")],
      why="New scheduling features need current drivers to engage.",
      changes="Shows Work Graphs guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["workgraphs", "gpu", "dx12"]),
    T("dx12-006", "Resource Binding Tier Check",
      "Guidance on checking the GPU's resource binding tier.",
      actions=[("guidance", "dxdiag shows your GPU's feature level and driver model. Tier 3 binding (12_2 GPUs) gives games more flexible descriptor layouts. There is nothing to change — it is hardware.")],
      revert=[("guidance", "No change to revert.")],
      why="Binding tier determines which DX12 effects a GPU can run.",
      changes="Shows binding-tier guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["binding", "descriptors", "tier"]),
    T("dx12-007", "DXR Ray Tracing Tuning",
      "Guidance to balance DXR quality and frame times.",
      actions=[("guidance", "When DXR is enabled, drop shadow/reflection resolution first. RT costs grow quickly; one or two RT effects on 'low' usually keeps 1% lows stable.")],
      revert=[("guidance", "Restore RT quality.")],
      why="RT effects compound in cost when stacked.",
      changes="Shows DXR tuning guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["dxr", "raytracing", "tuning"]),
    T("dx12-008", "Sampler Feedback Note",
      "Guidance on sampler feedback features.",
      actions=[("guidance", "Sampler feedback lets games load only the mip levels they need. It is automatic in supported DX12 games — enable 'GPU decompression' where the option exists.")],
      revert=[("guidance", "No change to revert.")],
      why="Sampler feedback reduces memory traffic on supported titles.",
      changes="Shows sampler-feedback guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["sampler", "feedback", "memory"]),
    T("dx12-009", "Force DX12 in Supported Games",
      "Guidance to run games on their DX12 renderer.",
      actions=[("guidance", "Many titles offer DX11/DX12 renderers (e.g. in the game's settings or config). DX12 usually reduces CPU hitches on multi-core CPUs. Test both and keep whichever gives better 1% lows.")],
      revert=[("guidance", "Switch back to DX11.")],
      why="DX12's parallel command lists lower CPU-bound frame times on modern CPUs.",
      changes="Shows renderer-selection guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["dx11", "dx12", "renderer"]),
    T("dx12-010", "Keep DX12 Memory Headroom",
      "Guidance to avoid DX12 VRAM pressure.",
      actions=[("guidance", "DX12 titles often reserve more VRAM. Close background apps and lower texture pools if a game runs out of memory despite fitting on paper.")],
      revert=[("guidance", "No change to revert.")],
      why="VRAM spills cause massive stutter in DX12 games.",
      changes="Shows VRAM guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["vram", "memory", "stutter"]),
])
