"""Category: Ethernet — wired adapter driver-level optimizations."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Ethernet", win_default="7,8,10,11")
CATEGORY = "Ethernet"

PS = "powershell -NoProfile -ExecutionPolicy Bypass -Command"

TWEAKS = validate_module("ethernet", [
    T("eth-001", "Disable Adapter Power Management",
      "Turns off all power-saving on the wired adapter.",
      actions=[("cmd", f'{PS} "Disable-NetAdapterPowerManagement -Name \'Ethernet*\' -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Enable-NetAdapterPowerManagement -Name \'Ethernet*\' -ErrorAction SilentlyContinue"')],
      why="Power management can put the adapter into low-power modes that add latency spikes.",
      changes="Disables adapter power management.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["power", "adapter", "ethernet"]),

    T("eth-004", "Disable Large Send Offload IPv4",
      "Turns off LSOv4 segmentation offload.",
      actions=[("cmd", f'{PS} "Set-NetAdapterLso -Name \'Ethernet*\' -IPv4Enabled $false -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Set-NetAdapterLso -Name \'Ethernet*\' -IPv4Enabled $true -ErrorAction SilentlyContinue"')],
      why="Offloading segmentation to the NIC can add micro-burst latency on some hardware.",
      changes="Disables LSO IPv4.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["lso", "offload", "tcp"]),
    T("eth-005", "Enable RSS on Adapter",
      "Enables receive-side scaling on the wired adapter.",
      actions=[("cmd", f'{PS} "Set-NetAdapterRss -Name \'Ethernet*\' -Enabled $true -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Set-NetAdapterRss -Name \'Ethernet*\' -Enabled $false -ErrorAction SilentlyContinue"')],
      why="Spreads receive processing across CPU cores to avoid single-core saturation.",
      changes="Enables adapter RSS.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["rss", "cpu", "receive"]),
    T("eth-006", "Disable Flow Control",
      "Turns off Ethernet flow control.",
      actions=[("cmd", f'{PS} "Set-NetAdapterAdvancedProperty -Name \'Ethernet*\' -DisplayName \'Flow Control\' -DisplayValue \'Disabled\' -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Set-NetAdapterAdvancedProperty -Name \'Ethernet*\' -DisplayName \'Flow Control\' -DisplayValue \'Enabled\' -ErrorAction SilentlyContinue"')],
      why="Pause frames can stall the adapter at the worst moments; disabled flow control is typical for gaming.",
      changes="Disables flow control.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["flowcontrol", "pause", "ethernet"]),

    T("eth-008", "Disable Energy Efficient Ethernet",
      "Turns off EEE/Green Ethernet power saving.",
      actions=[("cmd", f'{PS} "Set-NetAdapterAdvancedProperty -Name \'Ethernet*\' -DisplayName \'Energy Efficient Ethernet\' -DisplayValue \'Disabled\' -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Set-NetAdapterAdvancedProperty -Name \'Ethernet*\' -DisplayName \'Energy Efficient Ethernet\' -DisplayValue \'Enabled\' -ErrorAction SilentlyContinue"')],
      why="EEE drops the link into low-power idle that re-negotiates with latency when traffic resumes.",
      changes="Disables Energy Efficient Ethernet.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["eee", "green", "power"]),
    T("eth-009", "Disable Wake on Magic Packet",
      "Turns off Wake-on-LAN wake on magic packet.",
      actions=[("cmd", f'{PS} "Set-NetAdapterPowerManagement -Name \'Ethernet*\' -WakeOnMagicPacket Disabled -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Set-NetAdapterPowerManagement -Name \'Ethernet*\' -WakeOnMagicPacket Enabled -ErrorAction SilentlyContinue"')],
      why="Removes the always-listening wake path that keeps the adapter powered in sleep.",
      changes="Disables Wake-on-Magic-Packet.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["wol", "magic", "wake"]),
    T("eth-010", "Raise Receive Buffers",
      "Increases the adapter receive ring buffer size.",
      actions=[("cmd", f'{PS} "if (Get-NetAdapterAdvancedProperty -Name \'Ethernet*\' -RegistryKeyword \'ReceiveBuffers\' -ErrorAction SilentlyContinue) {{ Set-NetAdapterAdvancedProperty -Name \'Ethernet*\' -RegistryKeyword \'ReceiveBuffers\' -RegistryValue 2048 -ErrorAction SilentlyContinue }} else {{ Get-ChildItem \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\' -EA SilentlyContinue | ForEach-Object {{ Set-ItemProperty -Path $_.PSPath -Name \'ReceiveBuffers\' -Value 2048 -Type DWord -EA SilentlyContinue }} }}"')],
      revert=[("cmd", f'{PS} "if (Get-NetAdapterAdvancedProperty -Name \'Ethernet*\' -RegistryKeyword \'ReceiveBuffers\' -ErrorAction SilentlyContinue) {{ Set-NetAdapterAdvancedProperty -Name \'Ethernet*\' -RegistryKeyword \'ReceiveBuffers\' -RegistryValue 512 -ErrorAction SilentlyContinue }} else {{ Get-ChildItem \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\' -EA SilentlyContinue | ForEach-Object {{ Remove-ItemProperty -Path $_.PSPath -Name \'ReceiveBuffers\' -EA SilentlyContinue }} }}"')],
      why="Larger receive buffers reduce dropped packets during traffic bursts.",
      changes="Sets ReceiveBuffers to 2048.",
      risk="low", impact="low", recommended="recommended", admin=True,
      tags=["buffers", "receive", "drop"]),
    T("eth-011", "Raise Transmit Buffers",
      "Increases the adapter transmit ring buffer size.",
      actions=[("cmd", f'{PS} "if (Get-NetAdapterAdvancedProperty -Name \'Ethernet*\' -RegistryKeyword \'TransmitBuffers\' -ErrorAction SilentlyContinue) {{ Set-NetAdapterAdvancedProperty -Name \'Ethernet*\' -RegistryKeyword \'TransmitBuffers\' -RegistryValue 2048 -ErrorAction SilentlyContinue }} else {{ Get-ChildItem \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\' -EA SilentlyContinue | ForEach-Object {{ Set-ItemProperty -Path $_.PSPath -Name \'TransmitBuffers\' -Value 2048 -Type DWord -EA SilentlyContinue }} }}"')],
      revert=[("cmd", f'{PS} "if (Get-NetAdapterAdvancedProperty -Name \'Ethernet*\' -RegistryKeyword \'TransmitBuffers\' -ErrorAction SilentlyContinue) {{ Set-NetAdapterAdvancedProperty -Name \'Ethernet*\' -RegistryKeyword \'TransmitBuffers\' -RegistryValue 512 -ErrorAction SilentlyContinue }} else {{ Get-ChildItem \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\' -EA SilentlyContinue | ForEach-Object {{ Remove-ItemProperty -Path $_.PSPath -Name \'TransmitBuffers\' -EA SilentlyContinue }} }}"')],
      why="Larger transmit buffers smooth out bursty game traffic.",
      changes="Sets TransmitBuffers to 2048.",
      risk="low", impact="low", recommended="recommended", admin=True,
      tags=["buffers", "transmit", "burst"]),
    T("eth-012", "Reset Ethernet Adapter",
      "Restarts the wired network adapter.",
      actions=[("cmd", f'{PS} "Restart-NetAdapter -Name \'Ethernet*\' -ErrorAction SilentlyContinue"')],
      revert=[("guidance", "Adapter restart is non-destructive.")],
      why="Clears stuck driver state and re-negotiates the link.",
      changes="Restarts the Ethernet adapter.",
      risk="safe", impact="moderate", recommended="optional", admin=True, confirm=True,
      tags=["reset", "adapter", "restart"]),
    T("eth-013", "Full-Duplex Link Check",
      "Reports the negotiated link speed and duplex mode.",
      actions=[("cmd", f'{PS} "Get-NetAdapter -Name \'Ethernet*\' | Format-Table Name,LinkSpeed,FullDuplex -AutoSize"')],
      revert=[("guidance", "Read-only report.")],
      why="A 100 Mbps or half-duplex link is often a faulty cable or port, not a Windows problem.",
      changes="Shows the adapter link report.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["duplex", "speed", "link"]),

])
