"""Category: Experimental — experimental and niche tweaks."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Experimental", win_default="10,11")
CATEGORY = "Experimental"

TWEAKS = validate_module("experimental", [
    T("exp-001", "Enable Dev Mode",
      "Enables Developer Mode features.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock", "AllowDevelopmentWithoutDevLicense", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock", "AllowDevelopmentWithoutDevLicense", 0, "DWORD")],
      why="Lets sideloaded tools and apps run without store restrictions.",
      changes="Enables Developer Mode.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["devmode", "sideload", "developer"]),
    T("exp-002", "Enable Windows Subsystem for Linux",
      "Enables WSL support.",
      actions=[("cmd", "powershell -NoProfile -Command \"Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux -NoRestart\"")],
      revert=[("cmd", "powershell -NoProfile -Command \"Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux -NoRestart\"")],
      why="WSL is useful for scripting tools, not for games — enable only if you use Linux tools.",
      changes="Enables WSL.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["wsl", "linux", "subsystem"]),
    T("exp-003", "Disable Hypervisor via BCDEdit",
      "Disables the hypervisor at boot.",
      actions=[("cmd", "bcdedit /set hypervisorlaunchtype off")],
      revert=[("cmd", "bcdedit /set hypervisorlaunchtype auto")],
      why="Removes hypervisor overhead from the boot stack on some machines.",
      changes="Disables the hypervisor.",
      risk="safe", impact="moderate", recommended="optional", admin=True,
      tags=["hypervisor", "bcdedit", "boot"]),
    T("exp-004", "Enable Test Mode",
      "Enables test signing mode.",
      actions=[("cmd", "bcdedit /set testsigning on")],
      revert=[("cmd", "bcdedit /set testsigning off")],
      why="Allows unsigned driver testing — for developers only.",
      changes="Enables test signing.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["testsigning", "drivers", "dev"]),
    T("exp-005", "Disable Core Isolation",
      "Disables memory integrity.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\HypervisorEnforcedCodeIntegrity", "Enabled", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\HypervisorEnforcedCodeIntegrity", "Enabled", 1, "DWORD")],
      why="Removes the virtualization overhead of Hypervisor-enforced code integrity.",
      changes="Disables Core Isolation.",
      risk="safe", impact="moderate", recommended="optional", admin=True,
      tags=["coreisolation", "memoryintegrity", "security"]),
    T("exp-006", "Enable Undocumented GPU Tweaks",
      "Guidance on undocumented GPU registry values.",
      actions=[("guidance", "Undocumented GPU registry values (e.g. RIII tweaks, MMCSS overrides) rarely help on modern drivers and can break updates. Avoid them unless a known fix needs one.")],
      revert=[("guidance", "Remove the undocumented values.")],
      why="Unverified registry values are a frequent source of driver instability.",
      changes="Shows undocumented-tweak guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["registry", "undocumented", "warn"]),
    T("exp-007", "Enable Variable Refresh Overscan Fix",
      "Guidance on VRR overscan glitches.",
      actions=[("guidance", "Some monitors glitch at the edge of the VRR range. Test with an FPS cap inside the range; a firmware or driver update usually fixes overscan artifacts.")],
      revert=[("guidance", "No change to revert.")],
      why="VRR edge glitches are usually fixed by caps or updates.",
      changes="Shows VRR-overscan guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["vrr", "overscan", "fix"]),
    T("exp-008", "Disable XAML Activity Feed",
      "Disables the Windows activity timeline feed.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\System", "EnableActivityFeed", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\System", "EnableActivityFeed", 1, "DWORD")],
      why="Removes timeline feed processing.",
      changes="Disables the activity feed.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["timeline", "activity", "feed"]),
    T("exp-009", "Disable Virtualization for Games",
      "Guidance on disabling virtualization for Vanguard.",
      actions=[("guidance", "Vanguard requires virtualization-based security on some hardware. If Valorant will not launch, do not disable VBS — instead update BIOS and enable SVM/VT-x as the anti-cheat requires.")],
      revert=[("guidance", "No change to revert.")],
      why="Disabling VBS breaks anti-cheat compatibility on affected systems.",
      changes="Shows virtualization guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["vanguard", "virtualization", "anticheat"]),
    T("exp-010", "Enable Direct Storage on Older GPUs",
      "Guidance on DirectStorage fallback.",
      actions=[("guidance", "DirectStorage falls back to CPU decompression on GPUs without decompression support. There is no per-GPU toggle; rely on the game's settings.")],
      revert=[("guidance", "No change to revert.")],
      why="Older GPUs cannot offload decompression to the GPU.",
      changes="Shows DirectStorage fallback guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["directstorage", "fallback", "gpu"]),
])
