"""Category: Windows Explorer — shell and file browser optimizations."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Windows Explorer", win_default="7,8,10,11")
CATEGORY = "Windows Explorer"

TWEAKS = validate_module("explorer", [
    T("expl-001", "Show Hidden Files",
      "Displays hidden files and folders in Explorer.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "Hidden", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "Hidden", 0, "DWORD")],
      why="Modded game folders frequently hide crucial config and DLL files.",
      changes="Shows hidden files.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["hidden", "files", "folder"]),
    T("expl-002", "Show Protected Operating System Files",
      "Reveals protected system files in Explorer.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "ShowSuperHidden", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "ShowSuperHidden", 0, "DWORD")],
      why="Required for troubleshooting anti-cheat and driver issues in game directories.",
      changes="Shows protected OS files.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["hidden", "system", "files"]),
    T("expl-003", "Show File Name Extensions",
      "Displays full file name extensions.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "HideFileExt", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "HideFileExt", 1, "DWORD")],
      why="Lets you verify config and DLL files when tuning games.",
      changes="Shows file extensions.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["extension", "files", "config"]),
    T("expl-004", "Disable Thumbnail Cache",
      "Stops Explorer from generating thumbnail previews.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "DisableThumbnailCache", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "DisableThumbnailCache", 0, "DWORD")],
      why="Thumbnail decoding and caching burn CPU and disk IO in media-heavy folders.",
      changes="Disables thumbnail generation.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["thumbnails", "cache", "io"]),
    T("expl-005", "Disable Network Thumbnail Cache",
      "Turns off thumbnail caching for network folders.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "DisableNetworkThumbnailCache", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "DisableNetworkThumbnailCache", 0, "DWORD")],
      why="Prevents Explorer from polling network shares to build thumbnails.",
      changes="Disables network thumbnail cache.",
      risk="safe", impact="low", recommended="recommended",
      tags=["network", "thumbnails", "samba"]),
    T("expl-006", "Disable thumbs.db Creation",
      "Stops creation of thumbs.db database files on network folders.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer", "DisableThumbsDBOnNetwork", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer", "DisableThumbsDBOnNetwork", 0, "DWORD")],
      why="Prevents write churn on network storage and removes junk files.",
      changes="Disables thumbs.db on network paths.",
      risk="safe", impact="low", recommended="recommended",
      tags=["thumbs", "network", "cache"]),
    T("expl-007", "Enlarge Icon Cache",
      "Raises the shell icon cache size to 8192 entries.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer", "Max Cached Icons", 8192, "DWORD")],
      revert=[("regdel", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer", "Max Cached Icons")],
      why="A larger icon cache avoids repeated icon re-decoding when folders change.",
      changes="Sets Max Cached Icons to 8192.",
      risk="safe", impact="low", recommended="recommended",
      tags=["icons", "cache", "explorer"]),
    T("expl-008", "Explorer Opens to This PC",
      "Changes File Explorer's default landing page to This PC.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "LaunchTo", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "LaunchTo", 0, "DWORD")],
      why="Skips loading the Quick Access journal when opening Explorer.",
      changes="Sets Explorer launch target to This PC.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["quickaccess", "thispc", "explorer"]),
    T("expl-009", "Disable Recent Item Tracking",
      "Stops Start menu and jump list from tracking opened items.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "Start_TrackDocs", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "Start_TrackDocs", 1, "DWORD")],
      why="Removes the journaling overhead that maintains recent item lists.",
      changes="Disables recent item tracking.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["recent", "jumplist", "tracking"]),
    T("expl-010", "Full Path in Explorer Title Bar",
      "Shows the complete folder path in the window title bar.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\CabinetState", "FullPath", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\CabinetState", "FullPath", 0, "DWORD")],
      why="Helps when working deep inside mod directories.",
      changes="Shows full paths in title bars.",
      risk="safe", impact="very low", recommended="optional",
      tags=["path", "titlebar", "explorer"]),
    T("expl-011", "Hide Taskbar Search Box",
      "Reduces the taskbar search box to an icon (or removes it).",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Search", "SearchboxTaskbarMode", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Search", "SearchboxTaskbarMode", 1, "DWORD")],
      why="The live search box renders and queries continuously in the background.",
      changes="Hides the taskbar search box.",
      risk="safe", impact="low", recommended="recommended",
      tags=["search", "taskbar", "box"]),
    T("expl-012", "Disable Search Highlights",
      "Turns off the search box highlights content.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\SearchSettings", "IsDynamicSearchBoxEnabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\SearchSettings", "IsDynamicSearchBoxEnabled", 1, "DWORD")],
      why="Stops the rotating highlight content from refreshing in the search box.",
      changes="Disables search highlights.",
      risk="safe", impact="very low", recommended="recommended", win="11",
      tags=["search", "highlights", "content"]),
    T("expl-013", "Explorer Compact Mode",
      "Enables compact spacing in Windows 11 Explorer.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "UseCompactMode", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "UseCompactMode", 0, "DWORD")],
      why="Denser rows show more files per screen, reducing scrolling.",
      changes="Enables compact mode.",
      risk="safe", impact="very low", recommended="optional", win="11",
      tags=["compact", "spacing", "explorer"]),
    T("expl-014", "Restart Explorer Cleanly",
      "Restarts the Windows shell to apply Explorer changes.",
      actions=[("restart", "explorer")],
      revert=[("guidance", "Explorer restarts automatically after this action.")],
      why="Several Explorer tweaks need a shell restart to take effect.",
      changes="Restarts explorer.exe.",
      risk="safe", impact="low", recommended="recommended", confirm=True,
      tags=["restart", "shell", "explorer"]),
])
