"""Category: Fortnite — dedicated Fortnite performance and latency profile."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Fortnite", win_default="7,8,10,11")
CATEGORY = "Fortnite"

# Fortnite's GameUserSettings.ini lives under LOCALAPPDATA and uses the
# FortGameUserSettings section for the settings exposed below. The game
# rewrites the file on exit, so apply these while Fortnite is closed.
INI_PATH = (r"%LOCALAPPDATA%\FortniteGame\Saved\Config\WindowsClient"
            r"\GameUserSettings.ini")
INI_SEC = "/Script/FortniteGame.FortGameUserSettings"


def INI(key: str, value: str):
    """Build an ``ini`` action tuple for Fortnite's GameUserSettings.ini."""
    return ("ini", INI_PATH, INI_SEC, key, value)


def SG(key: str, value: str):
    """Build an ``ini`` action for the [ScalabilityGroups] section."""
    return ("ini", INI_PATH, "ScalabilityGroups", key, value)


def RT(key: str, value: str):
    """Build an ``ini`` action for the [RayTracing] section."""
    return ("ini", INI_PATH, "RayTracing", key, value)


def PM(key: str, value: str):
    """Build an ``ini`` action for the [PerformanceMode] section."""
    return ("ini", INI_PATH, "PerformanceMode", key, value)


def INIDEL(key: str):
    """Build an ``inidel`` action deleting a key from the main settings section."""
    return ("inidel", INI_PATH, INI_SEC, key)


def INIDEL_SEC(sec: str, key: str):
    """Build an ``inidel`` action deleting a key from another section."""
    return ("inidel", INI_PATH, sec, key)

TWEAKS = validate_module("fortnite", [
    T("fn-001", "Use Performance Mode",
      "Switches Fortnite to Performance rendering.",
      actions=[("guidance", "In Fortnite Settings > Advanced Graphics, set 'Rendering Mode' to Performance. It drops the engine to simplified shaders and raises FPS substantially on mid-range GPUs.")],
      revert=[("guidance", "Switch rendering mode back to DX12/DX11.")],
      why="Performance Mode removes shading and lighting passes that cost FPS.",
      changes="Shows Performance Mode guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["fortnite", "performance", "rendering"]),
    T("fn-002", "Cap FPS to Refresh",
      "Guidance on Fortnite FPS caps.",
      actions=[("guidance", "Set 'Frame Rate Limit' to your monitor's refresh rate (or 'Unlimited' only if you have large headroom). A cap slightly below refresh smooths VRR and input.")],
      revert=[("guidance", "Change the FPS limit back.")],
      why="Uncapped FPS above the monitor adds queue latency without benefit.",
      changes="Shows FPS-cap guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["fortnite", "fps", "cap"]),
    T("fn-003", "Enable Reflex",
      "Guidance to enable NVIDIA Reflex in Fortnite.",
      actions=[("guidance", "In Fortnite settings enable NVIDIA Reflex 'On + Boost' (or AMD Anti-Lag 2). This trims render queue latency in fights.")],
      revert=[("guidance", "Turn Reflex off.")],
      why="Reflex reduces the CPU/GPU queue gap during fast combat.",
      changes="Shows Reflex guidance.",
      risk="safe", impact="high", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["fortnite", "reflex", "latency"]),
    T("fn-004", "Lobby FPS Cap",
      "Guidance on lowering lobby FPS.",
      actions=[("guidance", "Cap the lobby/loading FPS to 60 (Settings > Frame Rate Limit) — it saves power and prevents the lobby from fighting the match thread.")],
      revert=[("guidance", "Uncap the lobby FPS.")],
      why="The lobby rendering at unlimited FPS wastes GPU time.",
      changes="Shows lobby-cap guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["fortnite", "lobby", "cap"]),
    T("fn-005", "Optimize View Distance",
      "Guidance on Fortnite view distance vs FPS.",
      actions=[("guidance", "Set 'View Distance' to Epic only for competitive visibility; drop it to Far/Near if FPS is low — it has a large GPU cost in large build battles.")],
      revert=[("guidance", "Restore the view distance.")],
      why="View distance directly scales geometry streaming cost.",
      changes="Shows view-distance guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["fortnite", "viewdistance", "geometry"]),
    T("fn-006", "Shadow and Effects Off",
      "Guidance for competitive Fortnite graphics.",
      actions=[("guidance", "Set Shadows, Effects and Post-processing to Low/Off in Competitive settings. Shadows and bloom add the biggest frame-time cost in Fortnite.")],
      revert=[("guidance", "Restore high visual settings.")],
      why="Effects and shadows cost a large share of Fortnite's frame time.",
      changes="Shows effects guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["fortnite", "shadows", "effects"]),
    T("fn-007", "Use Epic Launcher Offline Mode",
      "Guidance to reduce launcher load.",
      actions=[("guidance", "After Fortnite is installed, launch it from the Epic Games Launcher with automatic updates paused, and exit the launcher after the game starts.")],
      revert=[("guidance", "Keep auto-updates on.")],
      why="Launcher update checks add disk and network churn.",
      changes="Shows launcher guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["fortnite", "launcher", "updates"]),
    T("fn-008", "Verify Fortnite Files",
      "Guidance to verify Fortnite installation.",
      actions=[("guidance", "If Fortnite stutters or fails to load shaders, use 'Verify' in the Epic Games Launcher > Fortnite settings to repair corrupted files.")],
      revert=[("guidance", "No change to revert.")],
      why="Corrupt shader/asset files cause random hitches in Fortnite.",
      changes="Shows file-verify guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["fortnite", "verify", "repair"]),
    T("fn-009", "Disable HDR in Fortnite",
      "Guidance to turn off Fortnite HDR.",
      actions=[("guidance", "If your monitor is SDR, leave HDR off in Fortnite's graphics settings. HDR rendering adds a conversion pass on non-HDR displays.")],
      revert=[("guidance", "Re-enable HDR.")],
      why="HDR conversion on an SDR panel is wasted GPU work.",
      changes="Shows HDR guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["fortnite", "hdr", "sdr"]),
    T("fn-010", "Latency Network Settings",
      "Guidance on Fortnite network settings.",
      actions=[("guidance", "Use a wired connection and select the nearest server region. Reduce packet loss with a stable network; Fortnite's tick rate rewards consistent latency.")],
      revert=[("guidance", "No change to revert.")],
      why="Network jitter appears as input delay and rubber-banding in Fortnite.",
      changes="Shows network guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["fortnite", "network", "latency"]),
    T("fn-011", "Disable Dynamic Shadows",
      "Turns off dynamic character/building shadows in Fortnite's config.",
      actions=[INI("bShouldUseLotsOfDynamicShadows", "False")],
      revert=[INI("bShouldUseLotsOfDynamicShadows", "True")],
      why="Dynamic shadows re-project every frame and cost real GPU time in build fights.",
      changes="Sets bShouldUseLotsOfDynamicShadows=False in GameUserSettings.ini.",
      risk="safe", impact="high", recommended="recommended",
      tags=["fortnite", "shadows", "competitive"]),
    T("fn-012", "Lowest Shadow Quality",
      "Forces Fortnite shadow quality to Low.",
      actions=[SG("sg.ShadowQuality", "0")],
      revert=[SG("sg.ShadowQuality", "3")],
      why="Shadow rasterization is one of the biggest per-frame costs in Fortnite.",
      changes="Sets sg.ShadowQuality=0 under [ScalabilityGroups] in GameUserSettings.ini.",
      risk="safe", impact="high", recommended="recommended",
      tags=["fortnite", "shadows", "graphics"]),
    T("fn-013", "Disable Post-Processing",
      "Drops Fortnite post-processing (bloom, DOF, color grading).",
      actions=[SG("sg.PostProcessQuality", "0")],
      revert=[SG("sg.PostProcessQuality", "3")],
      why="Bloom, depth of field and color grading add frame time with zero competitive value.",
      changes="Sets sg.PostProcessQuality=0 under [ScalabilityGroups] in GameUserSettings.ini.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["fortnite", "postprocessing", "graphics"]),
    T("fn-014", "Lowest Effects Quality",
      "Lowers Fortnite effects (smoke, explosions, particles) quality.",
      actions=[SG("sg.EffectsQuality", "0")],
      revert=[SG("sg.EffectsQuality", "3")],
      why="Heavy particle effects can stutter fights; lowering them steadies frame times.",
      changes="Sets sg.EffectsQuality=0 under [ScalabilityGroups] in GameUserSettings.ini.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["fortnite", "effects", "graphics"]),
    T("fn-015", "Disable Motion Blur",
      "Turns off Fortnite motion blur for clearer tracking.",
      actions=[INI("bMotionBlur", "False")],
      revert=[INIDEL("bMotionBlur")],
      why="Motion blur smears targets during fast flicks and costs GPU time.",
      changes="Sets bMotionBlur=False in GameUserSettings.ini.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["fortnite", "motionblur", "competitive"]),
    T("fn-016", "Disable Grass",
      "Removes Fortnite grass rendering entirely.",
      actions=[INI("bShowGrass", "False")],
      revert=[INIDEL("bShowGrass")],
      why="Grass adds draw-call overhead with zero competitive value.",
      changes="Sets bShowGrass=False in GameUserSettings.ini.",
      risk="safe", impact="low", recommended="recommended",
      tags=["fortnite", "grass", "fps"]),
    T("fn-017", "Disable Anti-Aliasing",
      "Forces Fortnite to render with anti-aliasing disabled.",
      actions=[INI("FortAntiAliasingMethod", "Disabled")],
      revert=[INIDEL("FortAntiAliasingMethod")],
      why="AA over a sharp competitive image costs FPS and can soften far targets.",
      changes="Sets FortAntiAliasingMethod=Disabled in GameUserSettings.ini.",
      risk="safe", impact="high", recommended="recommended",
      tags=["fortnite", "antialiasing", "fps"]),
    T("fn-018", "Disable Global Illumination",
      "Drops Fortnite global illumination quality to off.",
      actions=[INI("DesiredGlobalIlluminationQuality", "0")],
      revert=[INI("DesiredGlobalIlluminationQuality", "2")],
      why="GI (Lumen) is one of the most expensive lighting passes in UE5 Fortnite.",
      changes="Sets DesiredGlobalIlluminationQuality=0 in GameUserSettings.ini.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["fortnite", "lighting", "lumen"]),
    T("fn-019", "Disable Reflections",
      "Drops Fortnite reflection quality to off.",
      actions=[INI("DesiredReflectionQuality", "0")],
      revert=[INI("DesiredReflectionQuality", "2")],
      why="Screen-space and Lumen reflections add a heavy per-frame cost.",
      changes="Sets DesiredReflectionQuality=0 in GameUserSettings.ini.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["fortnite", "reflections", "lumen"]),
    T("fn-020", "Lowest Shading Quality",
      "Forces the cheapest shading mode for maximum FPS.",
      actions=[INI("DesiredShadingQuality", "0")],
      revert=[INI("DesiredShadingQuality", "2")],
      why="Shading quality scales expensive per-pixel lighting work.",
      changes="Sets DesiredShadingQuality=0 in GameUserSettings.ini.",
      risk="safe", impact="high", recommended="recommended",
      tags=["fortnite", "shading", "fps"]),
    T("fn-021", "Lowest Texture Quality",
      "Frees VRAM by forcing lowest texture streaming quality.",
      actions=[INI("DesiredTextureQuality", "0")],
      revert=[INI("DesiredTextureQuality", "2")],
      why="Lower texture quality trims VRAM pressure and texture streaming hitches.",
      changes="Sets DesiredTextureQuality=0 in GameUserSettings.ini.",
      risk="safe", impact="low", recommended="recommended",
      tags=["fortnite", "textures", "vram"]),
    T("fn-022", "Foliage Off",
      "Removes Fortnite foliage quality.",
      actions=[INI("DesiredFoliageQuality", "0")],
      revert=[INI("DesiredFoliageQuality", "2")],
      why="Foliage culling saves CPU/GPU work in heavily built POIs.",
      changes="Sets DesiredFoliageQuality=0 in GameUserSettings.ini.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["fortnite", "foliage", "fps"]),
    T("fn-023", "Competitive View Distance",
      "Sets Fortnite view distance to Medium for visibility with FPS saved.",
      actions=[INI("DesiredViewDistanceQuality", "2")],
      revert=[INI("DesiredViewDistanceQuality", "3")],
      why="Epic view distance streams extra geometry; Medium keeps distant players visible while saving GPU.",
      changes="Sets DesiredViewDistanceQuality=2 in GameUserSettings.ini.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["fortnite", "viewdistance", "competitive"]),
    T("fn-024", "Disable Ray Tracing",
      "Turns off Fortnite ray tracing entirely.",
      actions=[RT("r.RayTracing.EnableInGame", "False")],
      revert=[INIDEL_SEC("RayTracing", "r.RayTracing.EnableInGame")],
      why="RT is a massive GPU cost and provides zero competitive advantage.",
      changes="Sets r.RayTracing.EnableInGame=False under [RayTracing].",
      risk="safe", impact="high", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["fortnite", "raytracing", "fps"]),
    T("fn-025", "Disable Nanite",
      "Turns off Nanite geometry for faster CPU-side culling.",
      actions=[INI("bUseNanite", "False")],
      revert=[INIDEL("bUseNanite")],
      why="Nanite geometry adds CPU cost in dense build fights.",
      changes="Sets bUseNanite=False in GameUserSettings.ini.",
      risk="safe", impact="high", recommended="recommended",
      tags=["fortnite", "nanite", "geometry"]),
    T("fn-026", "Disable DLSS Frame Generation",
      "Turns off DLSS Frame Generation for lower render latency.",
      actions=[INI("bEnableDLSSFrameGeneration", "False")],
      revert=[INIDEL("bEnableDLSSFrameGeneration")],
      why="Frame generation adds latency and ghosting; off is more consistent for input.",
      changes="Sets bEnableDLSSFrameGeneration=False in GameUserSettings.ini.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["fortnite", "dlss", "latency"]),
    T("fn-027", "Reflex Low Latency",
      "Enables Fortnite's low-latency input mode.",
      actions=[INI("LowInputLatencyModeIsEnabled", "True")],
      revert=[INI("LowInputLatencyModeIsEnabled", "False")],
      why="Low latency mode trims the render queue for snappier edits and input response.",
      changes="Sets LowInputLatencyModeIsEnabled=True in GameUserSettings.ini.",
      risk="safe", impact="high", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["fortnite", "reflex", "latency"]),
    T("fn-028", "Disable VSync",
      "Turns off VSync to remove added input latency.",
      actions=[INI("bUseVSync", "False")],
      revert=[INIDEL("bUseVSync")],
      why="VSync caps frames and adds a full frame of latency.",
      changes="Sets bUseVSync=False in GameUserSettings.ini.",
      risk="safe", impact="high", recommended="recommended",
      tags=["fortnite", "vsync", "latency"]),
    T("fn-029", "Disable Dynamic Resolution",
      "Turns off Fortnite's dynamic resolution scaling.",
      actions=[INI("bUseDynamicResolution", "False")],
      revert=[INIDEL("bUseDynamicResolution")],
      why="Dynamic resolution causes visual blur and resolution popping.",
      changes="Sets bUseDynamicResolution=False in GameUserSettings.ini.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["fortnite", "resolution", "stability"]),
    T("fn-030", "Multithreaded Rendering",
      "Enables Fortnite multithreaded rendering.",
      actions=[INI("bAllowMultithreadedRendering", "True")],
      revert=[INI("bAllowMultithreadedRendering", "False")],
      why="Lets Fortnite split rendering work across CPU cores for steadier frame times.",
      changes="Sets bAllowMultithreadedRendering=True in GameUserSettings.ini.",
      risk="safe", impact="high", recommended="recommended",
      tags=["fortnite", "cpu", "rendering"]),
    T("fn-031", "Keep Rendering in Background",
      "Prevents Fortnite dropping to the fake-frame hitch when unfocused.",
      actions=[INI("bStopRenderingInBackground", "False")],
      revert=[INIDEL("bStopRenderingInBackground")],
      why="Stopping background rendering can cause stutter when alt-tabbing back.",
      changes="Sets bStopRenderingInBackground=False in GameUserSettings.ini.",
      risk="safe", impact="low", recommended="recommended",
      tags=["fortnite", "background", "stutter"]),
    T("fn-032", "Disable Energy Saving",
      "Turns off Fortnite energy-saving throttling.",
      actions=[INI("bIsEnergySavingEnabledIdle", "False"),
               INI("bIsEnergySavingEnabledFocusLoss", "False")],
      revert=[INIDEL("bIsEnergySavingEnabledIdle"),
              INIDEL("bIsEnergySavingEnabledFocusLoss")],
      why="Energy saving downclocks the GPU at idle/focus loss and causes hiccups.",
      changes="Sets bIsEnergySavingEnabledIdle=False and bIsEnergySavingEnabledFocusLoss=False.",
      risk="safe", impact="low", recommended="recommended",
      tags=["fortnite", "power", "stutter"]),
    T("fn-033", "Disable Mouse Acceleration",
      "Turns off Fortnite mouse acceleration for 1:1 pointer input.",
      actions=[INI("bDisableMouseAcceleration", "False")],
      revert=[INIDEL("bDisableMouseAcceleration")],
      why="Mouse acceleration breaks muscle memory in a game about consistent flicks.",
      changes="Sets bDisableMouseAcceleration=False in GameUserSettings.ini.",
      risk="safe", impact="low", recommended="recommended",
      tags=["fortnite", "mouse", "input"]),
    T("fn-034", "Show FPS Counter",
      "Enables Fortnite's in-game FPS counter.",
      actions=[INI("bShowFPS", "True")],
      revert=[INIDEL("bShowFPS")],
      why="A visible FPS counter helps you verify the tweaks worked.",
      changes="Sets bShowFPS=True in GameUserSettings.ini.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["fortnite", "fps", "overlay"]),
    T("fn-035", "Lowest Textures (Scalability)",
      "Forces lowest texture quality in Fortnite scalability.",
      actions=[SG("sg.TextureQuality", "0")],
      revert=[INIDEL_SEC("ScalabilityGroups", "sg.TextureQuality")],
      why="Lowest texture streaming saves VRAM and trims loading hitches.",
      changes="Sets sg.TextureQuality=0 under [ScalabilityGroups].",
      risk="safe", impact="low", recommended="recommended",
      tags=["fortnite", "textures", "vram"]),
    T("fn-036", "Foliage Off (Scalability)",
      "Disables foliage quality in Fortnite scalability.",
      actions=[SG("sg.FoliageQuality", "0")],
      revert=[INIDEL_SEC("ScalabilityGroups", "sg.FoliageQuality")],
      why="Foliage is pure overhead in a game played for building and fighting.",
      changes="Sets sg.FoliageQuality=0 under [ScalabilityGroups].",
      risk="safe", impact="very low", recommended="recommended",
      tags=["fortnite", "foliage", "fps"]),
    T("fn-037", "Lowest Shading (Scalability)",
      "Forces lowest shading quality in Fortnite scalability.",
      actions=[SG("sg.ShadingQuality", "0")],
      revert=[INIDEL_SEC("ScalabilityGroups", "sg.ShadingQuality")],
      why="Lowest shading removes expensive per-pixel lighting for a solid FPS floor.",
      changes="Sets sg.ShadingQuality=0 under [ScalabilityGroups].",
      risk="safe", impact="high", recommended="recommended",
      tags=["fortnite", "shading", "fps"]),
    T("fn-038", "View Distance (Scalability)",
      "Sets Fortnite scalability view distance to Medium.",
      actions=[SG("sg.ViewDistanceQuality", "2")],
      revert=[INIDEL_SEC("ScalabilityGroups", "sg.ViewDistanceQuality")],
      why="Medium view distance keeps targets visible while cutting geometry streaming cost.",
      changes="Sets sg.ViewDistanceQuality=2 under [ScalabilityGroups].",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["fortnite", "viewdistance", "competitive"]),
    T("fn-039", "Performance Mesh Quality",
      "Lowers Fortnite mesh quality in Performance Mode.",
      actions=[PM("MeshQuality", "0")],
      revert=[INIDEL_SEC("PerformanceMode", "MeshQuality")],
      why="Lowest mesh quality cuts vertex work in dense POIs.",
      changes="Sets MeshQuality=0 under [PerformanceMode].",
      risk="safe", impact="low", recommended="recommended",
      tags=["fortnite", "mesh", "performance"]),
])
