"""Category: FPS — frame rate guidance and measurement."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("FPS", win_default="7,8,10,11")
CATEGORY = "FPS"

TWEAKS = validate_module("fps", [
    T("fps-001", "Uncap FPS in Game",
      "Guidance to remove FPS caps.",
      actions=[("guidance", "In games that default to 60 FPS caps (console ports), raise or remove the cap. Uncapped + high refresh is the biggest FPS gain you can get from settings alone.")],
      revert=[("guidance", "Re-cap FPS at 60.")],
      why="Console ports often ship with 60 FPS caps that waste PC hardware.",
      changes="Shows FPS-cap guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["fps", "cap", "refresh"]),
    T("fps-002", "Reduce Render Resolution",
      "Guidance on lowering render resolution.",
      actions=[("guidance", "If FPS is too low, lower the render resolution (100% -> 75%) or enable DLSS/FSR/XeSS Quality before dropping other settings — it is the single biggest FPS lever.")],
      revert=[("guidance", "Restore 100% render scale.")],
      why="Resolution scales pixel fill cost quadratically.",
      changes="Shows render-resolution guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["resolution", "renderscale", "fps"]),
    T("fps-003", "Disable Anti-Aliasing Overrides",
      "Guidance on AA settings.",
      actions=[("guidance", "Disable supersampling-style AA (MSAA 8x, SSAA) — it multiplies fill cost. Use a light TAA/FXAA or DLSS where available.")],
      revert=[("guidance", "Restore AA settings.")],
      why="MSAA/SSAA multiply the render cost per pixel.",
      changes="Shows AA guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["aa", "msaa", "fill"]),
    T("fps-004", "Disable Volumetric Effects",
      "Guidance to reduce volumetric clouds/fog.",
      actions=[("guidance", "Lower 'Volumetric clouds'/'Fog' to Low or Off in games that offer it — it is among the most expensive effects per frame.")],
      revert=[("guidance", "Restore volumetric quality.")],
      why="Volumetric rendering costs a large slice of GPU time.",
      changes="Shows volumetric guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["volumetric", "fog", "clouds"]),
    T("fps-005", "Disable Ray Tracing",
      "Guidance to turn off DXR.",
      actions=[("guidance", "For mid-range GPUs, turn ray tracing off (or to low) unless the title is RT-centric. RT can cut average FPS by 30-50%.")],
      revert=[("guidance", "Re-enable ray tracing.")],
      why="DXR consumes a disproportionate GPU budget.",
      changes="Shows ray-tracing guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["raytracing", "dxr", "fps"]),
    T("fps-006", "Lower Shadow Quality",
      "Guidance on shadow settings.",
      actions=[("guidance", "Shadows are rendered per-light and scale poorly. Set shadows to Medium (or High, never Ultra) for near-parity visuals at a big FPS saving.")],
      revert=[("guidance", "Restore shadow quality.")],
      why="Ultra shadows multiply render passes for marginal detail.",
      changes="Shows shadow guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["shadows", "lighting", "fps"]),
    T("fps-007", "Disable Motion Blur",
      "Guidance to turn off motion blur.",
      actions=[("guidance", "Turn off motion blur and depth of field. They are post-effects that cost GPU time and hurt clarity in competitive games.")],
      revert=[("guidance", "Re-enable motion blur.")],
      why="Post-effects add passes with no competitive benefit.",
      changes="Shows motion-blur guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["motionblur", "postfx", "fps"]),
    T("fps-008", "Lower Texture Pool Within VRAM",
      "Guidance on texture memory.",
      actions=[("guidance", "Set texture quality to fit within your VRAM (leave ~1GB headroom). Running out of VRAM causes the biggest FPS drops in modern games.")],
      revert=[("guidance", "Restore texture quality.")],
      why="VRAM overflow spills to system RAM and tanks frame rates.",
      changes="Shows texture-memory guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["textures", "vram", "memory"]),
    T("fps-009", "Use Per-Game Benchmark",
      "Guidance to benchmark per title.",
      actions=[("guidance", "Use each game's built-in benchmark (or CapFrameX) to compare settings. Change one setting at a time and re-measure average + 1% lows.")],
      revert=[("guidance", "No change to revert.")],
      why="Incremental measurement beats guessing which setting costs FPS.",
      changes="Shows benchmark-method guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["benchmark", "method", "fps"]),
    T("fps-010", "Close Background Encoders",
      "Guidance on background encoding.",
      actions=[("guidance", "Stop OBS/ShadowPlay/ReLive/Arc recording before a benchmark. Encoder load steals GPU video-engine and some render bandwidth.")],
      revert=[("guidance", "Restart the encoder.")],
      why="Background encoding consumes GPU resources during play.",
      changes="Shows encoder guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["encoder", "recording", "gpu"]),
    T("fps-011", "Lower CPU-Bound Settings",
      "Guidance on CPU-heavy settings.",
      actions=[("guidance", "When the CPU is the limit, lower draw distance, entity density, physics and AI settings. GPU settings stop mattering once you are CPU-bound.")],
      revert=[("guidance", "Restore the settings.")],
      why="CPU-bound frame times do not improve from GPU settings.",
      changes="Shows CPU-bound guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["cpu", "bound", "settings"]),
    T("fps-012", "Set Fixed Refresh in Drivers",
      "Guidance on driver refresh overrides.",
      actions=[("guidance", "Ensure the driver is not forcing a lower refresh rate per game profile (NVIDIA 'Preferred refresh rate' = Application-controlled).")],
      revert=[("guidance", "Restore the override.")],
      why="A driver refresh override silently caps your frame rate.",
      changes="Shows driver-refresh guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["refresh", "driver", "fps"]),
])
