"""Category: Frame Time — consistency and stutter analysis."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Frame Time", win_default="7,8,10,11")
CATEGORY = "Frame Time"

TWEAKS = validate_module("frame_time", [
    T("ft-001", "Measure 1% Lows",
      "Guidance to measure 1% lows.",
      actions=[("guidance", "Use CapFrameX or RTSS to log frame times. Compare the 1% low, not the average — smooth 1% lows are the real win.")],
      revert=[("guidance", "No change to revert.")],
      why="Average FPS hides stutter; 1% lows expose it.",
      changes="Shows 1%-low guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["frametime", "1%low", "measure"]),
    T("ft-002", "Cap Frame Rate for Consistency",
      "Guidance on capping for steady frame times.",
      actions=[("guidance", "If the GPU can hold 120 but spikes to 140, cap to 120 (or a value your GPU sustains). A stable cap removes the worst frame-time spikes.")],
      revert=[("guidance", "Remove the FPS cap.")],
      why="Running near the GPU's limit produces spiky frame times.",
      changes="Shows frame-cap guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["frametime", "cap", "consistency"]),
    T("ft-003", "Disable Scheduler Jitter",
      "Guidance on timer-resolution jitter.",
      actions=[("guidance", "Most games set their own timer resolution. Do not run third-party 'timer' utilities — they force 0.5ms timers system-wide and raise idle power for no real gain.")],
      revert=[("guidance", "Stop the timer utility.")],
      why="Global timer forcing adds idle CPU wake-ups without fixing stutter.",
      changes="Shows timer guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["timer", "jitter", "warn"]),
    T("ft-004", "Check DPC Latency",
      "Guidance to measure DPC latency.",
      actions=[("guidance", "Run LatencyMon for 5 minutes with a game open. Green 'Interrupt to process latency' means drivers are healthy; red DPC spikes point to a bad driver.")],
      revert=[("guidance", "No change to revert.")],
      why="High DPC latency shows up as audio crackle and micro-stutter.",
      changes="Shows DPC-latency guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["dpc", "latencymon", "driver"]),
    T("ft-005", "Update Chipset Drivers",
      "Guidance on chipset driver impact.",
      actions=[("guidance", "Install the latest chipset drivers from AMD/Intel. Old chipset drivers cause DPC spikes and USB jitter that show up as frame-time dips.")],
      revert=[("guidance", "Roll back the chipset driver.")],
      why="Chipset drivers control PCIe, USB and interrupt routing.",
      changes="Shows chipset-driver guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["chipset", "driver", "interrupt"]),
    T("ft-006", "Disable Third-Party Anti-Cheat Overhead",
      "Guidance on anti-cheat background cost.",
      actions=[("guidance", "Kernel anti-cheat (Vanguard, BattlEye, Easy Anti-Cheat) costs a little CPU at runtime. Keep it — removing it risks bans — but close the game's client app fully after exit.")],
      revert=[("guidance", "No change to revert.")],
      why="Anti-cheat drivers add a fixed per-frame cost you cannot remove safely.",
      changes="Shows anti-cheat guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["anticheat", "kernel", "overhead"]),
    T("ft-007", "Reduce USB Device Count",
      "Guidance on USB interrupt load.",
      actions=[("guidance", "Unplug unused USB devices (webcams, controllers) during play. Each device adds interrupts to shared USB controllers, which can cause frame jitter.")],
      revert=[("guidance", "Reconnect the devices.")],
      why="Shared USB controllers share interrupt handling with input.",
      changes="Shows USB guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["usb", "interrupt", "jitter"]),
    T("ft-008", "Check Thermal Throttling",
      "Guidance on throttling as a stutter cause.",
      actions=[("guidance", "Monitor CPU and GPU clocks during a game (HWiNFO). If clocks drop when stutter starts, you are thermal or power throttling — clean fans or improve cooling first.")],
      revert=[("guidance", "No change to revert.")],
      why="Throttling is the silent cause of regular frame-time dips.",
      changes="Shows throttling guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["thermal", "throttle", "clocks"]),
    T("ft-009", "Run Game on Same Disk as Windows",
      "Guidance on game drive placement.",
      actions=[("guidance", "For streaming-heavy games, install them on the same NVMe as Windows. Cross-drive reads and drive contention add asset-stream hitches.")],
      revert=[("guidance", "Move the game elsewhere.")],
      why="Asset streaming competes with the OS for drive bandwidth.",
      changes="Shows drive-placement guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["disk", "nvme", "streaming"]),
    T("ft-010", "Disable Browser Hardware Acceleration",
      "Guidance on browser GPU use.",
      actions=[("guidance", "Browsers with hardware acceleration offload compositing to the GPU, competing with the game for frame time. Close browsers or disable acceleration while gaming.")],
      revert=[("guidance", "Re-enable browser acceleration.")],
      why="Browser GPU load adds competing render work.",
      changes="Shows browser guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["browser", "gpu", "compositing"]),
    T("ft-011", "Test Frame Time After Each Tweak",
      "Guidance on A/B frame-time testing.",
      actions=[("guidance", "Change one tweak at a time and record a 5-minute frame-time log before and after. Revert anything that does not improve the 1% low.")],
      revert=[("guidance", "No change to revert.")],
      why="Cumulative tweaks hide which change actually helped.",
      changes="Shows A/B-testing guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["abtest", "frametime", "method"]),
    T("ft-012", "Prefer Dedicated GPU in Laptops",
      "Guidance for hybrid GPU frame pacing.",
      actions=[("guidance", "On laptops, force the discrete GPU for games (Windows Graphics settings). The iGPU-to-dGPU copy path adds a frame of latency and jitter.")],
      revert=[("guidance", "Restore automatic GPU selection.")],
      why="Hybrid graphics adds a copy between GPUs per frame.",
      changes="Shows hybrid-GPU guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"laptop": True},
      tags=["laptop", "hybrid", "frametime"]),
])
