"""Category: Game Profiles — per-title guidance for popular competitive games."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Game Profiles", win_default="7,8,10,11")
CATEGORY = "Game Profiles"

TWEAKS = validate_module("game_profiles", [
    T("gp-001", "Fortnite Profile",
      "Performance profile for Fortnite.",
      actions=[("guidance", "Fortnite: use Performance Mode (DX11/12 off), cap FPS to your refresh, Reflex enabled, view distance Epic, textures high, everything else low/off.")],
      revert=[("guidance", "Restore your usual Fortnite settings.")],
      why="Fortnite is CPU-bound in build fights; Performance Mode lowers overhead.",
      changes="Shows Fortnite guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["fortnite", "profile", "esports"]),
    T("gp-002", "Valorant Profile",
      "Performance profile for Valorant.",
      actions=[("guidance", "Valorant: resolution native or 4:3 stretched, everything low, V-Sync off, Reflex 'On + Boost', cap FPS 20+ above monitor refresh.")],
      revert=[("guidance", "Restore your usual Valorant settings.")],
      why="Valorant responds to raw FPS headroom and low latency.",
      changes="Shows Valorant guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["valorant", "profile", "esports"]),
    T("gp-003", "Counter-Strike 2 Profile",
      "Performance profile for CS2.",
      actions=[("guidance", "CS2: use the game's benchmark map (Nuke) to tune, set texture quality by VRAM, enable MSAA 2x, Reflex enabled, cap FPS below refresh for VRR.")],
      revert=[("guidance", "Restore your usual CS2 settings.")],
      why="CS2's smoke and shadows are CPU-heavy; benchmark before tuning.",
      changes="Shows CS2 guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["cs2", "counterstrike", "profile"]),
    T("gp-004", "Call of Duty Profile",
      "Performance profile for CoD titles.",
      actions=[("guidance", "CoD: DLSS/FSR Quality, reduced render resolution in options, weapon motion blur off, Reflex/Boost on, disable fullscreen optimizations if stutter persists.")],
      revert=[("guidance", "Restore your usual CoD settings.")],
      why="CoD's volumetric and ray-tracing effects hit GPU hard on low-end cards.",
      changes="Shows CoD guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["cod", "callofduty", "profile"]),
    T("gp-005", "Apex Legends Profile",
      "Performance profile for Apex.",
      actions=[("guidance", "Apex: adaptive resolution off, textures high, model detail high, shadows low, FPS cap via config (-fps_max), V-Sync off.")],
      revert=[("guidance", "Restore your usual Apex settings.")],
      why="Apex caps at 300 FPS and rewards consistent frame times.",
      changes="Shows Apex guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["apex", "respawn", "profile"]),
    T("gp-006", "Overwatch 2 Profile",
      "Performance profile for Overwatch 2.",
      actions=[("guidance", "OW2: use 'Custom' settings — render scale 100%, textures high, effects/lighting low, FPS cap to monitor, G-SYNC/FreeSync on.")],
      revert=[("guidance", "Restore your usual Overwatch settings.")],
      why="OW2 has consistent frame pacing when effects are limited.",
      changes="Shows Overwatch guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["overwatch", "ow2", "profile"]),
    T("gp-007", "Minecraft Profile",
      "Performance profile for Minecraft (Java).",
      actions=[("guidance", "Minecraft Java: allocate 4-8GB RAM via JVM args, install a modern Java, disable mipmaps if textures flicker, use Sodium for big FPS gains.")],
      revert=[("guidance", "Remove JVM args.")],
      why="Java heap sizing and the default renderer limit Minecraft FPS.",
      changes="Shows Minecraft guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["minecraft", "java", "sodium"]),
    T("gp-008", "Rocket League Profile",
      "Performance profile for Rocket League.",
      actions=[("guidance", "Rocket League: uncap FPS, V-Sync off, high quality shadows off, 'Performance' render mode, and use a wired connection to avoid input delay.")],
      revert=[("guidance", "Restore your usual Rocket League settings.")],
      why="Rocket League runs at high FPS cheaply once shadow work is limited.",
      changes="Shows Rocket League guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["rocketleague", "rl", "profile"]),
    T("gp-009", "League of Legends Profile",
      "Performance profile for LoL.",
      actions=[("guidance", "LoL: uncap FPS, character quality high, environment medium, shadow off (or low), keep V-Sync off, and enable 'Low Spec Mode' only on very weak GPUs.")],
      revert=[("guidance", "Restore your usual LoL settings.")],
      why="LoL is CPU-limited; high FPS with low settings keeps input crisp.",
      changes="Shows LoL guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["lol", "league", "profile"]),
    T("gp-010", "Rust Profile",
      "Performance profile for Rust.",
      actions=[("guidance", "Rust: graphics 'Fast' preset then raise textures to fit VRAM, disable HDRP bloom, install on SSD — Rust's asset streaming hits the disk constantly.")],
      revert=[("guidance", "Restore your usual Rust settings.")],
      why="Rust streams assets continuously; SSD and texture budget dominate.",
      changes="Shows Rust guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["rust", "survival", "profile"]),
    T("gp-011", "Escape from Tarkov Profile",
      "Performance profile for EFT.",
      actions=[("guidance", "Tarkov: textures high (if VRAM allows), shadows low, 'Object LOD quality' 2, 'Mip streaming' on, clear the cache before major patches, use offline raid to test FPS.")],
      revert=[("guidance", "Restore your usual Tarkov settings.")],
      why="Tarkov caches aggressively; stale caches cause stutter after updates.",
      changes="Shows Tarkov guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["tarkov", "eft", "profile"]),
    T("gp-012", "Warzone Profile",
      "Performance profile for Warzone.",
      actions=[("guidance", "Warzone: DLSS/FSR Balanced, render resolution 100%, 'Smart Access Memory/ReBAR' on, disable on-demand texture streaming if it stutters.")],
      revert=[("guidance", "Restore your usual Warzone settings.")],
      why="On-demand streaming can stall on slow connections.",
      changes="Shows Warzone guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["warzone", "cod", "profile"]),
])
