"""Category: Gaming — general gaming quality-of-life and performance."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Gaming", win_default="7,8,10,11")
CATEGORY = "Gaming"

TWEAKS = validate_module("gaming", [
    T("game-001", "Enable Game Mode",
      "Turns on Windows Game Mode.",
      actions=[
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\GameBar", "AutoGameModeEnabled", 1, "DWORD"),
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\GameBar", "AllowAutoGameMode", 1, "DWORD"),
      ],
      revert=[
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\GameBar", "AutoGameModeEnabled", 0, "DWORD"),
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\GameBar", "AllowAutoGameMode", 0, "DWORD"),
      ],
      why="Game Mode allocates scheduling priority and GPU budget to the game.",
      changes="Enables Game Mode.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["gamemode", "priority", "gaming"]),
    T("game-002", "Disable Game Bar",
      "Turns off the Xbox Game Bar widget layer.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\GameDVR", "AppCaptureEnabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\GameDVR", "AppCaptureEnabled", 1, "DWORD")],
      why="Removes the Game Bar capture/overlay hook when you do not use it.",
      changes="Disables Game DVR capture.",
      risk="safe", impact="low", recommended="recommended",
      tags=["gamebar", "dvr", "overlay"]),
    T("game-003", "Disable Background Game Recording",
      "Stops background recording entirely.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\GameDVR", "BackgroundRecordingEnabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\GameDVR", "BackgroundRecordingEnabled", 1, "DWORD")],
      why="Background recording keeps the video pipeline warm behind every game.",
      changes="Disables background recording.",
      risk="safe", impact="low", recommended="recommended",
      tags=["recording", "background", "dvr"]),
    T("game-004", "Install Gaming Features",
      "Guidance to install the optional gaming features.",
      actions=[("guidance", "Install 'Media Feature Pack' (Windows N) and optional 'Gaming' features in Settings > Apps > Optional features if a game complains about missing DirectShow/Media Foundation.")],
      revert=[("guidance", "Uninstall the optional features.")],
      why="Missing media runtime blocks older games' cutscenes and audio.",
      changes="Shows gaming-feature guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["features", "media", "runtime"]),
    T("game-005", "Set Game Client Priorities",
      "Guidance on launcher vs game process priorities.",
      actions=[("guidance", "Let the game manage its own threads. Do not force 'Above normal' priority on game processes globally — it starves audio/network threads and can add stutter.")],
      revert=[("guidance", "Reset process priorities.")],
      why="Forced priorities unbalance the process stack the game designed.",
      changes="Shows process-priority guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["priority", "process", "launcher"]),
    T("game-007", "Enable Hardware-Accelerated Video in Games",
      "Guidance for video-playback games.",
      actions=[("guidance", "For games that stream video, enable 'hardware acceleration' in the game's media settings so decoding runs on the GPU decoder, not the CPU.")],
      revert=[("guidance", "Disable hardware acceleration.")],
      why="CPU video decode steals cores from the game simulation.",
      changes="Shows video-decoding guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["video", "decode", "cpu"]),
    T("game-008", "Close Launchers After Start",
      "Guidance to exit store launchers post-launch.",
      actions=[("guidance", "After a game starts, exit its launcher (Epic, Riot, Battle.net, Ubisoft Connect). Launchers keep auto-update and telemetry processes running.")],
      revert=[("guidance", "Keep launchers open.")],
      why="Launchers run update checks and services that steal CPU/battery.",
      changes="Shows launcher guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["launcher", "background", "updater"]),
    T("game-009", "Disable Discord/Steam In-Game Overlay",
      "Guidance to turn off chat overlays.",
      actions=[("guidance", "In Discord and Steam, disable the in-game overlay for competitive titles. Overlay injection hooks the renderer and adds input/GPU overhead.")],
      revert=[("guidance", "Re-enable overlays.")],
      why="Overlay injection adds a hook into every game frame.",
      changes="Shows overlay guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["discord", "steam", "overlay"]),
    T("game-010", "Disable Auto Game Saves Syncing",
      "Guidance to reduce save-sync background load.",
      actions=[("guidance", "If a cloud-save service (Steam Cloud, Game Bar, Xbox cloud) uploads constantly, disable it per-game to stop background disk/network churn during play.")],
      revert=[("guidance", "Re-enable cloud saves.")],
      why="Save sync can spike disk and network activity mid-match.",
      changes="Shows save-sync guidance.",
      risk="safe", impact="very low", recommended="optional",
      tags=["sync", "cloud", "saves"]),
    T("game-011", "Verify Game File Integrity",
      "Guidance to repair corrupted game files.",
      actions=[("guidance", "If a game stutters or crashes after updates, run the launcher's 'Verify/Repair' option. Corrupted shader or asset files cause random hitches.")],
      revert=[("guidance", "No change to revert.")],
      why="Repairing files removes a common hidden stutter source.",
      changes="Shows file-integrity guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["verify", "repair", "files"]),
    T("game-012", "Game Folder on SSD",
      "Guidance to install games on the fastest drive.",
      actions=[("guidance", "Install games on an NVMe SSD (and on the same drive as Windows where possible). HDD installs are the top cause of texture-pop and load stutter in modern titles.")],
      revert=[("guidance", "Move games back to the HDD.")],
      why="Sequential reads are essential for streaming assets in DX12 games.",
      changes="Shows SSD guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["ssd", "nvme", "install"]),
    T("game-013", "Keep Graphics Drivers Current for New Titles",
      "Guidance on driver timings.",
      actions=[("guidance", "Install the Game Ready/Adrenalin driver matching a new game's release for its optimized profile; otherwise stay on a known-good version.")],
      revert=[("guidance", "Roll back the driver.")],
      why="Day-one drivers ship with per-game optimization profiles.",
      changes="Shows driver-timing guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["driver", "profile", "release"]),
    T("game-014", "Run Game on Dedicated GPU",
      "Guidance for laptop GPU assignment.",
      actions=[("guidance", "In Windows Settings > Display > Graphics set each game to the discrete GPU ('High performance'). Laptops often default games to the iGPU.")],
      revert=[("guidance", "Restore automatic GPU selection.")],
      why="The iGPU default tanks game performance on laptops.",
      changes="Shows GPU-assignment guidance.",
      risk="safe", impact="high", recommended="recommended",
      when={"laptop": True},
      tags=["laptop", "dgpu", "assignment"]),
    T("game-015", "Disable OneDrive During Play",
      "Guidance to pause OneDrive sync while gaming.",
      actions=[("guidance", "Pause OneDrive sync (or set its folder to 'Only known folders') during long sessions. Background sync spikes disk latency and can hitch streaming games.")],
      revert=[("guidance", "Resume OneDrive sync.")],
      why="OneDrive sync bursts raise disk latency during gameplay.",
      changes="Shows OneDrive guidance.",
      risk="safe", impact="very low", recommended="optional",
      tags=["onedrive", "sync", "disk"]),
    T("game-016", "Enable Game Overlay for Recording Only",
      "Guidance for recording needs.",
      actions=[("guidance", "If you record, keep only one capture tool active (e.g. OBS with NVENC/AMF) and disable every other overlay to avoid capture-controller conflicts.")],
      revert=[("guidance", "No change to revert.")],
      why="Multiple capture hooks fight over the same encoder queue.",
      changes="Shows capture-tool guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["obs", "capture", "encoder"]),
])
