"""Category: GPU — general graphics card and renderer tweaks."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("GPU", win_default="7,8,10,11")
CATEGORY = "GPU"

TWEAKS = validate_module("gpu", [
    T("gpu-001", "Enable Hardware Accelerated GPU Scheduling",
      "Lets the GPU driver schedule work without CPU help.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "HwSchMode", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "HwSchMode", 2, "DWORD")],
      why="HAGS reduces CPU scheduling overhead for the graphics stack. HwSchMode 1 enables it; 2 disables it.",
      changes="Sets GPU hardware scheduling mode to On.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["hags", "scheduling", "gpu"]),
    T("gpu-002", "Disable Multiplane Overlay",
      "Turns off MPO to avoid composition glitches.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "OverlayTestMode", 5, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "OverlayTestMode")],
      why="Known MPO bug: artifacts/stutters on some driver+display combos; disabling it stabilizes the desktop.",
      changes="Sets OverlayTestMode to 5.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["mpo", "overlay", "compose"]),
    T("gpu-003", "Increase TDR Delay",
      "Lets the driver recover instead of resetting on long renders.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "TdrDelay", 10, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "TdrDelay")],
      why="Prevents 'Display driver stopped responding' crashes on heavy shader loads.",
      changes="Sets TDR timeout to 10 seconds.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["tdr", "crash", "driver"]),
    T("gpu-004", "Disable GPU Energy Counters",
      "Turns off energy counters for a small driver overhead saving.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Power", "EnergyEstimationEnabled", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Power", "EnergyEstimationEnabled", 1, "DWORD")],
      why="Skipping energy estimation removes periodic driver bookkeeping.",
      changes="Disables GPU energy estimation.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["energy", "counter", "driver"]),
    T("gpu-005", "Prefer Native Resolution",
      "Guidance to keep games at native resolution.",
      actions=[("guidance", "Run games at your monitor's native resolution. Scaling from a lower internal res (except via FSR/XeSS/RSR) adds blur and extra compositing work.")],
      revert=[("guidance", "No change to revert.")],
      why="Native rendering avoids the extra scale pass entirely.",
      changes="Shows native-resolution guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["resolution", "native", "scaling"]),
    T("gpu-006", "Disable Background GPU Apps",
      "Guidance to close GPU-using background apps.",
      actions=[("guidance", "Close browsers with hardware acceleration, and disable overlays (Steam/Discord/NVIDIA/AMD/Arc) before benchmarks. Each adds GPU time and frame jitter.")],
      revert=[("guidance", "Reopen your usual apps.")],
      why="Background GPU load steals frame time from the game.",
      changes="Shows background-app guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["background", "apps", "gpu"]),
    T("gpu-007", "Clear Stale GPU Cache",
      "Guidance to clear GPU driver caches.",
      actions=[("guidance", "After driver updates, old shader caches can conflict. Clear them via NVIDIA Control Panel or by deleting %AppData% shader cache folders while games are closed.")],
      revert=[("guidance", "Let caches rebuild.")],
      why="Corrupt/stale caches cause recompile hitches and glitches.",
      changes="Shows GPU cache guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["cache", "shaders", "driver"]),
    T("gpu-008", "Enable GPU Video Decoding",
      "Guidance to enable GPU-accelerated video.",
      actions=[("guidance", "Enable 'hardware acceleration' in browsers and video players so video decode runs on the GPU instead of the CPU.")],
      revert=[("guidance", "Disable hardware acceleration.")],
      why="GPU decode frees CPU threads for the game.",
      changes="Shows video-decode guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["video", "decode", "hardware"]),
    T("gpu-009", "Set Frame Rate Target",
      "Guidance to cap FPS slightly below refresh.",
      actions=[("guidance", "Cap FPS at ~3 below your monitor's refresh (e.g. 141 for 144Hz). This removes queued-frame latency and evens frame times when VRR is off.")],
      revert=[("guidance", "Remove the FPS cap.")],
      why="Capping avoids GPU queuing that inflates input latency.",
      changes="Shows FPS-cap guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["fps", "cap", "latency"]),
    T("gpu-010", "Avoid Driver Overclocks",
      "Guidance on safe GPU overclocking.",
      actions=[("guidance", "If you overclock, raise core in +15MHz steps and test with a stress load (e.g. FurMark/3DMark) before gameplay. A crashing overclock causes full driver resets.")],
      revert=[("guidance", "Reset clocks to defaults.")],
      why="An unstable overclock manifests as stutter and resets, not crashes.",
      changes="Shows overclocking guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["overclock", "clock", "stability"]),
    T("gpu-011", "Monitor GPU Hotspot",
      "Guidance to watch GPU temperatures.",
      actions=[("guidance", "Watch the GPU hotspot temperature (HWiNFO) during stress. Sustained 105C+ hotspots throttle clocks and cause frame drops.")],
      revert=[("guidance", "No change to revert.")],
      why="Thermal throttling is the most common hidden FPS limit.",
      changes="Shows temperature guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["temperature", "thermal", "throttle"]),
    T("gpu-012", "Turn Off VSync",
      "Guidance to disable VSync for latency.",
      actions=[("guidance", "Disable VSync in games when using VRR, or rely on in-game triple buffering. Forced VSync doubles buffer latency when FPS is below the refresh rate.")],
      revert=[("guidance", "Re-enable VSync.")],
      why="VSync below refresh rate adds a full frame of latency.",
      changes="Shows VSync guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["vsync", "latency", "sync"]),
    T("gpu-013", "Use Reflex/LLM/ULMB Aware Settings",
      "Guidance for latency-tech interplay.",
      actions=[("guidance", "Use only one latency system per game (Reflex, Anti-Lag or Low Latency Mode). Stacking them can raise CPU load instead of lowering latency.")],
      revert=[("guidance", "No change to revert.")],
      why="Redundant latency systems add coordination overhead.",
      changes="Shows latency-tech guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["reflex", "latency", "stack"]),
    T("gpu-014", "Check PCIe Lane Width",
      "Guidance to verify the GPU is on the full PCIe lanes.",
      actions=[("guidance", "Check the GPU's PCIe link (GPU-Z) under load. A card at x8 or x4 instead of x16 (or PCIe 3 instead of 4) can bottleneck modern GPUs.")],
      revert=[("guidance", "Re-seat the GPU and check BIOS lane split.")],
      why="A bandwidth-limited link caps the GPU's effective performance.",
      changes="Shows PCIe guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["pcie", "bandwidth", "slot"]),
    T("gpu-015", "Disable Fullscreen Scaled View",
      "Guidance to fix stretched aspect ratios.",
      actions=[("guidance", "Set GPU scaling to 'Aspect Ratio' (not stretch) for 4:3 competitive titles, or 'Disabled' and let the monitor scale for lowest latency.")],
      revert=[("guidance", "Restore default scaling.")],
      why="Stretched scaling adds a full-surface transform pass.",
      changes="Shows GPU-scaling guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["scaling", "aspect", "stretch"]),
    T("gpu-016", "Run GPU Benchmark",
      "Guidance for baseline GPU benchmarks.",
      actions=[("guidance", "Run 3DMark Time Spy (DX12) and a game-specific benchmark before/after changes. Compare 1% lows and average FPS, not just peak.")],
      revert=[("guidance", "No change to revert.")],
      why="A repeatable baseline proves whether a tweak helped.",
      changes="Shows benchmark guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["benchmark", "3dmark", "baseline"]),
    T("gpu-017", "Disable TDR Watchdog",
      "Turns off the GPU timeout watchdog so long shader jobs are never force-killed by the driver.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "TdrLevel", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "TdrLevel")],
      why="TdrLevel 0 disables timeout detection and recovery, preventing mid-render driver resets on very long shader builds.",
      changes="Sets TdrLevel to 0 (TDR off).",
      risk="advanced", impact="moderate", recommended="experimental", admin=True, confirm=True,
      tags=["tdr", "watchdog", "driver"]),
    T("gpu-018", "Raise TDR Recovery Attempts",
      "Allows more driver recoveries before Windows gives up on a hung display adapter.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "TdrLimitCount", 5, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "TdrLimitCount")],
      why="TdrLimitCount sets how many recoveries are tolerated inside the detection window before a full reset.",
      changes="Raises TDR recovery limit to 5.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["tdr", "recovery", "stability"]),
    T("gpu-019", "Extend TDR Detection Window",
      "Widens the time window in which TDR recoveries are counted, avoiding unnecessary full resets.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "TdrLimitTime", 10, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "TdrLimitTime")],
      why="TdrLimitTime spaces out the allowed recoveries so a burst of transient hitches does not trip the hard reset.",
      changes="Sets TDR limit window to 10 seconds.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["tdr", "window", "stability"]),
    T("gpu-020", "Extend GPU Hung Timeout",
      "Raises how long Windows waits before declaring the GPU hung, protecting long shader compiles.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "GpuTimeoutValue", 30, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "GpuTimeoutValue")],
      why="Slow shader/HLSL compilation can exceed the default 2-second budget; raising the timeout prevents premature driver resets.",
      changes="Raises the GPU hung timeout to 30 seconds.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["timeout", "shader", "driver"]),
    T("gpu-021", "Disable Multi-GPU Switching",
      "Stops Microsoft's hybrid graphics stack from hot-swapping between integrated and discrete adapters.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "EnableMsHybrid", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "EnableMsHybrid")],
      why="Adapter hot-switching causes a render pipeline flush and frame hitch; pinning one adapter removes the switching overhead.",
      changes="Sets EnableMsHybrid to 0 (switching off).",
      risk="moderate", impact="moderate", recommended="optional", admin=True,
      tags=["multigpu", "igpu", "discrete"]),
    T("gpu-022", "Prefer Hardware Render Path",
      "Forces the desktop composition stack onto the hardware renderer instead of software fallbacks.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "HardwareAccelerationMode", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "HardwareAccelerationMode")],
      why="Software rasterization steals CPU cycles; the hardware path keeps presentation work on the GPU.",
      changes="Sets HardwareAccelerationMode to 1.",
      risk="moderate", impact="moderate", recommended="optional", admin=True,
      tags=["acceleration", "renderer", "compose"]),
    T("gpu-023", "Disable DWM Composition",
      "Turns off Desktop Window Manager composition to remove the compositing layer overhead.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "CompositionPolicy", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "CompositionPolicy", 1, "DWORD")],
      why="Composition adds a full-screen present pass on every frame; disabling it is the classic low-overhead desktop trick.",
      changes="Sets DWM CompositionPolicy to 0.",
      risk="advanced", impact="high", recommended="advanced", admin=True, confirm=True,
      tags=["dwm", "composition", "desktop"]),
    T("gpu-024", "Disable DWM Visual Effects",
      "Cuts DWM visual effects (animations, shadows) for snappier UI redraws on weaker GPUs.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "ForceEffectMode", 5, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "ForceEffectMode")],
      why="Each visual effect costs a blur/shadow pass; mode 5 disables them all.",
      changes="Sets DWM ForceEffectMode to 5 (none).",
      risk="safe", impact="moderate", recommended="optional", admin=True,
      tags=["dwm", "effects", "performance"]),
    T("gpu-025", "Disable Aero Peek",
      "Turns off the Aero Peek taskbar preview animations to save a little composition work.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "EnableAeroPeek", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "EnableAeroPeek", 1, "DWORD")],
      why="Peek previews render extra live windows; disabling them reduces idle GPU activity.",
      changes="Disables Aero Peek.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["dwm", "peek", "preview"]),
    T("gpu-026", "Disable Desktop Animations",
      "Disables window minimize/maximize animations that cause extra composition work.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "AnimationAttribute", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "AnimationAttribute")],
      why="Transition animations trigger full-window redraws; level 0 removes them.",
      changes="Sets DWM AnimationAttribute to 0 (off).",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["dwm", "animation", "desktop"]),
    T("gpu-027", "Suppress Animations While Shifting",
      "Lets you hold Shift to instantly disable window animations, useful for remote sessions.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "AnimationsShiftKey", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "AnimationsShiftKey")],
      why="Gives an on-demand animation kill switch instead of forcing a global setting.",
      changes="Enables Shift-to-suppress animations.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["dwm", "animation", "remote"]),
    T("gpu-028", "Disable DWM Telemetry",
      "Stops the DWM Customer Experience Improvement Program from collecting UI rendering data.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "DisableCEIP", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "DisableCEIP")],
      why="Removes periodic DWM telemetry bookkeeping from the composition path.",
      changes="Disables DWM CEIP telemetry.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["dwm", "telemetry", "privacy"]),
    T("gpu-029", "Disable DWM Machine Check Redraw",
      "Stops DWM's full-surface redraw when the desktop changes, cutting jank on low-end GPUs.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "EnableMachineCheck", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "EnableMachineCheck")],
      why="The machine-check path forces an expensive full composition pass; disabling it keeps present work incremental.",
      changes="Disables DWM machine-check redraw.",
      risk="low", impact="moderate", recommended="optional", admin=True,
      tags=["dwm", "redraw", "jank"]),
    T("gpu-030", "Skip DWM Machine Check Fast Path",
      "Prevents the DWM machine-check fast-path shortcut that can degrade presentation cadence.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "UseMachineCheck", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "UseMachineCheck")],
      why="UseMachineCheck skips straight to a reduced-fidelity present path; disabling it keeps full-quality composition.",
      changes="Disables DWM machine-check fast path.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["dwm", "compose", "fidelity"]),
    T("gpu-031", "Shrink Taskbar Thumbnail Previews",
      "Reduces the size of taskbar window thumbnails, lowering the offscreen render cost.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "DefaultWindowThumbnailSize", 2, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "DefaultWindowThumbnailSize")],
      why="Live thumbnails re-render windows in a second surface; smaller thumbnails mean a cheaper present.",
      changes="Sets default thumbnail size to small.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["dwm", "thumbnail", "taskbar"]),
    T("gpu-032", "Disable Window Blur",
      "Turns off the blur-behind-windows effect that costs extra GPU fill passes.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "BlurBehindEnabled", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "BlurBehindEnabled", 1, "DWORD")],
      why="Blur requires grabbing, downsampling and re-blurring the backdrop on every frame.",
      changes="Disables blur-behind windows.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["dwm", "blur", "effects"]),
    T("gpu-033", "Disable Accent Color Title Bars",
      "Stops Windows from tinting title bars with the accent color, removing a per-window recolor pass.",
      actions=[("reg", "HKCU", r"SOFTWARE\Microsoft\Windows\DWM", "ColorPrevalence", 0, "DWORD")],
      revert=[("reg", "HKCU", r"SOFTWARE\Microsoft\Windows\DWM", "ColorPrevalence", 1, "DWORD")],
      why="Accent tinting forces DWM to recolor the caption surface; disabling it keeps frames neutral.",
      changes="Disables accent color on title bars.",
      risk="safe", impact="very low", recommended="optional", admin=False,
      tags=["dwm", "titlebar", "accent"]),
    T("gpu-034", "Disable Title-Bar Colorization",
      "Disables legacy DWM colorization of window title bars entirely.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "EnableWindowColorization", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "EnableWindowColorization")],
      why="Removes the extra colorize step on window frame surfaces.",
      changes="Disables window colorization.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["dwm", "colorize", "frame"]),
    T("gpu-035", "Enable WPF Hardware Acceleration",
      "Ensures WPF (.NET) apps render on the GPU instead of the software rasterizer.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Avalon.Graphics", "DisableHWAcceleration", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Avalon.Graphics", "DisableHWAcceleration")],
      why="WPF falls back to software rendering when the flag is set; clearing it restores GPU-accelerated tier 2 rendering.",
      changes="Enables Avalon/WPF hardware acceleration.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["wpf", "avalon", "acceleration"]),
    T("gpu-036", "Raise WPF Texture Cap",
      "Raises the maximum texture size WPF will use for its render surfaces.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Avalon.Graphics", "MaxTextureSize", 4096, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Avalon.Graphics", "MaxTextureSize")],
      why="Bigger textures let WPF composite large UI surfaces without splitting passes.",
      changes="Sets Avalon max texture size to 4096.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["wpf", "texture", "avalon"]),
    T("gpu-037", "Raise WPF MSAA Level",
      "Increases the multisample anti-aliasing quality WPF is allowed to use.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Avalon.Graphics", "MaxMultisampleType", 4, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Avalon.Graphics", "MaxMultisampleType")],
      why="Higher MSAA smooths WPF vector rendering edges at a small fill-rate cost.",
      changes="Sets Avalon max MSAA to 4x.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["wpf", "msaa", "quality"]),
    T("gpu-038", "Cap WPF Render Width",
      "Limits the offscreen width WPF renders at, cutting fill-rate on very large monitors.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Avalon.Graphics", "MaxRenderWidth", 1920, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Avalon.Graphics", "MaxRenderWidth")],
      why="Capping the render surface avoids wasted overdraw for content that will be scaled down anyway.",
      changes="Caps Avalon render width at 1920.",
      risk="low", impact="very low", recommended="optional", admin=True,
      tags=["wpf", "render", "fillrate"]),
    T("gpu-039", "Cap WPF Render Height",
      "Limits the offscreen height WPF renders at to reduce composition work.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Avalon.Graphics", "MaxRenderHeight", 1080, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Avalon.Graphics", "MaxRenderHeight")],
      why="Lower render resolution means fewer pixels per UI pass while keeping layout intact.",
      changes="Caps Avalon render height at 1080.",
      risk="low", impact="very low", recommended="optional", admin=True,
      tags=["wpf", "render", "resolution"]),
    T("gpu-040", "Force DirectDraw Hardware Acceleration",
      "Forces legacy DirectDraw apps onto the real hardware 2D path instead of software emulation.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\DirectDraw", "EmulationOnly", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\DirectDraw", "EmulationOnly")],
      why="Software emulation is slow and does not use the GPU blitter; clearing the emulation-only flag restores HW blits.",
      changes="Sets DirectDraw EmulationOnly to 0.",
      risk="safe", impact="moderate", recommended="optional", admin=True,
      tags=["directdraw", "emulation", "blit"]),
    T("gpu-041", "Raise Direct3D Texture Cap",
      "Raises the maximum texture size the Direct3D runtime will hand out to legacy apps.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Direct3D", "MaxTextureSize", 4096, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Direct3D", "MaxTextureSize")],
      why="Older engines downsample large textures when capped low; raising the cap preserves detail.",
      changes="Sets Direct3D max texture size to 4096.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["direct3d", "texture", "compat"]),
    T("gpu-042", "Disable DirectX Update Checks",
      "Stops the DirectX runtime from checking for optional updates during installs.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\DirectX", "CheckForUpdates", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\DirectX", "CheckForUpdates")],
      why="Removes a network round-trip and notification prompt every time a DirectX-based installer runs.",
      changes="Disables DirectX update checks.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["directx", "updates", "installer"]),
    T("gpu-043", "Disable Game DVR via Policy",
      "Group-policy kill switch for background Game DVR recording, freeing GPU encode work.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\GameDVR", "AllowGameDVR", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\GameDVR", "AllowGameDVR")],
      why="Background DVR recording keeps the GPU video encoder busy; policy disabling is the most reliable kill switch.",
      changes="Policies-off Game DVR recording.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["gamedvr", "recording", "encode"]),
    T("gpu-044", "Disable Game Bar via Policy",
      "Policy-disables the Game Bar overlay so it cannot hook into games or use GPU time.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\GameBar", "AllowGameBar", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\GameBar", "AllowGameBar")],
      why="The overlay intercepts game frames to draw its UI; removing it eliminates the hook overhead.",
      changes="Policies-off the Game Bar overlay.",
      risk="safe", impact="moderate", recommended="optional", admin=True,
      tags=["gamebar", "overlay", "capture"]),
    T("gpu-045", "Enable Auto Game Mode via Policy",
      "Policy-enables Windows Game Mode so the scheduler boosts games on launch.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\GameBar", "AllowAutoGameMode", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\GameBar", "AllowAutoGameMode")],
      why="Game Mode hands the GPU scheduler priority to the foreground game process.",
      changes="Enables automatic Game Mode by policy.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["gamemode", "scheduler", "policy"]),
    T("gpu-046", "Clear DirectX Shader Cache",
      "Wipes the DirectX shader cache so stale or corrupt shader blobs recompile cleanly.",
      actions=[("cmd", r'if exist "%LOCALAPPDATA%\D3DSCache" rd /s /q "%LOCALAPPDATA%\D3DSCache"')],
      revert=[("cmd", r'if not exist "%LOCALAPPDATA%\D3DSCache" mkdir "%LOCALAPPDATA%\D3DSCache"')],
      why="Corrupt cached shaders cause compile hitches and glitches until purged; the cache rebuilds on demand.",
      changes="Deletes the local D3D shader cache folder.",
      risk="safe", impact="low", recommended="optional", admin=False,
      tags=["shader", "cache", "dxgi"]),
    T("gpu-047", "Export DirectX Diagnostic Report",
      "Generates a full DirectX/display diagnostic report to %TEMP% for troubleshooting.",
      actions=[("cmd", r'dxdiag /whql:off /x "%TEMP%\dxdiag_report.xml"')],
      revert=[("cmd", r'if exist "%TEMP%\dxdiag_report.xml" del /f /q "%TEMP%\dxdiag_report.xml"')],
      why="The XML report lists adapter state, driver dates and DirectX features, pinpointing renderer problems.",
      changes="Writes dxdiag_report.xml to %TEMP%.",
      risk="safe", impact="very low", recommended="optional", admin=False,
      tags=["dxdiag", "diagnostics", "driver"]),
    T("gpu-048", "Restart Desktop Window Manager",
      "Restarts dwm.exe so DWM registry changes apply without logging off (brief screen flicker).",
      actions=[("cmd", r'taskkill /F /IM dwm.exe')],
      revert=[],
      why="DWM reads most of its settings only at startup; restarting it applies composition tweaks immediately.",
      changes="Restarts the desktop compositor.",
      risk="low", impact="low", recommended="optional", admin=False,
      tags=["dwm", "restart", "apply"]),
    T("gpu-049", "Rescan Display Hardware",
      "Forces a full plug-and-play rescan so Windows re-enumerates the display adapter tree.",
      actions=[("cmd", r'pnputil /scan-devices')],
      revert=[],
      why="Re-enumeration clears stale adapter state after a driver install or after a hung device was unloaded.",
      changes="Scans for new/changed display hardware.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["pnputil", "rescan", "driver"]),
    T("gpu-050", "Disable Game DVR Capture System-Wide",
      "Turns off the system-level background Game DVR capture pipeline to free GPU encode time.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR", "AppCaptureEnabled", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR", "AppCaptureEnabled")],
      why="Constant background recording keeps the video encoder and frame copier busy even when you never open the Game Bar.",
      changes="Disables Game DVR app capture.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["gamedvr", "capture", "encoder"]),
    T("gpu-051", "Enable Automatic Game Mode",
      "Turns on automatic Game Mode so detected games get GPU scheduler priority by default.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\GameBar", "AutoGameModeEnabled", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\GameBar", "AutoGameModeEnabled")],
      why="Game Mode prioritizes the game process for GPU frames, reducing background frame stealing.",
      changes="Enables automatic Game Mode.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["gamemode", "priority", "scheduler"]),
    T("gpu-052", "Enable DirectDraw DPI Scaling",
      "Makes legacy DirectDraw apps DPI-aware so Windows does not bitmap-scale them.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\DirectDraw", "EnableDPIScaling", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\DirectDraw", "EnableDPIScaling")],
      why="Bitmap scaling of old fullscreen apps adds a stretch pass and blur; native DPI aware rendering avoids it.",
      changes="Enables DirectDraw DPI awareness.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["directdraw", "dpi", "scaling"]),
    T("gpu-053", "Restart Display Adapter",
      "Cycles the primary display adapter's power state to clear a hung or unstable driver without rebooting.",
      actions=[("cmd", r'powershell -NoProfile -Command "Get-PnpDevice -Class Display | ForEach-Object { Disable-PnpDevice -InstanceId $_.InstanceId -Confirm:$false; Enable-PnpDevice -InstanceId $_.InstanceId -Confirm:$false }"')],
      revert=[],
      why="Disabling and re-enabling the adapter forces a clean driver reload, recovering from a wedged GPU state.",
      changes="Disables and re-enables the display adapter.",
      risk="moderate", impact="high", recommended="experimental", admin=True, confirm=True,
      tags=["reset", "driver", "adapter"]),
])
