"""Category: GPU — general graphics card and renderer tweaks."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("GPU", win_default="7,8,10,11")
T_perf = make_T("Performance", win_default="7,8,10,11")
CATEGORY = "GPU"
_ALL_GPU = {"gpu": ["nvidia", "amd", "intel"]}

TWEAKS = validate_module("gpu", [
    # ---- Core GPU hardware tweaks (stay in GPU category) ----
    T("gpu-001", "Enable Hardware Accelerated GPU Scheduling",
      "Lets the GPU driver schedule work without CPU help.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "HwSchMode", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "HwSchMode", 2, "DWORD")],
      why="HAGS reduces CPU scheduling overhead for the graphics stack. HwSchMode 1 enables it; 2 disables it.",
      changes="Sets GPU hardware scheduling mode to On.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      when=_ALL_GPU,
      tags=["hags", "scheduling", "gpu"]),
    T("gpu-002", "Disable Multiplane Overlay",
      "Turns off MPO to avoid composition glitches.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "OverlayTestMode", 5, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "OverlayTestMode")],
      why="Known MPO bug: artifacts/stutters on some driver+display combos; disabling it stabilizes the desktop.",
      changes="Sets OverlayTestMode to 5.",
      risk="safe", impact="low", recommended="optional", admin=True,
      when=_ALL_GPU,
      tags=["mpo", "overlay", "compose"]),
    T("gpu-003", "Increase TDR Delay",
      "Lets the driver recover instead of resetting on long renders.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "TdrDelay", 10, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "TdrDelay")],
      why="Prevents 'Display driver stopped responding' crashes on heavy shader loads.",
      changes="Sets TDR timeout to 10 seconds.",
      risk="safe", impact="low", recommended="optional", admin=True,
      when=_ALL_GPU,
      tags=["tdr", "crash", "driver"]),
    T("gpu-018", "Raise TDR Recovery Attempts",
      "Allows more driver recoveries before Windows gives up on a hung display adapter.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "TdrLimitCount", 5, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "TdrLimitCount")],
      why="TdrLimitCount sets how many recoveries are tolerated inside the detection window before a full reset.",
      changes="Raises TDR recovery limit to 5.",
      risk="low", impact="low", recommended="optional", admin=True,
      when=_ALL_GPU,
      tags=["tdr", "recovery", "stability"]),
    T("gpu-019", "Extend TDR Detection Window",
      "Widens the time window in which TDR recoveries are counted, avoiding unnecessary full resets.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "TdrLimitTime", 10, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "TdrLimitTime")],
      why="TdrLimitTime spaces out the allowed recoveries so a burst of transient hitches does not trip the hard reset.",
      changes="Sets TDR limit window to 10 seconds.",
      risk="low", impact="low", recommended="optional", admin=True,
      when=_ALL_GPU,
      tags=["tdr", "window", "stability"]),
    T("gpu-020", "Extend GPU Hung Timeout",
      "Raises how long Windows waits before declaring the GPU hung, protecting long shader compiles.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "GpuTimeoutValue", 30, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "GpuTimeoutValue")],
      why="Slow shader/HLSL compilation can exceed the default 2-second budget; raising the timeout prevents premature driver resets.",
      changes="Raises the GPU hung timeout to 30 seconds.",
      risk="low", impact="low", recommended="optional", admin=True,
      when=_ALL_GPU,
      tags=["timeout", "shader", "driver"]),
    T("gpu-021", "Disable Multi-GPU Switching",
      "Stops Microsoft's hybrid graphics stack from hot-swapping between integrated and discrete adapters.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "EnableMsHybrid", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "EnableMsHybrid")],
      why="Adapter hot-switching causes a render pipeline flush and frame hitch; pinning one adapter removes the switching overhead.",
      changes="Sets EnableMsHybrid to 0 (switching off).",
      risk="moderate", impact="moderate", recommended="optional", admin=True,
      when={"laptop": False, "gpu": ["nvidia", "amd", "intel"]},
      tags=["multigpu", "igpu", "discrete"]),
    T("gpu-022", "Prefer Hardware Render Path",
      "Forces the desktop composition stack onto the hardware renderer instead of software fallbacks.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "HardwareAccelerationMode", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "HardwareAccelerationMode")],
      why="Software rasterization steals CPU cycles; the hardware path keeps presentation work on the GPU.",
      changes="Sets HardwareAccelerationMode to 1.",
      risk="moderate", impact="moderate", recommended="optional", admin=True,
      when=_ALL_GPU,
      tags=["acceleration", "renderer", "compose"]),
    T("gpu-024", "Disable DWM Visual Effects",
      "Cuts DWM visual effects (animations, shadows) for snappier UI redraws on weaker GPUs.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "ForceEffectMode", 5, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "ForceEffectMode")],
      why="Each visual effect costs a blur/shadow pass; mode 5 disables them all.",
      changes="Sets DWM ForceEffectMode to 5 (none).",
      risk="safe", impact="moderate", recommended="optional", admin=True,
      when={"gpu_type": ["dedicated"]},
      tags=["dwm", "effects", "performance"]),
    T("gpu-025", "Disable Aero Peek",
      "Turns off the Aero Peek taskbar preview animations to save a little composition work.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "EnableAeroPeek", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "EnableAeroPeek", 1, "DWORD")],
      why="Peek previews render extra live windows; disabling them reduces idle GPU activity.",
      changes="Disables Aero Peek.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      when=_ALL_GPU,
      tags=["dwm", "peek", "preview"]),
    T("gpu-060", "Enable MSI Mode for GPU",
      "Enables Message Signaled Interrupts on the display adapter for lower interrupt latency.",
      actions=[("cmd", r'powershell -NoProfile -Command "Get-PnpDevice -Class Display | ForEach-Object { $p = $_.InstanceId -replace \'\\\',\'#\' }; reg query \"HKLM\\SYSTEM\\CurrentControlSet\\Enum\\PCI\" /s /f MSISupported /k 2>$null | ForEach-Object { $k = $_.Trim(); if ($k -match \'MSISupported\') { $d = (Get-ItemProperty -Path \"Registry::HKEY_LOCAL_MACHINE\\$k\" -ErrorAction SilentlyContinue).MSISupported; if ($d -ne 1) { Set-ItemProperty -Path \"Registry::HKEY_LOCAL_MACHINE\\$k\" -Name MSISupported -Value 1 -Type DWord } } }"')],
      revert=[("cmd", r'powershell -NoProfile -Command "Get-ChildItem \"HKLM:\\SYSTEM\\CurrentControlSet\\Enum\\PCI\" -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.Name -match \'Device Specific\' } | ForEach-Object { $p = $_.PSPath; if ((Get-ItemProperty -Path $p -Name MSISupported -ErrorAction SilentlyContinue)) { Set-ItemProperty -Path $p -Name MSISupported -Value 0 -Type DWord } }"')],
      why="MSI interrupts allow the GPU to signal the CPU directly without polling, reducing interrupt dispatch latency.",
      changes="Enables MSI mode on display adapters.",
      risk="moderate", impact="moderate", recommended="optional", admin=True, confirm=True,
      when=_ALL_GPU,
      tags=["msi", "interrupt", "latency"]),

    # ---- GPU guidance & gaming tweaks (moved to Performance category) ----
    T_perf("gpu-005", "Prefer Native Resolution",
      "Guidance to keep games at native resolution.",
      actions=[("guidance", "Run games at your monitor's native resolution. Scaling from a lower internal res (except via FSR/XeSS/RSR) adds blur and extra compositing work.")],
      revert=[("guidance", "No change to revert.")],
      why="Native rendering avoids the extra scale pass entirely.",
      changes="Shows native-resolution guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["resolution", "native", "scaling"]),
    T_perf("gpu-006", "Disable Background GPU Apps",
      "Guidance to close GPU-using background apps.",
      actions=[("guidance", "Close browsers with hardware acceleration, and disable overlays (Steam/Discord/NVIDIA/AMD/Arc) before benchmarks. Each adds GPU time and frame jitter.")],
      revert=[("guidance", "Reopen your usual apps.")],
      why="Background GPU load steals frame time from the game.",
      changes="Shows background-app guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["background", "apps", "gpu"]),
    T_perf("gpu-007", "Clear Stale GPU Cache",
      "Guidance to clear GPU driver caches.",
      actions=[("guidance", "After driver updates, old shader caches can conflict. Clear them via NVIDIA Control Panel or by deleting %AppData% shader cache folders while games are closed.")],
      revert=[("guidance", "Let caches rebuild.")],
      why="Corrupt/stale caches cause recompile hitches and glitches.",
      changes="Shows GPU cache guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["cache", "shaders", "driver"]),
    T_perf("gpu-008", "Enable GPU Video Decoding",
      "Guidance to enable GPU-accelerated video.",
      actions=[("guidance", "Enable 'hardware acceleration' in browsers and video players so video decode runs on the GPU instead of the CPU.")],
      revert=[("guidance", "Disable hardware acceleration.")],
      why="GPU decode frees CPU threads for the game.",
      changes="Shows video-decode guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["video", "decode", "hardware"]),
    T_perf("gpu-009", "Set Frame Rate Target",
      "Guidance to cap FPS slightly below refresh.",
      actions=[("guidance", "Cap FPS at ~3 below your monitor's refresh (e.g. 141 for 144Hz). This removes queued-frame latency and evens frame times when VRR is off.")],
      revert=[("guidance", "Remove the FPS cap.")],
      why="Capping avoids GPU queuing that inflates input latency.",
      changes="Shows FPS-cap guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["fps", "cap", "latency"]),
    T_perf("gpu-010", "Avoid Driver Overclocks",
      "Guidance on safe GPU overclocking.",
      actions=[("guidance", "If you overclock, raise core in +15MHz steps and test with a stress load (e.g. FurMark/3DMark) before gameplay. A crashing overclock causes full driver resets.")],
      revert=[("guidance", "Reset clocks to defaults.")],
      why="An unstable overclock manifests as stutter and resets, not crashes.",
      changes="Shows overclocking guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["overclock", "clock", "stability"]),
    T_perf("gpu-011", "Monitor GPU Hotspot",
      "Guidance to watch GPU temperatures.",
      actions=[("guidance", "Watch the GPU hotspot temperature (HWiNFO) during stress. Sustained 105C+ hotspots throttle clocks and cause frame drops.")],
      revert=[("guidance", "No change to revert.")],
      why="Thermal throttling is the most common hidden FPS limit.",
      changes="Shows temperature guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["temperature", "thermal", "throttle"]),
    T_perf("gpu-012", "Turn Off VSync",
      "Guidance to disable VSync for latency.",
      actions=[("guidance", "Disable VSync in games when using VRR, or rely on in-game triple buffering. Forced VSync doubles buffer latency when FPS is below the refresh rate.")],
      revert=[("guidance", "Re-enable VSync.")],
      why="VSync below refresh rate adds a full frame of latency.",
      changes="Shows VSync guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["vsync", "latency", "sync"]),
    T_perf("gpu-013", "Use Reflex/LLM/ULMB Aware Settings",
      "Guidance for latency-tech interplay.",
      actions=[("guidance", "Use only one latency system per game (Reflex, Anti-Lag or Low Latency Mode). Stacking them can raise CPU load instead of lowering latency.")],
      revert=[("guidance", "No change to revert.")],
      why="Redundant latency systems add coordination overhead.",
      changes="Shows latency-tech guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["reflex", "latency", "stack"]),
    T_perf("gpu-014", "Check PCIe Lane Width",
      "Guidance to verify the GPU is on the full PCIe lanes.",
      actions=[("guidance", "Check the GPU's PCIe link (GPU-Z) under load. A card at x8 or x4 instead of x16 (or PCIe 3 instead of 4) can bottleneck modern GPUs.")],
      revert=[("guidance", "Re-seat the GPU and check BIOS lane split.")],
      why="A bandwidth-limited link caps the GPU's effective performance.",
      changes="Shows PCIe guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["pcie", "bandwidth", "slot"]),
    T_perf("gpu-015", "Disable Fullscreen Scaled View",
      "Guidance to fix stretched aspect ratios.",
      actions=[("guidance", "Set GPU scaling to 'Aspect Ratio' (not stretch) for 4:3 competitive titles, or 'Disabled' and let the monitor scale for lowest latency.")],
      revert=[("guidance", "Restore default scaling.")],
      why="Stretched scaling adds a full-surface transform pass.",
      changes="Shows GPU-scaling guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["scaling", "aspect", "stretch"]),
    T_perf("gpu-016", "Run GPU Benchmark",
      "Guidance for baseline GPU benchmarks.",
      actions=[("guidance", "Run 3DMark Time Spy (DX12) and a game-specific benchmark before/after changes. Compare 1% lows and average FPS, not just peak.")],
      revert=[("guidance", "No change to revert.")],
      why="A repeatable baseline proves whether a tweak helped.",
      changes="Shows benchmark guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["benchmark", "3dmark", "baseline"]),
    T_perf("gpu-027", "Suppress Animations While Shifting",
      "Lets you hold Shift to instantly disable window animations, useful for remote sessions.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "AnimationsShiftKey", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "AnimationsShiftKey")],
      why="Gives an on-demand animation kill switch instead of forcing a global setting.",
      changes="Enables Shift-to-suppress animations.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["dwm", "animation", "remote"]),
    T_perf("gpu-028", "Disable DWM Telemetry",
      "Stops the DWM Customer Experience Improvement Program from collecting UI rendering data.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "DisableCEIP", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "DisableCEIP")],
      why="Removes periodic DWM telemetry bookkeeping from the composition path.",
      changes="Disables DWM CEIP telemetry.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["dwm", "telemetry", "privacy"]),
    T_perf("gpu-029", "Disable DWM Machine Check Redraw",
      "Stops DWM's full-surface redraw when the desktop changes, cutting jank on low-end GPUs.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "EnableMachineCheck", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "EnableMachineCheck")],
      why="The machine-check path forces an expensive full composition pass; disabling it keeps present work incremental.",
      changes="Disables DWM machine-check redraw.",
      risk="low", impact="moderate", recommended="optional", admin=True,
      tags=["dwm", "redraw", "jank"]),
    T_perf("gpu-030", "Skip DWM Machine Check Fast Path",
      "Prevents the DWM machine-check fast-path shortcut that can degrade presentation cadence.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "UseMachineCheck", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "UseMachineCheck")],
      why="UseMachineCheck skips straight to a reduced-fidelity present path; disabling it keeps full-quality composition.",
      changes="Disables DWM machine-check fast path.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["dwm", "compose", "fidelity"]),
    T_perf("gpu-032", "Disable Window Blur",
      "Turns off the blur-behind-windows effect that costs extra GPU fill passes.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "BlurBehindEnabled", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\DWM", "BlurBehindEnabled", 1, "DWORD")],
      why="Blur requires grabbing, downsampling and re-blurring the backdrop on every frame.",
      changes="Disables blur-behind windows.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["dwm", "blur", "effects"]),
    T_perf("gpu-035", "Enable WPF Hardware Acceleration",
      "Ensures WPF (.NET) apps render on the GPU instead of the software rasterizer.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Avalon.Graphics", "DisableHWAcceleration", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Avalon.Graphics", "DisableHWAcceleration")],
      why="WPF falls back to software rendering when the flag is set; clearing it restores GPU-accelerated tier 2 rendering.",
      changes="Enables Avalon/WPF hardware acceleration.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["wpf", "avalon", "acceleration"]),
    T_perf("gpu-042", "Disable DirectX Update Checks",
      "Stops the DirectX runtime from checking for optional updates during installs.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\DirectX", "CheckForUpdates", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\DirectX", "CheckForUpdates")],
      why="Removes a network round-trip and notification prompt every time a DirectX-based installer runs.",
      changes="Disables DirectX update checks.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["directx", "updates", "installer"]),
    T_perf("gpu-043", "Disable Game DVR via Policy",
      "Group-policy kill switch for background Game DVR recording, freeing GPU encode work.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\GameDVR", "AllowGameDVR", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\GameDVR", "AllowGameDVR")],
      why="Background DVR recording keeps the GPU video encoder busy; policy disabling is the most reliable kill switch.",
      changes="Policies-off Game DVR recording.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["gamedvr", "recording", "encode"]),
    T_perf("gpu-044", "Disable Game Bar via Policy",
      "Policy-disables the Game Bar overlay so it cannot hook into games or use GPU time.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\GameBar", "AllowGameBar", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\GameBar", "AllowGameBar")],
      why="The overlay intercepts game frames to draw its UI; removing it eliminates the hook overhead.",
      changes="Policies-off the Game Bar overlay.",
      risk="safe", impact="moderate", recommended="optional", admin=True,
      tags=["gamebar", "overlay", "capture"]),
    T_perf("gpu-045", "Enable Auto Game Mode via Policy",
      "Policy-enables Windows Game Mode so the scheduler boosts games on launch.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\GameBar", "AllowAutoGameMode", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\GameBar", "AllowAutoGameMode")],
      why="Game Mode hands the GPU scheduler priority to the foreground game process.",
      changes="Enables automatic Game Mode by policy.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["gamemode", "scheduler", "policy"]),
    T_perf("gpu-046", "Clear DirectX Shader Cache",
      "Wipes the DirectX shader cache so stale or corrupt shader blobs recompile cleanly.",
      actions=[("cmd", r'if exist "%LOCALAPPDATA%\D3DSCache" rd /s /q "%LOCALAPPDATA%\D3DSCache"')],
      revert=[("cmd", r'if not exist "%LOCALAPPDATA%\D3DSCache" mkdir "%LOCALAPPDATA%\D3DSCache"')],
      why="Corrupt cached shaders cause compile hitches and glitches until purged; the cache rebuilds on demand.",
      changes="Deletes the local D3D shader cache folder.",
      risk="safe", impact="low", recommended="optional", admin=False,
      tags=["shader", "cache", "dxgi"]),
    T_perf("gpu-047", "Export DirectX Diagnostic Report",
      "Generates a full DirectX/display diagnostic report to %TEMP% for troubleshooting.",
      actions=[("cmd", r'dxdiag /whql:off /x "%TEMP%\dxdiag_report.xml"')],
      revert=[("cmd", r'if exist "%TEMP%\dxdiag_report.xml" del /f /q "%TEMP%\dxdiag_report.xml"')],
      why="The XML report lists adapter state, driver dates and DirectX features, pinpointing renderer problems.",
      changes="Writes dxdiag_report.xml to %TEMP%.",
      risk="safe", impact="very low", recommended="optional", admin=False,
      tags=["dxdiag", "diagnostics", "driver"]),
    T_perf("gpu-048", "Restart Desktop Window Manager",
      "Restarts dwm.exe so DWM registry changes apply without logging off (brief screen flicker).",
      actions=[("cmd", r'taskkill /F /IM dwm.exe')],
      revert=[],
      why="DWM reads most of its settings only at startup; restarting it applies composition tweaks immediately.",
      changes="Restarts the desktop compositor.",
      risk="low", impact="low", recommended="optional", admin=False,
      tags=["dwm", "restart", "apply"]),
    T_perf("gpu-050", "Disable Game DVR Capture System-Wide",
      "Turns off the system-level background Game DVR capture pipeline to free GPU encode time.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR", "AppCaptureEnabled", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR", "AppCaptureEnabled")],
      why="Constant background recording keeps the video encoder and frame copier busy even when you never open the Game Bar.",
      changes="Disables Game DVR app capture.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["gamedvr", "capture", "encoder"]),
    T_perf("gpu-051", "Enable Automatic Game Mode",
      "Turns on automatic Game Mode so detected games get GPU scheduler priority by default.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\GameBar", "AutoGameModeEnabled", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\GameBar", "AutoGameModeEnabled")],
      why="Game Mode prioritizes the game process for GPU frames, reducing background frame stealing.",
      changes="Enables automatic Game Mode.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["gamemode", "priority", "scheduler"]),
    T_perf("gpu-058", "Enable GPU MMCSS Scheduling",
      "Tunes the Multimedia Class Scheduler Service profile for GPU-priority tasks.",
      actions=[
          ("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\{e96051d2-4e84-4e3e-8403-e8ba6078e564}", "GPU Priority", 8, "DWORD"),
          ("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\{e96051d2-4e84-4e3e-8403-e8ba6078e564}", "Priority", 6, "DWORD"),
          ("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\{e96051d2-4e84-4e3e-8403-e8ba6078e564}", "Scheduling Category", "High", "STRING"),
      ],
      revert=[
          ("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\{e96051d2-4e84-4e3e-8403-e8ba6078e564}", "GPU Priority"),
          ("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\{e96051d2-4e84-4e3e-8403-e8ba6078e564}", "Priority"),
          ("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\{e96051d2-4e84-4e3e-8403-e8ba6078e564}", "Scheduling Category"),
      ],
      why="MMCSS governs thread priority for multimedia workloads; raising GPU priority and scheduling category gives game frames higher scheduling precedence.",
      changes="Sets GPU MMCSS task profile to high priority.",
      risk="safe", impact="moderate", recommended="optional", admin=True,
      tags=["mmcss", "scheduling", "priority"]),
])
