"""Category: Intel — Intel Graphics driver and control panel guidance."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Intel", win_default="7,8,10,11")
CATEGORY = "Intel"

TWEAKS = validate_module("intel", [
    T("int-001", "Disable Intel Gaming Overlay",
      "Guidance to disable the Arc Control overlay.",
      actions=[("guidance", "In Intel Arc Control or Intel Graphics Command Center, disable the in-game overlay to remove its hook from games.")],
      revert=[("guidance", "Re-enable the overlay.")],
      why="The overlay layer intercepts presentation and adds overhead.",
      changes="Shows overlay guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["intel"]},
      tags=["overlay", "arc", "intel"]),
    T("int-002", "Enable Resizable BAR",
      "Guidance to enable ReBAR for Arc GPUs.",
      actions=[("guidance", "For Intel Arc GPUs, enable 'Resizable BAR' in the BIOS (with Above 4G Decoding) — Arc requires it for full performance in many titles.")],
      revert=[("guidance", "Disable ReBAR.")],
      why="ReBAR lets the CPU access the full VRAM, which Arc relies on.",
      changes="Shows ReBAR guidance.",
      risk="safe", impact="high", recommended="recommended",
      when={"gpu": ["intel"]},
      tags=["rebar", "vram", "bios"]),
    T("int-003", "Disable Intel VSync",
      "Disables driver-enforced VSync via the Intel graphics registry.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\*\Curver", "KMD_EnableVSync", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\*\Curver", "KMD_EnableVSync", 1, "DWORD")],
      why="Driver-enforced VSync caps effective rate and adds input lag. Disabling it lets the game or VRR handle sync.",
      changes="Disables Intel driver-level VSync.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      when={"gpu": ["intel"]},
      tags=["vsync", "latency", "sync"]),
    T("int-004", "Prefer Performance Mode",
      "Guidance to select performance GPU profiles.",
      actions=[("guidance", "In the Arc Control 'Performance' page, ensure power and thermal targets are at their max for desktop use, and confirm the GPU is not in a low-power profile.")],
      revert=[("guidance", "Restore balanced profiles.")],
      why="Power profiles gate the GPU's sustained clock ceiling.",
      changes="Shows performance-profile guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["intel"]},
      tags=["profile", "power", "performance"]),
    T("int-005", "Driver Update Guidance",
      "Guidance to keep Intel Graphics drivers current.",
      actions=[("guidance", "Install Intel Graphics drivers from intel.com or Windows Update, and check for Arc-specific Game On drivers for the latest game fixes.")],
      revert=[("guidance", "Roll back the driver.")],
      why="Arc GPUs improve substantially with new driver releases.",
      changes="Shows driver-update guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["intel"]},
      tags=["driver", "update", "gameon"]),
    T("int-006", "Enable Adaptive Sync",
      "Guidance to enable adaptive sync on supported panels.",
      actions=[("guidance", "Enable 'Adaptive Sync' in Intel Graphics Command Center for monitors that support it, and enable VRR in Windows, to remove tearing in borderless games.")],
      revert=[("guidance", "Disable Adaptive Sync.")],
      why="Adaptive sync smooths variable frame rates on compatible displays.",
      changes="Shows adaptive-sync guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["intel"]},
      tags=["adaptivesync", "vrr", "sync"]),
    T("int-007", "Shader Cache Guidance",
      "Guidance on Intel shader caching.",
      actions=[("guidance", "Keep the shader cache enabled (Windows and per-game). If a new Arc driver is installed, allow shaders to rebuild once — the first run may stutter.")],
      revert=[("guidance", "No change to revert.")],
      why="Driver updates invalidate shader caches, causing a one-time rebuild.",
      changes="Shows shader-cache guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["intel"]},
      tags=["shaders", "cache", "rebuild"]),
    T("int-008", "XeSS Upscaling Guidance",
      "Guidance on Intel XeSS upscaling.",
      actions=[("guidance", "In supported games, enable XeSS at 'Balanced' or 'Performance' to gain FPS with modest image-quality loss. Prefer the game's own XeSS over driver upscaling.")],
      revert=[("guidance", "Turn off XeSS.")],
      why="XeSS offloads upscaling to the XMX accelerators on Arc GPUs.",
      changes="Shows XeSS guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["intel"]},
      tags=["xess", "upscale", "ai"]),
    T("int-009", "Opt Out of Intel Telemetry",
      "Disables Intel driver telemetry via registry keys.",
      actions=[
          ("reg", "HKLM", r"SOFTWARE\Intel\DTEm", "TelemetryEnabled", 0, "DWORD"),
          ("reg", "HKLM", r"SOFTWARE\Policies\Intel\TeleClient", "DisableTelemetry", 1, "DWORD"),
      ],
      revert=[
          ("regdel", "HKLM", r"SOFTWARE\Intel\DTEm", "TelemetryEnabled"),
          ("regdel", "HKLM", r"SOFTWARE\Policies\Intel\TeleClient", "DisableTelemetry"),
      ],
      why="Telemetry services add occasional background wake-ups. Disabling them removes a background data collector.",
      changes="Disables Intel driver telemetry.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      when={"gpu": ["intel"]},
      tags=["telemetry", "privacy", "background"]),
    T("int-010", "Check Forced Max FPS",
      "Guidance to clear any forced FPS caps.",
      actions=[("guidance", "Check Intel Graphics Command Center for any per-app FPS limit that may have been set for a game — a stale cap limits your refresh rate headroom.")],
      revert=[("guidance", "Restore the FPS cap.")],
      why="Stale per-app frame caps silently cap performance.",
      changes="Shows FPS-cap guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["intel"]},
      tags=["fps", "cap", "limit"]),
    T("int-011", "Hybrid Graphics GPU Selection",
      "Guidance for choosing the discrete GPU on hybrid laptops.",
      actions=[("guidance", "On hybrid laptops, assign games to the discrete GPU in Windows Graphics settings and keep the Intel iGPU for desktop/streaming to balance load.")],
      revert=[("guidance", "Restore automatic GPU selection.")],
      why="Wrong GPU selection tanks performance or battery on hybrid systems.",
      changes="Shows hybrid-GPU guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["intel"]},
      tags=["hybrid", "igpu", "dGPU"]),
    T("int-012", "Fix Dual-GPU Tearing",
      "Guidance for tearing on dual-GPU laptops.",
      actions=[("guidance", "If tearing appears on a laptop with Intel iGPU + discrete GPU, try forcing 'Exclusive fullscreen' or disabling the iGPU display output in the BIOS if the discrete GPU drives the panel directly.")],
      revert=[("guidance", "No change to revert.")],
      why="Dual-GPU display paths can miss sync signals.",
      changes="Shows dual-GPU guidance.",
      risk="safe", impact="low", recommended="optional",
      when={"gpu": ["intel"]},
      tags=["tearing", "dual", "laptop"]),
    T("int-013", "Enable Intel Speed Shift",
      "Enables Intel Speed Shift Technology for faster CPU frequency transitions.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Power", "IntelSpeedShiftEnabled", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Power", "IntelSpeedShiftEnabled")],
      why="Speed Shift lets the hardware choose CPU frequency in microseconds instead of milliseconds, reducing latency spikes.",
      changes="Enables Intel Speed Shift Technology.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["speedshift", "cpu", "power"]),
    T("int-014", "Enable Intel Turbo Boost Max 3.0",
      "Ensures Intel Turbo Boost Max 3.0 is active for best single-core performance.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Processor", "IntelTurboBoostMax30Disable", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Processor", "IntelTurboBoostMax30Disable")],
      why="Turbo Boost Max 3.0 boosts the fastest core further; disabling it (or leaving it enabled) keeps single-threaded game performance up.",
      changes="Sets IntelTurboBoostMax30Disable to 0 (enabled).",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["turbo", "boost", "clock"]),

])
