"""Category: Keyboard — input repeat, accessibility and hotkey optimizations."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Keyboard", win_default="7,8,10,11")
CATEGORY = "Keyboard"

TWEAKS = validate_module("keyboard", [
    T("kbd-001", "Zero Key Repeat Delay",
      "Sets the key repeat delay to its minimum.",
      actions=[("reg", "HKCU", r"Control Panel\Keyboard", "KeyboardDelay", 0, "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Keyboard", "KeyboardDelay", 1, "STRING")],
      why="Minimizes the wait before a held key starts repeating.",
      changes="Sets KeyboardDelay to 0.",
      risk="safe", impact="low", recommended="recommended",
      tags=["keyboard", "repeat", "delay"]),
    T("kbd-003", "Disable Filter Keys",
      "Turns off the Filter Keys accessibility feature.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\Keyboard Response", "Flags", 126, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\Keyboard Response", "Flags", 122, "DWORD")],
      why="Filter Keys deliberately swallows fast keystrokes; disabling removes input loss in fast games.",
      changes="Disables Filter Keys.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["filterkeys", "keystrokes", "input"]),
    T("kbd-004", "Disable Sticky Keys",
      "Turns off the Sticky Keys accessibility feature.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\StickyKeys", "Flags", 506, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\StickyKeys", "Flags", 510, "DWORD")],
      why="Sticky Keys alters modifier behaviour; disabling prevents accidental game input changes.",
      changes="Disables Sticky Keys.",
      risk="safe", impact="low", recommended="recommended",
      tags=["stickykeys", "modifier", "input"]),
    T("kbd-005", "Disable Toggle Keys",
      "Turns off the Toggle Keys beep indicator.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\ToggleKeys", "Flags", 58, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\ToggleKeys", "Flags", 62, "DWORD")],
      why="Removes the annoying beep and its audio pipeline work.",
      changes="Disables Toggle Keys.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["togglekeys", "beep", "accessibility"]),
    T("kbd-006", "NumLock On at Logon",
      "Turns NumLock on at the sign-in screen.",
      actions=[("reg", "HKCU", r"Control Panel\Keyboard", "InitialKeyboardIndicators", 2, "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Keyboard", "InitialKeyboardIndicators", 0, "STRING")],
      why="Ensures a known key state at sign-in.",
      changes="Sets InitialKeyboardIndicators to 2.",
      risk="safe", impact="very low", recommended="optional",
      tags=["numlock", "logon", "keyboard"]),
    T("kbd-008", "Gaming Keyboard Polling Guidance",
      "Explains polling rates and input latency for keyboards.",
      actions=[("guidance", "Many gaming keyboards already run at 1000 Hz. In the keyboard software set 1000 Hz polling and set RGB effects to static — dynamic RGB firmware updates cost CPU cycles.")],
      revert=[("guidance", "Restore keyboard software defaults.")],
      why="Lower polling rates add latency; dynamic RGB firmware can consume measurable CPU.",
      changes="Shows keyboard polling guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["polling", "keyboard", "rgb"]),
    T("kbd-009", "Disable Key Remap Software",
      "Guidance to uninstall unnecessary keyboard remap software.",
      actions=[("guidance", "If you do not use keyboard remap software, remove it from startup (Startup tab in Task Manager). Remap software injects a hook into every game process.")],
      revert=[("guidance", "Re-enable the software in Startup.")],
      why="Hook-based remappers add per-key latency and can trigger anti-cheat.",
      changes="Shows remap-software guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["remap", "hooks", "startup"]),
    T("kbd-010", "Disable Caps Lock Accidental Toggle",
      "Guidance to disable Caps Lock when unused.",
      actions=[("guidance", "Use PowerToys Keyboard Manager or keyboard firmware to remap Caps Lock to nothing if you never use it. Prevents accidental toggles affecting chat/game input.")],
      revert=[("guidance", "Restore Caps Lock.")],
      why="An accidental Caps Lock toggle mid-match can break communication and muscle memory.",
      changes="Shows Caps Lock guidance.",
      risk="safe", impact="very low", recommended="optional",
      tags=["capslock", "remap", "input"]),
    T("kbd-011", "Fast Key Repeat Guidance",
      "Explains the key repeat settings already applied.",
      actions=[("guidance", "Key repeat speed and delay are personal. The applied settings (delay 0, speed 31) are the fastest; dial them back if you overshoot in text entry.")],
      revert=[("guidance", "Adjust in Control Panel > Keyboard or revert this tweak.")],
      why="Predictable repeat behaviour helps rapid-input games.",
      changes="Shows key repeat guidance.",
      risk="safe", impact="very low", recommended="optional",
      tags=["repeat", "speed", "delay"]),
    T("kbd-012", "Update Keyboard Driver",
      "Guidance to update the keyboard and HID driver.",
      actions=[("guidance", "In Device Manager, update the 'HID Keyboard Device' and your vendor keyboard driver. Gaming keyboards ship firmware updates that fix input-latency bugs.")],
      revert=[("guidance", "Roll back the driver if needed.")],
      why="Vendor firmware and driver fixes directly reduce input latency.",
      changes="Shows keyboard driver guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["driver", "firmware", "keyboard"]),
    T("kbd-013", "Keyboard Input Boost (MMCSS)",
      "Raises the Multimedia Class Scheduler priority for the keyboard task so input is serviced like a high-priority thread.",
      actions=[
          ("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Keyboard", "Priority", 6, "DWORD"),
          ("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Keyboard", "Scheduling Category", "High", "STRING"),
          ("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Keyboard", "Latency", 1, "DWORD"),
      ],
      revert=[
          ("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Keyboard", "Priority", 1, "DWORD"),
          ("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Keyboard", "Scheduling Category", "Medium", "STRING"),
          ("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Keyboard", "Latency", 0, "DWORD"),
      ],
      why="A higher MMCSS priority keeps the keyboard kernel thread ahead of background work, trimming input jitter.",
      changes="Sets the Keyboard MMCSS task to High priority.",
      risk="low", impact="moderate", recommended="recommended", admin=True,
      tags=["mmcss", "keyboard", "priority"]),
    T("kbd-014", "Instant Key Acceptance",
      "Zeroes the Filter Keys delay before a press is accepted, so no keystroke is swallowed.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\Keyboard Response", "DelayBeforeAcceptance", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\Keyboard Response", "DelayBeforeAcceptance", 1000, "DWORD")],
      why="Filter Keys' acceptance delay silently drops fast keystrokes.",
      changes="Sets DelayBeforeAcceptance to 0.",
      risk="safe", impact="low", recommended="optional",
      tags=["filterkeys", "delay", "keystrokes"]),
    T("kbd-015", "Zero FilterKeys Bounce Time",
      "Sets Filter Keys bounce time to zero so a key can be re-pressed immediately.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\Keyboard Response", "BounceTime", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\Keyboard Response", "BounceTime", 300, "DWORD")],
      why="Bounce time filters rapid re-presses of the same key, which can eat inputs in fast games.",
      changes="Sets BounceTime to 0.",
      risk="safe", impact="low", recommended="optional",
      tags=["filterkeys", "bounce", "input"]),
    T("kbd-016", "Fast FilterKeys Auto-Repeat",
      "Speeds up Filter Keys' internal auto-repeat delay and rate for held keys.",
      actions=[
          ("reg", "HKCU", r"Control Panel\Accessibility\Keyboard Response", "AutoRepeatDelay", 250, "DWORD"),
          ("reg", "HKCU", r"Control Panel\Accessibility\Keyboard Response", "AutoRepeatRate", 33, "DWORD"),
      ],
      revert=[
          ("reg", "HKCU", r"Control Panel\Accessibility\Keyboard Response", "AutoRepeatDelay", 1000, "DWORD"),
          ("reg", "HKCU", r"Control Panel\Accessibility\Keyboard Response", "AutoRepeatRate", 500, "DWORD"),
      ],
      why="Slow Filter Keys repeat values make held keys stutter when the feature is enabled.",
      changes="Sets AutoRepeatDelay 250 ms, AutoRepeatRate 33 ms.",
      risk="safe", impact="low", recommended="optional",
      tags=["filterkeys", "repeat", "held"]),
    T("kbd-017", "No FilterKeys Auto-Disable Timeout",
      "Disables the timeout that auto-turns off Filter Keys while you step away.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\Keyboard Response", "Timeout", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\Keyboard Response", "Timeout", 30, "DWORD")],
      why="A stray timeout can silently re-enable Filter Keys mid-session.",
      changes="Sets Timeout to 0 (never).",
      risk="safe", impact="very low", recommended="optional",
      tags=["filterkeys", "timeout", "accessibility"]),
    T("kbd-018", "Turn Off Filter Keys Switch",
      "Flips the Filter Keys on/off switch value to fully off.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\Keyboard Response", "On", "0", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\Keyboard Response", "On", "1", "STRING")],
      why="The on/off switch is the authoritative state Filter Keys reads at boot.",
      changes="Sets the Filter Keys switch to Off.",
      risk="safe", impact="low", recommended="recommended",
      tags=["filterkeys", "switch", "input"]),
    T("kbd-019", "Silence Sticky Keys Feedback",
      "Disables the audible and visual feedback Sticky Keys plays when a modifier activates.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\StickyKeys", "AudioFeedback", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\StickyKeys", "AudioFeedback", 1, "DWORD")],
      why="Feedback sounds add audio-pipeline work and can mask in-game cues.",
      changes="Disables Sticky Keys feedback.",
      risk="safe", impact="very low", recommended="optional",
      tags=["stickykeys", "feedback", "sound"]),
    T("kbd-020", "Disable Sticky Keys Hotkey",
      "Disables the Shift x5 hotkey that turns Sticky Keys on mid-game.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\StickyKeys", "HotKey", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\StickyKeys", "HotKey", 1, "DWORD")],
      why="A rapid Shift tap sequence can trip Sticky Keys during gameplay.",
      changes="Disables the Sticky Keys hotkey.",
      risk="safe", impact="low", recommended="recommended",
      tags=["stickykeys", "hotkey", "modifier"]),
    T("kbd-021", "Turn Off Sticky Keys Switch",
      "Sets the Sticky Keys main on/off value to disabled.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\StickyKeys", "On", "0", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\StickyKeys", "On", "1", "STRING")],
      why="The on/off switch is the authoritative Sticky Keys state read at sign-in.",
      changes="Sets the Sticky Keys switch to Off.",
      risk="safe", impact="low", recommended="recommended",
      tags=["stickykeys", "switch", "modifier"]),
    T("kbd-022", "Sticky Keys Off at Logon",
      "Disables Sticky Keys for the logon session before any profile loads.",
      actions=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\StickyKeys", "Flags", 506, "DWORD")],
      revert=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\StickyKeys", "Flags", 510, "DWORD")],
      why="Accessibility pop-ups at the logon screen add delay and can grab focus.",
      changes="Disables Sticky Keys at logon.",
      risk="safe", impact="low", recommended="recommended",
      tags=["stickykeys", "logon", "accessibility"]),
    T("kbd-023", "Silence Toggle Keys Beep",
      "Disables the Toggle Keys beep audio feedback.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\ToggleKeys", "AudioFeedback", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\ToggleKeys", "AudioFeedback", 1, "DWORD")],
      why="Removes the beep and its audio pipeline work.",
      changes="Disables Toggle Keys beep.",
      risk="safe", impact="very low", recommended="optional",
      tags=["togglekeys", "beep", "sound"]),
    T("kbd-024", "Disable Toggle Keys Hotkey",
      "Disables the Num Lock x5 hotkey that turns Toggle Keys on by accident.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\ToggleKeys", "HotKey", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\ToggleKeys", "HotKey", 1, "DWORD")],
      why="Rapid Num Lock taps can enable Toggle Keys and its beeping mid-match.",
      changes="Disables the Toggle Keys hotkey.",
      risk="safe", impact="low", recommended="recommended",
      tags=["togglekeys", "hotkey", "numlock"]),
    T("kbd-025", "Turn Off Toggle Keys Switch",
      "Sets the Toggle Keys main on/off value to disabled.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\ToggleKeys", "On", "0", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\ToggleKeys", "On", "1", "STRING")],
      why="The on/off switch is the authoritative Toggle Keys state read at sign-in.",
      changes="Sets the Toggle Keys switch to Off.",
      risk="safe", impact="low", recommended="recommended",
      tags=["togglekeys", "switch", "beep"]),
    T("kbd-026", "Toggle Keys Off at Logon",
      "Disables Toggle Keys for the logon session.",
      actions=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\ToggleKeys", "Flags", 58, "DWORD")],
      revert=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\ToggleKeys", "Flags", 62, "DWORD")],
      why="Keeps the sign-in screen free of accessibility toggles.",
      changes="Disables Toggle Keys at logon.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["togglekeys", "logon", "beep"]),
    T("kbd-027", "Disable High Contrast Mode",
      "Turns off the High Contrast theme renderer.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\HighContrast", "Flags", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\HighContrast", "Flags", 122, "DWORD")],
      why="High Contrast forces a heavy theme repaint and changes game colour output.",
      changes="Disables High Contrast.",
      risk="safe", impact="low", recommended="optional",
      tags=["highcontrast", "theme", "accessibility"]),
    T("kbd-028", "Disable Mouse Keys Hotkey",
      "Disables the hotkey that turns Mouse Keys on from the numeric keypad.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\MouseKeys", "HotKey", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\MouseKeys", "HotKey", 1, "DWORD")],
      why="The Mouse Keys hotkey can be triggered by stray numpad taps, changing pointer behaviour.",
      changes="Disables the Mouse Keys hotkey.",
      risk="safe", impact="low", recommended="recommended",
      tags=["mousekeys", "hotkey", "numpad"]),
    T("kbd-029", "Keep Mouse Keys Active",
      "Sets the Mouse Keys auto-off delay to never, so the feature stays active.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\MouseKeys", "DelayBeforeMouseKeysOff", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\MouseKeys", "DelayBeforeMouseKeysOff", 60, "DWORD")],
      why="A timed auto-off can deactivate numpad input during long stretches of keyboard-only use.",
      changes="Sets DelayBeforeMouseKeysOff to 0.",
      risk="safe", impact="very low", recommended="optional",
      tags=["mousekeys", "timeout", "numpad"]),
    T("kbd-030", "Disable Sound Sentry",
      "Turns off Sound Sentry's flash-based sound alerts.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\SoundSentry", "Flags", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\SoundSentry", "Flags", 62, "DWORD")],
      why="Sound Sentry flashes the whole window on sounds, wasting GPU work.",
      changes="Disables Sound Sentry.",
      risk="safe", impact="low", recommended="optional",
      tags=["soundsentry", "flash", "accessibility"]),
    T("kbd-031", "Disable Show Sounds Captions",
      "Disables Show Sounds so no accessibility caption overlay is drawn.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility", "ShowSounds", "0", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility", "ShowSounds", "1", "STRING")],
      why="Caption overlays add compositing work and can cover game UI.",
      changes="Disables Show Sounds.",
      risk="safe", impact="very low", recommended="optional",
      tags=["showsounds", "captions", "accessibility"]),
    T("kbd-032", "Disable Ignore Repeated Keystrokes",
      "Turns off the accessibility option that deliberately ignores repeated keystrokes.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility", "Keyboard Preference", "0", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility", "Keyboard Preference", "1", "STRING")],
      why="Ignoring repeated keystrokes can eat input during held-key mashing.",
      changes="Disables keyboard preference filtering.",
      risk="safe", impact="low", recommended="recommended",
      tags=["repeat", "keystrokes", "accessibility"]),
    T("kbd-033", "Filter Keys Off at Logon",
      "Disables Filter Keys for the logon session.",
      actions=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\Keyboard Response", "Flags", 126, "DWORD")],
      revert=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\Keyboard Response", "Flags", 122, "DWORD")],
      why="Filter Keys active at the logon screen can make the password box swallow fast typing.",
      changes="Disables Filter Keys at logon.",
      risk="safe", impact="low", recommended="recommended",
      tags=["filterkeys", "logon", "input"]),
    T("kbd-034", "Hide Touch Keyboard Taskbar Button",
      "Hides the touch keyboard taskbar button from the tray.",
      actions=[("reg", "HKCU", r"Software\Microsoft\TabletTip\1.7", "TipbandDesiredVisibility", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\TabletTip\1.7", "TipbandDesiredVisibility", 1, "DWORD")],
      why="Removes a taskbar element and prevents accidental touch keyboard pop-ups.",
      changes="Hides the touch keyboard button.",
      risk="safe", impact="very low", recommended="optional",
      tags=["touch", "taskbar", "keyboard"]),
    T("kbd-035", "Caps Lock to Control Remap",
      "Remaps Caps Lock to the left Control key using a scancode map.",
      actions=[("reg", "HKCU", r"Keyboard Layout", "Scancode Map", "0000000000000000030000001D003A00000000000000", "BINARY")],
      revert=[("regdel", "HKCU", r"Keyboard Layout", "Scancode Map")],
      why="Caps Lock is wasted space for gamers; turning it into Control is the classic remap.",
      changes="Maps Caps Lock to Left Control.",
      risk="moderate", impact="moderate", recommended="optional",
      tags=["remap", "capslock", "scancode"]),
    T("kbd-036", "No USB Keyboard Selective Suspend",
      "Prevents the USB keyboard device from entering selective suspend.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e96b-e325-11ce-bfc1-08002be10318}\0000", "DeviceSelectiveSuspended", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e96b-e325-11ce-bfc1-08002be10318}\0000", "DeviceSelectiveSuspended", 1, "DWORD")],
      why="A suspended USB keyboard adds wake latency and can miss the first keystroke.",
      changes="Disables keyboard selective suspend.",
      risk="low", impact="moderate", recommended="recommended", admin=True,
      tags=["usb", "suspend", "keyboard"]),
    T("kbd-037", "Keyboard Never Powers Off",
      "Disables 'Allow the computer to turn off this device' for the keyboard.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e96b-e325-11ce-bfc1-08002be10318}\0000", "EnhancedPowerManagementEnabled", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e96b-e325-11ce-bfc1-08002be10318}\0000", "EnhancedPowerManagementEnabled", 1, "DWORD")],
      why="Power management can drop the keyboard bus to low power and add input latency.",
      changes="Disables keyboard power management.",
      risk="low", impact="moderate", recommended="recommended", admin=True,
      tags=["usb", "power", "keyboard"]),
    T("kbd-038", "No HID Selective Suspend",
      "Prevents HID devices (keyboards, mice) from entering selective suspend.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0000", "DeviceSelectiveSuspended", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0000", "DeviceSelectiveSuspended", 1, "DWORD")],
      why="HID selective suspend can pause the whole input bus between bursts of activity.",
      changes="Disables HID selective suspend.",
      risk="low", impact="moderate", recommended="recommended", admin=True,
      tags=["hid", "suspend", "input"]),
    T("kbd-039", "HID Devices Never Power Off",
      "Disables power management off-switching for HID devices.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0000", "EnhancedPowerManagementEnabled", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0000", "EnhancedPowerManagementEnabled", 1, "DWORD")],
      why="Prevents the OS from dropping HID devices to low-power idle mid-game.",
      changes="Disables HID power management.",
      risk="low", impact="moderate", recommended="recommended", admin=True,
      tags=["hid", "power", "input"]),
    T("kbd-040", "Keyboard MMCSS GPU Priority",
      "Raises the MMCSS GPU priority for keyboard rendering work.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Keyboard", "GPU Priority", 8, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Keyboard", "GPU Priority", 0, "DWORD")],
      why="Keyboard compositing threads compete with game rendering; a high GPU priority helps.",
      changes="Sets Keyboard GPU Priority to 8.",
      risk="low", impact="low", recommended="recommended", admin=True,
      tags=["mmcss", "gpu", "keyboard"]),
    T("kbd-041", "Keyboard MMCSS SFIO Priority",
      "Raises the MMCSS storage I/O priority for keyboard services.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Keyboard", "SFIO Priority", "High", "STRING")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Keyboard", "SFIO Priority", "Normal", "STRING")],
      why="High storage I/O priority keeps keyboard-related loads ahead of disk-heavy apps.",
      changes="Sets Keyboard SFIO Priority to High.",
      risk="low", impact="low", recommended="recommended", admin=True,
      tags=["mmcss", "sfio", "keyboard"]),
    T("kbd-042", "Keyboard MMCSS Background Only Off",
      "Allows the keyboard MMCSS task to run in the foreground.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Keyboard", "Background Only", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Keyboard", "Background Only", 1, "DWORD")],
      why="Foreground scheduling keeps keyboard processing active while games run.",
      changes="Disables Background Only for the Keyboard task.",
      risk="low", impact="low", recommended="recommended", admin=True,
      tags=["mmcss", "background", "keyboard"]),
    T("kbd-043", "Disable Touch Keyboard Service",
      "Disables the Touch Keyboard and Handwriting Panel service.",
      actions=[("svc", "TabletInputService", "disabled"), ("svcstop", "TabletInputService")],
      revert=[("svc", "TabletInputService", "manual")],
      why="The touch keyboard service sits in memory even on desktop-only setups.",
      changes="Disables the TabletInputService service.",
      risk="low", impact="moderate", recommended="optional", admin=True,
      tags=["touch", "service", "keyboard"]),
    T("kbd-044", "Disable Bluetooth for Wired Input",
      "Disables the Bluetooth support service when all input devices are wired.",
      actions=[("svc", "bthserv", "disabled"), ("svcstop", "bthserv")],
      revert=[("svc", "bthserv", "manual")],
      why="The Bluetooth stack polls radios and can steal CPU and interrupt time.",
      changes="Disables the Bluetooth Support Service.",
      risk="moderate", impact="low", recommended="optional", admin=True,
      tags=["bluetooth", "wireless", "service"]),
    T("kbd-045", "Enable TSC Sync (Input Timing)",
      "Enables enhanced TSC synchronization for consistent timer reads.",
      actions=[("cmd", "bcdedit /set tscsyncpolicy Enhanced")],
      revert=[("cmd", "bcdedit /deletevalue tscsyncpolicy")],
      why="Consistent time-source reads reduce jitter in input latency measurement.",
      changes="Sets tscsyncpolicy to Enhanced.",
      risk="moderate", impact="low", recommended="experimental", admin=True,
      tags=["tsc", "timer", "latency"]),
    T("kbd-046", "Disable Firmware PCI Settings",
      "Stops firmware PCI settings overriding MSI-capable interrupt routing.",
      actions=[("cmd", "bcdedit /set usefirmwarepcisettings no")],
      revert=[("cmd", "bcdedit /deletevalue usefirmwarepcisettings")],
      why="Cleaner interrupt routing keeps keyboard and HID interrupts on low-latency paths.",
      changes="Sets usefirmwarepcisettings to no.",
      risk="moderate", impact="low", recommended="experimental", admin=True,
      tags=["pci", "interrupts", "latency"]),
    T("kbd-047", "Block Keyboard Wake from Sleep",
      "Stops the HID keyboard from waking the PC from sleep.",
      actions=[("cmd", "powercfg /devicedisablewake \"HID Keyboard Device\"")],
      revert=[("cmd", "powercfg /deviceenablewake \"HID Keyboard Device\"")],
      why="Prevents accidental key presses from waking the PC and burning battery.",
      changes="Disables keyboard wake from sleep.",
      risk="low", impact="very low", recommended="optional", admin=True,
      tags=["powercfg", "wake", "keyboard"]),
    T("kbd-048", "NumLock On at Logon Screen",
      "Turns NumLock on for the sign-in screen itself.",
      actions=[("reg", "HKU", r".DEFAULT\Control Panel\Keyboard", "InitialKeyboardIndicators", 2, "STRING")],
      revert=[("reg", "HKU", r".DEFAULT\Control Panel\Keyboard", "InitialKeyboardIndicators", 0, "STRING")],
      why="Ensures the numpad works before your profile loads.",
      changes="Sets NumLock on at logon.",
      risk="safe", impact="very low", recommended="optional",
      tags=["numlock", "logon", "keyboard"]),
    T("kbd-049", "Fast Key Repeat at Logon Screen",
      "Applies the zero key repeat delay to the logon session.",
      actions=[("reg", "HKU", r".DEFAULT\Control Panel\Keyboard", "KeyboardDelay", 0, "STRING")],
      revert=[("reg", "HKU", r".DEFAULT\Control Panel\Keyboard", "KeyboardDelay", 1, "STRING")],
      why="Matches the fast repeat behaviour your main profile already uses.",
      changes="Sets logon KeyboardDelay to 0.",
      risk="safe", impact="very low", recommended="optional",
      tags=["repeat", "logon", "delay"]),
    T("kbd-050", "Mouse Keys Off at Logon",
      "Disables Mouse Keys for the logon session.",
      actions=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\MouseKeys", "Flags", 0, "DWORD")],
      revert=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\MouseKeys", "Flags", 62, "DWORD")],
      why="Numpad pointer input at the logon screen serves no purpose for most users.",
      changes="Disables Mouse Keys at logon.",
      risk="safe", impact="very low", recommended="optional",
      tags=["mousekeys", "logon", "numpad"]),
    T("kbd-051", "High Contrast Off at Logon",
      "Disables High Contrast mode for the logon session.",
      actions=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\HighContrast", "Flags", 0, "DWORD")],
      revert=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\HighContrast", "Flags", 122, "DWORD")],
      why="Avoids a jarring theme switch at the logon screen.",
      changes="Disables High Contrast at logon.",
      risk="safe", impact="very low", recommended="optional",
      tags=["highcontrast", "logon", "theme"]),
    T("kbd-052", "Sound Sentry Off at Logon",
      "Disables Sound Sentry for the logon session.",
      actions=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\SoundSentry", "Flags", 0, "DWORD")],
      revert=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\SoundSentry", "Flags", 62, "DWORD")],
      why="Prevents flash animations from running at the logon screen.",
      changes="Disables Sound Sentry at logon.",
      risk="safe", impact="very low", recommended="optional",
      tags=["soundsentry", "logon", "flash"]),
    T("kbd-053", "Silence Toggle Keys Beep at Logon",
      "Disables Toggle Keys beep feedback at the logon session.",
      actions=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\ToggleKeys", "AudioFeedback", 0, "DWORD")],
      revert=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\ToggleKeys", "AudioFeedback", 1, "DWORD")],
      why="Stops logon-time beeps entirely.",
      changes="Disables Toggle Keys beep at logon.",
      risk="safe", impact="very low", recommended="optional",
      tags=["togglekeys", "logon", "beep"]),
    T("kbd-054", "Silent Sticky Keys at Logon",
      "Disables Sticky Keys feedback sounds at the logon session.",
      actions=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\StickyKeys", "AudioFeedback", 0, "DWORD")],
      revert=[("reg", "HKU", r".DEFAULT\Control Panel\Accessibility\StickyKeys", "AudioFeedback", 1, "DWORD")],
      why="Removes modifier-activation sounds before any profile loads.",
      changes="Disables Sticky Keys feedback at logon.",
      risk="safe", impact="very low", recommended="optional",
      tags=["stickykeys", "logon", "feedback"]),
    T("kbd-055", "Mouse Keys Off Switch",
      "Sets the Mouse Keys main on/off value to disabled.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\MouseKeys", "On", "0", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\MouseKeys", "On", "1", "STRING")],
      why="The on/off switch is the authoritative Mouse Keys state read at sign-in.",
      changes="Sets the Mouse Keys switch to Off.",
      risk="safe", impact="low", recommended="recommended",
      tags=["mousekeys", "switch", "pointer"]),
    T("kbd-056", "High Contrast Off Switch",
      "Sets the High Contrast main on/off value to disabled.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\HighContrast", "On", "0", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\HighContrast", "On", "1", "STRING")],
      why="The on/off switch is the authoritative High Contrast state read at sign-in.",
      changes="Sets the High Contrast switch to Off.",
      risk="safe", impact="low", recommended="optional",
      tags=["highcontrast", "switch", "theme"]),
    T("kbd-057", "Sound Sentry Off Switch",
      "Sets the Sound Sentry main on/off value to disabled.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\SoundSentry", "On", "0", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\SoundSentry", "On", "1", "STRING")],
      why="The on/off switch is the authoritative Sound Sentry state read at sign-in.",
      changes="Sets the Sound Sentry switch to Off.",
      risk="safe", impact="low", recommended="optional",
      tags=["soundsentry", "switch", "flash"]),
])
