"""Category: Monitor — display hardware behaviour optimizations."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Monitor", win_default="7,8,10,11")
CATEGORY = "Monitor"

TWEAKS = validate_module("monitor", [
    T("mon-001", "Disable Monitor Auto-Detect Sleep",
      "Prevents the display from entering power save during long play sessions.",
      actions=[("power", "display_timeout", 0)],
      revert=[("power", "display_timeout", 600)],
      why="A monitor that sleeps mid-session causes a disruptive black screen and reconnect delay.",
      changes="Sets the display turn-off timeout to 'never' on AC.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["monitor", "sleep", "display"]),
    T("mon-002", "Disable Screen Saver",
      "Turns off the screen saver entirely.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "ScreenSaveActive", 0, "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "ScreenSaveActive", 1, "STRING")],
      why="Screen savers add an unnecessary wake-up delay after idle.",
      changes="Disables the screen saver.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["screensaver", "monitor", "idle"]),
    T("mon-003", "Native Refresh Rate Check",
      "Reports the detected display resolution and refresh rate.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-CimInstance Win32_VideoController | Format-Table Name,CurrentHorizontalResolution,CurrentVerticalResolution,CurrentRefreshRate -AutoSize\"")],
      revert=[("guidance", "Read-only report.")],
      why="Confirms the monitor is running at its rated refresh rate.",
      changes="Shows the display mode report.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["refresh", "resolution", "report"]),
    T("mon-004", "High Refresh Rate Guidance",
      "Guidance for enabling the monitor's maximum refresh rate.",
      actions=[("guidance", "Open Settings > System > Display > Advanced display and select the highest refresh rate. On HDMI, enable the monitor's high-refresh mode (DisplayPort is preferred).")],
      revert=[("guidance", "Return to a lower refresh rate.")],
      why="Higher refresh reduces persistence blur and perceived input latency.",
      changes="Shows refresh-rate guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["refresh", "hz", "144hz"]),
    T("mon-005", "Response Time Overdrive",
      "Guidance to set the monitor's response-time setting.",
      actions=[("guidance", "In the monitor OSD set 'Response Time' / 'Overdrive' to its highest stable setting. Excessive overdrive causes ghosting trails; back off if you see them.")],
      revert=[("guidance", "Restore the default OSD setting.")],
      why="Lower response time reduces motion blur on fast camera movement.",
      changes="Shows overdrive guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["overdrive", "response", "ghosting"]),
    T("mon-006", "Disable Adaptive Brightness",
      "Turns off display adaptive brightness in the power plan.",
      actions=[("power", "adaptive_brightness", 0, "AC"), ("power", "adaptive_brightness", 0, "DC")],
      revert=[("power", "adaptive_brightness", 1, "AC"), ("power", "adaptive_brightness", 1, "DC")],
      why="Ambient-light brightness adjustments cause visible brightness dips during dark scenes.",
      changes="Disables adaptive brightness on AC.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["brightness", "ambient", "display"]),
    T("mon-007", "Disable HDR Auto-Toggle",
      "Guidance to keep HDR stable.",
      actions=[("guidance", "If HDR toggling causes black screens, turn off 'Auto HDR' for the game and manage HDR from the display OSD or game instead of letting Windows toggle it.")],
      revert=[("guidance", "Re-enable Auto HDR.")],
      why="Auto HDR switching can drop frames at the moment of transition.",
      changes="Shows HDR guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["hdr", "toggle", "display"]),
    T("mon-008", "GSYNC/FreeSync Guidance",
      "Guidance for sync-technology setup.",
      actions=[("guidance", "For G-SYNC/FreeSync: enable it in the GPU control panel AND the monitor OSD, disable V-Sync in the driver, and cap FPS 3 below the refresh ceiling to stay in the sync range.")],
      revert=[("guidance", "Disable the sync technology.")],
      why="Adaptive sync removes tearing without V-Sync's latency penalty.",
      changes="Shows adaptive-sync guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["gsync", "freesync", "tearing"]),
    T("mon-009", "Disable Monitor Off During Streaming",
      "Guidance to keep the monitor awake while streaming.",
      actions=[("guidance", "Keep the display on while streaming or recording by setting the display timeout to 'never' (see related tweaks) so you do not lose the video output mid-stream.")],
      revert=[("guidance", "Restore a display timeout.")],
      why="A sleeping monitor can interrupt capture sessions.",
      changes="Shows streaming display guidance.",
      risk="safe", impact="very low", recommended="optional",
      tags=["streaming", "display", "sleep"]),
    T("mon-010", "Resolution Scaling Check",
      "Guidance for running at native resolution.",
      actions=[("guidance", "Run the game at your monitor's native resolution and use in-game or driver scaling rather than a lower desktop resolution, which adds a scaling pass.")],
      revert=[("guidance", "No change to revert.")],
      why="Non-native resolutions add scaling latency and blur.",
      changes="Shows resolution guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["resolution", "scaling", "native"]),
    T("mon-011", "Disable Night Light Scheduler",
      "Guidance to avoid color-mode switches during play.",
      actions=[("guidance", "If Night Light is scheduled, it changes the color profile mid-session. Disable it for gaming or set it outside your play hours.")],
      revert=[("guidance", "Re-enable Night Light.")],
      why="Color profile changes cause brief display recalibration.",
      changes="Shows Night Light guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["nightlight", "color", "display"]),
    T("mon-012", "Monitor Firmware/Driver Guidance",
      "Guidance to install the monitor's driver package.",
      actions=[("guidance", "Install the monitor driver (.inf) from the manufacturer so Windows applies the correct color and timing tables instead of generic PnP.")],
      revert=[("guidance", "Uninstall the monitor driver.")],
      why="Correct EDID/timing tables prevent refresh and scaling misbehaviour.",
      changes="Shows monitor driver guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["driver", "edid", "monitor"]),
    T("mon-013", "Disable 'Hide Display Timeout' in Games",
      "Guidance to ensure the display never sleeps during AFK games.",
      actions=[("guidance", "For AFK/idle-heavy games, set the display timeout to never (applied by related tweaks) so a fullscreen game is never interrupted.")],
      revert=[("guidance", "Restore the display timeout.")],
      why="Display sleep during an AFK session breaks the game session.",
      changes="Shows display-sleep guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["afk", "sleep", "display"]),
    T("mon-014", "Display Topology Report",
      "Lists connected display adapters and monitors.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-CimInstance -Namespace root\\wmi -ClassName WmiMonitorBasicDisplayParams | Format-Table InstanceName -AutoSize; Get-CimInstance Win32_DesktopMonitor | Format-Table Name,ScreenWidth,ScreenHeight -AutoSize\"")],
      revert=[("guidance", "Read-only report.")],
      why="Confirms which monitors Windows sees and their current modes.",
      changes="Shows the display topology report.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["monitors", "topology", "report"]),
])
