"""Category: Mouse — pointer behaviour and cursor latency optimizations."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Mouse", win_default="7,8,10,11")
CATEGORY = "Mouse"

TWEAKS = validate_module("mouse", [
    T("mouse-001", "Disable Mouse Acceleration",
      "Turns off pointer acceleration and enhancement.",
      actions=[
          ("reg", "HKCU", r"Control Panel\Mouse", "MouseSpeed", 0, "STRING"),
          ("reg", "HKCU", r"Control Panel\Mouse", "MouseThreshold1", 0, "STRING"),
          ("reg", "HKCU", r"Control Panel\Mouse", "MouseThreshold2", 0, "STRING"),
      ],
      revert=[
          ("reg", "HKCU", r"Control Panel\Mouse", "MouseSpeed", 1, "STRING"),
          ("reg", "HKCU", r"Control Panel\Mouse", "MouseThreshold1", 6, "STRING"),
          ("reg", "HKCU", r"Control Panel\Mouse", "MouseThreshold2", 10, "STRING"),
      ],
      why="Acceleration makes cursor distance depend on swipe speed, breaking pointer muscle memory.",
      changes="Disables pointer acceleration.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["acceleration", "pointer", "input"]),
    T("mouse-002", "Disable Cursor Suppression",
      "Stops Windows from hiding the cursor during typing in games.",
      actions=[("reg", "HKCU", r"Control Panel\Mouse", "EnableCursorSuppression", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Mouse", "EnableCursorSuppression", 1, "DWORD")],
      why="Cursor suppression can misfire in games that emulate typing, losing the cursor mid-movement.",
      changes="Disables cursor suppression.",
      risk="safe", impact="low", recommended="recommended",
      tags=["cursor", "suppression", "pointer"]),
    T("mouse-004", "Instant Hover Time",
      "Sets the pointer hover activation time to its minimum.",
      actions=[("reg", "HKCU", r"Control Panel\Mouse", "MouseHoverTime", 1, "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Mouse", "MouseHoverTime", 400, "STRING")],
      why="Reduces the delay before hover actions trigger.",
      changes="Sets MouseHoverTime to 1 ms.",
      risk="safe", impact="low", recommended="recommended",
      tags=["hover", "pointer", "delay"]),
    T("mouse-005", "Default Pointer Curves",
      "Resets the smooth pointer acceleration curves to defaults.",
      actions=[("guidance", "Mouse acceleration curves (SmoothMouseXCurve/YCurve) are best left at their defaults. This tweak confirms they have not been modified by other tools.")],
      revert=[("guidance", "No change to revert.")],
      why="Modified pointer curves cause inconsistent pointer behaviour across games.",
      changes="Shows pointer-curve guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["curve", "pointer", "sensitivity"]),
    T("mouse-006", "Mouse DPI Guidance",
      "Explains how to pick a stable DPI for consistent pointer input.",
      actions=[("guidance", "Prefer a fixed mouse DPI (800-1600 is common for FPS) and use in-game sensitivity for fine tuning. Avoid Windows pointer speed adjustments once acceleration is off.")],
      revert=[("guidance", "No change to revert.")],
      why="Consistent DPI with raw input produces predictable pointer movement.",
      changes="Shows DPI guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["dpi", "sensitivity", "input"]),
    T("mouse-007", "Mouse Polling Rate Guidance",
      "Guides setting the mouse to 1000 Hz polling.",
      actions=[("guidance", "In the mouse software set the polling rate to 1000 Hz. Below 500 Hz, cursor position updates become visibly stuttery in shooters.")],
      revert=[("guidance", "Restore the previous polling rate.")],
      why="Higher polling rates deliver fresher cursor positions to the OS.",
      changes="Shows polling-rate guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["polling", "mouse", "rate"]),
    T("mouse-008", "Raw Input for FPS",
      "Guidance to enable raw input in games.",
      actions=[("guidance", "Enable 'Raw Input' in game settings (Fortnite, Valorant, CS2) so the mouse bypasses Windows pointer processing entirely.")],
      revert=[("guidance", "Disable raw input in the game.")],
      why="Raw input removes OS-level pointer transforms for the most consistent pointer input.",
      changes="Shows raw-input guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["rawinput", "input", "pointer"]),
    T("mouse-011", "Disable Double-Click Lock",
      "Prevents the double-click from locking into drag mode.",
      actions=[("guidance", "In Mouse settings, ensure 'Turn on Click Lock' is disabled so drag actions do not stick during rapid clicking.")],
      revert=[("guidance", "Re-enable Click Lock if wanted.")],
      why="Click Lock can cause unintended drags during rapid double-clicks in games.",
      changes="Shows Click Lock guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["clicklock", "doubleclick", "drag"]),
    T("mouse-012", "USB Mouse Power Saving",
      "Guidance to disable USB selective suspend for the mouse.",
      actions=[("guidance", "Apply the 'Disable USB Selective Suspend' tweak in the USB category so the mouse never drops to a power-saving mode mid-game.")],
      revert=[("guidance", "Re-enable USB selective suspend.")],
      why="A suspended USB device adds wake latency and occasional first-move stutter.",
      changes="Points to USB selective suspend guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["usb", "power", "mouse"]),
    T("mouse-013", "Left-Handed Buttons",
      "Swaps the primary and secondary mouse buttons for left-handed users.",
      actions=[("reg", "HKCU", r"Control Panel\Mouse", "SwapMouseButtons", "1", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Mouse", "SwapMouseButtons", "0", "STRING")],
      why="Left-handed users get a faster primary click without hunting for button remap software.",
      changes="Swaps left/right buttons.",
      risk="safe", impact="low", recommended="optional",
      tags=["buttons", "lefty", "pointer"]),
    T("mouse-014", "Fast Double-Click",
      "Lowers the double-click speed threshold so rapid clicks register faster.",
      actions=[("reg", "HKCU", r"Control Panel\Mouse", "DoubleClickSpeed", "200", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Mouse", "DoubleClickSpeed", "500", "STRING")],
      why="A tight double-click window turns two quick clicks into an intentional double-click sooner.",
      changes="DoubleClickSpeed set to 200 ms.",
      risk="safe", impact="low", recommended="optional",
      tags=["doubleclick", "speed", "rapidfire"]),
    T("mouse-015", "Compact Double-Click Zone",
      "Shrinks the vertical double-click hit zone for precise rapid clicking.",
      actions=[("reg", "HKCU", r"Control Panel\Mouse", "DoubleClickHeight", "2", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Mouse", "DoubleClickHeight", "4", "STRING")],
      why="A smaller hit zone stops neighbouring clicks from merging into unwanted double-clicks.",
      changes="DoubleClickHeight set to 2 px.",
      risk="safe", impact="very low", recommended="optional",
      tags=["doubleclick", "hitbox", "pointer"]),
    T("mouse-016", "Compact Double-Click Zone Width",
      "Shrinks the horizontal double-click hit zone for rapid clicking.",
      actions=[("reg", "HKCU", r"Control Panel\Mouse", "DoubleClickWidth", "2", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Mouse", "DoubleClickWidth", "4", "STRING")],
      why="A tighter horizontal zone keeps fast clicks from blending into drags.",
      changes="DoubleClickWidth set to 2 px.",
      risk="safe", impact="very low", recommended="optional",
      tags=["doubleclick", "hitbox", "width"]),
    T("mouse-017", "Disable Pointer Trails",
      "Turns off cursor motion trails for a clean, precise pointer.",
      actions=[("reg", "HKCU", r"Control Panel\Mouse", "MouseTrails", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Mouse", "MouseTrails", 6, "DWORD")],
      why="Trails smear cursor position and add perceived latency in fast games.",
      changes="MouseTrails disabled.",
      risk="safe", impact="low", recommended="recommended",
      tags=["trails", "cursor", "latency"]),
    T("mouse-018", "Disable Snap-To",
      "Prevents the pointer from jumping to the default button in dialogs.",
      actions=[("reg", "HKCU", r"Control Panel\Mouse", "SnapToDefaultButton", "0", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Mouse", "SnapToDefaultButton", "1", "STRING")],
      why="Snap-to moves the cursor on dialog open, which can mis-place a fast flick in games.",
      changes="SnapToDefaultButton disabled.",
      risk="safe", impact="very low", recommended="optional",
      tags=["snap", "pointer", "dialog"]),
    T("mouse-019", "Linear Pointer Curve",
      "Replaces the Windows acceleration curves with a flat 1:1 pointer response.",
      actions=[
          ("reg", "HKCU", r"Control Panel\Mouse", "SmoothMouseXCurve",
           "00 00 00 00 00 00 00 00 00 01 00 00 00 00 01 00 00 02 00 00 00 00 02 00 00 03 00 00 00 00 03 00 00 04 00 00 00 00 04 00", "BINARY"),
          ("reg", "HKCU", r"Control Panel\Mouse", "SmoothMouseYCurve",
           "00 00 00 00 00 00 00 00 00 01 00 00 00 00 01 00 00 02 00 00 00 00 02 00 00 03 00 00 00 00 03 00 00 04 00 00 00 00 04 00", "BINARY"),
      ],
      revert=[
          ("reg", "HKCU", r"Control Panel\Mouse", "SmoothMouseXCurve",
           "00 00 00 00 00 00 00 00 15 6E 00 00 00 40 01 00 29 DC 00 00 00 80 02 00 00 00 00 00 00 00 05 00 00 00 00 00 00 00 00 00", "BINARY"),
          ("reg", "HKCU", r"Control Panel\Mouse", "SmoothMouseYCurve",
           "00 00 00 00 00 00 00 00 00 38 00 00 00 70 00 00 00 70 01 00 00 60 03 00 00 68 02 00 00 20 0C 00 00 00 00 00 00 00 00", "BINARY"),
      ],
      why="A flat curve gives pixel-consistent pointer movement once acceleration is off.",
      changes="SmoothMouseXCurve/YCurve set to a linear 1:1 response.",
      risk="low", impact="moderate", recommended="recommended",
      tags=["curve", "acceleration", "linear"]),
    T("mouse-020", "Tight Hover Zone",
      "Narrows the horizontal pointer hover zone for faster hover activation.",
      actions=[("reg", "HKCU", r"Control Panel\Mouse", "MouseHoverWidth", "2", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Mouse", "MouseHoverWidth", "4", "STRING")],
      why="A narrower hover window makes hover-based tooltips and activation trigger with less drift.",
      changes="MouseHoverWidth set to 2 px.",
      risk="safe", impact="very low", recommended="optional",
      tags=["hover", "zone", "pointer"]),
    T("mouse-021", "Tight Hover Zone Height",
      "Narrows the vertical pointer hover zone for faster hover activation.",
      actions=[("reg", "HKCU", r"Control Panel\Mouse", "MouseHoverHeight", "2", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Mouse", "MouseHoverHeight", "4", "STRING")],
      why="Pairs with MouseHoverTime to shave overall hover-response delay.",
      changes="MouseHoverHeight set to 2 px.",
      risk="safe", impact="very low", recommended="optional",
      tags=["hover", "zone", "height"]),
    T("mouse-022", "Disable Click Lock",
      "Turns off Click Lock so dragging never sticks after a long press.",
      actions=[("reg", "HKCU", r"Control Panel\Mouse", "ClickLock", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Mouse", "ClickLock", 1, "DWORD")],
      why="Click Lock turns hold+drag into a stuck drag, which ruins pickups and windows management mid-game.",
      changes="Click Lock disabled.",
      risk="safe", impact="low", recommended="recommended",
      tags=["clicklock", "drag", "pointer"]),
    T("mouse-023", "Faster Click Lock Engage",
      "Shortens the hold time before Click Lock engages when it is enabled.",
      actions=[("reg", "HKCU", r"Control Panel\Mouse", "ClickLockTime", 500, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Mouse", "ClickLockTime", 1200, "DWORD")],
      why="A shorter engage delay keeps hold-to-drag responsive for users who rely on it.",
      changes="ClickLockTime set to 500 ms.",
      risk="safe", impact="very low", recommended="optional",
      tags=["clicklock", "delay", "drag"]),
    T("mouse-024", "Disable Cursor Blink",
      "Stops the text cursor from blinking.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "CursorBlinkRate", -1, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "CursorBlinkRate", 530, "DWORD")],
      why="A steady text caret is easier to track and removes constant redraw flicker.",
      changes="CursorBlinkRate set to -1 (no blink).",
      risk="safe", impact="very low", recommended="optional",
      tags=["caret", "blink", "desktop"]),
    T("mouse-025", "Disable Smooth Scrolling",
      "Turns off the legacy smooth-scroll animation for instant wheel response.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "SmoothScroll", "0", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "SmoothScroll", "1", "STRING")],
      why="Animated scrolling lags wheel input; disabling it gives immediate, game-like scroll response.",
      changes="SmoothScroll disabled.",
      risk="safe", impact="low", recommended="recommended",
      tags=["scroll", "wheel", "animation"]),
    T("mouse-026", "Fast Wheel Scroll",
      "Scrolls more lines per wheel notch for fewer wrist movements.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "WheelScrollLines", 5, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "WheelScrollLines", 3, "DWORD")],
      why="More lines per notch makes long pages pass with fewer wheel turns.",
      changes="WheelScrollLines set to 5.",
      risk="safe", impact="low", recommended="optional",
      tags=["wheel", "scroll", "lines"]),
    T("mouse-027", "Horizontal Wheel Chars",
      "Sets how many characters a horizontal wheel tilt scrolls.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "WheelScrollChars", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "WheelScrollChars", 3, "DWORD")],
      why="A small tilt step keeps horizontal panning under control in editors and sheets.",
      changes="WheelScrollChars set to 1.",
      risk="safe", impact="very low", recommended="optional",
      tags=["wheel", "tilt", "scroll"]),
    T("mouse-028", "Snappy Window Drag",
      "Lowers the vertical threshold before a window switches to full-window drag.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "DragHeight", 2, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "DragHeight", 4, "DWORD")],
      why="A smaller drag threshold shows the window outline sooner, feeling more responsive.",
      changes="DragHeight set to 2 px.",
      risk="safe", impact="very low", recommended="optional",
      tags=["drag", "window", "threshold"]),
    T("mouse-029", "Snappy Window Drag Width",
      "Lowers the horizontal threshold before a window switches to full-window drag.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "DragWidth", 2, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "DragWidth", 4, "DWORD")],
      why="Pairs with DragHeight to make dragging feel immediate.",
      changes="DragWidth set to 2 px.",
      risk="safe", impact="very low", recommended="optional",
      tags=["drag", "window", "width"]),
    T("mouse-030", "Activate Window on Hover",
      "Makes windows activate as soon as the pointer passes over them.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "ActiveWindowTracking", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "ActiveWindowTracking", 0, "DWORD")],
      why="Hover activation removes the extra click when switching between open windows.",
      changes="ActiveWindowTracking enabled.",
      risk="safe", impact="low", recommended="optional",
      tags=["hover", "activate", "window"]),
    T("mouse-031", "Disable Snap Layouts",
      "Turns off the Win11 Snap Layouts popup when dragging a window to an edge.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "WindowArrangementActive", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "WindowArrangementActive", 1, "DWORD")],
      why="The layout overlay can trap a drag; disabling it keeps edge snapping instant.",
      changes="Snap Layouts disabled.",
      risk="safe", impact="low", recommended="optional",
      win="11",
      tags=["snap", "layout", "window"]),
    T("mouse-032", "Minimize Flash Count",
      "Sets the number of flashes a background window makes when it steals attention.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "ForegroundFlashCount", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "ForegroundFlashCount", 3, "DWORD")],
      why="One quick flash instead of three keeps attention drawn back to the game.",
      changes="ForegroundFlashCount set to 1.",
      risk="safe", impact="very low", recommended="optional",
      tags=["flash", "focus", "window"]),
    T("mouse-033", "Aero Arrow Cursor",
      "Sets the arrow pointer to the Aero scheme cursor.",
      actions=[("reg", "HKCU", r"Control Panel\Cursors", "Arrow", "C:\\Windows\\Cursors\\aero_arrow.cur", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Cursors", "Arrow", "", "STRING")],
      why="A consistent arrow across apps keeps the pointer easy to track at speed.",
      changes="Arrow cursor set to aero_arrow.cur.",
      risk="safe", impact="very low", recommended="optional",
      tags=["cursor", "arrow", "scheme"]),
    T("mouse-034", "Aero Busy Cursor",
      "Sets the wait cursor to the Aero busy cursor.",
      actions=[("reg", "HKCU", r"Control Panel\Cursors", "Wait", "C:\\Windows\\Cursors\\aero_busy.cur", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Cursors", "Wait", "", "STRING")],
      why="The Aero busy cursor keeps the pointer visible while an app is working.",
      changes="Wait cursor set to aero_busy.cur.",
      risk="safe", impact="very low", recommended="optional",
      tags=["cursor", "wait", "scheme"]),
    T("mouse-035", "Aero Beam Cursor",
      "Sets the text I-beam cursor to the Aero scheme cursor.",
      actions=[("reg", "HKCU", r"Control Panel\Cursors", "IBeam", "C:\\Windows\\Cursors\\aero_beam.cur", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Cursors", "IBeam", "", "STRING")],
      why="A crisp I-beam makes text selection less ambiguous.",
      changes="IBeam cursor set to aero_beam.cur.",
      risk="safe", impact="very low", recommended="optional",
      tags=["cursor", "ibeam", "text"]),
    T("mouse-036", "Aero Link Cursor",
      "Sets the hand/link cursor to the Aero scheme cursor.",
      actions=[("reg", "HKCU", r"Control Panel\Cursors", "Hand", "C:\\Windows\\Cursors\\aero_link.cur", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Cursors", "Hand", "", "STRING")],
      why="A clean hand cursor avoids the low-contrast defaults on some themes.",
      changes="Hand cursor set to aero_link.cur.",
      risk="safe", impact="very low", recommended="optional",
      tags=["cursor", "hand", "link"]),
    T("mouse-037", "Aero Unavailable Cursor",
      "Sets the 'not allowed' cursor to the Aero scheme cursor.",
      actions=[("reg", "HKCU", r"Control Panel\Cursors", "No", "C:\\Windows\\Cursors\\aero_unavail.cur", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Cursors", "No", "", "STRING")],
      why="A clearly visible no-drop cursor prevents ambiguous drop targets in games.",
      changes="No cursor set to aero_unavail.cur.",
      risk="safe", impact="very low", recommended="optional",
      tags=["cursor", "no", "drop"]),
    T("mouse-038", "Aero Help Cursor",
      "Sets the help/question-mark cursor to the Aero scheme cursor.",
      actions=[("reg", "HKCU", r"Control Panel\Cursors", "Help", "C:\\Windows\\Cursors\\aero_help.cur", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Cursors", "Help", "", "STRING")],
      why="Makes help-mode affordances easier to spot.",
      changes="Help cursor set to aero_help.cur.",
      risk="safe", impact="very low", recommended="optional",
      tags=["cursor", "help", "question"]),
    T("mouse-039", "Aero Working Cursor",
      "Sets the app-starting cursor to the Aero working cursor.",
      actions=[("reg", "HKCU", r"Control Panel\Cursors", "AppStarting", "C:\\Windows\\Cursors\\aero_working.cur", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Cursors", "AppStarting", "", "STRING")],
      why="Keeps the pointer clearly visible while a program starts.",
      changes="AppStarting cursor set to aero_working.cur.",
      risk="safe", impact="very low", recommended="optional",
      tags=["cursor", "working", "app"]),
    T("mouse-040", "Aero Move Cursor",
      "Sets the move/SizeAll cursor to the Aero scheme cursor.",
      actions=[("reg", "HKCU", r"Control Panel\Cursors", "SizeAll", "C:\\Windows\\Cursors\\aero_move.cur", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Cursors", "SizeAll", "", "STRING")],
      why="A distinct move cursor makes drag-move states unambiguous.",
      changes="SizeAll cursor set to aero_move.cur.",
      risk="safe", impact="very low", recommended="optional",
      tags=["cursor", "move", "sizeall"]),
    T("mouse-041", "Aero Cross Cursor",
      "Sets the precision crosshair cursor to the Aero scheme cursor.",
      actions=[("reg", "HKCU", r"Control Panel\Cursors", "Crosshair", "C:\\Windows\\Cursors\\aero_cross.cur", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Cursors", "Crosshair", "", "STRING")],
      why="A clean crosshair is easier to aim with in precision apps.",
      changes="Crosshair cursor set to aero_cross.cur.",
      risk="safe", impact="very low", recommended="optional",
      tags=["cursor", "crosshair", "precision"]),
    T("mouse-042", "Aero Vertical Resize Cursor",
      "Sets the vertical resize cursor to the Aero scheme cursor.",
      actions=[("reg", "HKCU", r"Control Panel\Cursors", "SizeNS", "C:\\Windows\\Cursors\\aero_ns.cur", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Cursors", "SizeNS", "", "STRING")],
      why="Clear resize feedback helps edge-dragging windows precisely.",
      changes="SizeNS cursor set to aero_ns.cur.",
      risk="safe", impact="very low", recommended="optional",
      tags=["cursor", "resize", "vertical"]),
    T("mouse-043", "Aero Horizontal Resize Cursor",
      "Sets the horizontal resize cursor to the Aero scheme cursor.",
      actions=[("reg", "HKCU", r"Control Panel\Cursors", "SizeWE", "C:\\Windows\\Cursors\\aero_ew.cur", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Cursors", "SizeWE", "", "STRING")],
      why="Clear resize feedback for horizontal window edges.",
      changes="SizeWE cursor set to aero_ew.cur.",
      risk="safe", impact="very low", recommended="optional",
      tags=["cursor", "resize", "horizontal"]),
    T("mouse-044", "Aero Diagonal Resize Cursor",
      "Sets the NW-SE diagonal resize cursor to the Aero scheme cursor.",
      actions=[("reg", "HKCU", r"Control Panel\Cursors", "SizeNWSE", "C:\\Windows\\Cursors\\aero_nwse.cur", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Cursors", "SizeNWSE", "", "STRING")],
      why="Distinct corner-resize cursors speed up window corner dragging.",
      changes="SizeNWSE cursor set to aero_nwse.cur.",
      risk="safe", impact="very low", recommended="optional",
      tags=["cursor", "resize", "corner"]),
    T("mouse-045", "Aero Diagonal Resize Cursor 2",
      "Sets the NE-SW diagonal resize cursor to the Aero scheme cursor.",
      actions=[("reg", "HKCU", r"Control Panel\Cursors", "SizeNESW", "C:\\Windows\\Cursors\\aero_nesw.cur", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Cursors", "SizeNESW", "", "STRING")],
      why="Pairs with the NW-SE cursor for a complete resize set.",
      changes="SizeNESW cursor set to aero_nesw.cur.",
      risk="safe", impact="very low", recommended="optional",
      tags=["cursor", "resize", "corner"]),
    T("mouse-046", "Smaller Cursor Scale",
      "Lowers the base cursor size so pointer graphics render smaller.",
      actions=[("reg", "HKCU", r"Control Panel\Cursors", "CursorBaseSize", 24, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Cursors", "CursorBaseSize", 32, "DWORD")],
      why="A smaller base cursor matches low-DPI gaming and takes up less screen.",
      changes="CursorBaseSize set to 24.",
      risk="safe", impact="very low", recommended="optional",
      tags=["cursor", "size", "scale"]),
    T("mouse-047", "Scroll Inactive Windows on Hover",
      "Lets the wheel scroll windows under the pointer without activating them.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "LastActiveClick", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "LastActiveClick", 0, "DWORD")],
      why="Scrolling over a background window without clicking keeps focus on the game.",
      changes="LastActiveClick enabled.",
      risk="safe", impact="low", recommended="recommended",
      win="11",
      tags=["scroll", "hover", "focus"]),
    T("mouse-048", "Disable Snap Assist",
      "Disables the Snap Assist layout buttons shown when dragging a window to an edge.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "SnapAssist", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "SnapAssist", 1, "DWORD")],
      why="Snap Assist delays window placement while deciding a layout; disabling it snaps instantly.",
      changes="Snap Assist disabled.",
      risk="safe", impact="low", recommended="optional",
      win="11",
      tags=["snap", "window", "drag"]),
    T("mouse-049", "Disable Snap Fill",
      "Prevents windows from auto-filling available space when snapped.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "SnapFill", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "SnapFill", 1, "DWORD")],
      why="Auto-fill resizes windows the user did not ask to resize; disabling it keeps snap size predictable.",
      changes="Snap Fill disabled.",
      risk="safe", impact="very low", recommended="optional",
      win="11",
      tags=["snap", "fill", "window"]),
    T("mouse-050", "Drag Maximized Windows",
      "Allows dragging a maximized window off the top edge to restore and move it.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "DragFromMaximize", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "DragFromMaximize", 0, "DWORD")],
      why="One motion to restore and reposition a maximized game window is faster than double-clicking the titlebar.",
      changes="DragFromMaximize enabled.",
      risk="safe", impact="low", recommended="recommended",
      win="11",
      tags=["drag", "maximize", "window"]),
    T("mouse-051", "Disable MouseKeys",
      "Turns off the numpad-based MouseKeys pointer control.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\MouseKeys", "Flags", "62", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\MouseKeys", "Flags", "126", "STRING")],
      why="Stray numpad presses move the pointer when MouseKeys is on; disabling it keeps input predictable.",
      changes="MouseKeys disabled.",
      risk="safe", impact="low", recommended="recommended",
      tags=["mousekeys", "accessibility", "numpad"]),
    T("mouse-052", "Faster MouseKeys Speed",
      "Raises the top pointer speed for the numpad MouseKeys control.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\MouseKeys", "MaximumSpeed", "80", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\MouseKeys", "MaximumSpeed", "40", "STRING")],
      why="A higher ceiling makes MouseKeys usable when it is the only pointer input available.",
      changes="MouseKeys MaximumSpeed set to 80.",
      risk="safe", impact="very low", recommended="optional",
      tags=["mousekeys", "speed", "accessibility"]),
    T("mouse-053", "Faster MouseKeys Acceleration",
      "Shortens the time MouseKeys takes to reach its top pointer speed.",
      actions=[("reg", "HKCU", r"Control Panel\Accessibility\MouseKeys", "TimeToMaximumSpeed", "1500", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Accessibility\MouseKeys", "TimeToMaximumSpeed", "3000", "STRING")],
      why="A shorter ramp reaches full pointer speed sooner for quicker navigation.",
      changes="MouseKeys TimeToMaximumSpeed set to 1500 ms.",
      risk="safe", impact="very low", recommended="optional",
      tags=["mousekeys", "acceleration", "accessibility"]),
    T("mouse-054", "Mouse Driver Scan Mode",
      "Adds DeviceScanMode to every mouse class driver instance so USB mice stay reliably enumerated.",
      actions=[("regall", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e96f-e325-11ce-bfc1-08002be10318}", "DeviceScanMode", 4, "DWORD")],
      revert=[("regdelall", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e96f-e325-11ce-bfc1-08002be10318}", "DeviceScanMode")],
      why="Some wireless/USB mice drop out of enumeration under heavy USB traffic; scan mode 4 keeps the driver polling reliably.",
      changes="DeviceScanMode set to 4 on all mouse class instances.",
      risk="advanced", impact="low", recommended="advanced", admin=True,
      tags=["mouse", "driver", "usb"]),
    T("mouse-055", "Apply Pointer Settings Now",
      "Pushes the current pointer and desktop settings without a reboot.",
      actions=[("cmd", "rundll32.exe user32.dll,UpdatePerUserSystemParameters")],
      revert=[("guidance", "No persistent change to revert.")],
      why="Most Control Panel\\Mouse and desktop values only apply after a broadcast; this forces an immediate refresh.",
      changes="Refreshes per-user system parameters.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["apply", "refresh", "settings"]),
    T("mouse-056", "Open Mouse Properties",
      "Opens the classic Mouse control panel applet.",
      actions=[("cmd", "control mouse")],
      revert=[("guidance", "Close the window.")],
      why="Fast access to pointer options, buttons and wheel settings.",
      changes="Opens the Mouse control panel.",
      risk="safe", impact="very low", recommended="optional",
      tags=["control", "panel", "mouse"]),
    T("mouse-057", "Rescan Mouse Devices",
      "Tells Windows to re-detect all mouse and HID input devices.",
      actions=[("cmd", "pnputil /scan-devices")],
      revert=[("guidance", "No persistent change to revert.")],
      why="A rescan recovers a mouse that stopped responding after a driver hiccup or hub replug.",
      changes="Scans for new/changed input devices.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["pnputil", "rescan", "hid"]),
    T("mouse-058", "List Pointing Devices",
      "Lists every detected pointing device with its status and instance ID.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-PnpDevice -Class Mouse | Select-Object FriendlyName,InstanceId,Status | Format-Table -AutoSize\"")],
      revert=[("guidance", "No change to revert.")],
      why="Shows whether the mouse is healthy before hunting other causes of input lag.",
      changes="Prints the mouse device list.",
      risk="safe", impact="very low", recommended="optional",
      tags=["pnp", "device", "mouse"]),
    T("mouse-059", "Restart Explorer for Pointer UI",
      "Restarts Explorer so pointer and hover settings take effect in the shell.",
      actions=[("restart", "explorer")],
      revert=[("guidance", "No persistent change to revert.")],
      why="Some shell-level pointer options require Explorer to re-read their registry values.",
      changes="Restarts explorer.exe.",
      risk="low", impact="moderate", recommended="optional",
      tags=["explorer", "restart", "shell"]),
])
