"""Category: Network — TCP/IP stack and internet settings."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Network", win_default="7,8,10,11")
CATEGORY = "Network"

TWEAKS = validate_module("network", [
    T("net-002", "TCP Congestion Provider CTCP",
      "Switches the TCP congestion provider to Compound TCP.",
      actions=[("cmd", "netsh int tcp set global congestionprovider=ctcp")],
      revert=[("cmd", "netsh int tcp set global congestionprovider=none")],
      why="CTCP recovers throughput faster after packet loss, smoothing connections during spikes.",
      changes="Sets congestion provider to ctcp.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["tcp", "congestion", "ctcp"]),
    T("net-003", "Enable Receive-Side Scaling",
      "Turns on RSS so network processing spreads across CPU cores.",
      actions=[("cmd", "netsh int tcp set global rss=enabled")],
      revert=[("cmd", "netsh int tcp set global rss=disabled")],
      why="RSS distributes interrupt-heavy network work over multiple cores, lowering latency under load.",
      changes="Enables RSS.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["rss", "cpu", "scaling"]),
    T("net-004", "Enable ECN Capability",
      "Enables Explicit Congestion Notification on TCP.",
      actions=[("cmd", "netsh int tcp set global ecncapability=enabled")],
      revert=[("cmd", "netsh int tcp set global ecncapability=disabled")],
      why="ECN lets routers signal congestion without dropping packets, avoiding retransmit spikes.",
      changes="Enables ECN.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["ecn", "congestion", "tcp"]),
    T("net-005", "Disable TCP Timestamps",
      "Turns off TCP timestamp options.",
      actions=[("cmd", "netsh int tcp set global timestamps=disabled")],
      revert=[("cmd", "netsh int tcp set global timestamps=enabled")],
      why="Timestamps add 12 bytes per packet and can inflate RTT estimates on some routes.",
      changes="Disables TCP timestamps.",
      risk="low", impact="moderate", recommended="recommended", admin=True,
      tags=["timestamps", "rtt", "tcp"]),
    T("net-006", "Initial RTO 2000 ms",
      "Sets the TCP initial retransmission timeout to 2000 ms.",
      actions=[("cmd", "netsh int tcp set global initialrto=2000")],
      revert=[("cmd", "netsh int tcp set global initialrto=3000")],
      why="A faster first retransmit recovers from early packet loss sooner.",
      changes="Sets initial RTO to 2000 ms.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["rto", "retransmit", "tcp"]),
    T("net-007", "Max Connections Per Server (IE/Apps)",
      "Raises simultaneous connections per HTTP server to 8.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Internet Settings", "MaxConnectionsPerServer", 8, "DWORD")],
      revert=[("regdel", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Internet Settings", "MaxConnectionsPerServer")],
      why="Lets launchers and browsers download assets over more parallel connections.",
      changes="Sets MaxConnectionsPerServer to 8.",
      risk="safe", impact="low", recommended="recommended",
      tags=["http", "connections", "download"]),
    T("net-008", "Max Connections Per 1.0 Server",
      "Raises parallel connections for HTTP/1.0 servers to 8.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Internet Settings", "MaxConnectionsPer1_0Server", 8, "DWORD")],
      revert=[("regdel", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Internet Settings", "MaxConnectionsPer1_0Server")],
      why="Speeds up asset downloads from older launcher CDNs.",
      changes="Sets MaxConnectionsPer1_0Server to 8.",
      risk="safe", impact="low", recommended="recommended",
      tags=["http", "connections", "cdn"]),
    T("net-009", "Disable Network Throttling",
      "Raises the MMCSS network throttling index to maximum.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile", "NetworkThrottlingIndex", 0xffffffff, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile", "NetworkThrottlingIndex", 10, "DWORD")],
      why="Removes the 10-packet-per-second MMCSS cap that delays game network traffic.",
      changes="Disables network throttling in the multimedia scheduler.",
      risk="safe", impact="high", recommended="recommended", admin=True,
      tags=["throttling", "mmcss", "packets"]),
    T("net-010", "Default TTL 64",
      "Sets the default IPv4 time-to-live to 64.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "DefaultTTL", 64, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "DefaultTTL")],
      why="A consistent TTL avoids path quirks on home routers and keeps packets within the LAN.",
      changes="Sets DefaultTTL to 64.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["ttl", "ipv4", "routing"]),
    T("net-011", "TCP Window Scaling + Timestamps",
      "Enables RFC 1323 options for TCP (timestamps and window scaling).",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "Tcp1323Opts", 3, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "Tcp1323Opts")],
      why="Window scaling allows high-latency/high-bandwidth links to use larger windows.",
      changes="Sets Tcp1323Opts to 3.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["window", "tcp", "1323"]),
    T("net-012", "Fast DNS Guidance",
      "Recommends fast, low-latency public DNS servers.",
      actions=[("guidance", "Set DNS to Cloudflare 1.1.1.1 / 1.0.0.1 or Google 8.8.8.8 / 8.8.4.4 in your adapter properties. Avoid your ISP's default DNS if it is slow or filters content.")],
      revert=[("guidance", "Set DNS back to automatic (DHCP).")],
      why="Slow DNS resolution adds delay to every hostname lookup a game or launcher makes.",
      changes="Shows DNS guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["dns", "resolve", "latency"]),
    T("net-013", "Disable Delivery Optimization P2P",
      "Disables peer-to-peer Windows Update sharing.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Settings", "DODownloadMode", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Settings", "DODownloadMode", 1, "DWORD")],
      why="Stops background P2P uploads that can saturate your upstream during games.",
      changes="Sets DODownloadMode to 0 (off).",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["p2p", "update", "upload"]),
    T("net-014", "Flush DNS Cache",
      "Clears the DNS resolver cache.",
      actions=[("cmd", "ipconfig /flushdns")],
      revert=[("guidance", "The DNS cache repopulates automatically.")],
      why="Removes stale DNS entries that can send game traffic to dead endpoints.",
      changes="Flushes the DNS cache.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["dns", "flush", "resolve"]),
    T("net-015", "Reset TCP/IP Stack",
      "Resets the Winsock catalog and TCP/IP stack.",
      actions=[("cmd", "netsh winsock reset & netsh int ip reset & ipconfig /flushdns")],
      revert=[("guidance", "The stack resets to defaults after a restart.")],
      why="Fixes corrupted network stack state that causes random disconnects.",
      changes="Resets Winsock and TCP/IP.",
      risk="moderate", impact="low", recommended="optional", admin=True, confirm=True,
      tags=["winsock", "reset", "network"]),
    T("net-016", "Network Adapter Report",
      "Lists installed network adapters and their link speed.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-NetAdapter | Format-Table Name,InterfaceDescription,Status,LinkSpeed -AutoSize\"")],
      revert=[("guidance", "Read-only report; nothing to revert.")],
      why="Confirms your adapter negotiated the fastest link speed.",
      changes="Shows the adapter report.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["adapter", "link", "report"]),
])
