"""Category: Network — TCP/IP stack and internet settings."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Network", win_default="7,8,10,11")
CATEGORY = "Network"

TWEAKS = validate_module("network", [
    T("net-002", "TCP Congestion Provider CTCP",
      "Switches the TCP congestion provider to Compound TCP (modern Win11 + legacy fallback).",
      actions=[
          ("cmd", 'powershell -NoProfile -Command "if ([int](Get-CimInstance Win32_OperatingSystem).BuildNumber -ge 22000) { netsh int tcp set supplemental template=Internet congestionprovider=ctcp } else { netsh int tcp set global congestionprovider=ctcp }"'),
      ],
      revert=[
          ("cmd", 'powershell -NoProfile -Command "if ([int](Get-CimInstance Win32_OperatingSystem).BuildNumber -ge 22000) { netsh int tcp set supplemental template=Internet congestionprovider=default } else { netsh int tcp set global congestionprovider=none }"'),
      ],
      why="CTCP recovers throughput faster after packet loss, smoothing connections during spikes.",
      changes="Sets congestion provider to ctcp.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["tcp", "congestion", "ctcp"]),
    T("net-003", "Enable Receive-Side Scaling",
      "Turns on RSS so network processing spreads across CPU cores.",
      actions=[("cmd", "netsh int tcp set global rss=enabled")],
      revert=[("cmd", "netsh int tcp set global rss=disabled")],
      why="RSS distributes interrupt-heavy network work over multiple cores, lowering latency under load.",
      changes="Enables RSS.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["rss", "cpu", "scaling"]),
    T("net-004", "Enable ECN Capability",
      "Enables Explicit Congestion Notification on TCP.",
      actions=[("cmd", "netsh int tcp set global ecncapability=enabled")],
      revert=[("cmd", "netsh int tcp set global ecncapability=disabled")],
      why="ECN lets routers signal congestion without dropping packets, avoiding retransmit spikes.",
      changes="Enables ECN.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["ecn", "congestion", "tcp"]),
    T("net-005", "Disable TCP Timestamps",
      "Turns off TCP timestamp options.",
      actions=[("cmd", "netsh int tcp set global timestamps=disabled")],
      revert=[("cmd", "netsh int tcp set global timestamps=enabled")],
      why="Timestamps add 12 bytes per packet and can inflate RTT estimates on some routes.",
      changes="Disables TCP timestamps.",
      risk="low", impact="moderate", recommended="recommended", admin=True,
      tags=["timestamps", "rtt", "tcp"]),
    T("net-006", "Initial RTO 2000 ms",
      "Sets the TCP initial retransmission timeout to 2000 ms.",
      actions=[("cmd", "netsh int tcp set global initialrto=2000")],
      revert=[("cmd", "netsh int tcp set global initialrto=3000")],
      why="A faster first retransmit recovers from early packet loss sooner.",
      changes="Sets initial RTO to 2000 ms.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["rto", "retransmit", "tcp"]),
    T("net-007", "Max Connections Per Server (IE/Apps)",
      "Raises simultaneous connections per HTTP server to 8.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Internet Settings", "MaxConnectionsPerServer", 8, "DWORD")],
      revert=[("regdel", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Internet Settings", "MaxConnectionsPerServer")],
      why="Lets launchers and browsers download assets over more parallel connections.",
      changes="Sets MaxConnectionsPerServer to 8.",
      risk="safe", impact="low", recommended="recommended",
      tags=["http", "connections", "download"]),
    T("net-008", "Max Connections Per 1.0 Server",
      "Raises parallel connections for HTTP/1.0 servers to 8.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Internet Settings", "MaxConnectionsPer1_0Server", 8, "DWORD")],
      revert=[("regdel", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Internet Settings", "MaxConnectionsPer1_0Server")],
      why="Speeds up asset downloads from older launcher CDNs.",
      changes="Sets MaxConnectionsPer1_0Server to 8.",
      risk="safe", impact="low", recommended="recommended",
      tags=["http", "connections", "cdn"]),
    T("net-009", "Disable Network Throttling",
      "Raises the MMCSS network throttling index to maximum.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile", "NetworkThrottlingIndex", 0xffffffff, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile", "NetworkThrottlingIndex", 10, "DWORD")],
      why="Removes the 10-packet-per-second MMCSS cap that delays game network traffic.",
      changes="Disables network throttling in the multimedia scheduler.",
      risk="safe", impact="high", recommended="recommended", admin=True,
      tags=["throttling", "mmcss", "packets"]),
    T("net-010", "Default TTL 64",
      "Sets the default IPv4 time-to-live to 64.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "DefaultTTL", 64, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "DefaultTTL")],
      why="A consistent TTL avoids path quirks on home routers and keeps packets within the LAN.",
      changes="Sets DefaultTTL to 64.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["ttl", "ipv4", "routing"]),

    T("net-012", "Set DNS to Cloudflare",
      "Switches DNS to Cloudflare's fast public resolvers.",
      actions=[
          ("cmd", r'netsh interface ip set dns "Ethernet" static 1.1.1.1'),
          ("cmd", r'netsh interface ip add dns "Ethernet" 1.0.0.1 index=2'),
      ],
      revert=[("cmd", r'netsh interface ip set dns "Ethernet" dhcp')],
      why="Slow DNS resolution adds delay to every hostname lookup a game or launcher makes. Cloudflare 1.1.1.1 is among the fastest public resolvers.",
      changes="Sets primary DNS to 1.1.1.1 and secondary to 1.0.0.1.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["dns", "resolve", "latency"]),
    T("net-013", "Disable Delivery Optimization P2P",
      "Disables peer-to-peer Windows Update sharing.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Settings", "DODownloadMode", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Settings", "DODownloadMode", 1, "DWORD")],
      why="Stops background P2P uploads that can saturate your upstream during games.",
      changes="Sets DODownloadMode to 0 (off).",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["p2p", "update", "upload"]),
    T("net-014", "Flush DNS Cache",
      "Clears the DNS resolver cache.",
      actions=[("cmd", "ipconfig /flushdns")],
      revert=[("guidance", "The DNS cache repopulates automatically.")],
      why="Removes stale DNS entries that can send game traffic to dead endpoints.",
      changes="Flushes the DNS cache.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["dns", "flush", "resolve"]),
    T("net-015", "Reset TCP/IP Stack",
      "Resets the Winsock catalog and TCP/IP stack.",
      actions=[("cmd", "netsh winsock reset & netsh int ip reset & ipconfig /flushdns")],
      revert=[("guidance", "The stack resets to defaults after a restart.")],
      why="Fixes corrupted network stack state that causes random disconnects.",
      changes="Resets Winsock and TCP/IP.",
      risk="moderate", impact="low", recommended="optional", admin=True, confirm=True,
      tags=["winsock", "reset", "network"]),
    T("net-016", "Network Adapter Report",
      "Lists installed network adapters and their link speed.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-NetAdapter | Format-Table Name,InterfaceDescription,Status,LinkSpeed -AutoSize\"")],
      revert=[("guidance", "Read-only report; nothing to revert.")],
      why="Confirms your adapter negotiated the fastest link speed.",
      changes="Shows the adapter report.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["adapter", "link", "report"]),
    T("net-017", "Disable Nagle Algorithm",
      "Disables Nagle's algorithm on all network interfaces for lower latency.",
      actions=[
          ("cmd", 'powershell -NoProfile -ExecutionPolicy Bypass -Command "Get-ChildItem \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\' -ErrorAction SilentlyContinue | ForEach-Object { Set-ItemProperty -Path $_.PSPath -Name \'TcpAckFrequency\' -Value 1 -Type DWord -ErrorAction SilentlyContinue; Set-ItemProperty -Path $_.PSPath -Name \'TcpNoDelay\' -Value 1 -Type DWord -ErrorAction SilentlyContinue }"'),
      ],
      revert=[
          ("cmd", 'powershell -NoProfile -ExecutionPolicy Bypass -Command "Get-ChildItem \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\' -ErrorAction SilentlyContinue | ForEach-Object { Remove-ItemProperty -Path $_.PSPath -Name \'TcpAckFrequency\' -ErrorAction SilentlyContinue; Remove-ItemProperty -Path $_.PSPath -Name \'TcpNoDelay\' -ErrorAction SilentlyContinue }"'),
      ],
      why="Nagle's algorithm batches small packets, adding latency to real-time game traffic.",
      changes="Sets TcpAckFrequency=1 and TcpNoDelay=1 on all interfaces.",
      risk="low", impact="high", recommended="recommended", admin=True,
      tags=["nagle", "latency", "tcp"]),
    T("net-019", "Disable RSS on Low RAM",
      "Disables Receive-Side Scaling on systems with limited RAM to free memory for games.",
      actions=[("cmd", "netsh int tcp set global rss=disabled")],
      revert=[("cmd", "netsh int tcp set global rss=enabled")],
      why="RSS consumes dedicated memory per CPU core; on low-RAM systems disabling it frees memory that games need more than network throughput.",
      changes="Disables Receive-Side Scaling.",
      risk="low", impact="low", recommended="optional", admin=True,
      when={"ram_gb": {"<": 8}},
      tags=["rss", "network", "lowram"]),

])
