"""Category: NVIDIA — GeForce driver and NVIDIA Control Panel guidance."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("NVIDIA", win_default="7,8,10,11")
CATEGORY = "NVIDIA"

TWEAKS = validate_module("nvidia", [
    T("nv-001", "Enable Persistence Mode",
      "Keeps the NVIDIA driver resident to lower launch stalls.",
      actions=[("cmd", "nvidia-smi -pm 1")],
      revert=[("cmd", "nvidia-smi -pm 0")],
      why="Persistence mode avoids reloading driver state between applications.",
      changes="Sets GPU persistence mode on.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["persistence", "driver", "nvidia"]),
    T("nv-002", "Reset Auto Boost Defaults",
      "Returns GPU boost clocks to driver defaults.",
      actions=[("cmd", "nvidia-smi --auto-boost-default=0")],
      revert=[("cmd", "nvidia-smi --auto-boost-default=1")],
      why="Clears custom boost state so the GPU boost algorithm runs normally.",
      changes="Resets auto-boost settings.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["boost", "clock", "nvidia"]),
    T("nv-003", "Enable PowerMizer",
      "Allows the driver to manage GPU power states.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000", "PowerMizerEnable", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000", "PowerMizerEnable")],
      why="PowerMizer handles GPU clock transitions on GeForce cards.",
      changes="Enables PowerMizer control.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      when={"gpu": ["nvidia"]},
      tags=["powermizer", "power", "clock"]),
    T("nv-004", "Set Performance Level Source",
      "Selects the highest GPU performance level set.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000", "PerfLevelSrc", 0x3322, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000", "PerfLevelSrc")],
      why="PerfLevelSrc 0x3322 keeps the GPU at its boostable performance level set.",
      changes="Sets PerfLevelSrc to maximum performance.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      when={"gpu": ["nvidia"]},
      tags=["perflevel", "boost", "clock"]),
    T("nv-005", "Disable NVIDIA Telemetry Service",
      "Stops the NVIDIA telemetry background service.",
      actions=[("sc", "disable", "NvTelemetryContainer")],
      revert=[("sc", "enable", "NvTelemetryContainer")],
      why="Telemetry services poll in the background and add wake-ups.",
      changes="Disables NvTelemetryContainer.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      when={"gpu": ["nvidia"]},
      tags=["telemetry", "service", "nvidia"]),
    T("nv-006", "Disable GeForce Experience Overlay",
      "Guidance to disable the in-game overlay.",
      actions=[("guidance", "In GeForce Experience > Settings turn off the 'In-Game Overlay'. This removes the shadowplay layer and its input overhead from games.")],
      revert=[("guidance", "Re-enable the overlay.")],
      why="The overlay intercepts frame presentation and input.",
      changes="Shows overlay guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["overlay", "geforce", "shadowplay"]),
    T("nv-007", "Low Latency Mode Guidance",
      "Guidance on NVIDIA Low Latency Mode.",
      actions=[("guidance", "In NVIDIA Control Panel set 'Low Latency Mode' to 'Ultra' for competitive shooters (works best with Reflex), or 'On' otherwise. Do not combine Ultra with frame caps below the monitor rate.")],
      revert=[("guidance", "Set Low Latency Mode back to Off.")],
      why="Low Latency Mode trims queued frames before they reach the GPU.",
      changes="Shows low-latency guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["latency", "reflex", "nvidia"]),
    T("nv-008", "Prefer Maximum Performance Power",
      "Guidance to prefer max performance power mode.",
      actions=[("guidance", "In NVIDIA Control Panel > Manage 3D Settings set 'Power management mode' to 'Prefer maximum performance' for the game profile to avoid downclock dips between frames.")],
      revert=[("guidance", "Restore 'Optimal power'.")],
      why="GPU downclocking between frames shows up as frame-time spikes.",
      changes="Shows power-mode guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["power", "downclock", "performance"]),
    T("nv-009", "G-SYNC Compatibility Check",
      "Guidance to verify G-SYNC on a monitor.",
      actions=[("guidance", "In NVIDIA Control Panel > Set up G-SYNC, enable G-SYNC for your monitor. Use the G-SYNC pendulum demo or 'G-SYNC indicator' overlay to confirm it is active in-game.")],
      revert=[("guidance", "Disable G-SYNC.")],
      why="A G-SYNC monitor not detected is a missed smoothness upgrade.",
      changes="Shows G-SYNC guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["gsync", "sync", "monitor"]),
    T("nv-010", "Disable DSR Factors",
      "Guidance to turn off DSR downscaling.",
      actions=[("guidance", "If DSR is enabled in NVIDIA Control Panel, disable it for games. DSR renders above native resolution then downscales, costing a lot of GPU time for little visible gain at native res.")],
      revert=[("guidance", "Re-enable DSR.")],
      why="DSR multiplies render cost and reduces effective refresh headroom.",
      changes="Shows DSR guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["dsr", "resolution", "supersample"]),
    T("nv-011", "Threaded Optimization",
      "Guidance on NVIDIA threaded optimization.",
      actions=[("guidance", "Leave 'Threaded Optimization' at 'Auto'. Forcing it 'On' can hurt old single-threaded titles; forcing 'Off' can raise CPU load on modern ones.")],
      revert=[("guidance", "Set Threaded Optimization to Auto.")],
      why="Driver heuristics usually pick the right threading mode.",
      changes="Shows threaded-optimization guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["threads", "cpu", "optimization"]),
    T("nv-012", "Pre-Rendered Frames Setting",
      "Guidance on maximum pre-rendered frames.",
      actions=[("guidance", "For latency-sensitive games set 'Maximum pre-rendered frames' to 1 in the NVIDIA Control Panel. Use Low Latency Mode or Reflex instead of stacking both.")],
      revert=[("guidance", "Restore the default pre-rendered frame count.")],
      why="Fewer queued frames = less latency but can raise CPU cost.",
      changes="Shows pre-rendered frames guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["frames", "queue", "latency"]),
    T("nv-013", "Driver Update Guidance",
      "Guidance for stable driver updates.",
      actions=[("guidance", "Use the latest Game Ready driver or a verified Studio driver. Avoid beta drivers for ranked play; install via 'Clean install' to reset stale settings.")],
      revert=[("guidance", "Roll back the driver.")],
      why="New game releases rely on updated drivers, but betas can regress.",
      changes="Shows driver guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["driver", "update", "game ready"]),
    T("nv-014", "Disable Ansel",
      "Guidance to disable the Ansel screenshot tool.",
      actions=[("guidance", "If you do not use NVIDIA Ansel (free camera screenshots), avoid launching it — it can pause the render loop. There is no registry toggle; just do not invoke Alt+F2.")],
      revert=[("guidance", "No change to revert.")],
      why="Ansel pauses game rendering while active.",
      changes="Shows Ansel guidance.",
      risk="safe", impact="very low", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["ansel", "screenshot", "overlay"]),
    T("nv-015", "Reflex Low Latency Guidance",
      "Guidance for NVIDIA Reflex in supported games.",
      actions=[("guidance", "Enable NVIDIA Reflex 'On + Boost' in supported games. Reflex aligns CPU and GPU work and trims render queue latency — the biggest measurable input-lag reduction available.")],
      revert=[("guidance", "Turn Reflex off in the game.")],
      why="Reflex reduces system latency by coordinating the CPU and GPU.",
      changes="Shows Reflex guidance.",
      risk="safe", impact="high", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["reflex", "latency", "esports"]),
    T("nv-016", "Disable ShadowPlay Recording",
      "Guidance to stop background recording.",
      actions=[("guidance", "Turn off 'Instant Replay' in GeForce Experience or ShadowPlay when not recording. Constant background recording taxes the encoder and VRAM.")],
      revert=[("guidance", "Re-enable Instant Replay.")],
      why="Continuous encoding consumes GPU video engine time and memory.",
      changes="Shows ShadowPlay guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["shadowplay", "recording", "encode"]),
])
