"""Category: Power Plans — creating and managing power plans."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Power Plans", win_default="7,8,10,11")
CATEGORY = "Power Plans"

TWEAKS = validate_module("power_plans", [
    T("pp-001", "List Available Power Plans",
      "Lists all available power schemes.",
      actions=[("cmd", "powercfg /list")],
      revert=[("guidance", "No change to revert.")],
      why="Confirms which plans exist and their GUIDs before switching.",
      changes="Shows the power plan list.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["power", "plan", "list"]),
    T("pp-002", "Create Balanced Duplicate",
      "Guidance on duplicating a plan to customize.",
      actions=[("guidance", "Run 'powercfg /duplicatescheme GUID' to clone a plan, then edit the copy with powercfg. Never edit the built-in plans directly so you keep a known-good fallback.")],
      revert=[("guidance", "Delete the duplicate plan.")],
      why="A custom plan that breaks can be removed without losing defaults.",
      changes="Shows plan-duplication guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["duplicate", "plan", "custom"]),
    T("pp-003", "Set AC Processor Boost Mode",
      "Sets the processor boost mode on AC power.",
      actions=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_PROCESSOR PERFBOOSTMODE 2")],
      revert=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_PROCESSOR PERFBOOSTMODE 3")],
      why="Boost mode 2 (aggressive) lets the CPU hold higher boost clocks.",
      changes="Sets processor boost mode to Aggressive.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["boost", "cpu", "ac"]),
    T("pp-004", "Set AC Processor Performance Boost Percent",
      "Raises the processor performance boost percentage.",
      actions=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_PROCESSOR PERFBOOSTMODE 2")],
      revert=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_PROCESSOR PERFBOOSTMODE 3")],
      why="A higher boost percentage allows sustained boost clocks.",
      changes="Raises the AC boost percentage.",
      risk="safe", impact="moderate", recommended="optional", admin=True,
      tags=["boost", "percent", "cpu"]),
    T("pp-005", "Set Idle Disable Timer",
      "Guidance on the CPU idle disable threshold.",
      actions=[("guidance", "The 'Idle Disable' threshold lets Windows trade idle time for clock stability. Raising it via the hidden 'Processor performance boost' advanced settings can stabilize frame times at the cost of idle power.")],
      revert=[("guidance", "Reset the idle disable setting.")],
      why="Short idle windows downclock the CPU just before the next frame.",
      changes="Shows idle-disable guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["idle", "disable", "clock"]),
    T("pp-006", "Export Current Plan",
      "Exports the active power plan to a file.",
      actions=[("cmd", "powercfg /EXPORT /tmp/powerplan.pow")],
      revert=[("guidance", "Delete the exported file.")],
      why="A backup lets you restore a working plan after experiments.",
      changes="Exports the active power plan.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["export", "backup", "plan"]),
    T("pp-007", "Import a Power Plan",
      "Imports a power plan from a .pow file.",
      actions=[("cmd", "powercfg /IMPORT /tmp/powerplan.pow")],
      revert=[("guidance", "Remove the imported plan.")],
      why="Restores a plan exported earlier or from another machine.",
      changes="Imports the power plan.",
      risk="safe", impact="low", recommended="optional",
      tags=["import", "restore", "plan"]),
    T("pp-009", "Disable Sleep on Lid Close (Laptop)",
      "Guidance for laptop lid-close behaviour.",
      actions=[("guidance", "On laptops set lid-close to 'Do nothing' when plugged in (Control Panel > Power Options) so a closing lid does not sleep mid-match.")],
      revert=[("guidance", "Restore lid-close to Sleep.")],
      why="Lid close sleeping disconnects the game session and GPU.",
      changes="Shows lid-close guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"laptop": True},
      tags=["laptop", "lid", "sleep"]),
    T("pp-010", "Restore Default Plans",
      "Restores the built-in power plans.",
      actions=[("cmd", "powercfg -restoredefaultschemes")],
      revert=[("guidance", "Re-apply the tweaked plan.")],
      why="Recreates missing default plans after cleanup.",
      changes="Restores default power schemes.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["restore", "default", "plans"]),
    T("pp-011", "Power Scheme Battery Guidance",
      "Guidance for laptop battery plans.",
      actions=[("guidance", "For laptop gaming on battery, the 'Balanced' plan with boost mode off extends playtime; on AC use a performance plan. Switching plans per session is normal.")],
      revert=[("guidance", "No change to revert.")],
      why="Battery plans trade boost clocks for runtime.",
      changes="Shows battery-plan guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"laptop": True},
      tags=["battery", "laptop", "plan"]),
    T("pp-012", "Remove Unused Power Plans",
      "Guidance to delete unused plans.",
      actions=[("guidance", "Run 'powercfg /delete GUID' for plans you never use. Fewer plans = fewer surprises when Windows picks a plan at boot.")],
      revert=[("guidance", "Recreate the deleted plan.")],
      why="Windows can switch to hidden default plans unexpectedly.",
      changes="Shows plan-deletion guidance.",
      risk="safe", impact="very low", recommended="optional",
      tags=["delete", "plans", "cleanup"]),
])
