"""Category: Power — power settings and energy behaviour."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Power", win_default="7,8,10,11")
CATEGORY = "Power"

TWEAKS = validate_module("power", [
    T("power-001", "Set High Performance Plan",
      "Activates the High performance power plan.",
      actions=[("cmd", "powercfg /setactive SCHEME_MIN")],
      revert=[("cmd", "powercfg /setactive SCHEME_BALANCED")],
      why="Keeps CPU and GPU clocks from dropping between frames.",
      changes="Sets the High performance plan active.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["power", "plan", "performance"]),
    T("power-002", "Disable USB Selective Suspend",
      "Prevents USB ports from suspending.",
      actions=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 0")],
      revert=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 1")],
      why="USB suspend causes controller dropouts for mice and headsets during play.",
      changes="Disables USB selective suspend.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["usb", "suspend", "peripheral"]),
    T("power-003", "Disable PCI Express ASPM",
      "Prevents PCIe link power saving.",
      actions=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 501a4d13-42af-4429-9fd1-a8218c268e20 ee12f906-d277-404b-b6da-e5fa1a576df5 0")],
      revert=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 501a4d13-42af-4429-9fd1-a8218c268e20 ee12f906-d277-404b-b6da-e5fa1a576df5 3")],
      why="ASPM power-saving can add latency to GPU/SSD links.",
      changes="Disables PCI Express Link State power management.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["pcie", "aspm", "latency"]),
    T("power-004", "Set Sleep to Never",
      "Prevents the system from sleeping.",
      actions=[("cmd", "powercfg /change standby-timeout-ac 0")],
      revert=[("cmd", "powercfg /change standby-timeout-ac 30")],
      why="Sleep interrupts long downloads and game sessions.",
      changes="Sets sleep timeout to never on AC.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["sleep", "timeout", "power"]),
    T("power-005", "Set Display Off Timeout",
      "Sets display-off timeout to 15 minutes.",
      actions=[("cmd", "powercfg /change monitor-timeout-ac 15")],
      revert=[("cmd", "powercfg /change monitor-timeout-ac 10")],
      why="Keeps the monitor on through menus without burning power forever.",
      changes="Sets monitor timeout to 15 minutes.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["monitor", "timeout", "display"]),
    T("power-006", "Disable Hibernation",
      "Turns off hibernation and deletes the hibernation file.",
      actions=[("cmd", "powercfg /h off")],
      revert=[("cmd", "powercfg /h on")],
      why="Frees the hiberfil.sys disk space and removes hibernation overhead.",
      changes="Disables hibernation.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["hibernate", "disk", "power"]),
    T("power-007", "Enable Ultimate Performance Plan",
      "Activates the Ultimate Performance power plan.",
      actions=[("cmd", "powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61")],
      revert=[("cmd", "powercfg /setactive SCHEME_BALANCED")],
      why="Exposes hidden maximum-performance settings on supported systems.",
      changes="Creates and activates Ultimate Performance.",
      risk="safe", impact="moderate", recommended="optional", admin=True,
      tags=["ultimate", "plan", "power"]),
    T("power-008", "Disable Processor Idle State Control",
      "Guidance about C-states and latency.",
      actions=[("guidance", "Disabling C-states (processor idle) via BIOS reduces exit latency but raises idle power and heat. Only do this on a desktop chasing minimum input latency, and monitor thermals.")],
      revert=[("guidance", "Re-enable C-states.")],
      why="C-state exit latency adds microseconds that can matter at 1000Hz.",
      changes="Shows C-state guidance.",
      risk="safe", impact="moderate", recommended="optional",
      tags=["cstates", "idle", "latency"]),
    T("power-009", "Set Minimum Processor State",
      "Keeps the CPU at a high clock floor on AC.",
      actions=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 54533251-82be-4824-96c1-47b60b740d00 893dee8e-2bef-41e0-89c6-b55d0929964c 20")],
      revert=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 54533251-82be-4824-96c1-47b60b740d00 893dee8e-2bef-41e0-89c6-b55d0929964c 5")],
      why="Raising the clock floor (20%) avoids deep downclocking in short idle frames.",
      changes="Sets minimum processor state to 20%.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["cpu", "clock", "power"]),
    T("power-010", "Disable Adaptive Brightness",
      "Turns off display adaptive brightness.",
      actions=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 7516b95f-f776-4464-8c53-06167f40cc99 fbd9aa66-9553-4097-ba44-ed6e9d65eab8 0")],
      revert=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 7516b95f-f776-4464-8c53-06167f40cc99 fbd9aa66-9553-4097-ba44-ed6e9d65eab8 1")],
      why="Sensor-based dimming changes brightness mid-match.",
      changes="Disables adaptive brightness on AC.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["brightness", "adaptive", "sensor"]),
    T("power-011", "Disable Hard Disk Sleep",
      "Prevents the disk from idling down.",
      actions=[("cmd", "powercfg /change disk-timeout-ac 0")],
      revert=[("cmd", "powercfg /change disk-timeout-ac 20")],
      why="Disk spin-down causes a stall when a game reads assets after idle.",
      changes="Sets hard disk timeout to never.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["disk", "sleep", "timeout"]),
    T("power-012", "Disable Power Throttling",
      "Prevents background app power throttling.",
      actions=[("guidance", "For laptops, disable 'Power throttling' for game executables in Task Manager > Details > Power usage mode > Unrestricted, or disable it globally in Power Options.")],
      revert=[("guidance", "Re-enable power throttling.")],
      why="Power throttling limits CPU frequency for background/edge apps.",
      changes="Shows power-throttling guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["throttle", "cpu", "laptop"]),
    T("power-013", "Disable Connected Standby",
      "Guidance about Modern Standby.",
      actions=[("guidance", "Modern Standby keeps the CPU in low-power states with network on. On desktops it can delay wake and cause background wakes. Only disable via BIOS if your system supports classic S3.")],
      revert=[("guidance", "Re-enable Modern Standby.")],
      why="Modern Standby wake behavior confuses some desktop builds.",
      changes="Shows Modern Standby guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["standby", "s3", "wake"]),
    T("power-014", "Set USB Power Policy",
      "Guidance on USB controller power.",
      actions=[("guidance", "In Device Manager, set each USB Root Hub 'Allow the computer to turn off this device' to off to avoid controller resets mid-game.")],
      revert=[("guidance", "Allow the computer to power off the device.")],
      why="Controller power-off resets momentarily drop mouse/keyboard input.",
      changes="Shows USB power guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["usb", "power", "input"]),
])
