"""Category: Power — power settings and energy behaviour."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Power", win_default="7,8,10,11")
CATEGORY = "Power"

TWEAKS = validate_module("power", [
    T("power-002", "Disable USB Selective Suspend",
      "Prevents USB ports from suspending.",
      actions=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 0")],
      revert=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 1")],
      why="USB suspend causes controller dropouts for mice and headsets during play.",
      changes="Disables USB selective suspend.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["usb", "suspend", "peripheral"]),
    T("power-003", "Disable PCI Express ASPM",
      "Prevents PCIe link power saving.",
      actions=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 501a4d13-42af-4429-9fd1-a8218c268e20 ee12f906-d277-404b-b6da-e5fa1a576df5 0")],
      revert=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 501a4d13-42af-4429-9fd1-a8218c268e20 ee12f906-d277-404b-b6da-e5fa1a576df5 3")],
      why="ASPM power-saving can add latency to GPU/SSD links.",
      changes="Disables PCI Express Link State power management.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["pcie", "aspm", "latency"]),
    T("power-004", "Set Sleep to Never",
      "Prevents the system from sleeping.",
      actions=[("cmd", "powercfg /change standby-timeout-ac 0")],
      revert=[("cmd", "powercfg /change standby-timeout-ac 30")],
      why="Sleep interrupts long downloads and game sessions.",
      changes="Sets sleep timeout to never on AC.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["sleep", "timeout", "power"]),
    T("power-005", "Set Display Off Timeout",
      "Sets display-off timeout to 15 minutes.",
      actions=[("cmd", "powercfg /change monitor-timeout-ac 15")],
      revert=[("cmd", "powercfg /change monitor-timeout-ac 10")],
      why="Keeps the monitor on through menus without burning power forever.",
      changes="Sets monitor timeout to 15 minutes.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["monitor", "timeout", "display"]),
    T("power-006", "Disable Hibernation",
      "Turns off hibernation and deletes the hibernation file.",
      actions=[("cmd", "powercfg /h off")],
      revert=[("cmd", "powercfg /h on")],
      why="Frees the hiberfil.sys disk space and removes hibernation overhead.",
      changes="Disables hibernation.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["hibernate", "disk", "power"]),

    T("power-008", "Disable Processor Idle State Control",
      "Guidance about C-states and latency.",
      actions=[("guidance", "Disabling C-states (processor idle) via BIOS reduces exit latency but raises idle power and heat. Only do this on a desktop chasing minimum input latency, and monitor thermals.")],
      revert=[("guidance", "Re-enable C-states.")],
      why="C-state exit latency adds microseconds that can matter at 1000Hz.",
      changes="Shows C-state guidance.",
      risk="safe", impact="moderate", recommended="optional",
      tags=["cstates", "idle", "latency"]),
    T("power-009", "Set Minimum Processor State",
      "Keeps the CPU at a high clock floor on AC.",
      actions=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 54533251-82be-4824-96c1-47b60b740d00 893dee8e-2bef-41e0-89c6-b55d0929964c 5")],
      revert=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 54533251-82be-4824-96c1-47b60b740d00 893dee8e-2bef-41e0-89c6-b55d0929964c 5")],
      why="Raising the clock floor (5%) avoids deep downclocking in short idle frames.",
      changes="Sets minimum processor state to 5%.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["cpu", "clock", "power"]),
    T("power-010", "Disable Adaptive Brightness",
      "Turns off display adaptive brightness.",
      actions=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 7516b95f-f776-4464-8c53-06167f40cc99 fbd9aa66-9553-4097-ba44-ed6e9d65eab8 0")],
      revert=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 7516b95f-f776-4464-8c53-06167f40cc99 fbd9aa66-9553-4097-ba44-ed6e9d65eab8 1")],
      why="Sensor-based dimming changes brightness mid-match.",
      changes="Disables adaptive brightness on AC.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["brightness", "adaptive", "sensor"]),
    T("power-011", "Disable Hard Disk Sleep",
      "Prevents the disk from idling down.",
      actions=[("cmd", "powercfg /change disk-timeout-ac 0")],
      revert=[("cmd", "powercfg /change disk-timeout-ac 20")],
      why="Disk spin-down causes a stall when a game reads assets after idle.",
      changes="Sets hard disk timeout to never.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["disk", "sleep", "timeout"]),
    T("power-012", "Disable Power Throttling",
      "Prevents background app power throttling.",
      actions=[("guidance", "For laptops, disable 'Power throttling' for game executables in Task Manager > Details > Power usage mode > Unrestricted, or disable it globally in Power Options.")],
      revert=[("guidance", "Re-enable power throttling.")],
      why="Power throttling limits CPU frequency for background/edge apps.",
      changes="Shows power-throttling guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["throttle", "cpu", "laptop"]),
    T("power-013", "Disable Connected Standby",
      "Guidance about Modern Standby.",
      actions=[("guidance", "Modern Standby keeps the CPU in low-power states with network on. On desktops it can delay wake and cause background wakes. Only disable via BIOS if your system supports classic S3.")],
      revert=[("guidance", "Re-enable Modern Standby.")],
      why="Modern Standby wake behavior confuses some desktop builds.",
      changes="Shows Modern Standby guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["standby", "s3", "wake"]),
    T("power-014", "Disable USB Idle Power Management",
      "Prevents USB controllers from entering idle power states that cause resets.",
      actions=[("regall", "HKLM", r"SYSTEM\CurrentControlSet\Enum\ROOT\USB\*\*\Device Parameters\WDF", "AllowIdleIrpInD3", 0, "DWORD")],
      revert=[("regdelall", "HKLM", r"SYSTEM\CurrentControlSet\Enum\ROOT\USB\*\*\Device Parameters\WDF", "AllowIdleIrpInD3")],
      why="Controller power-off resets momentarily drop mouse/keyboard input. Disabling idle IRP in D3 prevents USB controller resets mid-game.",
      changes="Sets AllowIdleIrpInD3 to 0 on all USB controllers.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["usb", "power", "input"]),

    T("power-016", "Disable Fast Startup",
      "Turns off Windows Fast Startup so the system performs a full cold boot every time.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Power", "HiberbootEnabled", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Power", "HiberbootEnabled", 1, "DWORD")],
      why="Fast Startup uses a hibernation-based resume that can cause driver state issues and slower cold-boot performance.",
      changes="Sets HiberbootEnabled to 0.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["boot", "faststartup", "hibernate"]),
    T("power-017", "Disable Timer Coalescing",
      "Forces all timer resolution requests to merge so the system keeps the highest requested resolution.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\kernel", "GlobalTimerResolutionRequests", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\kernel", "GlobalTimerResolutionRequests")],
      why="Timer coalescing can merge high-frequency timers into lower-frequency batches, adding frame-time jitter in games.",
      changes="Sets GlobalTimerResolutionRequests to 1.",
      risk="low", impact="moderate", recommended="optional", admin=True,
      tags=["timer", "coalescing", "latency"]),
    T("power-018", "Disable Power Telemetry",
      "Turns off Windows power telemetry collection to reduce background CPU and disk activity.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Power", "DisablePowerTelemetry", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Power", "DisablePowerTelemetry")],
      why="Power telemetry periodically samples power usage; disabling it removes a constant background poller.",
      changes="Sets DisablePowerTelemetry to 1.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["telemetry", "power", "background"]),
    T("power-019", "Disable Power Estimation",
      "Turns off the Windows power estimation engine to stop periodic CPU wake-ups for power tracking.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Power", "DisablePowerEstimation", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Power", "DisablePowerEstimation")],
      why="The power estimation engine wakes the CPU at intervals to compute power draw; disabling it eliminates those wakes.",
      changes="Sets DisablePowerEstimation to 1.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["power", "estimation", "background"]),
    T("power-020", "Disable Device Power Saving",
      "Turns off device-level power saving on AC so peripherals and storage never enter low-power states.",
      actions=[
          ("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT e276e160-8f0a-4f71-8ab2-366a5eb94e14 0198bb97-0a37-4e35-8801-0f1b3f6d1a8b 0"),
          ("cmd", "powercfg /setactive SCHEME_CURRENT"),
      ],
      revert=[
          ("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT e276e160-8f0a-4f71-8ab2-366a5eb94e14 0198bb97-0a37-4e35-8801-0f1b3f6d1a8b 1"),
          ("cmd", "powercfg /setactive SCHEME_CURRENT"),
      ],
      why="Device power saving can cause controller dropouts, storage latency spikes, and USB disconnects during gameplay.",
      changes="Disables device idle power saving on AC.",
      risk="low", impact="moderate", recommended="recommended", admin=True,
      tags=["device", "power", "idle", "peripheral"]),
    T("power-021", "Disable Power Throttling",
      "Turns off Windows Power Throttling globally so background processes are not duty-cycled to save energy.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Power\PowerThrottling", "PowerThrottlingOff", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Power\PowerThrottling", "PowerThrottlingOff", 0, "DWORD")],
      why="Power Throttling duty-cycles background threads to conserve energy; disabling it keeps work finishing promptly on AC.",
      changes="Sets PowerThrottlingOff=1 in the PowerThrottling control key.",
      risk="low", impact="moderate", recommended="recommended", admin=True,
      tags=["throttling", "power", "background"]),
    T("power-022", "Disable Lazy Mode",
      "Turns off CPU lazy idle mode so cores transition out of idle states immediately instead of waiting.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Power", "LazyMode", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Power", "LazyMode", 1, "DWORD")],
      why="Lazy mode delays idle-state transitions to save power; disabling it makes cores wake faster under sudden load.",
      changes="Sets LazyMode to 0.",
      risk="low", impact="moderate", recommended="optional", admin=True,
      tags=["idle", "power", "wake", "latency"]),
    T("power-023", "Disable DIPM",
      "Disables Device Initiated Power Management on NVMe drives to prevent aggressive low-power transitions.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Services\stornvme", "DIPM", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Services\stornvme", "DIPM", 1, "DWORD")],
      why="DIPM lets NVMe drives enter power-saving states during idle, which adds wake latency when the drive is accessed again.",
      changes="Sets stornvme DIPM to 0.",
      risk="low", impact="moderate", recommended="optional", admin=True,
      tags=["nvme", "dipm", "storage", "power"]),
    T("power-024", "Disable HIPM",
      "Disables Host Initiated Power Management on NVMe drives to prevent the OS from putting drives into low-power states.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Services\stornvme", "HIPM", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Services\stornvme", "HIPM", 1, "DWORD")],
      why="HIPM allows the host to command NVMe drives into power-saving states, adding wake latency on the next access.",
      changes="Sets stornvme HIPM to 0.",
      risk="low", impact="moderate", recommended="optional", admin=True,
      tags=["nvme", "hipm", "storage", "power"]),
    T("power-025", "Disable Hidden Power Saving",
      "Turns off the AoAcOverride that enables Always On Always Connected hidden power-saving states.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Power", "AoAcOverride", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Power", "AoAcOverride", 1, "DWORD")],
      why="AoAcOverride enables hidden low-power states that can throttle devices and add wake latency on desktop systems.",
      changes="Sets AoAcOverride to 0.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["aoac", "power", "standby", "desktop"]),
    T("power-026", "Disable Sleep Study",
      "Turns off the Windows Sleep Study diagnostic logger to reduce background disk and CPU activity.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Power\SleepStudy", "Enabled", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Power\SleepStudy", "Enabled", 1, "DWORD")],
      why="Sleep Study periodically logs power-state transitions; disabling it removes unnecessary background I/O.",
      changes="Sets SleepStudy Enabled to 0.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["sleep", "study", "diagnostic", "background"]),
    T("power-027", "Disable Connected Standby",
      "Disables Connected Standby (Modern Standby) via the platform override to force classic S3 sleep behavior.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Power", "PlatformAoAcOverride", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Power", "PlatformAoAcOverride")],
      why="Connected Standby keeps the network stack and background tasks alive during sleep, which can cause wake delays and unexpected power draws.",
      changes="Sets PlatformAoAcOverride to 0.",
      risk="moderate", impact="moderate", recommended="optional", admin=True,
      tags=["standby", "connected", "modern", "s3"]),
])
