"""Category: Privacy — privacy settings and data collection."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Privacy", win_default="10,11")
CATEGORY = "Privacy"

TWEAKS = validate_module("privacy", [
    T("priv-001", "Disable Suggested Content",
      "Turns off suggested app content in Start.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-338389Enabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-338389Enabled", 1, "DWORD")],
      why="Stops Start from pulling suggested apps and content.",
      changes="Disables suggested content.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["start", "suggestions", "content"]),
    T("priv-002", "Disable Tailored Experiences",
      "Turns off tailored ad experiences.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Privacy", "TailoredExperiencesWithDiagnosticDataEnabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Privacy", "TailoredExperiencesWithDiagnosticDataEnabled", 1, "DWORD")],
      why="Stops ad personalization using diagnostic data.",
      changes="Disables tailored experiences.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["tailored", "ads", "privacy"]),
    T("priv-003", "Disable Online Speech",
      "Turns off online speech recognition.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Speech", "OnlineSpeechPrivacy", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Speech", "OnlineSpeechPrivacy", 1, "DWORD")],
      why="Prevents voice data uploads for recognition.",
      changes="Disables online speech.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["speech", "voice", "privacy"]),
    T("priv-004", "Disable Handwriting Data",
      "Turns off handwriting data collection.",
      actions=[("reg", "HKCU", r"Software\Microsoft\InputPersonalization", "RestrictImplicitInkCollection", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\InputPersonalization", "RestrictImplicitInkCollection", 0, "DWORD")],
      why="Stops implicit ink/handwriting training data collection.",
      changes="Restricts implicit ink collection.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["ink", "handwriting", "privacy"]),
    T("priv-005", "Disable Advertiser Tracking",
      "Turns off the ad tracking ID.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\AdvertisingInfo", "DisabledByGroupPolicy", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\AdvertisingInfo", "DisabledByGroupPolicy", 0, "DWORD")],
      why="Removes the advertising ID from tracking.",
      changes="Disables the ad tracking ID via policy.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["advertising", "tracking", "policy"]),
    T("priv-006", "Disable Camera Access",
      "Denies camera access to apps.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam", "Value", "Deny", "STRING")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam", "Value", "Allow", "STRING")],
      why="Stops apps from accessing the webcam.",
      changes="Denies webcam access.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["webcam", "camera", "privacy"]),
    T("priv-008", "Disable Contacts Access",
      "Denies contacts access.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\contacts", "Value", "Deny", "STRING")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\contacts", "Value", "Allow", "STRING")],
      why="Stops app contact-sync polling.",
      changes="Denies contacts access.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["contacts", "privacy", "access"]),
    T("priv-009", "Disable Email Access",
      "Denies email access to apps.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\email", "Value", "Deny", "STRING")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\email", "Value", "Allow", "STRING")],
      why="Stops apps syncing mail in the background.",
      changes="Denies email access.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["email", "mail", "privacy"]),
    T("priv-010", "Disable Notifications",
      "Disables app notification access.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\notifications", "Value", "Deny", "STRING")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\notifications", "Value", "Allow", "STRING")],
      why="Blocks notification polling and popups during play.",
      changes="Denies notification access.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["notifications", "popup", "focus"]),
    T("priv-011", "Disable Call History Access",
      "Denies call history access.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\phoneCallHistory", "Value", "Deny", "STRING")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\phoneCallHistory", "Value", "Allow", "STRING")],
      why="Stops call-history syncing from linked phones.",
      changes="Denies call history access.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["calls", "history", "privacy"]),
    T("priv-012", "Disable App Sync",
      "Turns off app and settings sync.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\SettingSync", "DisableSettingSync", 2, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\SettingSync", "DisableSettingSync", 0, "DWORD")],
      why="Stops settings/app sync backgrounding.",
      changes="Disables setting sync.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["sync", "settings", "cloud"]),
])
