"""Category: RAM — memory management optimizations."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("RAM", win_default="7,8,10,11")
CATEGORY = "RAM"

TWEAKS = validate_module("ram", [
    T("ram-001", "Enable Prefetch",
      "Turns on boot and application prefetching.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters", "EnablePrefetcher", 3, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters", "EnablePrefetcher", 1, "DWORD")],
      why="Prefetch accelerates application startup on traditional storage.",
      changes="Sets EnablePrefetcher to 3.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      when={"hdd": True},
      tags=["prefetch", "startup", "hdd"]),
    T("ram-002", "Enable SysMain Service",
      "Sets the SysMain (Superfetch) service to automatic.",
      actions=[("svc", "SysMain", "auto"), ("svcstart", "SysMain")],
      revert=[("svc", "SysMain", "disabled")],
      why="Superfetch intelligently preloads frequently used app pages into RAM.",
      changes="Enables the SysMain service.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      when={"hdd": True},
      tags=["superfetch", "sysmain", "preload"]),
    T("ram-003", "Disable SysMain on SSD",
      "Disables Superfetch on SSD-only systems.",
      actions=[("svc", "SysMain", "disabled"), ("svcstop", "SysMain")],
      revert=[("svc", "SysMain", "auto")],
      why="On SSDs Superfetch mostly wastes RAM and CPU; storage is fast enough without preloading.",
      changes="Disables the SysMain service.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      when={"ssd": True},
      tags=["superfetch", "sysmain", "ssd"]),
    T("ram-004", "Disable Superfetch Registry (SSD)",
      "Turns off the Superfetch prefetcher at the registry level.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters", "EnableSuperfetch", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters", "EnableSuperfetch", 3, "DWORD")],
      why="Reduces background read-ahead activity on fast SSDs.",
      changes="Sets EnableSuperfetch to 0.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      when={"ssd": True},
      tags=["superfetch", "ssd", "prefetch"]),
    T("ram-005", "Enable Superfetch on HDD",
      "Turns on the Superfetch prefetcher for HDD systems.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters", "EnableSuperfetch", 3, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters", "EnableSuperfetch", 0, "DWORD")],
      why="Superfetch meaningfully speeds repeated application loads on mechanical drives.",
      changes="Sets EnableSuperfetch to 3.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      when={"hdd": True},
      tags=["superfetch", "hdd", "preload"]),

    T("ram-007", "Pagefile Placement Guidance",
      "Explains the ideal pagefile setup.",
      actions=[("guidance", "Keep the pagefile on your fastest drive (ideally NVMe) and let Windows manage its size. Move it OFF any near-full mechanical drive. Do not disable it entirely on systems with less than 16 GB RAM.")],
      revert=[("guidance", "Re-enable automatic pagefile management.")],
      why="A slow or missing pagefile causes hard hitches when memory pressure spikes.",
      changes="Shows pagefile guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["pagefile", "virtualmemory"]),
    T("ram-008", "Disable Hibernation Reserve",
      "Frees the RAM-space reserved for the hibernation file.",
      actions=[("cmd", "powercfg /h off")],
      revert=[("cmd", "powercfg /h on")],
      why="Hibernation reserves disk space equal to RAM and adds background write activity.",
      changes="Disables hibernation and deletes hiberfil.sys.",
      risk="low", impact="low", recommended="recommended", admin=True,
      when={"laptop": False},
      tags=["hibernate", "hiberfil", "disk"]),
    T("ram-009", "32-bit Large Address Space",
      "Raises the user address space for 32-bit games.",
      actions=[("cmd", "bcdedit /set increaseuserva 3072")],
      revert=[("cmd", "bcdedit /deletevalue increaseuserva")],
      why="Lets 32-bit games allocate up to 3 GB, reducing out-of-memory crashes.",
      changes="Sets increaseuserva to 3072 MB.",
      risk="advanced", impact="moderate", recommended="optional", admin=True, confirm=True,
      win="7,8,10", tags=["32bit", "largeaddress", "memory"]),
    T("ram-010", "RAM Disk for Temp Files",
      "Guidance for moving temporary files to a RAM disk.",
      actions=[("guidance", "For 16 GB+ systems, create a small RAM disk (ImDisk/SoftPerfect) and point TEMP/TMP and browser caches at it. Loses contents on reboot by design.")],
      revert=[("guidance", "Restore TEMP environment variables to the default location.")],
      why="Temp-file churn moves from disk to RAM, cutting I/O latency for caches.",
      changes="Shows RAM-disk guidance.",
      risk="moderate", impact="moderate", recommended="optional",
      when={"ram_gb": {">=": 16}},
      tags=["ramdisk", "temp", "cache"]),
    T("ram-011", "Enable XMP/DOCP/EXPO Profile",
      "Guidance to enable memory overclocking profiles in BIOS.",
      actions=[("guidance", "Enter the BIOS and enable the XMP (Intel) / DOCP (AMD) / EXPO (Ryzen 7000+) profile so RAM runs at its rated speed. Verify stability with a memory stress test afterwards.")],
      revert=[("guidance", "Reset memory settings to AUTO in BIOS.")],
      why="Running DDR4/DDR5 below rated speed leaves significant memory bandwidth unused.",
      changes="Shows memory-profile guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["xmp", "docp", "expo", "bios", "ram"]),
    T("ram-012", "Memory Stability Test",
      "Launches the Windows Memory Diagnostic.",
      actions=[("cmd", "mdsched")],
      revert=[("guidance", "Memory Diagnostic runs on next reboot and reports results after.")],
      why="Confirms RAM stability before you trust other optimizations.",
      changes="Opens the Memory Diagnostic tool.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["memtest", "stability", "diagnostic"]),
    T("ram-013", "Dual-Channel Verification",
      "Guides checking that RAM runs in dual-channel mode.",
      actions=[("guidance", "Maximum Tweaks detected your RAM slots. Dual-channel requires matched modules in paired slots (check your motherboard manual). Tools like CPU-Z show 'Channel #: Dual' under the Memory tab.")],
      revert=[("guidance", "No change to revert.")],
      why="Dual-channel mode can add 10-20% memory bandwidth, directly lifting minimum FPS.",
      changes="Shows memory-channel guidance.",
      risk="safe", impact="high", recommended="recommended",
      when={"ram_channels": {"<": 2}},
      tags=["dualchannel", "bandwidth", "slots"]),
    T("ram-014", "Disable Memory Diagnostics at Boot",
      "Prevents the scheduled memory check at boot.",
      actions=[("cmd", "bcdedit /set bootstatuspolicy IgnoreAllFailures")],
      revert=[("cmd", "bcdedit /set bootstatuspolicy DisplayAllFailures")],
      why="Skips the post-crash memory verification screen on startup.",
      changes="Sets boot status policy to ignore all failures.",
      risk="low", impact="low", recommended="recommended", admin=True,
      tags=["boot", "memtest", "startup"]),
    T("ram-015", "Clear Standby Memory List",
      "Guidance for clearing the cached standby RAM.",
      actions=[("guidance", "Use a lightweight tool such as RAMMap to 'Empty Standby List', or reboot. Windows normally manages standby RAM automatically — only clear it when a specific game hitches.")],
      revert=[("guidance", "Let Windows manage standby memory automatically.")],
      why="Frees cached pages quickly if a game demands a large contiguous allocation.",
      changes="Shows standby-list guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["standby", "ram", "cache"]),
    T("ram-016", "Disable Large Page Pool Waste",
      "Keeps the kernel's large page pool allocation modest.",
      actions=[("guidance", "The 'large system cache' (already handled) and page pool settings are best left at defaults unless you run SQL/Exchange servers.")],
      revert=[("guidance", "No change to revert.")],
      why="Prevents unnecessary kernel memory reservations on client machines.",
      changes="Shows memory-pool guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["pool", "kernel", "memory"]),
    T("ram-017", "Second-Level Cache Hint",
      "Provides the memory manager with the CPU's L2 cache size.",
      actions=[("guidance", "SecondLevelDataCache should match your CPU's L2 cache size. Windows auto-detects this on modern CPUs; only set manually if you notice page-table issues.")],
      revert=[("guidance", "Let Windows auto-detect cache size.")],
      why="Modern CPUs report cache size via CPUID; this is a fallback hint for page-table cache sizing.",
      changes="Shows cache-size guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["cache", "l2", "pagetable"]),
    T("ram-021", "Cache Memory-Mapped Images",
      "Lets Windows keep loaded DLL and executable pages in the standby cache.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "MoveImages", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "MoveImages")],
      why="Repeatedly launched executables can reuse cached image pages instead of re-reading from disk.",
      changes="Sets MoveImages to 1 (enabled).",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["images", "cache", "dll"]),
    T("ram-022", "Physical Address Extension (32-bit)",
      "Enables PAE so 32-bit Windows can address more physical RAM.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "PhysicalAddressExtension", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "PhysicalAddressExtension")],
      why="On x86 systems PAE unlocks the full installed RAM for the kernel and applications.",
      changes="Sets PhysicalAddressExtension to 1.",
      risk="moderate", impact="moderate", recommended="optional", admin=True, confirm=True,
      win="7,8,10", tags=["pae", "32bit", "memory"]),
    T("ram-023", "Enable Hibernation for Fast Startup",
      "Turns hibernation back on so Fast Startup can preload the kernel.",
      actions=[("cmd", "powercfg /h on")],
      revert=[("cmd", "powercfg /h off")],
      why="Hibernation plus Fast Startup resumes from the RAM-sized hibernation file faster than a cold boot.",
      changes="Enables hibernation and recreates hiberfil.sys.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["hibernate", "faststartup", "boot"]),
    T("ram-024", "System-Managed Pagefile",
      "Lets Windows automatically size the pagefile on all drives.",
      actions=[("cmd", "wmic computersystem set AutomaticManagedPagefile=True")],
      revert=[("cmd", "wmic computersystem set AutomaticManagedPagefile=False")],
      why="Automatic sizing grows and shrinks the pagefile with real memory pressure, avoiding out-of-memory stalls.",
      changes="Sets AutomaticManagedPagefile to True.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["pagefile", "virtualmemory", "auto"]),

    T("ram-028", "Restore Automatic Pagefile Size",
      "Returns the system-drive pagefile to Windows-managed sizing.",
      actions=[("cmd", "wmic pagefileset where name=\"C:\\pagefile.sys\" set InitialSize=0,MaximumSize=0")],
      revert=[("cmd", "wmic pagefileset where name=\"C:\\pagefile.sys\" set InitialSize=8192,MaximumSize=16384")],
      why="Lets Windows grow the pagefile on demand instead of fighting a fixed cap.",
      changes="Sets C:\\pagefile.sys back to system-managed.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["pagefile", "auto", "restore"]),
    T("ram-029", "Disable Windows Search Indexing",
      "Stops the Windows Search indexer service.",
      actions=[("svc", "WSearch", "disabled")],
      revert=[("svc", "WSearch", "auto")],
      why="The indexer keeps a large in-memory index and wakes on file changes; disabling frees RAM and background I/O.",
      changes="Disables the WSearch service.",
      risk="low", impact="moderate", recommended="optional", admin=True,
      tags=["search", "indexer", "ram"]),
    T("ram-030", "Disable Telemetry Service",
      "Stops the Connected User Experiences and Telemetry service.",
      actions=[("svc", "DiagTrack", "disabled")],
      revert=[("svc", "DiagTrack", "delayed")],
      why="DiagTrack continuously collects and uploads diagnostics, holding resident memory and network use.",
      changes="Disables the DiagTrack service.",
      risk="low", impact="low", recommended="recommended", admin=True,
      tags=["telemetry", "diagtrack", "privacy"]),
    T("ram-031", "Disable Maps Broker",
      "Stops the downloaded-maps manager service.",
      actions=[("svc", "MapsBroker", "disabled")],
      revert=[("svc", "MapsBroker", "manual")],
      why="MapsBroker polls for map updates and keeps map-download state resident.",
      changes="Disables the MapsBroker service.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["maps", "service", "ram"]),
    T("ram-032", "Disable WMP Network Sharing",
      "Stops the Windows Media Player network sharing service.",
      actions=[("svc", "WMPNetworkSvc", "disabled")],
      revert=[("svc", "WMPNetworkSvc", "manual")],
      why="The media-sharing service stays resident and watches the music library even when unused.",
      changes="Disables the WMPNetworkSvc service.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["media", "sharing", "service"]),
    T("ram-033", "Disable Retail Demo Service",
      "Stops the retail demo mode service.",
      actions=[("svc", "RetailDemo", "disabled")],
      revert=[("svc", "RetailDemo", "manual")],
      why="RetailDemo drives store-front kiosk demo content and wastes RAM on personal machines.",
      changes="Disables the RetailDemo service.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["retail", "demo", "service"]),

    T("ram-035", "Disable Device WAP Push",
      "Stops the Device Management WAP Push service.",
      actions=[("svc", "dmwappushservice", "disabled")],
      revert=[("svc", "dmwappushservice", "manual")],
      why="This mobile-device-management channel sits idle on desktops while keeping its service resident.",
      changes="Disables dmwappushservice.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["wap", "mdm", "service"]),
    T("ram-036", "Disable Diagnostics Hub",
      "Stops the Diagnostics Hub Standard Collector service.",
      actions=[("svc", "diagnosticshub.standardcollector.service", "disabled")],
      revert=[("svc", "diagnosticshub.standardcollector.service", "manual")],
      why="The collector buffers diagnostics traces that most users never inspect.",
      changes="Disables the Diagnostics Hub service.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["diagnostics", "service", "traces"]),
    T("ram-037", "Disable Fax Service",
      "Stops the Fax service.",
      actions=[("svc", "Fax", "disabled")],
      revert=[("svc", "Fax", "manual")],
      why="The fax stack keeps drivers and queues resident despite faxing being effectively extinct.",
      changes="Disables the Fax service.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["fax", "service", "ram"]),
    T("ram-038", "Disable Windows Error Reporting",
      "Stops the WerSvc error reporting service.",
      actions=[("svc", "WerSvc", "disabled")],
      revert=[("svc", "WerSvc", "manual")],
      why="WerSvc holds a resident queue and snapshots crash memory; most users never open the report viewer.",
      changes="Disables the WerSvc service.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["error", "reporting", "service"]),

    T("ram-039", "Disable Windows Error Reporting (WER)",
      "Stops Windows Error Reporting from collecting crash dumps.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\Windows Error Reporting", "Disabled", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\Windows Error Reporting", "Disabled")],
      why="WER allocates memory for crash dumps and holds background processes; disabling frees resources on gaming PCs.",
      changes="Sets WER Disabled to 1.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["wer", "error", "reporting"]),

    T("ram-040", "Disable Memory Compression",
      "Turns off Windows 10/11 memory compression.",
      actions=[("svc", "MemCompression", "disabled")],
      revert=[("svc", "MemCompression", "auto")],
      why="Memory compression trades CPU time to fit more in RAM; on high-RAM gaming rigs the CPU cost can hurt frame times.",
      changes="Disables the MemCompression service.",
      risk="moderate", impact="moderate", recommended="experimental", admin=True,
      win="10,11", tags=["compression", "memory", "swap"]),

    T("ram-042", "Shorten Service Shutdown Timeout",
      "Cuts how long Windows waits for services to stop at shutdown.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control", "WaitToKillServiceTimeout", "5000", "STRING")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control", "WaitToKillServiceTimeout", "20000", "STRING")],
      why="A shorter timeout stops lingering services faster, closing processes that otherwise hold RAM until power-off.",
      changes="Sets WaitToKillServiceTimeout to 5000 ms.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["shutdown", "timeout", "services"]),
    T("ram-043", "Disable Boot Memory Diagnostic",
      "Prevents the scheduled Windows Memory Diagnostic run.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\MemoryDiagnostics", "RunTime", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\MemoryDiagnostics", "RunTime", 2, "DWORD")],
      why="Scheduled memory scans delay boot; most users run the diagnostic manually when a fault is suspected.",
      changes="Sets MemoryDiagnostics RunTime to 0 (never).",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["memory", "diagnostic", "boot"]),
    T("ram-044", "Disable Data Sharing Service",
      "Stops the DsmSvc data sharing service.",
      actions=[("svc", "DsmSvc", "disabled")],
      revert=[("svc", "DsmSvc", "manual")],
      why="DsmSvc manages data-sharing contracts and keeps a resident process that desktops rarely need.",
      changes="Disables the DsmSvc service.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["datasharing", "service", "ram"]),
    T("ram-045", "Disable Tablet Input Service",
      "Stops the Tablet Input Service (TabletInputService).",
      actions=[("svc", "TabletInputService", "disabled")],
      revert=[("svc", "TabletInputService", "manual")],
      why="TabletInputService manages pen/touch input and keeps resident drivers loaded even on desktops with no tablet.",
      changes="Disables the TabletInputService service.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["tablet", "touch", "service"]),
    T("ram-046", "Disable Push Notifications",
      "Stops the Windows Push Notifications System service.",
      actions=[("svc", "WpnService", "disabled")],
      revert=[("svc", "WpnService", "auto")],
      why="Push notification listeners hold resident memory and network sockets for app notifications most gamers do not need.",
      changes="Disables the WpnService service.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["push", "notifications", "service"]),

    T("ram-047", "Disable Full Memory Diagnostic Task",
      "Disables the scheduled full memory check task.",
      actions=[("sched", "disable", "/TN \"\\Microsoft\\Windows\\MemoryDiagnostic\\RunFullMemoryDiagnostic\"")],
      revert=[("sched", "enable", "/TN \"\\Microsoft\\Windows\\MemoryDiagnostic\\RunFullMemoryDiagnostic\"")],
      why="The scheduled full-RAM scan can fire during play and hammer memory bandwidth.",
      changes="Disables the RunFullMemoryDiagnostic task.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["memory", "diagnostic", "task"]),
    T("ram-048", "Disable Memory Diagnostic Events",
      "Disables the memory-diagnostic event processing task.",
      actions=[("sched", "disable", "/TN \"\\Microsoft\\Windows\\MemoryDiagnostic\\ProcessMemoryDiagnosticEvents\"")],
      revert=[("sched", "enable", "/TN \"\\Microsoft\\Windows\\MemoryDiagnostic\\ProcessMemoryDiagnosticEvents\"")],
      why="Removes the background listener that reacts to memory-diagnostic events and logs results.",
      changes="Disables the ProcessMemoryDiagnosticEvents task.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["memory", "diagnostic", "events"]),
    T("ram-049", "Disable Compatibility Appraiser",
      "Disables the Microsoft Compatibility Appraiser task.",
      actions=[("sched", "disable", "/TN \"\\Microsoft\\Windows\\Application Experience\\Microsoft Compatibility Appraiser\"")],
      revert=[("sched", "enable", "/TN \"\\Microsoft\\Windows\\Application Experience\\Microsoft Compatibility Appraiser\"")],
      why="The appraiser periodically inventory-scans the system and can consume noticeable CPU and RAM while idle.",
      changes="Disables the Compatibility Appraiser task.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["appraiser", "telemetry", "task"]),
    T("ram-050", "Disable Program Data Updater",
      "Disables the Application Experience ProgramDataUpdater task.",
      actions=[("sched", "disable", "/TN \"\\Microsoft\\Windows\\Application Experience\\ProgramDataUpdater\"")],
      revert=[("sched", "enable", "/TN \"\\Microsoft\\Windows\\Application Experience\\ProgramDataUpdater\"")],
      why="Removes a background telemetry and update poll that spins up memory while idle.",
      changes="Disables the ProgramDataUpdater task.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["telemetry", "updater", "task"]),
    T("ram-051", "Disable CEIP Consolidator",
      "Disables the Customer Experience Improvement Program task.",
      actions=[("sched", "disable", "/TN \"\\Microsoft\\Windows\\Customer Experience Improvement Program\\Consolidator\"")],
      revert=[("sched", "enable", "/TN \"\\Microsoft\\Windows\\Customer Experience Improvement Program\\Consolidator\"")],
      why="The consolidator aggregates and uploads usage telemetry, holding memory while it processes logs.",
      changes="Disables the CEIP Consolidator task.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["ceip", "telemetry", "task"]),
    T("ram-052", "Disable WER Queue Reporting",
      "Disables the error-reporting queue task.",
      actions=[("sched", "disable", "/TN \"\\Microsoft\\Windows\\Windows Error Reporting\\QueueReporting\"")],
      revert=[("sched", "enable", "/TN \"\\Microsoft\\Windows\\Windows Error Reporting\\QueueReporting\"")],
      why="Prevents queued crash reports from being processed and uploaded in the background.",
      changes="Disables the QueueReporting task.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["error", "reporting", "task"]),
    T("ram-053", "Remove Solitaire and Casual Games",
      "Uninstalls the built-in Solitaire Collection and casual games.",
      actions=[("appx", "remove", "Microsoft.MicrosoftSolitaireCollection")],
      revert=[("appx", "register", "Microsoft.MicrosoftSolitaireCollection")],
      why="Pre-installed casual games stay partially resident after first launch and consume disk space and background update bandwidth.",
      changes="Removes the Solitaire Collection appx package.",
      risk="safe", impact="very low", recommended="optional",
      tags=["solitaire", "games", "bloat"]),

    T("ram-054", "Remove Xbox Gaming Overlay",
      "Uninstalls the Xbox Game Bar overlay app.",
      actions=[("appx", "remove", "Microsoft.XboxGamingOverlay")],
      revert=[("appx", "register", "Microsoft.XboxGamingOverlay")],
      why="The overlay hooks every game for capture and broadcasting, holding resident memory even when unused.",
      changes="Removes the Xbox Gaming Overlay appx package.",
      risk="safe", impact="low", recommended="optional",
      tags=["xbox", "overlay", "capture"]),
    T("ram-055", "Disable Print Spooler",
      "Stops the Print Spooler service.",
      actions=[("svc", "Spooler", "disabled")],
      revert=[("svc", "Spooler", "auto")],
      why="The spooler keeps driver queues and worker threads resident; users with no printer reclaim that memory.",
      changes="Disables the Spooler service.",
      risk="moderate", impact="low", recommended="optional", admin=True,
      tags=["printer", "spooler", "service"]),
    T("ram-056", "Remove Pagefile From Second Drive",
      "Deletes a pagefile that was placed on D:.",
      actions=[("cmd", "wmic pagefileset where name=\"D:\\pagefile.sys\" delete")],
      revert=[("cmd", "wmic pagefileset create name=\"D:\\pagefile.sys\"")],
      why="Removes an unwanted pagefile so paging I/O returns to the primary drive.",
      changes="Deletes D:\\pagefile.sys.",
      risk="moderate", impact="moderate", recommended="optional", admin=True,
      tags=["pagefile", "drive", "remove"]),

    T("ram-057", "Enable Large System Cache",
      "Sets the LargeSystemCache registry value to optimize file system caching.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "LargeSystemCache", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "LargeSystemCache")],
      why="On systems with ample RAM, a larger system cache keeps frequently accessed files in memory, reducing disk reads.",
      changes="Sets LargeSystemCache to 1.",
      risk="low", impact="moderate", recommended="optional", admin=True,
      tags=["cache", "system", "memory"]),
    T("ram-059", "Disable Paging Executive",
      "Keeps the kernel and drivers in physical RAM instead of paging them to disk.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "DisablePagingExecutive", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "DisablePagingExecutive", 0, "DWORD")],
      why="Preventing kernel paging keeps critical code in fast RAM, reducing pagefault latency during gameplay.",
      changes="Sets DisablePagingExecutive to 1.",
      risk="low", impact="moderate", recommended="recommended", admin=True,
      tags=["paging", "kernel", "ram"]),

    T("ram-058", "Increase Io Page Lock Limit",
      "Lets Windows auto-manage the I/O page lock limit.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "IoPageLockLimit", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "IoPageLockLimit")],
      why="Setting IoPageLockLimit to 0 lets Windows dynamically manage the limit based on available memory.",
      changes="Sets IoPageLockLimit to 0 (auto-manage).",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["io", "lock", "pages"]),

    T("ram-060", "Set System Pages",
      "Lets Windows manage the number of system page table entries.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "SystemPages", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "SystemPages")],
      why="A value of 0 allows Windows to dynamically size system page table entries based on installed RAM.",
      changes="Sets SystemPages to 0 (auto-manage).",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["pages", "system", "memory"]),
    T("ram-061", "Optimize Paged Pool Size",
      "Lets Windows auto-manage the paged pool size.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "PagedPoolSize", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "PagedPoolSize")],
      why="A value of 0 lets Windows grow the paged pool dynamically to match kernel memory demands.",
      changes="Sets PagedPoolSize to 0 (auto-manage).",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["pool", "paged", "memory"]),
    T("ram-062", "Enable Memory Compression",
      "Enables Windows memory compression to fit more data in RAM.",
      actions=[("cmd", "powershell -NoProfile -ExecutionPolicy Bypass -Command \"Enable-MMAgent -MemoryCompression\"")],
      revert=[("cmd", "powershell -NoProfile -ExecutionPolicy Bypass -Command \"Disable-MMAgent -MemoryCompression\"")],
      why="Memory compression reduces pagefile writes by compressing inactive pages in RAM instead of swapping to disk.",
      changes="Enables memory compression via MMAgent.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["compression", "memory", "swap"]),
    T("ram-063", "Set Process Count Limit",
      "Optimizes the shared section size for desktop heap.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "SharedSection", "1024,1280,512", "STRING")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "SharedSection", "1024,768,512", "STRING")],
      why="Increasing the desktop heap from 768 KB to 1280 KB prevents out-of-memory errors for applications that create many UI threads.",
      changes="Sets SharedSection to 1024,1280,512.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["desktop", "heap", "shared"]),
])
