"""Category: Registry — direct registry value optimizations."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Registry", win_default="7,8,10,11")
CATEGORY = "Registry"

TWEAKS = validate_module("registry", [
    T("reg-001", "Foreground Lock Timeout 0",
      "Removes the delay before a clicked window receives focus.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "ForegroundLockTimeout", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "ForegroundLockTimeout", 200000, "DWORD")],
      why="Windows delays focus changes to prevent focus stealing; in games you want instant focus on click.",
      changes="Sets ForegroundLockTimeout to 0.",
      risk="safe", impact="low", recommended="recommended",
      tags=["focus", "foreground", "alt-tab"]),
    T("reg-002", "Active Window Tracking Timeout 0",
      "Removes the hover delay for focus-follows-mouse tracking.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "ActiveWndTrkTimeout", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "ActiveWndTrkTimeout", 10000, "DWORD")],
      why="Faster window tracking makes mouse-over focus feel instant.",
      changes="Sets ActiveWndTrkTimeout to 0.",
      risk="safe", impact="low", recommended="optional",
      tags=["focus", "mouse", "tracking"]),
    T("reg-003", "Suppress Low Disk Space Warnings",
      "Stops the low-disk-space balloon warnings.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "NoLowDiskSpaceChecks", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "NoLowDiskSpaceChecks", 0, "DWORD")],
      why="Eliminates intrusive popups that can appear during large game installs.",
      changes="Disables low disk space warnings.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["disk", "warning", "popup"]),
    T("reg-004", "Disable Recent Documents History",
      "Stops tracking of recently opened documents.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Policies\Explorer", "NoRecentDocsHistory", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Policies\Explorer", "NoRecentDocsHistory", 0, "DWORD")],
      why="Removes the background work of journaling recent items.",
      changes="Disables recent documents tracking.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["privacy", "recent", "history"]),
    T("reg-005", "Disable Screen Saver",
      "Turns the screen saver off.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "ScreenSaveActive", 0, "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "ScreenSaveActive", 1, "STRING")],
      why="A screen saver can kick in during long AFK moments and disturb sessions.",
      changes="Disables the active screen saver.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["screensaver", "display", "idle"]),
    T("reg-006", "Disable Taskbar Animations",
      "Turns off taskbar animation effects.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "TaskbarAnimations", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "TaskbarAnimations", 1, "DWORD")],
      why="Skips animation redraws on the always-visible taskbar.",
      changes="Disables taskbar animations.",
      risk="safe", impact="low", recommended="recommended",
      tags=["taskbar", "animation", "dwm"]),
    T("reg-007", "Disable ListView Shadows",
      "Turns off drop shadows behind list views.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "ListviewShadow", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "ListviewShadow", 1, "DWORD")],
      why="Removes shadow compositing work in Explorer lists.",
      changes="Disables listview drop shadows.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["shadow", "explorer", "dwm"]),
    T("reg-008", "Never Combine Taskbar Buttons",
      "Shows every window as a separate taskbar button.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "TaskbarGlomLevel", 2, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "TaskbarGlomLevel", 1, "DWORD")],
      why="Separate buttons avoid alt-tab mistakes during frantic game switching.",
      changes="Sets taskbar buttons to never combine.",
      risk="safe", impact="very low", recommended="optional",
      tags=["taskbar", "windows", "alt-tab"]),
    T("reg-009", "Explorer Separate Processes",
      "Runs each Explorer folder in its own process.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "SeparateProcess", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "SeparateProcess", 0, "DWORD")],
      why="A crash in one folder window no longer takes down the whole shell.",
      changes="Enables separate Explorer processes.",
      risk="safe", impact="low", recommended="recommended",
      tags=["explorer", "stability", "process"]),
    T("reg-010", "Hide Sync Provider Notifications",
      "Removes cloud sync badges and banners in Explorer.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "ShowSyncProviderNotifications", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "ShowSyncProviderNotifications", 1, "DWORD")],
      why="Removes OneDrive-style status icons that wake the shell to poll sync state.",
      changes="Hides sync provider notifications.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["onedrive", "sync", "badge"]),
    T("reg-011", "Disable Desktop Peek Preview",
      "Turns off the Aero Peek hover preview.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "DisablePreviewDesktop", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "DisablePreviewDesktop", 0, "DWORD")],
      why="Prevents accidental peek previews and their compositor work.",
      changes="Disables peek preview.",
      risk="safe", impact="low", recommended="recommended",
      tags=["peek", "preview", "dwm"]),
    T("reg-012", "Disable Icons Only Thumbnails",
      "Shows only file icons instead of embedded thumbnail previews in lists.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "IconsOnly", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "IconsOnly", 0, "DWORD")],
      why="Less thumbnail decoding work when browsing folders with many media files.",
      changes="Enables IconsOnly mode.",
      risk="safe", impact="low", recommended="optional",
      tags=["thumbnails", "icons", "explorer"]),
    T("reg-013", "Hide Frequent Folders in Quick Access",
      "Removes the frequent folders section from Quick Access.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "ShowFrequent", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "ShowFrequent", 1, "DWORD")],
      why="Fewer journaled items to maintain in the shell.",
      changes="Hides frequent folders from Quick Access.",
      risk="safe", impact="very low", recommended="optional",
      tags=["quickaccess", "frequent", "explorer"]),
    T("reg-014", "Disable AutoPlay Handlers",
      "Disables AutoPlay for removable media.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers", "DisableAutoplay", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers", "DisableAutoplay", 0, "DWORD")],
      why="Stops background processes from auto-launching on media insertion.",
      changes="Disables AutoPlay.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["autoplay", "media", "usb"]),
    T("reg-015", "Disable Widgets Button",
      "Removes the Widgets button from the taskbar.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "TaskbarDa", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "TaskbarDa", 1, "DWORD")],
      why="Widgets run a live web feed pipeline in the background.",
      changes="Disables the taskbar widgets button.",
      risk="safe", impact="low", recommended="recommended", win="11",
      tags=["widgets", "taskbar", "news"]),
    T("reg-016", "Disable Copilot Button",
      "Removes the Copilot icon from the taskbar.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "ShowCopilotButton", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "ShowCopilotButton", 1, "DWORD")],
      why="Removes an unneeded taskbar process surface while gaming.",
      changes="Hides the Copilot taskbar button.",
      risk="safe", impact="very low", recommended="recommended", win="11",
      tags=["copilot", "taskbar", "ai"]),
])
