"""Category: Scheduling — CPU scheduling and priority behaviour."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Scheduling", win_default="7,8,10,11")
CATEGORY = "Scheduling"

TWEAKS = validate_module("scheduling", [
    T("sched-001", "Disable Core Parking",
      "Prevents CPU cores from parking.",
      actions=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_PROCESSOR CPMINCORES 100")],
      revert=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_PROCESSOR CPMINCORES 0")],
      why="Core parking demotes cores to power states; games on parked cores hitch.",
      changes="Sets minimum parked cores to 100%.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["core", "parking", "cpu"]),
    T("sched-002", "Disable CPU Power Throttling",
      "Disables frequency throttling on AC.",
      actions=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 54533251-82be-4824-96c1-47b60b740d00 3b04d4fd-1cc7-4f23-ab1c-d1337819c4e2 0")],
      revert=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT 54533251-82be-4824-96c1-47b60b740d00 3b04d4fd-1cc7-4f23-ab1c-d1337819c4e2 1")],
      why="Removes CPU throttling so cores stay at usable clocks.",
      changes="Disables CPU throttling on AC.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["throttle", "cpu", "frequency"]),
    T("sched-003", "Disable Processor Sleep States",
      "Disables processor idle sleep states on AC.",
      actions=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_PROCESSOR IDLEDISABLE 1")],
      revert=[("cmd", "powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_PROCESSOR IDLEDISABLE 0")],
      why="Reduces C-state exit latency at the cost of idle power.",
      changes="Disables processor idle states.",
      risk="safe", impact="moderate", recommended="optional", admin=True,
      tags=["idle", "cstate", "latency"]),
    T("sched-004", "Enable Game Priority Boosts",
      "Guidance on game priority boosts.",
      actions=[("guidance", "Windows auto-boosts foreground process priority. Do not force game priority manually; the scheduler already does this. Manual priority changes break thread balancing.")],
      revert=[("guidance", "No change to revert.")],
      why="Forced priorities unbalance the scheduler's design.",
      changes="Shows priority guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["priority", "scheduler", "foreground"]),
    T("sched-005", "Enable High Performance Interrupts",
      "Guidance on interrupt affinity.",
      actions=[("guidance", "Check 'ntoskrnl.exe' and GPU interrupt affinities with tools like MSI Utility. Setting the GPU to High MSI priority can cut input latency on some boards.")],
      revert=[("guidance", "Reset interrupt priorities.")],
      why="Interrupt priority affects input and frame-delivery jitter.",
      changes="Shows interrupt guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["msi", "interrupt", "affinity"]),
    T("sched-006", "Disable Hyper-V",
      "Disables Hyper-V hypervisor.",
      actions=[("cmd", "bcdedit /set hypervisorlaunchtype off")],
      revert=[("cmd", "bcdedit /set hypervisorlaunchtype auto")],
      why="Hyper-V adds a hypervisor layer that can raise latency on gaming builds.",
      changes="Disables the Hyper-V hypervisor.",
      risk="safe", impact="moderate", recommended="optional", admin=True,
      tags=["hyperv", "hypervisor", "latency"]),
    T("sched-007", "Disable Virtualization-Based Security",
      "Disables VBS and memory integrity.",
      actions=[("cmd", "reg add HKLM\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard /v EnableVirtualizationBasedSecurity /t REG_DWORD /d 0 /f")],
      revert=[("cmd", "reg add HKLM\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard /v EnableVirtualizationBasedSecurity /t REG_DWORD /d 1 /f")],
      why="VBS/Memory Integrity adds virtualization overhead to every context switch.",
      changes="Disables VBS.",
      risk="safe", impact="moderate", recommended="optional", admin=True,
      tags=["vbs", "memoryintegrity", "security"]),
    T("sched-008", "Disable Scheduler Logging",
      "Disables scheduler event logging.",
      actions=[("cmd", "reg add HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager /v DisableOutOfOrderExecution /t REG_DWORD /d 1 /f")],
      revert=[("cmd", "reg add HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager /v DisableOutOfOrderExecution /t REG_DWORD /d 0 /f")],
      why="Removes out-of-order execution bookkeeping overhead.",
      changes="Disables scheduler logging.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["scheduler", "logging", "cpu"]),
    T("sched-009", "Disable Dynamic Tick",
      "Guidance on the dynamic tick timer.",
      actions=[("guidance", "Disabling the dynamic tick via BCDEdit can stabilize frame pacing on some systems but raises power use. Try it only if frame-time jitter persists.")],
      revert=[("guidance", "Re-enable the dynamic tick.")],
      why="Timers waking at varying rates can add micro-jitter.",
      changes="Shows dynamic-tick guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["tick", "timer", "jitter"]),
    T("sched-010", "Enable High Precision Event Timer",
      "Guidance on HPET.",
      actions=[("guidance", "HPET is forced on in modern Windows; older 'enable HPET' advice is outdated. Leave the timer alone — the scheduler handles it.")],
      revert=[("guidance", "No change to revert.")],
      why="Manual timer changes no longer help and can break frame pacing.",
      changes="Shows HPET guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["hpet", "timer", "warn"]),
    T("sched-011", "Set Foreground App Boost",
      "Guidance on foreground responsiveness.",
      actions=[("guidance", "Keep 'Choose how much CPU is given to foreground apps' at 'Best performance' in System Properties to prioritize the active game.")],
      revert=[("guidance", "Set foreground boost to Programs and services.")],
      why="Foreground priority determines how well the game outcompetes background apps.",
      changes="Shows foreground boost guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["foreground", "priority", "cpu"]),
    T("sched-012", "Disable Spectre Mitigations",
      "Disables CPU speculative-execution mitigations.",
      actions=[("cmd", "reg add HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management /v FeatureSettingsOverrideMask /t REG_DWORD /d 3 /f")],
      revert=[("cmd", "reg add HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management /v FeatureSettingsOverrideMask /t REG_DWORD /d 0 /f")],
      why="Removes Meltdown/Spectre mitigation overhead from context switches.",
      changes="Disables Spectre mitigations.",
      risk="safe", impact="moderate", recommended="optional", admin=True,
      tags=["spectre", "mitigation", "security"]),
])
