"""Category: Security & Performance — security settings that affect performance."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Security & Performance", win_default="10,11")
CATEGORY = "Security & Performance"

TWEAKS = validate_module("security_perf", [
    T("sec-001", "Add Game Folder to Defender Exclusions",
      "Excludes game folders from real-time scanning.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows Defender\Exclusions\Paths", r"C:\Games", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows Defender\Exclusions\Paths", r"C:\Games")],
      why="Real-time scanning of huge game folders steals disk and CPU time.",
      changes="Adds C:\\Games to Defender exclusions.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["defender", "exclusion", "antivirus"]),
    T("sec-002", "Exclude Game Processes",
      "Excludes game executables from scanning.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows Defender\Exclusions\Processes", "game.exe", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows Defender\Exclusions\Processes", "game.exe")],
      why="Process exclusions skip per-access scanning of the game's hot files.",
      changes="Adds game.exe to Defender process exclusions.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["defender", "process", "scan"]),
    T("sec-003", "Disable Real-Time Protection While Gaming",
      "Guidance on pausing Defender during play.",
      actions=[("guidance", "Temporarily disable real-time protection in Windows Security while gaming on a trusted machine — then re-enable it after the session. Exclusions are safer long-term.")],
      revert=[("guidance", "Re-enable real-time protection.")],
      why="Full real-time scanning adds per-file-access overhead.",
      changes="Shows Defender guidance.",
      risk="safe", impact="moderate", recommended="optional",
      tags=["defender", "protection", "gaming"]),
    T("sec-004", "Keep Windows Defender Enabled",
      "Guidance on keeping basic protection.",
      actions=[("guidance", "Keep Defender (or another AV) running. Disabling all AV for FPS gains is not worth the risk; exclusions recover most of the cost safely.")],
      revert=[("guidance", "No change to revert.")],
      why="Malware scans and hitching cost far more performance than AV overhead.",
      changes="Shows AV guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["antivirus", "defender", "security"]),
    T("sec-005", "Disable Windows Defender Tamper Delay",
      "Guidance about Defender controlled folder access.",
      actions=[("guidance", "If games write to protected folders (mods, saves in Documents), add them to Controlled Folder Access exceptions instead of disabling it.")],
      revert=[("guidance", "Remove the exceptions.")],
      why="Controlled Folder Access blocks legit game writes and causes save errors.",
      changes="Shows CFA guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["controlledfolder", "mods", "saves"]),
    T("sec-006", "Enable User Account Control",
      "Guidance on UAC level.",
      actions=[("guidance", "Keep UAC at its default. Lowering it to 'Never notify' does not improve game performance and reduces protection.")],
      revert=[("guidance", "Restore the default UAC level.")],
      why="UAC has no measurable frame-time cost at runtime.",
      changes="Shows UAC guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["uac", "security", "warn"]),
    T("sec-007", "Run as Administrator for Tweak Tools",
      "Guidance on admin elevation.",
      actions=[("guidance", "MaximumTweaks (and driver tools) need admin rights for service, powercfg and HKLM changes. Run the terminal as Administrator once, then close it.")],
      revert=[("guidance", "No change to revert.")],
      why="Non-elevated sessions silently skip privileged tweaks.",
      changes="Shows elevation guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["admin", "elevation", "tweaks"]),
    T("sec-008", "Disable Remote Desktop",
      "Disables RDP if unused.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Terminal Server", "fDenyTSConnections", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Terminal Server", "fDenyTSConnections", 0, "DWORD")],
      why="RDP listens on a network port and adds a small service cost.",
      changes="Disables Remote Desktop.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["rdp", "remote", "network"]),
    T("sec-009", "Disable SMB1 Protocol",
      "Disables the legacy SMB1 feature.",
      actions=[("cmd", "dism /online /disable-feature /featurename:SMB1Protocol /norestart")],
      revert=[("cmd", "dism /online /enable-feature /featurename:SMB1Protocol /all /norestart")],
      why="Removes a legacy network stack and its audit overhead.",
      changes="Disables SMB1.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["smb", "network", "legacy"]),
    T("sec-010", "Disable PowerShell Script Logging",
      "Guidance on PowerShell audit logging.",
      actions=[("guidance", "PowerShell script-block logging is off by default. Leave it off unless you need audit forensics — it adds overhead to every PS session.")],
      revert=[("guidance", "Enable script-block logging.")],
      why="Script logging adds per-command overhead in admin tooling.",
      changes="Shows PowerShell-logging guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["powershell", "logging", "audit"]),
    T("sec-011", "Disable Network Discovery",
      "Disables network discovery.",
      actions=[("cmd", "powershell -NoProfile -Command Set-NetFirewallRule -DisplayGroup 'Network Discovery' -Enabled False")],
      revert=[("cmd", "powershell -NoProfile -Command Set-NetFirewallRule -DisplayGroup 'Network Discovery' -Enabled True")],
      why="Network discovery broadcasts and answers mDNS constantly.",
      changes="Disables Network Discovery firewall rules.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["network", "discovery", "broadcast"]),
    T("sec-012", "Disable Diagnostic Data",
      "Guidance on diagnostic data levels.",
      actions=[("guidance", "Set diagnostic data to 'Required only' in Settings > Privacy > Diagnostics. Higher levels upload more telemetry and enable diagnostic partners.")],
      revert=[("guidance", "Restore full diagnostics.")],
      why="Less telemetry means fewer background uploads and watchers.",
      changes="Shows diagnostic-data guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["diagnostics", "telemetry", "privacy"]),
])
