"""Category: Services — Windows service tuning."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Services", win_default="7,8,10,11")
CATEGORY = "Services"

TWEAKS = validate_module("services", [
    T("svc-001", "Disable SysMain",
      "Disables the SysMain (Superfetch) service.",
      actions=[("sc", "disable", "SysMain")],
      revert=[("sc", "enable", "SysMain")],
      why="Preloads and prefetching cause constant disk activity and lock contention on HDD/older systems.",
      changes="Disables SysMain.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["sysmain", "prefetch", "disk"]),
    T("svc-002", "Disable Windows Search",
      "Disables the Windows Search indexer.",
      actions=[("sc", "disable", "WSearch")],
      revert=[("sc", "enable", "WSearch")],
      why="The indexer scans file systems in the background; games on mechanical drives suffer seek contention.",
      changes="Disables Windows Search.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["search", "indexer", "disk"]),

    T("svc-005", "Disable Remote Registry",
      "Disables remote registry access.",
      actions=[("sc", "disable", "RemoteRegistry")],
      revert=[("sc", "enable", "RemoteRegistry")],
      why="Removes a rarely-needed network attack surface and its polling.",
      changes="Disables Remote Registry.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["registry", "remote", "security"]),
    T("svc-006", "Disable Print Spooler",
      "Disables the print spooler if you have no printers.",
      actions=[("sc", "disable", "Spooler")],
      revert=[("sc", "enable", "Spooler")],
      why="The spooler listens for print jobs and was a frequent exploit target.",
      changes="Disables Print Spooler.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["printer", "spooler", "security"]),
    T("svc-007", "Disable Xbox Services",
      "Disables the Xbox Live services.",
      actions=[
          ("sc", "disable", "XblAuthManager"),
          ("sc", "disable", "XblGameSave"),
      ],
      revert=[
          ("sc", "enable", "XblAuthManager"),
          ("sc", "enable", "XblGameSave"),
      ],
      why="Xbox auth/game-save services idle-poll when not using Xbox features.",
      changes="Disables Xbox Live services.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["xbox", "live", "gaming"]),

    T("svc-010", "Disable Bluetooth Support",
      "Disables the Bluetooth service if unused.",
      actions=[("sc", "disable", "bthserv")],
      revert=[("sc", "enable", "bthserv")],
      why="Bluetooth discovery polls radios in the background.",
      changes="Disables the Bluetooth service.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["bluetooth", "radio", "battery"]),
    T("svc-011", "Disable Fax Service",
      "Disables the Fax service.",
      actions=[("sc", "disable", "Fax")],
      revert=[("sc", "enable", "Fax")],
      why="The fax service is unneeded on modern systems.",
      changes="Disables Fax service.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["fax", "obsolete", "service"]),
    T("svc-012", "Disable Touch Keyboard Service",
      "Disables the touch keyboard if not needed.",
      actions=[("sc", "disable", "TabletInputService")],
      revert=[("sc", "enable", "TabletInputService")],
      why="The touch keyboard service listens for input events on desktop systems.",
      changes="Disables the touch keyboard service.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["touch", "keyboard", "input"]),
    T("svc-013", "Disable Phone Service",
      "Disables the Phone Link service.",
      actions=[("sc", "disable", "PhoneSvc")],
      revert=[("sc", "enable", "PhoneSvc")],
      why="Phone Link syncs messages/photos in the background.",
      changes="Disables Phone Link.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["phone", "link", "sync"]),
    T("svc-014", "Disable Desktop Window Manager Session",
      "Guidance about DWM service.",
      actions=[("guidance", "Do not disable the Desktop Window Manager (Dwm) service — Windows 8+ requires DWM for the desktop and games. The window animations tweak is enough.")],
      revert=[("guidance", "No change to revert.")],
      why="DWM is mandatory since Windows 8; disabling it breaks the session.",
      changes="Shows DWM guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["dwm", "desktop", "warn"]),

    T("svc-016", "Disable Infrared Service",
      "Disables the infrared device service.",
      actions=[("sc", "disable", "irmon")],
      revert=[("sc", "enable", "irmon")],
      why="Legacy infrared monitoring is unused on modern hardware.",
      changes="Disables the Infrared service.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["infrared", "legacy", "service"]),

    T("svc-019", "Disable Windows Insider Service",
      "Disables the Windows Insider Preview service.",
      actions=[("svc", "wisvc", "disabled")],
      revert=[("svc", "wisvc", "manual")],
      why="The wisvc service polls for Insider builds and consumes background bandwidth and CPU.",
      changes="Sets wisvc to disabled.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["insider", "preview", "update"]),
])
