"""Category: Startup — launch-time and boot behaviour."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Startup", win_default="7,8,10,11")
CATEGORY = "Startup"

TWEAKS = validate_module("startup", [
    T("start-001", "Check Startup Impact",
      "Lists startup apps with their launch impact.",
      actions=[("cmd", "start ms-settings:startupapps")],
      revert=[("guidance", "No change to revert.")],
      why="Startup apps stretch boot time and fight the game for resources.",
      changes="Opens the Startup Apps settings page.",
      risk="safe", impact="low", recommended="recommended",
      tags=["startup", "impact", "apps"]),
    T("start-002", "Disable Unused Startup Apps",
      "Guidance on disabling startup bloat.",
      actions=[("guidance", "In Task Manager > Startup apps, disable anything not needed at login (chat clients, launchers, updaters, RGB software). Keep antivirus and driver tools.")],
      revert=[("guidance", "Re-enable the startup apps.")],
      why="Every startup app delays boot and holds background threads.",
      changes="Shows startup guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["startup", "disable", "bloat"]),
    T("start-003", "Disable Fast Startup",
      "Turns off hybrid shutdown (fast startup).",
      actions=[
          ("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Power", "HiberbootEnabled", 0, "DWORD"),
      ],
      revert=[
          ("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Power", "HiberbootEnabled", 1, "DWORD"),
      ],
      why="Hybrid shutdown can leave drivers in a stale half-initialized state; a clean boot is more reliable after hardware changes.",
      changes="Disables Fast Startup.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["faststartup", "shutdown", "boot"]),
    T("start-005", "Enable Multi-Core Boot",
      "Uses all CPU cores while booting Windows.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters", "EnableBootAndPrefetch", 3, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters", "EnableBootAndPrefetch", 2, "DWORD")],
      why="Boot prefetch and superfetch modes speed cold-boot times on HDDs.",
      changes="Enables boot prefetching on all cores.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["boot", "cores", "prefetch"]),
    T("start-006", "Disable Boot Optimization Delay",
      "Guidance on boot-time feature delays.",
      actions=[("guidance", "Windows delays some drivers at boot (Boot-Start Driver Optimization). Only adjust if you understand your drivers; most systems are fine at default.")],
      revert=[("guidance", "No change to revert.")],
      why="Aggressive boot flags can break driver startup on some hardware.",
      changes="Shows boot-delay guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["boot", "driver", "delay"]),
    T("start-007", "Disable Startup Repair Poll",
      "Guidance about the automatic repair loop.",
      actions=[("guidance", "If Windows is stuck in 'Preparing Automatic Repair', interrupt the loop with a forced shutdown (3x power button), then use a bootable USB to repair.")],
      revert=[("guidance", "No change to revert.")],
      why="The repair loop usually means a driver or update broke boot.",
      changes="Shows repair-loop guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["repair", "boot", "loop"]),
    T("start-008", "Set BIOS Boot Order",
      "Guidance for boot order and UEFI.",
      actions=[("guidance", "In the BIOS set the Windows boot drive first, enable UEFI (not Legacy/CSM), and disable the floppy/network boot entries to shorten POST and startup.")],
      revert=[("guidance", "Restore the previous boot order.")],
      why="Network and removable boot checks add seconds to startup.",
      changes="Shows BIOS boot guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["bios", "uefi", "boot"]),
    T("start-009", "Disable Third-Party Services",
      "Guidance to clean third-party boot services.",
      actions=[("guidance", "Use 'msconfig' or Autoruns to inspect non-Microsoft boot services. Disable only ones you recognize (e.g. updaters). Unknown services can break software.")],
      revert=[("guidance", "Re-enable the services.")],
      why="Third-party boot services are the top startup-time hog.",
      changes="Shows service-cleanup guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["services", "msconfig", "autoruns"]),
    T("start-010", "Reboot After Major Tweaks",
      "Guidance on rebooting after system changes.",
      actions=[("guidance", "Reboot after driver, service, or policy changes before benchmarking. Some kernel-level tweaks only apply on a clean boot.")],
      revert=[("guidance", "No change to revert.")],
      why="A clean boot ensures tweaks actually take effect.",
      changes="Shows reboot guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["reboot", "restart", "apply"]),
    T("start-011", "Clean Temporary Boot Files",
      "Guidance on cleaning temp folders.",
      actions=[("guidance", "Run 'Disk Cleanup' (cleanmgr) and delete C:\\Windows\\Temp and %TEMP% contents once a month. Stale temp files slow startup scans and Defender checks.")],
      revert=[("guidance", "No change to revert.")],
      why="Antivirus scans of bloated temp folders extend sign-in time.",
      changes="Shows temp-file guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["temp", "cleanup", "disk"]),
    T("start-012", "Disable Automatic Sign-in Animations",
      "Guidance on the first sign-in animation.",
      actions=[("guidance", "On Windows 11, the sign-in animation can delay desktop readiness by a second. Settings > Accounts > Sign-in options > 'Show sign-in options' (or the registry tweak) can be used to skip it.")],
      revert=[("guidance", "Re-enable the animation.")],
      why="The sign-in animation delays usable desktop time.",
      changes="Shows sign-in animation guidance.",
      risk="safe", impact="very low", recommended="optional",
      tags=["signin", "animation", "boot"]),
    T("start-013", "Preload Game on Dedicated GPU",
      "Guidance for cold-start game loads.",
      actions=[("guidance", "For games that must warm shader caches, launch them once after driver updates and let the intro/benchmark run before playing to pre-warm caches.")],
      revert=[("guidance", "No change to revert.")],
      why="Pre-warming caches removes first-match stutter.",
      changes="Shows cache-warm guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["cache", "warmup", "stutter"]),
    T("start-014", "Disable Automatic Startup of Update Tools",
      "Guidance for update-tool startup entries.",
      actions=[("guidance", "Disable the startup entries for game update tools (Epic, Steam, Battle.net, Riot) if you launch games from shortcuts — they keep checking for updates at boot.")],
      revert=[("guidance", "Re-enable the update tools.")],
      why="Launcher updaters at boot delay the desktop and hold locks.",
      changes="Shows updater guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["updater", "startup", "launcher"]),
])
