"""Category: Storage — drive and filesystem optimizations."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Storage", win_default="7,8,10,11")
CATEGORY = "Storage"

TWEAKS = validate_module("storage", [
    T("stor-001", "Enable SSD TRIM",
      "Turns on the TRIM command for SSD/NVMe drives.",
      actions=[("cmd", "fsutil behavior set DisableDeleteNotify 0")],
      revert=[("cmd", "fsutil behavior set DisableDeleteNotify 1")],
      why="TRIM lets SSDs reclaim deleted blocks, keeping write speed high over time.",
      changes="Enables DeleteNotify (TRIM).",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      when={"ssd": True},
      tags=["trim", "ssd", "maintenance"]),
    T("stor-002", "Disable 8.3 Short Names",
      "Stops NTFS from generating legacy 8.3 filenames.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\FileSystem", "NtfsDisable8dot3NameCreation", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\FileSystem", "NtfsDisable8dot3NameCreation", 0, "DWORD")],
      why="Reduces directory-lookup overhead on volumes with many files (common in games).",
      changes="Disables 8.3 name generation.",
      risk="low", impact="moderate", recommended="recommended", admin=True,
      tags=["ntfs", "8.3", "filenames"]),
    T("stor-003", "Disable Last Access Timestamps",
      "Turns off NTFS last-access time updates.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\FileSystem", "NtfsDisableLastAccessUpdate", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\FileSystem", "NtfsDisableLastAccessUpdate", 0, "DWORD")],
      why="Eliminates a metadata write on every file access, reducing I/O.",
      changes="Disables last-access timestamp updates.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["ntfs", "timestamps", "io"]),
    T("stor-004", "MFT Zone Reservation",
      "Reserves extra space for the NTFS Master File Table.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\FileSystem", "NtfsMftZoneReservation", 2, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\FileSystem", "NtfsMftZoneReservation", 1, "DWORD")],
      why="Prevents MFT fragmentation on drives that fill up fast.",
      changes="Sets NtfsMftZoneReservation to 2.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["ntfs", "mft", "fragmentation"]),
    T("stor-005", "Disable HDD Idle Spin-Down",
      "Prevents the hard drive from spinning down during long sessions.",
      actions=[("power", "hdd_timeout", 0)],
      revert=[("power", "hdd_timeout", 1200)],
      why="Spin-down wakes add multi-second delays and wear when a game suddenly needs the drive.",
      changes="Sets the HDD turn-off timeout to 'never' on AC.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      when={"hdd": True},
      tags=["hdd", "spin", "power"]),
    T("stor-006", "Disable Scheduled Defragmentation",
      "Disables the automatic disk defrag task.",
      actions=[("sched", "disable", "/TN \"\\Microsoft\\Windows\\Defrag\\ScheduledDefrag\"")],
      revert=[("sched", "enable", "/TN \"\\Microsoft\\Windows\\Defrag\\ScheduledDefrag\"")],
      why="Auto-defrag churns SSDs and wakes drives at arbitrary times.",
      changes="Disables the scheduled defrag task.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      when={"ssd": True},
      tags=["defrag", "ssd", "schedule"]),
    T("stor-007", "Disable Storage Sense",
      "Turns off automatic storage cleanup.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy", "01", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy", "01", 1, "DWORD")],
      why="Prevents automatic deletion of temporary files that games may still want.",
      changes="Disables Storage Sense.",
      risk="safe", impact="low", recommended="recommended",
      tags=["storage", "cleanup", "temp"]),
    T("stor-008", "Clean Temporary Files",
      "Deletes the user temporary file folder contents.",
      actions=[("cmd", r"del /f /s /q \"%TEMP%\*\" >nul 2>&1")],
      revert=[("guidance", "Temporary files regenerate as needed.")],
      why="Thousands of stale temp files slow directory scans and consume space.",
      changes="Empties the TEMP folder.",
      risk="safe", impact="low", recommended="recommended", confirm=True,
      tags=["temp", "cleanup", "disk"]),
    T("stor-009", "Storage Health Report",
      "Shows the health and bus type of every physical disk.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-PhysicalDisk | Format-Table DeviceId,FriendlyName,MediaType,BusType,HealthStatus,OperationalStatus -AutoSize\"")],
      revert=[("guidance", "Read-only diagnostic; nothing to revert.")],
      why="Identifies failing drives or misconfigured storage before they cause data loss.",
      changes="Runs a physical disk health report.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["smart", "health", "diagnostic"]),
    T("stor-010", "Defragment HDD Now",
      "Runs defragmentation on the system drive.",
      actions=[("cmd", "defrag C: /U")],
      revert=[("guidance", "Read-only maintenance operation.")],
      why="Reunites fragmented files on mechanical drives, reducing seek latency.",
      changes="Defragments drive C:.",
      risk="safe", impact="moderate", recommended="optional", admin=True, confirm=True,
      when={"hdd": True},
      tags=["defrag", "hdd", "fragment"]),
    T("stor-011", "NTFS Scan (Read-Only)",
      "Runs a quick read-only NTFS consistency scan.",
      actions=[("cmd", "chkdsk C: /scan")],
      revert=[("guidance", "Read-only diagnostic; nothing to revert.")],
      why="Catches file-system errors before they cause corruption during gameplay.",
      changes="Scans drive C: for errors.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["chkdsk", "scan", "ntfs"]),
    T("stor-012", "Write Caching Guidance",
      "Explains the disk write-caching policy.",
      actions=[("guidance", "In Device Manager > Disk drives > Properties > Policies, enable 'Enable write caching on the device' and 'Turn off Windows write-cache buffer flushing on the device' ONLY on internal drives you can afford to lose data on in a sudden power loss.")],
      revert=[("guidance", "Re-enable write-cache buffer flushing.")],
      why="Write caching smooths burst I/O for games, at a small power-loss data risk.",
      changes="Shows write-caching guidance.",
      risk="moderate", impact="low", recommended="optional",
      tags=["cache", "write", "io"]),
    T("stor-013", "Game Folder Compression Warning",
      "Explains why compressed game folders can hurt performance.",
      actions=[("guidance", "Do not compress game installation folders with NTFS compression. Every file read pays a decompression CPU cost that can halve load speed and cause stutter.")],
      revert=[("guidance", "Uncheck 'Compress contents to save disk space' on game folders.")],
      why="NTFS compression trades CPU for disk space and hurts games specifically.",
      changes="Shows compression guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["compression", "games", "ntfs"]),
    T("stor-014", "Move Games to Fastest Drive",
      "Guidance for placing games on NVMe or SSD.",
      actions=[("guidance", "Maximum Tweaks detected your storage layout. Install competitive shooters on the fastest NVMe/SSD. Keep HDDs for media and archives. Many games also read config live, so slow storage causes in-game hitches.")],
      revert=[("guidance", "No change to revert.")],
      why="Random-access latency is the main driver of game load times and open-world streaming.",
      changes="Shows storage-tier guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["nvme", "ssd", "hdd", "games"]),
])
