"""Category: System — OS-level memory, crash and responsiveness settings."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("System", win_default="7,8,10,11")
CATEGORY = "System"

TWEAKS = validate_module("system", [

    T("sys-002", "Do Not Clear Pagefile at Shutdown",
      "Skips clearing the pagefile during shutdown.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "ClearPageFileAtShutdown", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "ClearPageFileAtShutdown", 1, "DWORD")],
      why="Clearing the pagefile on shutdown can take a long time and wears SSDs.",
      changes="Disables pagefile clearing at shutdown.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["pagefile", "shutdown", "ssd"]),

    T("sys-004", "Disable Windows Error Reporting",
      "Turns off WER popups and background report submission.",
      actions=[
          ("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\Windows Error Reporting", "Disabled", 1, "DWORD"),
          ("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\Windows Error Reporting", "DontShowUI", 1, "DWORD"),
      ],
      revert=[
          ("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\Windows Error Reporting", "Disabled"),
          ("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows\Windows Error Reporting", "DontShowUI"),
      ],
      why="WER dialogs and report queueing add background CPU and disk work.",
      changes="Disables Windows Error Reporting.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["wer", "crash", "reporting"]),

    T("sys-006", "Disable Auto Reboot on Crash",
      "Prevents automatic restart after a system failure.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\CrashControl", "AutoReboot", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\CrashControl", "AutoReboot", 1, "DWORD")],
      why="An unplanned restart loses all state; better to fail visibly than reboot mid-session.",
      changes="Disables automatic restart on system failure.",
      risk="low", impact="low", recommended="recommended", admin=True,
      tags=["crash", "reboot", "stability"]),
    T("sys-007", "Enable Long Paths",
      "Enables Win32 long path support (>260 chars).",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\FileSystem", "LongPathsEnabled", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\FileSystem", "LongPathsEnabled", 0, "DWORD")],
      why="Mod tools and deep game directories frequently exceed the classic path limit.",
      changes="Enables long paths in Win32.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["paths", "ntfs", "filesystem"]),
    T("sys-008", "Create System Restore Point",
      "Creates a manual restore point before making changes.",
      actions=[("cmd", "powershell -NoProfile -ExecutionPolicy Bypass -Command \"Checkpoint-Computer -Description 'Maximum Tweaks backup' -RestorePointType MODIFY_SETTINGS\"")],
      revert=[("guidance", "No automatic undo — System Restore is rolled back from System Protection if needed.")],
      why="A restore point is the safety net that makes every other tweak reversible.",
      changes="Creates a System Restore point.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["restore", "backup", "safety"]),
    T("sys-009", "Boot Manager Timeout 0",
      "Removes the boot manager selection delay.",
      actions=[("cmd", "bcdedit /timeout 0")],
      revert=[("cmd", "bcdedit /timeout 30")],
      why="Shaves seconds off every cold boot when no dual-boot selection is needed.",
      changes="Sets boot manager timeout to 0.",
      risk="low", impact="low", recommended="recommended", admin=True,
      tags=["boot", "startup", "timeout"]),
    T("sys-010", "Disable Automatic Driver Downloads",
      "Stops Windows Update from automatically installing drivers.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\DriverSearching", "SearchOrderConfig", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\DriverSearching", "SearchOrderConfig", 1, "DWORD")],
      why="An auto-updated GPU driver mid-week can silently change performance behaviour.",
      changes="Disables driver search via Windows Update.",
      risk="moderate", impact="moderate", recommended="optional", admin=True, confirm=True,
      tags=["driver", "update", "gpu"]),
    T("sys-011", "Pagefile Sizing Guidance",
      "Explains and applies a sane pagefile policy.",
      actions=[("guidance", "Keep the pagefile on the fastest drive and let Windows manage its size for stability. A manually fixed size equal to your RAM amount on the OS drive is a good gaming default.")],
      revert=[("guidance", "Re-enable automatic pagefile management in System Properties if desired.")],
      why="A badly sized or misplaced pagefile causes random game hitches when memory pressure rises.",
      changes="Shows pagefile guidance (no destructive change).",
      risk="safe", impact="low", recommended="recommended",
      tags=["pagefile", "memory", "vram"]),
    T("sys-012", "Fast App Shutdown Timeouts",
      "Reduces how long Windows waits for hung applications at shutdown.",
      actions=[
          ("reg", "HKCU", r"Control Panel\Desktop", "WaitToKillAppTimeout", 2000, "STRING"),
          ("reg", "HKCU", r"Control Panel\Desktop", "HungAppTimeout", 1000, "STRING"),
      ],
      revert=[
          ("reg", "HKCU", r"Control Panel\Desktop", "WaitToKillAppTimeout", 5000, "STRING"),
          ("reg", "HKCU", r"Control Panel\Desktop", "HungAppTimeout", 5000, "STRING"),
      ],
      why="Speeds up shutdown and restart cycles; unsaved work may be lost if an app hangs.",
      changes="Lowers shutdown/hung app timeouts.",
      risk="moderate", impact="low", recommended="optional", confirm=True,
      tags=["shutdown", "timeout", "hang"]),
    T("sys-013", "Auto-End Tasks at Logoff",
      "Forces hung applications to close when you log off.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "AutoEndTasks", 1, "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "AutoEndTasks", 0, "STRING")],
      why="Prevents a stuck app from blocking logout.",
      changes="Enables AutoEndTasks.",
      risk="low", impact="low", recommended="recommended",
      tags=["logoff", "tasks", "shutdown"]),
    T("sys-014", "Disable Drive AutoRun",
      "Disables AutoRun for all drive types.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Policies\Explorer", "NoDriveTypeAutoRun", 255, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Policies\Explorer", "NoDriveTypeAutoRun", 0, "DWORD")],
      why="Prevents unexpected background processes from launching when media is inserted.",
      changes="Disables AutoRun for all drives.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["autorun", "security", "usb"]),
    T("sys-015", "Disable Aero Shake",
      "Turns off the Aero Shake minimize gesture.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "DisallowShaking", 1, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "DisallowShaking", 0, "DWORD")],
      why="Accidental shakes while dragging can minimize a game window.",
      changes="Disables window shake minimize.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["shake", "window", "minimize"]),
    T("sys-016", "Disable Minimize Animation",
      "Turns off window minimize/restore animations.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop\WindowMetrics", "MinAnimate", 0, "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop\WindowMetrics", "MinAnimate", 1, "STRING")],
      why="Skips animation work when alt-tabbing between the game and other windows.",
      changes="Disables minimize animation.",
      risk="safe", impact="low", recommended="recommended",
      tags=["animation", "window", "alt-tab"]),
    T("sys-017", "Disable Notification Center",
      "Turns off the notification center via policy.",
      actions=[("reg", "HKCU", r"Software\Policies\Microsoft\Windows\Explorer", "DisableNotificationCenter", 1, "DWORD")],
      revert=[("regdel", "HKCU", r"Software\Policies\Microsoft\Windows\Explorer", "DisableNotificationCenter")],
      why="Removes toast scheduling work and accidental notifications during play.",
      changes="Disables the notification center.",
      risk="safe", impact="low", recommended="recommended",
      tags=["notifications", "toast", "center"]),

    T("sys-019", "Disable 'Start Full-Screen Optimizations' Help",
      "Turns off the fullscreen optimization compatibility help overlay.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "EnableOverlays", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "EnableOverlays", 1, "DWORD")],
      why="Removes overlay layers that can add latency in borderless games.",
      changes="Disables overlay content for fullscreen apps.",
      risk="safe", impact="low", recommended="recommended",
      tags=["overlay", "fullscreen", "latency"]),

    T("sys-021", "Reduce Hung App Timeout",
      "Lowers the threshold before Windows considers an app hung.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "HungAppTimeout", "1000", "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "HungAppTimeout", "5000", "STRING")],
      why="Windows detects and prompts to close hung apps sooner, reducing stalls.",
      changes="Sets HungAppTimeout to 1000 ms.",
      risk="low", impact="low", recommended="optional",
      tags=["hung", "timeout", "responsiveness"]),
    T("sys-023", "Optimize Active Hours",
      "Sets Windows Update active hours to reduce background disruption.",
      actions=[
          ("reg", "HKLM", r"SOFTWARE\Microsoft\WindowsUpdate\UX\Settings", "ActiveHoursStart", 8, "DWORD"),
          ("reg", "HKLM", r"SOFTWARE\Microsoft\WindowsUpdate\UX\Settings", "ActiveHoursEnd", 20, "DWORD"),
      ],
      revert=[
          ("reg", "HKLM", r"SOFTWARE\Microsoft\WindowsUpdate\UX\Settings", "ActiveHoursStart", 7, "DWORD"),
          ("reg", "HKLM", r"SOFTWARE\Microsoft\WindowsUpdate\UX\Settings", "ActiveHoursEnd", 17, "DWORD"),
      ],
      why="Prevents Windows Update from restarting or installing during typical gaming hours.",
      changes="Sets active hours to 08:00 - 20:00.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["update", "activehours", "restart"]),

])
