"""Category: System Tools — convenient launchers for Windows tools."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("System Tools", win_default="7,8,10,11")
CATEGORY = "System Tools"

TWEAKS = validate_module("system_tools", [
    T("tools-001", "Open Task Manager",
      "Opens Task Manager.",
      actions=[("cmd", "taskmgr")],
      revert=[("guidance", "Close the window.")],
      why="Check processes, startup impact and GPU usage.",
      changes="Opens Task Manager.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["taskmanager", "processes", "tools"]),
    T("tools-002", "Open Services",
      "Opens the Services console.",
      actions=[("cmd", "services.msc")],
      revert=[("guidance", "Close the window.")],
      why="Manage and verify the services you disabled.",
      changes="Opens Services.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["services", "console", "tools"]),
    T("tools-003", "Open Device Manager",
      "Opens Device Manager.",
      actions=[("cmd", "devmgmt.msc")],
      revert=[("guidance", "Close the window.")],
      why="Check device status and update drivers.",
      changes="Opens Device Manager.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["devicemanager", "drivers", "tools"]),
    T("tools-004", "Open Registry Editor",
      "Opens the Registry Editor.",
      actions=[("cmd", "regedit")],
      revert=[("guidance", "Close the window.")],
      why="Inspect registry values changed by tweaks.",
      changes="Opens regedit.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["registry", "regedit", "tools"]),
    T("tools-005", "Open System Properties",
      "Opens the System Properties window.",
      actions=[("cmd", "sysdm.cpl")],
      revert=[("guidance", "Close the window.")],
      why="Adjust visual effects and performance options.",
      changes="Opens System Properties.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["system", "properties", "performance"]),
    T("tools-006", "Open System Configuration",
      "Opens msconfig.",
      actions=[("cmd", "msconfig")],
      revert=[("guidance", "Close the window.")],
      why="Manage boot options and startup services.",
      changes="Opens System Configuration.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["msconfig", "boot", "services"]),
    T("tools-007", "Open Performance Monitor",
      "Opens Performance Monitor.",
      actions=[("cmd", "perfmon.msc")],
      revert=[("guidance", "Close the window.")],
      why="Track counters like DPC time and page faults.",
      changes="Opens Performance Monitor.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["perfmon", "counters", "tools"]),
    T("tools-008", "Open Resource Monitor",
      "Opens Resource Monitor.",
      actions=[("cmd", "resmon")],
      revert=[("guidance", "Close the window.")],
      why="See per-process CPU, memory, disk and network load.",
      changes="Opens Resource Monitor.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["resmon", "resource", "monitor"]),
    T("tools-009", "Open Task Scheduler",
      "Opens Task Scheduler.",
      actions=[("cmd", "taskschd.msc")],
      revert=[("guidance", "Close the window.")],
      why="Review scheduled tasks that run during play.",
      changes="Opens Task Scheduler.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["scheduler", "tasks", "tools"]),
    T("tools-010", "Open Disk Management",
      "Opens Disk Management.",
      actions=[("cmd", "diskmgmt.msc")],
      revert=[("guidance", "Close the window.")],
      why="Manage partitions and drive letters.",
      changes="Opens Disk Management.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["disk", "partitions", "tools"]),
    T("tools-011", "Open Computer Management",
      "Opens Computer Management.",
      actions=[("cmd", "compmgmt.msc")],
      revert=[("guidance", "Close the window.")],
      why="One console for devices, disk, services and events.",
      changes="Opens Computer Management.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["computer", "management", "tools"]),
    T("tools-012", "Open Windows Security",
      "Opens Windows Security.",
      actions=[("cmd", "start windowsdefender:")],
      revert=[("guidance", "Close the window.")],
      why="Manage exclusions and protection settings.",
      changes="Opens Windows Security.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["security", "defender", "tools"]),
    T("tools-013", "Open Power Options",
      "Opens the Power Options control panel.",
      actions=[("cmd", "powercfg.cpl")],
      revert=[("guidance", "Close the window.")],
      why="Adjust power plan and advanced settings.",
      changes="Opens Power Options.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["power", "options", "plan"]),
    T("tools-014", "Open Network Connections",
      "Opens Network Connections.",
      actions=[("cmd", "ncpa.cpl")],
      revert=[("guidance", "Close the window.")],
      why="Check adapter properties and speeds.",
      changes="Opens Network Connections.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["network", "adapter", "connections"]),
])
