"""Category: Telemetry — Microsoft telemetry reduction."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Telemetry", win_default="10,11")
CATEGORY = "Telemetry"

TWEAKS = validate_module("telemetry", [
    T("tel-001", "Set Telemetry to Security",
      "Sets diagnostic data to the minimum level.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\DataCollection", "AllowTelemetry", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\DataCollection", "AllowTelemetry", 1, "DWORD")],
      why="Lowers the telemetry level to security-only.",
      changes="Sets AllowTelemetry to 0.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["telemetry", "data", "policy"]),
    T("tel-002", "Disable Compatibility Telemetry",
      "Turns off the compatibility appraiser telemetry.",
      actions=[("sc", "disable", "CompatTelRunner")],
      revert=[("sc", "enable", "CompatTelRunner")],
      why="CompatTelRunner scans and uploads compatibility data.",
      changes="Disables CompatTelRunner.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["compatibility", "telemetry", "scanner"]),
    T("tel-003", "Disable Inventory Collector",
      "Disables the Device Inventory Collector.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\DeviceInformation", "DisableDeviceInformationCollection", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\DeviceInformation", "DisableDeviceInformationCollection", 0, "DWORD")],
      why="Stops periodic device inventory uploads.",
      changes="Disables device information collection.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["inventory", "device", "telemetry"]),
    T("tel-004", "Disable Activity History",
      "Turns off activity history tracking.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\System", "EnableActivityFeed", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\System", "EnableActivityFeed", 1, "DWORD")],
      why="Activity feed tracking writes timeline data.",
      changes="Disables the activity feed.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["activity", "timeline", "privacy"]),
    T("tel-005", "Disable Advertising ID",
      "Turns off the advertising ID.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo", "Enabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo", "Enabled", 1, "DWORD")],
      why="Stops the advertising ID from being tracked.",
      changes="Disables the advertising ID.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["advertising", "id", "tracking"]),

    T("tel-009", "Disable Windows Update Telemetry",
      "Disables update telemetry services.",
      actions=[("sc", "disable", "WaaSMedicSvc")],
      revert=[("sc", "enable", "WaaSMedicSvc")],
      why="WaaSMedic scans and repairs update telemetry state.",
      changes="Disables WaaS Medic service.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["waas", "updates", "telemetry"]),
    T("tel-010", "Disable Feedback Requests",
      "Turns off Windows feedback prompts.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Siuf\Rules", "NumberOfSIUFInPeriod", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Siuf\Rules", "NumberOfSIUFInPeriod", 1, "DWORD")],
      why="Stops the feedback hub from prompting.",
      changes="Disables feedback requests.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["feedback", "prompts", "siuf"]),
    T("tel-011", "Disable Sign-in Telemetry",
      "Guidance on sign-in data sharing.",
      actions=[("guidance", "In Settings > Privacy > Diagnostics, turn off 'Tailored experiences' and 'Improve inking & typing'. These send usage data to personalize ads and suggestions.")],
      revert=[("guidance", "Re-enable tailored experiences.")],
      why="Tailored experiences continuously send usage context.",
      changes="Shows sign-in telemetry guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["tailored", "inking", "typing"]),
    T("tel-012", "Disable Location Service",
      "Turns off location access.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\location", "Value", "Deny", "STRING")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\location", "Value", "Allow", "STRING")],
      why="Location polling wakes the location stack.",
      changes="Denies location access.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["location", "gps", "privacy"]),
    T("tel-013", "Disable Find My Device",
      "Turns off device-finder telemetry.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Settings\FindMyDevice", "LocationSyncEnabled", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Settings\FindMyDevice", "LocationSyncEnabled", 1, "DWORD")],
      why="Find My Device periodically syncs location.",
      changes="Disables Find My Device sync.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["findmydevice", "location", "sync"]),

    T("tel-016", "Disable App Diagnostics",
      "Turns off per-app diagnostic data access.",
      actions=[("reg", "HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\AppDiagnostics", "DiagTrackEnabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\AppDiagnostics", "DiagTrackEnabled", 1, "DWORD")],
      why="App diagnostics allow applications to read device and usage information.",
      changes="Disables app diagnostic data access.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["diagnostics", "apps", "privacy"]),
    T("tel-017", "Disable Customer Experience",
      "Disables the Customer Experience Improvement Program.",
      actions=[("cmd", "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\SQMClient\\Windows\" /v CEIPEnable /t REG_DWORD /d 0 /f")],
      revert=[("cmd", "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\SQMClient\\Windows\" /v CEIPEnable /t REG_DWORD /d 1 /f")],
      why="CEIP collects usage data and sends it to Microsoft on a schedule.",
      changes="Sets CEIPEnable to 0 to opt out of the Customer Experience program.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["ceip", "experience", "telemetry"]),

    T("tel-019", "Disable Diagnostic Data Viewer",
      "Disables the Diagnostic Data Viewer plugin.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Diagnostics\DiagTrack\EventDataPlugin", "DisableEventDataPlugin", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Diagnostics\DiagTrack\EventDataPlugin", "DisableEventDataPlugin", 0, "DWORD")],
      why="The EventDataPlugin processes and logs diagnostic events in the background.",
      changes="Disables the Diagnostic Data Viewer event plugin.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["diagnostic", "viewer", "plugin"]),
])
