"""Category: Telemetry — Microsoft telemetry reduction."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Telemetry", win_default="10,11")
CATEGORY = "Telemetry"

TWEAKS = validate_module("telemetry", [
    T("tel-001", "Set Telemetry to Security",
      "Sets diagnostic data to the minimum level.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\DataCollection", "AllowTelemetry", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\DataCollection", "AllowTelemetry", 1, "DWORD")],
      why="Lowers the telemetry level to security-only.",
      changes="Sets AllowTelemetry to 0.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["telemetry", "data", "policy"]),
    T("tel-002", "Disable Compatibility Telemetry",
      "Turns off the compatibility appraiser telemetry.",
      actions=[("sc", "disable", "CompatTelRunner")],
      revert=[("sc", "enable", "CompatTelRunner")],
      why="CompatTelRunner scans and uploads compatibility data.",
      changes="Disables CompatTelRunner.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["compatibility", "telemetry", "scanner"]),
    T("tel-003", "Disable Inventory Collector",
      "Disables the Device Inventory Collector.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\DeviceInformation", "DisableDeviceInformationCollection", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\DeviceInformation", "DisableDeviceInformationCollection", 0, "DWORD")],
      why="Stops periodic device inventory uploads.",
      changes="Disables device information collection.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["inventory", "device", "telemetry"]),
    T("tel-004", "Disable Activity History",
      "Turns off activity history tracking.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\System", "EnableActivityFeed", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\System", "EnableActivityFeed", 1, "DWORD")],
      why="Activity feed tracking writes timeline data.",
      changes="Disables the activity feed.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["activity", "timeline", "privacy"]),
    T("tel-005", "Disable Advertising ID",
      "Turns off the advertising ID.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo", "Enabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo", "Enabled", 1, "DWORD")],
      why="Stops the advertising ID from being tracked.",
      changes="Disables the advertising ID.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["advertising", "id", "tracking"]),
    T("tel-006", "Disable Cortana",
      "Turns off Cortana telemetry and polling.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Windows Search", "AllowCortana", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Windows Search", "AllowCortana", 1, "DWORD")],
      why="Cortana processes voice/search data in the background.",
      changes="Disables Cortana.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["cortana", "assistant", "search"]),
    T("tel-007", "Disable Bing Search Integration",
      "Removes Bing from the Start menu search.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Search", "BingSearchEnabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Search", "BingSearchEnabled", 1, "DWORD")],
      why="Stops local search from calling web services.",
      changes="Disables Bing search integration.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["bing", "search", "start"]),
    T("tel-008", "Disable Telemetry Scheduled Tasks",
      "Disables telemetry scheduled tasks.",
      actions=[("cmd", "schtasks /Change /TN \"\\Microsoft\\Windows\\Application Experience\\Microsoft Compatibility Appraiser\" /Disable")],
      revert=[("cmd", "schtasks /Change /TN \"\\Microsoft\\Windows\\Application Experience\\Microsoft Compatibility Appraiser\" /Enable")],
      why="Removes the scheduled telemetry runs that hit CPU/disk on idle.",
      changes="Disables the Compatibility Appraiser task.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["tasks", "telemetry", "schedule"]),
    T("tel-009", "Disable Windows Update Telemetry",
      "Disables update telemetry services.",
      actions=[("sc", "disable", "WaaSMedicSvc")],
      revert=[("sc", "enable", "WaaSMedicSvc")],
      why="WaaSMedic scans and repairs update telemetry state.",
      changes="Disables WaaS Medic service.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["waas", "updates", "telemetry"]),
    T("tel-010", "Disable Feedback Requests",
      "Turns off Windows feedback prompts.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Siuf\Rules", "NumberOfSIUFInPeriod", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Siuf\Rules", "NumberOfSIUFInPeriod", 1, "DWORD")],
      why="Stops the feedback hub from prompting.",
      changes="Disables feedback requests.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["feedback", "prompts", "siuf"]),
    T("tel-011", "Disable Sign-in Telemetry",
      "Guidance on sign-in data sharing.",
      actions=[("guidance", "In Settings > Privacy > Diagnostics, turn off 'Tailored experiences' and 'Improve inking & typing'. These send usage data to personalize ads and suggestions.")],
      revert=[("guidance", "Re-enable tailored experiences.")],
      why="Tailored experiences continuously send usage context.",
      changes="Shows sign-in telemetry guidance.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["tailored", "inking", "typing"]),
    T("tel-012", "Disable Location Service",
      "Turns off location access.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\location", "Value", "Deny", "STRING")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\location", "Value", "Allow", "STRING")],
      why="Location polling wakes the location stack.",
      changes="Denies location access.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["location", "gps", "privacy"]),
    T("tel-013", "Disable Find My Device",
      "Turns off device-finder telemetry.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Settings\FindMyDevice", "LocationSyncEnabled", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Settings\FindMyDevice", "LocationSyncEnabled", 1, "DWORD")],
      why="Find My Device periodically syncs location.",
      changes="Disables Find My Device sync.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["findmydevice", "location", "sync"]),
    T("tel-014", "Disable Delivery Optimization Uploads",
      "Stops P2P uploads from your machine.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Settings", "DownloadMode", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Settings", "DownloadMode", 1, "DWORD")],
      why="DownloadMode 0 disables peer sharing entirely.",
      changes="Disables Delivery Optimization P2P.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["delivery", "p2p", "bandwidth"]),
])
