"""Category: USB — controller, suspend and device optimizations."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("USB", win_default="7,8,10,11")
CATEGORY = "USB"

TWEAKS = validate_module("usb", [
    T("usb-001", "Disable USB Selective Suspend",
      "Turns off USB selective suspend in the active power scheme.",
      actions=[("power", "usb_selective", 0)],
      revert=[("power", "usb_selective", 1)],
      why="Selective suspend drops hubs to low-power mode, adding wake latency to mice and keyboards.",
      changes="Disables USB selective suspend on AC.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["usb", "suspend", "power"]),

    T("usb-003", "USB Device Report",
      "Lists USB controllers and devices with their status.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-PnpDevice -PresentOnly | Where-Object { $_.Class -eq 'USB' -or $_.Class -eq 'HIDClass' } | Format-Table FriendlyName,Status,Problem -AutoSize\"")],
      revert=[("guidance", "Read-only report.")],
      why="Surfaces USB devices in error state that cause intermittent input drops.",
      changes="Shows the USB device report.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["usb", "report", "devices"]),
    T("usb-004", "USB Controller Report",
      "Lists the USB host controllers and their driver dates.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-CimInstance Win32_USBController | Format-Table Name,Manufacturer,Status -AutoSize\"")],
      revert=[("guidance", "Read-only report.")],
      why="Confirms the correct xHCI controller is active and in a healthy state.",
      changes="Shows the USB controller report.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["controller", "xhci", "usb"]),
    T("usb-005", "USB Polling Rate Guidance",
      "Explains USB polling rates for input devices.",
      actions=[("guidance", "USB mice/keyboards typically report at 125-1000 Hz. Use the vendor software to raise polling to 1000 Hz. Note that extremely high rates can add CPU load on weak CPUs.")],
      revert=[("guidance", "Restore default polling.")],
      why="Higher polling delivers fresher input samples to the OS.",
      changes="Shows USB polling guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["polling", "usb", "input"]),
    T("usb-006", "Disable USB Host Controller Power Management",
      "Disables power management on all USB host controllers to prevent input device sleep.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{36fc9e60-c465-11cf-8056-444553540000}\*", "PnPCapabilities", 256, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{36fc9e60-c465-11cf-8056-444553540000}\*", "PnPCapabilities")],
      why="USB power management can drop an input device to sleep mid-session.",
      changes="Disables 'Allow the computer to turn off this device' on USB host controllers.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["usb", "power", "input"]),
    T("usb-007", "USB 3.x Driver Guidance",
      "Guidance to install current USB 3.x drivers.",
      actions=[("guidance", "Install the latest chipset and USB 3.x drivers from the motherboard vendor. Generic Windows drivers work but lack the latency optimizations of vendor drivers.")],
      revert=[("guidance", "Roll back the driver.")],
      why="Vendor USB drivers handle large transfers and interrupts more efficiently.",
      changes="Shows USB driver guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["usb3", "driver", "chipset"]),
    T("usb-008", "Legacy USB in BIOS",
      "Guidance to disable Legacy USB support for cleaner boot.",
      actions=[("guidance", "If you do not use USB keyboards at the BIOS level, disable 'Legacy USB Support' in the BIOS. This removes an emulation layer that can add input latency in Windows on some boards.")],
      revert=[("guidance", "Re-enable Legacy USB Support in the BIOS.")],
      why="Legacy USB emulation occasionally interferes with native XHCI input handling.",
      changes="Shows Legacy USB guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["bios", "legacyusb", "input"]),

    T("usb-010", "Reset USB Stack",
      "Guidance for a clean USB re-enumeration.",
      actions=[("guidance", "Restart the PC to re-enumerate all USB devices. If a device keeps failing, unplug it, reboot, and reinsert — do not hot-unplug a frozen device mid-session.")],
      revert=[("guidance", "No change to revert.")],
      why="A hung USB device can take down the whole controller and your input.",
      changes="Shows USB reset guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["reset", "enumeration", "usb"]),

    T("usb-012", "Verify XHCI Controller",
      "Checks that the XHCI (USB 3) controller is the active host.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-PnpDevice -PresentOnly -Class USB | Where-Object { $_.FriendlyName -match 'Host Controller' } | Format-Table FriendlyName,Status -AutoSize\"")],
      revert=[("guidance", "Read-only check.")],
      why="Ensures Windows is using the modern xHCI stack rather than a legacy EHCI fallback.",
      changes="Shows the active host controller.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["xhci", "host", "controller"]),

    T("usb-014", "Set USB Data Queue Size",
      "Sets the minimum USB transfer bytes to zero for lower latency.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Services\usb", "MinimumTransferBytes", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Services\usb", "MinimumTransferBytes", 64, "DWORD")],
      why="Reducing the minimum transfer size removes unnecessary buffering that adds USB round-trip latency.",
      changes="Sets MinimumTransferBytes to 0.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["usb", "transfer", "latency"]),

])
