"""Category: Wi-Fi — wireless adapter optimizations."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Wi-Fi", win_default="7,8,10,11")
CATEGORY = "Wi-Fi"

PS = "powershell -NoProfile -ExecutionPolicy Bypass -Command"

TWEAKS = validate_module("wifi", [
    T("wifi-001", "Disable Wi-Fi Power Saving",
      "Turns off power management on the wireless adapter.",
      actions=[("cmd", f'{PS} "Disable-NetAdapterPowerManagement -Name \'Wi-Fi*\' -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Enable-NetAdapterPowerManagement -Name \'Wi-Fi*\' -ErrorAction SilentlyContinue"')],
      why="Wireless adapters drop to low-power modes that add latency and packet loss spikes.",
      changes="Disables Wi-Fi adapter power management.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["power", "wifi", "latency"]),
    T("wifi-002", "Highest Roaming Aggressiveness",
      "Sets roaming aggressiveness to its highest value.",
      actions=[("cmd", f'{PS} "Set-NetAdapterAdvancedProperty -Name \'Wi-Fi*\' -DisplayName \'Roaming Aggressiveness\' -DisplayValue \'Highest\' -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Set-NetAdapterAdvancedProperty -Name \'Wi-Fi*\' -DisplayName \'Roaming Aggressiveness\' -DisplayValue \'Medium\' -ErrorAction SilentlyContinue"')],
      why="The adapter re-evaluates access points faster and leaves weak cells sooner.",
      changes="Sets roaming aggressiveness to highest.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["roaming", "wifi", "signal"]),
    T("wifi-003", "Disable LSO on Wi-Fi",
      "Turns off Large Send Offload on the wireless adapter.",
      actions=[("cmd", f'{PS} "Set-NetAdapterLso -Name \'Wi-Fi*\' -IPv4Enabled $false -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Set-NetAdapterLso -Name \'Wi-Fi*\' -IPv4Enabled $true -ErrorAction SilentlyContinue"')],
      why="Wi-Fi offload engines occasionally drop oversized frames during congestion.",
      changes="Disables LSO IPv4 on Wi-Fi.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["lso", "wifi", "offload"]),
    T("wifi-004", "Wi-Fi Signal Report",
      "Shows the connected network and its signal quality.",
      actions=[("cmd", f'{PS} "netsh wlan show interfaces"')],
      revert=[("guidance", "Read-only report.")],
      why="Weak signal (< -70 dBm) causes the packet loss that feels like game lag.",
      changes="Displays the Wi-Fi signal report.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["signal", "wifi", "report"]),
    T("wifi-005", "Prefer 5 GHz / 6 GHz Band",
      "Sets the wireless adapter preferred band to 5 GHz / 6 GHz.",
      actions=[("cmd", f'{PS} "Get-NetAdapter -Name \'Wi-Fi*\' | ForEach-Object {{ netsh wlan set interface $_.Name band=five }}"')],
      revert=[("cmd", f'{PS} "Get-NetAdapter -Name \'Wi-Fi*\' | ForEach-Object {{ netsh wlan set interface $_.Name band=any }}"')],
      why="5/6 GHz bands offer lower latency and less congestion than 2.4 GHz.",
      changes="Sets preferred Wi-Fi band to 5 GHz / 6 GHz.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["5ghz", "6ghz", "band"]),
    T("wifi-006", "Use Ethernet for Competitive Play",
      "Guidance recommending wired connections for ranked play.",
      actions=[("guidance", "For ranked FPS play, connect via Ethernet. Wi-Fi adds jitter (varying packet delay) that feels like stutter even at the same average ping.")],
      revert=[("guidance", "No change to revert.")],
      why="Wired links have consistent latency; Wi-Fi jitter ruins input and movement consistency.",
      changes="Shows wired-vs-wireless guidance.",
      risk="safe", impact="high", recommended="recommended",
      tags=["ethernet", "wifi", "jitter"]),
    T("wifi-007", "Disable Auto-Connect to Hotspots",
      "Stops automatic connections to suggested open hotspots via registry.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\WcmSvc\wifinetworkmanager\GroupPolicy", "AutoConnectAllowedOEM", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\WcmSvc\wifinetworkmanager\GroupPolicy", "AutoConnectAllowedOEM")],
      why="Prevents surprise network switches mid-session that drop online games.",
      changes="Disables auto-connect to suggested open hotspots.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["hotspot", "autoconnect", "wifi"]),
    T("wifi-008", "Renew DHCP Lease",
      "Releases and renews the IP address lease.",
      actions=[("cmd", "ipconfig /release & ipconfig /renew")],
      revert=[("guidance", "Non-destructive network refresh.")],
      why="Clears stale DHCP state that can cause black-screen connection hangs.",
      changes="Renews the DHCP lease.",
      risk="safe", impact="low", recommended="optional", admin=True, confirm=True,
      tags=["dhcp", "lease", "ip"]),
    T("wifi-009", "Disable Wake on Magic Packet (Wi-Fi)",
      "Turns off wireless Wake-on-LAN.",
      actions=[("cmd", f'{PS} "Set-NetAdapterPowerManagement -Name \'Wi-Fi*\' -WakeOnMagicPacket Disabled -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Set-NetAdapterPowerManagement -Name \'Wi-Fi*\' -WakeOnMagicPacket Enabled -ErrorAction SilentlyContinue"')],
      why="Removes the constant-listening wake channel that keeps the Wi-Fi radio powered.",
      changes="Disables wireless wake-on-magic-packet.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["wol", "wake", "wifi"]),
    T("wifi-010", "Disable LSO IPv6 (Wi-Fi)",
      "Turns off IPv6 large send offload on Wi-Fi.",
      actions=[("cmd", f'{PS} "Set-NetAdapterLso -Name \'Wi-Fi*\' -IPv6Enabled $false -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Set-NetAdapterLso -Name \'Wi-Fi*\' -IPv6Enabled $true -ErrorAction SilentlyContinue"')],
      why="Reduces offload-engine frame drops on wireless links.",
      changes="Disables LSO IPv6 on Wi-Fi.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["lso", "ipv6", "wifi"]),
    T("wifi-011", "Disable Background Scanning",
      "Reduces frequent wireless background scans via registry.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\PolicyManager\default\WiFi\AllowWiFiHotSpotReporting", "Value", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Microsoft\PolicyManager\default\WiFi\AllowWiFiHotSpotReporting", "Value", 1, "DWORD")],
      why="Periodic background scans can pause the adapter for hundreds of milliseconds.",
      changes="Disables Wi-Fi background scan reporting.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["scan", "background", "wifi"]),
    T("wifi-012", "Reset Wi-Fi Adapter",
      "Restarts the wireless adapter.",
      actions=[("cmd", f'{PS} "Restart-NetAdapter -Name \'Wi-Fi*\' -ErrorAction SilentlyContinue"')],
      revert=[("guidance", "Adapter restart is non-destructive.")],
      why="Clears stuck radio/driver state after long uptime.",
      changes="Restarts the Wi-Fi adapter.",
      risk="safe", impact="moderate", recommended="optional", admin=True, confirm=True,
      tags=["reset", "adapter", "wifi"]),
    T("wifi-013", "Reduce Wi-Fi Packet Queue",
      "Guidance for lowering wireless buffer bloat.",
      actions=[("guidance", "In the router, enable QoS/SQM and cap Wi-Fi bandwidth slightly below the link rate. High wireless buffers inflate latency under load.")],
      revert=[("guidance", "Disable QoS in the router.")],
      why="Bufferbloat on Wi-Fi causes ping to climb whenever anyone streams or downloads.",
      changes="Shows bufferbloat guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["bufferbloat", "qos", "ping"]),
    T("wifi-014", "Disable Preferred Network Promotion",
      "Prevents Windows from promoting 'better' networks automatically.",
      actions=[("guidance", "In the adapter advanced properties set 'Preferred Network Promotion' to 'Disable' if present (Intel adapters).")],
      revert=[("guidance", "Restore the default setting.")],
      why="Automatic network promotion can switch networks at exactly the wrong moment.",
      changes="Shows network-promotion guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["network", "switch", "wifi"]),
])
