"""Category: Windows Graphics — graphics stack and presentation settings."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Windows Graphics", win_default="10,11")
CATEGORY = "Windows Graphics"
_ALL_GPU = {"gpu": ["nvidia", "amd", "intel"]}

TWEAKS = validate_module("win_graphics", [
    T("wgr-001", "Enable Swap Effect Upgrade",
      "Lets Windows replace legacy swap chains with modern ones.",
      actions=[("reg", "HKCU", r"Software\Microsoft\DirectX\UserGpuPreferences", "DirectXUserGlobalSettings", "SwapEffectUpgradeEnable=1;", "STRING")],
      revert=[("reg", "HKCU", r"Software\Microsoft\DirectX\UserGpuPreferences", "DirectXUserGlobalSettings", "SwapEffectUpgradeEnable=0;", "STRING")],
      why="Modern swap effects reduce frame queueing latency in windowed games.",
      changes="Sets SwapEffectUpgradeEnable in DirectX user settings.",
      risk="low", impact="moderate", recommended="recommended",
      when=_ALL_GPU,
      tags=["swap", "directx", "latency"]),
    T("wgr-003", "Disable Auto HDR",
      "Disables Windows Auto HDR via policy registry key.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Display", "DisableAutoHDR", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Display", "DisableAutoHDR")],
      why="Auto HDR conversion adds a compute pass that can cost FPS on mid-range GPUs.",
      changes="Sets DisableAutoHDR to 1.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      when=_ALL_GPU,
      tags=["hdr", "auto", "overhead"]),
    T("wgr-004", "Enable Variable Refresh Rate",
      "Enables Variable Refresh Rate in DirectX user settings.",
      actions=[("reg", "HKCU", r"Software\Microsoft\DirectX\UserGpuPreferences", "DirectXUserGlobalSettings", "VRROptimizeEnable=1;", "STRING")],
      revert=[("reg", "HKCU", r"Software\Microsoft\DirectX\UserGpuPreferences", "DirectXUserGlobalSettings", "VRROptimizeEnable=0;", "STRING")],
      why="VRR removes tearing and stutter from frame-rate fluctuations.",
      changes="Sets VRROptimizeEnable to 1.",
      risk="safe", impact="moderate", recommended="recommended",
      when=_ALL_GPU,
      tags=["vrr", "freesync", "gsync"]),
    T("wgr-005", "Graphics Preference App List",
      "Guidance for assigning per-app GPUs in Windows.",
      actions=[("guidance", "In Settings > System > Display > Graphics, add each game and set 'High performance' for its GPU (or 'Power saving' for the iGPU) so Windows does not guess.")],
      revert=[("guidance", "Remove the per-app assignments.")],
      why="Explicit GPU assignment avoids Windows picking the slow iGPU for a game.",
      changes="Shows graphics-preference guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when=_ALL_GPU,
      tags=["gpu", "preference", "app"]),
    T("wgr-006", "Restore MPO Composition",
      "Re-enables Multiplane Overlay (undo of the MPO disable tweak).",
      actions=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "OverlayTestMode")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "OverlayTestMode", 5, "DWORD")],
      why="If your display had no MPO issues, restoring it returns to the hardware composition path.",
      changes="Removes the MPO override.",
      risk="safe", impact="low", recommended="optional", admin=True,
      when=_ALL_GPU,
      tags=["mpo", "overlay", "restore"]),
    T("wgr-007", "NVIDIA Maximum Performance Global",
      "Sets NVIDIA global power mode to maximum performance via registry.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\*\Curver", "PowerMizerLevelAC", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\*\Curver", "PowerMizerLevelAC")],
      why="Downclocking between frames causes inconsistent frame times.",
      changes="Sets PowerMizerLevelAC to 1 (max performance).",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      when={"gpu": ["nvidia"]},
      tags=["power", "performance", "gpu"]),
    T("wgr-008", "Disable Windowed Game Optimizations",
      "Disables Windows 11 windowed game optimization layer via registry.",
      actions=[("reg", "HKCU", r"Software\Microsoft\DirectX\UserGpuPreferences", "DirectXUserGlobalSettings", "DisableFeatureSetCreation=1;", "STRING")],
      revert=[("reg", "HKCU", r"Software\Microsoft\DirectX\UserGpuPreferences", "DirectXUserGlobalSettings", "DisableFeatureSetCreation=0;", "STRING")],
      why="The optimization layer helps some games and hurts others.",
      changes="Sets DisableFeatureSetCreation to 1.",
      risk="safe", impact="low", recommended="recommended",
      when=_ALL_GPU,
      tags=["windowed", "optimization", "borderless"]),
    T("wgr-009", "DirectStorage Check",
      "Guidance to verify DirectStorage is active.",
      actions=[("guidance", "DirectStorage requires an NVMe SSD, a DX12 GPU and the game's support. Check in-game settings; if unsupported games hit 'GPU decompression', enable the per-game option where present.")],
      revert=[("guidance", "No change to revert.")],
      why="DirectStorage moves asset decompression to the GPU, cutting load times.",
      changes="Shows DirectStorage guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"nvme": True, "gpu": ["nvidia", "amd", "intel"]},
      tags=["directstorage", "nvme", "loadtimes"]),
    T("wgr-010", "8-bit Color Depth for Performance",
      "Guidance to drop color depth on very weak GPUs.",
      actions=[("guidance", "If frame times are bad on an old GPU, set the display to 8-bit color in Settings > Display > Advanced display. Skipping 10-bit output saves bandwidth and compute.")],
      revert=[("guidance", "Restore 10-bit color.")],
      why="Wide color output adds measurable pixel bandwidth cost on low-end GPUs.",
      changes="Shows color-depth guidance.",
      risk="safe", impact="low", recommended="optional",
      when=_ALL_GPU,
      tags=["color", "bandwidth", "gpu"]),
    T("wgr-011", "Disable Desktop Composition Overlay",
      "Guidance for fullscreen-exclusive play to avoid DWM overhead.",
      actions=[("guidance", "For the lowest latency, run games in exclusive fullscreen (not borderless). DWM composition still runs, but the game renders directly to the primary surface.")],
      revert=[("guidance", "Return to borderless.")],
      why="Exclusive fullscreen avoids the extra presentation copy.",
      changes="Shows fullscreen guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when=_ALL_GPU,
      tags=["fullscreen", "dwm", "latency"]),
    T("wgr-012", "Reset Graphics Settings",
      "Deletes all per-app DirectX GPU preference settings.",
      actions=[("cmd", r'reg delete "HKCU\SOFTWARE\Microsoft\DirectX\UserGpuPreferences" /f')],
      revert=[("guidance", "No revert possible — settings were fully deleted.")],
      why="Stale per-app graphics entries cause wrong-GPU launches.",
      changes="Deletes DirectX UserGpuPreferences key.",
      risk="low", impact="low", recommended="recommended",
      when=_ALL_GPU,
      tags=["reset", "graphics", "settings"]),
])
