"""Category: Windows Graphics — graphics stack and presentation settings."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Windows Graphics", win_default="10,11")
CATEGORY = "Windows Graphics"

TWEAKS = validate_module("win_graphics", [
    T("wgr-001", "Enable Swap Effect Upgrade",
      "Lets Windows replace legacy swap chains with modern ones.",
      actions=[("reg", "HKCU", r"Software\Microsoft\DirectX\UserGpuPreferences", "DirectXUserGlobalSettings", "SwapEffectUpgradeEnable=1;", "STRING")],
      revert=[("reg", "HKCU", r"Software\Microsoft\DirectX\UserGpuPreferences", "DirectXUserGlobalSettings", "SwapEffectUpgradeEnable=0;", "STRING")],
      why="Modern swap effects reduce frame queueing latency in windowed games.",
      changes="Sets SwapEffectUpgradeEnable in DirectX user settings.",
      risk="low", impact="moderate", recommended="recommended",
      tags=["swap", "directx", "latency"]),
    T("wgr-003", "Disable Auto HDR",
      "Guidance to turn off Auto HDR for SDR games.",
      actions=[("guidance", "If Auto HDR causes banding or stutter, disable it in Settings > System > Display > HDR or per-game in the Graphics settings, and rely on the game's own HDR.")],
      revert=[("guidance", "Re-enable Auto HDR.")],
      why="Auto HDR conversion adds a compute pass that can cost FPS on mid-range GPUs.",
      changes="Shows Auto HDR guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["hdr", "auto", "overhead"]),
    T("wgr-004", "Enable Variable Refresh Rate",
      "Guidance to enable VRR in Windows for borderless games.",
      actions=[("guidance", "Enable 'Variable refresh rate' in Settings > System > Display > Advanced display for the monitor, and enable G-SYNC/FreeSync in the driver as well.")],
      revert=[("guidance", "Disable VRR.")],
      why="VRR removes tearing and stutter from frame-rate fluctuations.",
      changes="Shows VRR guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["vrr", "freesync", "gsync"]),
    T("wgr-005", "Graphics Preference App List",
      "Guidance for assigning per-app GPUs in Windows.",
      actions=[("guidance", "In Settings > System > Display > Graphics, add each game and set 'High performance' for its GPU (or 'Power saving' for the iGPU) so Windows does not guess.")],
      revert=[("guidance", "Remove the per-app assignments.")],
      why="Explicit GPU assignment avoids Windows picking the slow iGPU for a game.",
      changes="Shows graphics-preference guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["gpu", "preference", "app"]),
    T("wgr-006", "Restore MPO Composition",
      "Re-enables Multiplane Overlay (undo of the MPO disable tweak).",
      actions=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "OverlayTestMode")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "OverlayTestMode", 5, "DWORD")],
      why="If your display had no MPO issues, restoring it returns to the hardware composition path.",
      changes="Removes the MPO override.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["mpo", "overlay", "restore"]),
    T("wgr-007", "Prefer Maximum Performance Global",
      "Guidance to set global GPU power mode to maximum performance.",
      actions=[("guidance", "In NVIDIA Control Panel set 'Power management mode' globally to 'Prefer maximum performance'. AMD users enable 'Performance' mode in AMD Software. This prevents GPU downclocking between frames.")],
      revert=[("guidance", "Restore 'Optimal power'.")],
      why="Downclocking between frames causes inconsistent frame times.",
      changes="Shows global power-mode guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["power", "performance", "gpu"]),
    T("wgr-008", "Windowed Game Optimizations",
      "Guidance for the Windows 11 windowed-game optimization setting.",
      actions=[("guidance", "If a borderless game stutters, toggle 'Optimizations for windowed games' off for that game in Settings > System > Display > Graphics, or turn it off globally.")],
      revert=[("guidance", "Re-enable windowed game optimizations.")],
      why="The optimization layer helps some games and hurts others.",
      changes="Shows windowed-optimization guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["windowed", "optimization", "borderless"]),
    T("wgr-009", "DirectStorage Check",
      "Guidance to verify DirectStorage is active.",
      actions=[("guidance", "DirectStorage requires an NVMe SSD, a DX12 GPU and the game's support. Check in-game settings; if unsupported games hit 'GPU decompression', enable the per-game option where present.")],
      revert=[("guidance", "No change to revert.")],
      why="DirectStorage moves asset decompression to the GPU, cutting load times.",
      changes="Shows DirectStorage guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"nvme": True},
      tags=["directstorage", "nvme", "loadtimes"]),
    T("wgr-010", "8-bit Color Depth for Performance",
      "Guidance to drop color depth on very weak GPUs.",
      actions=[("guidance", "If frame times are bad on an old GPU, set the display to 8-bit color in Settings > Display > Advanced display. Skipping 10-bit output saves bandwidth and compute.")],
      revert=[("guidance", "Restore 10-bit color.")],
      why="Wide color output adds measurable pixel bandwidth cost on low-end GPUs.",
      changes="Shows color-depth guidance.",
      risk="safe", impact="low", recommended="optional",
      tags=["color", "bandwidth", "gpu"]),
    T("wgr-011", "Disable Desktop Composition Overlay",
      "Guidance for fullscreen-exclusive play to avoid DWM overhead.",
      actions=[("guidance", "For the lowest latency, run games in exclusive fullscreen (not borderless). DWM composition still runs, but the game renders directly to the primary surface.")],
      revert=[("guidance", "Return to borderless.")],
      why="Exclusive fullscreen avoids the extra presentation copy.",
      changes="Shows fullscreen guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["fullscreen", "dwm", "latency"]),
    T("wgr-012", "Reset Graphics Settings",
      "Guidance to reset per-app graphics settings.",
      actions=[("guidance", "In Settings > System > Display > Graphics > Reset, restore default graphics settings if a game keeps picking the wrong GPU or settings.")],
      revert=[("guidance", "No change to revert.")],
      why="Stale per-app graphics entries cause wrong-GPU launches.",
      changes="Shows graphics-reset guidance.",
      risk="safe", impact="low", recommended="recommended",
      tags=["reset", "graphics", "settings"]),
])
