"""Category: Windows — core Windows behaviour optimizations."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Windows", win_default="10,11")
CATEGORY = "Windows"

TWEAKS = validate_module("windows", [
    T("win-001", "Disable Game DVR",
      "Turns off the Xbox Game DVR background capture feature.",
      actions=[("reg", "HKCU", r"System\GameConfigStore", "GameDVR_Enabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"System\GameConfigStore", "GameDVR_Enabled", 1, "DWORD")],
      why="Game DVR silently records in the background, consuming CPU, GPU and disk while games run.",
      changes="Disables Game DVR capture globally.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["dvr", "capture", "recording", "overlay"]),

    T("win-004", "Disable Fullscreen Optimizations",
      "Uses the legacy fullscreen path so games bypass the DWM composition overlay.",
      actions=[("reg", "HKCU", r"System\GameConfigStore", "GameDVR_FSEBehaviorMode", 2, "DWORD")],
      revert=[("reg", "HKCU", r"System\GameConfigStore", "GameDVR_FSEBehaviorMode", 0, "DWORD")],
      why="Some engines get extra latency or stutter from the GameDVR fullscreen optimizations layer.",
      changes="Sets the fullscreen optimization behaviour mode to legacy.",
      risk="low", impact="moderate", recommended="recommended", confirm=True,
      tags=["fullscreen", "fse", "dwm", "latency"]),
    T("win-005", "Disable Balloon Tip Notifications",
      "Turns off Explorer balloon tips and toasts.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "EnableBalloonTips", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "EnableBalloonTips", 1, "DWORD")],
      why="Pop-up notifications interrupt attention and can steal scheduler priority in the foreground.",
      changes="Disables balloon tips.",
      risk="safe", impact="low", recommended="recommended",
      tags=["notifications", "balloon", "tips"]),
    T("win-006", "Visual Effects: Best Performance",
      "Sets the system visual effects preset to 'best performance'.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects", "VisualFXSetting", 2, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects", "VisualFXSetting", 0, "DWORD")],
      why="Disables fading, animation and shadow effects that consume CPU during window transitions.",
      changes="Switches visual effects to the performance preset.",
      risk="safe", impact="moderate", recommended="recommended",
      tags=["visual", "effects", "animation", "performance"]),
    T("win-007", "Menu Show Delay 0",
      "Removes the delay before submenus open.",
      actions=[("reg", "HKCU", r"Control Panel\Desktop", "MenuShowDelay", 0, "STRING")],
      revert=[("reg", "HKCU", r"Control Panel\Desktop", "MenuShowDelay", 400, "STRING")],
      why="Instant submenu response reduces perceived and actual input-to-action delay.",
      changes="Sets the menu show delay to 0 ms.",
      risk="safe", impact="low", recommended="recommended",
      tags=["menu", "delay", "responsiveness"]),
    T("win-008", "Disable Transparency Effects",
      "Turns off acrylic/blur transparency in the UI.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "EnableTransparency", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "EnableTransparency", 1, "DWORD")],
      why="Live blur effects force constant redraws of the desktop compositor.",
      changes="Disables transparency effects.",
      risk="safe", impact="low", recommended="recommended",
      tags=["transparency", "blur", "acrylic", "dwm"]),
    T("win-009", "Disable Windows Tips and Suggestions",
      "Disables the Start/tips content delivered by Windows.",
      actions=[
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-338393Enabled", 0, "DWORD"),
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-353694Enabled", 0, "DWORD"),
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-353696Enabled", 0, "DWORD"),
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-310093Enabled", 0, "DWORD"),
      ],
      revert=[
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-338393Enabled", 1, "DWORD"),
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-353694Enabled", 1, "DWORD"),
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-353696Enabled", 1, "DWORD"),
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-310093Enabled", 1, "DWORD"),
      ],
      why="Removes attention-diverting popups while gaming.",
      changes="Disables content delivery subscriptions for tips.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["tips", "suggestions", "contentdelivery"]),
    T("win-010", "Disable Tailored Experiences",
      "Stops Windows from using diagnostics data to personalize tips and ads.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Privacy", "TailoredExperiencesWithDiagnosticDataEnabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Privacy", "TailoredExperiencesWithDiagnosticDataEnabled", 1, "DWORD")],
      why="Reduces background data collection chatter on the network stack.",
      changes="Disables tailored experiences.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["telemetry", "privacy", "tailored"]),
    T("win-011", "Disable Automatic Windows Update",
      "Turns off automatic Windows Update download/install.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU", "NoAutoUpdate", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU", "NoAutoUpdate")],
      why="Background update downloads consume bandwidth, disk IO and CPU during play sessions.",
      changes="Sets Windows Update to not install automatically.",
      risk="moderate", impact="moderate", recommended="optional", admin=True, confirm=True,
      tags=["update", "wu", "bandwidth"]),
    T("win-012", "Disable Web Search in Start",
      "Stops Start menu web search results.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Search", "ConnectedSearchUseWeb", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Search", "ConnectedSearchUseWeb", 1, "DWORD")],
      why="Avoids network round-trips on every Start menu query.",
      changes="Disables connected web search.",
      risk="safe", impact="low", recommended="recommended",
      tags=["search", "start", "web"]),
    T("win-013", "Disable Cortana",
      "Turns off Cortana via policy.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Windows Search", "AllowCortana", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Windows Search", "AllowCortana")],
      why="Cortana keeps an always-listening/background voice pipeline that consumes CPU.",
      changes="Disables Cortana.",
      risk="low", impact="low", recommended="recommended", admin=True,
      tags=["cortana", "voice", "assistant"]),
    T("win-014", "Disable Bing Search in Start",
      "Disables Bing results in Windows Search.",
      actions=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Search", "BingSearchEnabled", 0, "DWORD")],
      revert=[("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\Search", "BingSearchEnabled", 1, "DWORD")],
      why="Stops search indexing of web results that can wake the network adapter.",
      changes="Disables Bing in search.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["search", "bing", "web"]),
    T("win-015", "Legacy Windows 10 Context Menu",
      "Restores the classic full context menu in Windows 11.",
      actions=[("reg", "HKCR", r"CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32", "(default)", "", "STRING")],
      revert=[("regdel", "HKCR", r"CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32", "(default)")],
      why="The modern context menu hides common items behind a second click; the classic menu is faster to navigate.",
      changes="Restores the classic right-click menu.",
      risk="low", impact="low", recommended="recommended", win="11", admin=True,
      tags=["contextmenu", "explorer", "rightclick"]),
    T("win-017", "Disable First Sign-in Animation",
      "Skips the Windows welcome/first-sign-in animation.",
      actions=[
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "FirstLogonAnimationEnabled", 0, "DWORD"),
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SoftLandingEnabled", 0, "DWORD"),
      ],
      revert=[
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "FirstLogonAnimationEnabled", 1, "DWORD"),
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SoftLandingEnabled", 1, "DWORD"),
      ],
      why="Removes a resource-heavy onboarding animation on every sign-in.",
      changes="Disables first sign-in animation.",
      risk="safe", impact="low", recommended="recommended",
      tags=["signin", "animation", "welcome"]),
    T("win-018", "Disable Start Menu App Suggestions",
      "Removes promoted app suggestions from the Start menu.",
      actions=[
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SystemPaneSuggestionsEnabled", 0, "DWORD"),
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-314559Enabled", 0, "DWORD"),
      ],
      revert=[
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SystemPaneSuggestionsEnabled", 1, "DWORD"),
          ("reg", "HKCU", r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-314559Enabled", 1, "DWORD"),
      ],
      why="Removes ad-like tiles and their background refresh.",
      changes="Disables Start suggestions.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["start", "suggestions", "ads"]),
    T("win-019", "Disable Timeline",
      "Turns off Windows Timeline activity history tracking.",
      actions=[("reg", "HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\ActivityHistory", "PublishActivityHistory", 0, "DWORD")],
      revert=[("reg", "HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\ActivityHistory", "PublishActivityHistory", 1, "DWORD")],
      why="Timeline continuously records activity snapshots, consuming CPU and disk in the background.",
      changes="Disables activity history publishing.",
      risk="safe", impact="low", recommended="recommended",
      tags=["timeline", "activity", "history"]),

    T("win-021", "Disable Search Cloud",
      "Stops Windows Search from fetching cloud/web results.",
      actions=[("reg", "HKCU", r"SOFTWARE\Policies\Microsoft\Windows\Windows Search", "ConnectedSearchUseWeb", 0, "DWORD")],
      revert=[("reg", "HKCU", r"SOFTWARE\Policies\Microsoft\Windows\Windows Search", "ConnectedSearchUseWeb", 1, "DWORD")],
      why="Cloud search results require network round-trips that add latency and background bandwidth use.",
      changes="Disables cloud-connected search.",
      risk="safe", impact="low", recommended="recommended",
      tags=["search", "cloud", "web"]),
    T("win-022", "Disable Search Box Suggestions",
      "Turns off predictive suggestions in the Windows Search box.",
      actions=[("reg", "HKCU", r"SOFTWARE\Policies\Microsoft\Windows\Explorer", "DisableSearchBoxSuggestions", 1, "DWORD")],
      revert=[("reg", "HKCU", r"SOFTWARE\Policies\Microsoft\Windows\Explorer", "DisableSearchBoxSuggestions", 0, "DWORD")],
      why="Search box suggestions trigger background network and indexing activity on every keystroke.",
      changes="Disables search box suggestions.",
      risk="safe", impact="low", recommended="recommended",
      tags=["search", "suggestions", "index"]),
    T("win-023", "Disable News and Interests",
      "Turns off the News and Interests widget on the taskbar.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Feeds", "EnableFeeds", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Feeds", "EnableFeeds", 1, "DWORD")],
      why="The News and Interests widget polls and renders live content on the taskbar, consuming CPU and network.",
      changes="Disables the News and Interests feeds.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      tags=["news", "feeds", "taskbar"]),

])
