"""License database for the MAXIMUM TWEAKS license server.

SQLite by default, PostgreSQL (Neon) when ``DATABASE_URL`` is set.

* SQLite (no ``DATABASE_URL``): used for local development. Defaults to
  ``auth_backend/licenses.db`` (override with ``LICENSE_DB_PATH``).
* PostgreSQL (``DATABASE_URL`` set): used in production on Render/Neon so
  licenses survive restarts/redeploys without a persistent disk.

Both backends expose the same ``LicenseDB`` API; the licensing logic in
``main.py``/``keys.py`` is identical either way. The desktop app never touches
this store — it only ever talks to the HTTP API in ``main.py``.

All times are UTC in ``YYYY-MM-DD HH:MM:SS`` strings (same format the old
Discord backend used). ``expires_at`` is NULL for lifetime licenses.
"""
from __future__ import annotations

import atexit
import os
import sqlite3
import threading
from datetime import datetime, timezone
from pathlib import Path

try:
    import psycopg
    from psycopg.rows import dict_row
    from psycopg_pool import ConnectionPool
except ImportError:  # pragma: no cover - only needed when DATABASE_URL is set
    psycopg = None
    dict_row = None
    ConnectionPool = None

import logging
logger = logging.getLogger("maxtweaks.license.db")

DEFAULT_DB_PATH = Path(__file__).resolve().parent / "licenses.db"

SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS licenses (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    license_key      TEXT    NOT NULL UNIQUE,
    status           TEXT    NOT NULL DEFAULT 'unused',   -- unused|active|revoked|expired
    plan             TEXT    NOT NULL DEFAULT 'lifetime', -- lifetime|monthly|yearly|custom
    customer         TEXT    NOT NULL DEFAULT '',
    note             TEXT    NOT NULL DEFAULT '',
    created_at       TEXT    NOT NULL,
    expires_at       TEXT    DEFAULT NULL,                -- NULL = lifetime
    activated_at     TEXT    DEFAULT NULL,
    device_id        TEXT    DEFAULT NULL,                -- hashed device fingerprint
    activation_count INTEGER NOT NULL DEFAULT 0,
    last_validated   TEXT    DEFAULT NULL,
    revoked_at       TEXT    DEFAULT NULL,
    revoked_reason   TEXT    NOT NULL DEFAULT '',
    reset_count      INTEGER NOT NULL DEFAULT 0           -- support unbinds (PC change)
);
CREATE INDEX IF NOT EXISTS idx_licenses_status ON licenses(status);
"""

PG_SCHEMA = """
CREATE TABLE IF NOT EXISTS licenses (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_key      TEXT    NOT NULL UNIQUE,
    status           TEXT    NOT NULL DEFAULT 'unused',
    plan             TEXT    NOT NULL DEFAULT 'lifetime',
    customer         TEXT    NOT NULL DEFAULT '',
    note             TEXT    NOT NULL DEFAULT '',
    created_at       TEXT    NOT NULL,
    expires_at       TEXT    DEFAULT NULL,
    activated_at     TEXT    DEFAULT NULL,
    device_id        TEXT    DEFAULT NULL,
    activation_count INTEGER NOT NULL DEFAULT 0,
    last_validated   TEXT    DEFAULT NULL,
    revoked_at       TEXT    DEFAULT NULL,
    revoked_reason   TEXT    NOT NULL DEFAULT '',
    reset_count      INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_licenses_status ON licenses(status);
"""


def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")


def _parse_db_path() -> str:
    override = os.environ.get("LICENSE_DB_PATH", "").strip()
    if override:
        return override
    return str(DEFAULT_DB_PATH)


class _PooledConnection:
    """Proxy over a pooled psycopg connection: ``close()`` hands the
    connection back to the pool instead of truly closing it, so the rest of
    the code can keep the same connect/commit/close idiom as SQLite."""

    def __init__(self, pool: ConnectionPool, conn):
        self._pool = pool
        self._conn = conn

    def __getattr__(self, name):
        return getattr(self._conn, name)

    def close(self) -> None:
        self._pool.putconn(self._conn)

    def __enter__(self):
        return self

    def __exit__(self, *exc) -> None:
        self.close()


class LicenseDB:
    """Thread-safe license store: SQLite locally, PostgreSQL when DATABASE_URL
    is set. The public API is identical for both backends."""

    _pool: "ConnectionPool | None" = None
    _pool_lock = threading.Lock()

    def __init__(self, path: str | None = None):
        self._dsn = os.environ.get("DATABASE_URL", "").strip() or None
        self._engine = "postgres" if self._dsn else "sqlite"
        self._path = path or _parse_db_path()
        if self._engine == "sqlite":
            os.makedirs(os.path.dirname(self._path) or ".", exist_ok=True)
        self._lock = threading.RLock()
        with self._lock:
            conn = self._connect()
            try:
                self._init_schema(conn)
                conn.commit()
            finally:
                conn.close()

    @property
    def engine(self) -> str:
        """'postgres' when DATABASE_URL is set, else 'sqlite'."""
        return self._engine

    def _connect(self):
        if self._engine == "postgres":
            if psycopg is None:  # pragma: no cover
                raise RuntimeError(
                    "DATABASE_URL is set but psycopg is not installed - "
                    "run: pip install -r requirements.txt")
            pool = type(self)._pool
            if pool is None:
                # Serverless (Neon) pays a multi-second cold start per new
                # connection, so keep a small warm pool instead of dialing a
                # fresh connection on every DB op.
                with type(self)._pool_lock:
                    pool = type(self)._pool
                    if pool is None:
                        pool = ConnectionPool(
                            self._dsn,
                            min_size=1,
                            max_size=4,
                            open=False,
                            kwargs={"connect_timeout": 30,
                                    "row_factory": dict_row},
                        )
                        pool.open()
                        type(self)._pool = pool
            # Borrow a connection; close() hands it back to the pool.
            return _PooledConnection(pool, pool.getconn(timeout=30))
        conn = sqlite3.connect(self._path, timeout=30)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA busy_timeout = 30000")
        return conn

    def _init_schema(self, conn) -> None:
        if self._engine == "postgres":
            for stmt in PG_SCHEMA.split(";"):
                stmt = stmt.strip()
                if stmt:
                    conn.execute(stmt)
        else:
            conn.executescript(SQLITE_SCHEMA)

    def _sql(self, q: str) -> str:
        """Rewrite SQLite '?' placeholders to psycopg '%s' for Postgres."""
        if self._engine == "postgres":
            return q.replace("?", "%s")
        return q

    @staticmethod
    def _is_stale_conn(exc) -> bool:
        """True when the error indicates a dead/purged pooled connection."""
        msg = str(exc).lower()
        return any(s in msg for s in (
            "adminshutdown", "server closed", "connection attempt failed",
            "connection already closed", "could not connect",
        ))

    def _exec(self, conn, sql: str, params=()):
        """Run one statement with engine-appropriate placeholders."""
        if params:
            return conn.execute(self._sql(sql), params)
        return conn.execute(self._sql(sql))

    def _run_with_retry(self, fn, *, commit: bool = True):
        """Execute *fn(conn)* with a fresh connection; retry once on stale-pool errors."""
        for attempt in range(2):
            conn = self._connect()
            try:
                result = fn(conn)
                if commit:
                    conn.commit()
                return result
            except Exception as exc:
                try:
                    conn.close()
                except Exception:  # noqa: BLE001
                    pass
                if attempt == 0 and self._is_stale_conn(exc):
                    logger.warning("db: stale Neon connection, retrying (attempt %d)", attempt + 1)
                    continue
                raise
            else:
                try:
                    conn.close()
                except Exception:  # noqa: BLE001
                    pass

    # ------------------------------------------------------------------
    # Row helpers
    # ------------------------------------------------------------------

    def _row_to_dict(self, row) -> dict | None:
        if row is None:
            return None
        return {key: row[key] for key in row.keys()}

    def get(self, license_key: str) -> dict | None:
        def _fn(conn):
            row = self._exec(
                conn, "SELECT * FROM licenses WHERE license_key = ?",
                (license_key,)).fetchone()
            return self._row_to_dict(row)
        with self._lock:
            return self._run_with_retry(_fn, commit=False)

    # ------------------------------------------------------------------
    # Writes (admin + activation flow)
    # ------------------------------------------------------------------

    def create(self, license_key: str, plan: str = "lifetime",
               customer: str = "", note: str = "",
               expires_at: str | None = None) -> dict:
        def _fn(conn):
            self._exec(
                conn,
                "INSERT INTO licenses (license_key, status, plan, customer,"
                " note, created_at, expires_at) VALUES (?, 'unused', ?, ?, ?, ?, ?)",
                (license_key, plan, customer, note, _utc_now(), expires_at))
        with self._lock:
            self._run_with_retry(_fn)
        rec = self.get(license_key)
        if rec is None:  # pragma: no cover
            raise RuntimeError("license record was not created")
        return rec

    def activate(self, license_key: str, device_id: str) -> dict:
        """Bind an unused license to a device and mark it active."""
        now = _utc_now()
        def _fn(conn):
            self._exec(
                conn,
                "UPDATE licenses SET status = 'active', device_id = ?,"
                " activated_at = COALESCE(activated_at, ?),"
                " activation_count = activation_count + 1,"
                " last_validated = ?, revoked_at = NULL,"
                " revoked_reason = '' WHERE license_key = ?",
                (device_id, now, now, license_key))
        with self._lock:
            self._run_with_retry(_fn)
        return self.get(license_key)

    def touch_validation(self, license_key: str) -> None:
        def _fn(conn):
            self._exec(
                conn,
                "UPDATE licenses SET last_validated = ? WHERE license_key = ?",
                (_utc_now(), license_key))
        with self._lock:
            self._run_with_retry(_fn)

    def mark_expired(self, license_key: str) -> None:
        def _fn(conn):
            self._exec(
                conn,
                "UPDATE licenses SET status = 'expired' WHERE license_key = ?",
                (license_key,))
        with self._lock:
            self._run_with_retry(_fn)

    def revoke(self, license_key: str, reason: str = "") -> dict | None:
        def _fn(conn):
            self._exec(
                conn,
                "UPDATE licenses SET status = 'revoked', revoked_at = ?,"
                " revoked_reason = ? WHERE license_key = ?",
                (_utc_now(), reason, license_key))
        with self._lock:
            self._run_with_retry(_fn)
        return self.get(license_key)

    def unrevoke(self, license_key: str) -> dict | None:
        def _fn(conn):
            self._exec(
                conn,
                "UPDATE licenses SET status = 'active', revoked_at = NULL,"
                " revoked_reason = '' WHERE license_key = ?",
                (license_key,))
        with self._lock:
            self._run_with_retry(_fn)
        return self.get(license_key)

    def unbind(self, license_key: str) -> dict | None:
        """Support action for a PC change: unbind the device and free the key."""
        def _fn(conn):
            self._exec(
                conn,
                "UPDATE licenses SET status = 'unused', device_id = NULL,"
                " activated_at = NULL, reset_count = reset_count + 1,"
                " revoked_at = NULL, revoked_reason = '' WHERE license_key = ?",
                (license_key,))
        with self._lock:
            self._run_with_retry(_fn)
        return self.get(license_key)

    def list_all(self, status: str | None = None) -> list[dict]:
        def _fn(conn):
            if status:
                rows = self._exec(
                    conn,
                    "SELECT * FROM licenses WHERE status = ?"
                    " ORDER BY created_at DESC", (status,)).fetchall()
            else:
                rows = self._exec(
                    conn,
                    "SELECT * FROM licenses ORDER BY created_at DESC").fetchall()
            return [self._row_to_dict(r) for r in rows]
        with self._lock:
            return self._run_with_retry(_fn, commit=False)

    def search(self, q: str) -> list[dict]:
        """Admin search across license key / customer / note (substring)."""
        def _fn(conn):
            like = f"%{q}%"
            rows = self._exec(
                conn,
                "SELECT * FROM licenses WHERE license_key LIKE ?"
                " OR customer LIKE ? OR note LIKE ?"
                " ORDER BY created_at DESC",
                (like, like, like)).fetchall()
            return [self._row_to_dict(r) for r in rows]
        with self._lock:
            return self._run_with_retry(_fn, commit=False)

    def stats(self) -> dict:
        def _fn(conn):
            rows = self._exec(
                conn,
                "SELECT status, COUNT(*) AS n FROM licenses GROUP BY status").fetchall()
            total = self._exec(
                conn,
                "SELECT COUNT(*) AS n FROM licenses").fetchone()["n"]
            return {"total": total, "by_status": {r["status"]: r["n"] for r in rows}}
        with self._lock:
            return self._run_with_retry(_fn, commit=False)


def _close_pool() -> None:
    """Close the shared Postgres pool at interpreter exit so tests and the
    server don't leave serverless connections dangling."""
    pool = LicenseDB._pool
    if pool is not None:
        pool.close()


atexit.register(_close_pool)
