"""Generated audit classification for every tweak (do not edit by hand).
Regenerate with _dev/audit_gen.py."""

OVERRIDES = {
    'adv-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'adv-002': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'adv-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'adv-004': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'adv-005': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'adv-006': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'adv-007': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID'},
    'adv-008': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'adv-009': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID'},
    'adv-010': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'adv-011': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'adv-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'aim-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'aim-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'aim-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'aim-004': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID'},
    'aim-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'aim-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'amd-001': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'amd-002': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'amd-003': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'amd-004': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'amd-005': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'amd-006': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'amd-007': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'amd-008': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'amd-009': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'amd-010': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'amd-011': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'amd-012': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'amd-013': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'amd-014': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'audio-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'AUDIO'},
    'audio-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'AUDIO'},
    'audio-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'AUDIO'},
    'audio-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'AUDIO'},
    'audio-005': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'AUDIO'},
    'audio-006': {'status': 'VALID', 'target': 'AUDIO', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'audio-007': {'status': 'VALID', 'target': 'AUDIO', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'audio-008': {'status': 'VALID', 'target': 'AUDIO', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'audio-009': {'status': 'VALID', 'target': 'AUDIO', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'audio-010': {'status': 'VALID', 'target': 'AUDIO', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'audio-011': {'status': 'VALID', 'target': 'AUDIO', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'audio-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'AUDIO'},
    'bg-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STARTUP'},
    'bg-002': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'STARTUP'},
    'bg-003': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bg-004': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bg-005': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bg-006': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bg-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STARTUP'},
    'bg-008': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bg-009': {'status': 'OUTDATED', 'target': 'STARTUP'},
    'bg-010': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bios-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'bios-002': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bios-003': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bios-004': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bios-005': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bios-006': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bios-007': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bios-008': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bios-009': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bios-010': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bios-011': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bios-012': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'cpu-001': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'CPU'},
    'cpu-002': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'CPU'},
    'cpu-003': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'CPU'},
    'cpu-004': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'CPU'},
    'cpu-005': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'CPU'},
    'cpu-006': {'status': 'HARDWARE-SPECIFIC', 'target': 'CPU'},
    'cpu-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'CPU'},
    'cpu-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'CPU'},
    'cpu-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'CPU'},
    'cpu-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'CPU'},
    'cpu-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'CPU'},
    'cpu-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'CPU'},
    'cpu-013': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'CPU'},
    'cpu-014': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'CPU'},
    'cpu-015': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'CPU'},
    'cpu-016': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'CPU'},
    'cpu-017': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'CPU'},
    'cpu-018': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'CPU'},
    'cpu-020': {'status': 'INVALID', 'evidence': 'LOW', 'verdict': 'REMOVE',
                'note': 'no-op: apply and revert both set processor_max to 100'},
    'cpu-023': {'status': 'INVALID', 'evidence': 'LOW', 'verdict': 'REMOVE',
                'note': 'no-op: apply and revert both set boost_policy to 100'},
    'db-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-010': {'status': 'OUTDATED'},
    'db-011': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'db-012': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'db-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'diag-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-013': {'status': 'VALID', 'target': 'DIAGNOSTICS', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'diag-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'disp-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'disp-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'disp-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'disp-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'disp-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'disp-006': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'disp-007': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'disp-008': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'disp-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'disp-010': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'disp-011': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'disp-012': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'dx-002': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'dx-004': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx-005': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx-006': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx-007': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx-008': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx-009': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx-010': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx12-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'dx12-002': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx12-003': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx12-004': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx12-005': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx12-006': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx12-007': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx12-008': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx12-009': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx12-010': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'eth-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'exp-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'exp-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'exp-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'exp-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'exp-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'exp-006': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'exp-007': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'exp-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'exp-009': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'exp-010': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'expl-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-004': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'expl-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-008': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'expl-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'fn-001': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fn-002': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fn-003': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fn-004': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fn-005': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fn-006': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fn-007': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fn-008': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fn-009': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fn-010': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fn-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-015': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-016': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-017': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-018': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-019': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-020': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-021': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-022': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-023': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-024': {'status': 'HARDWARE-SPECIFIC', 'target': 'GAME'},
    'fn-025': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-026': {'status': 'HARDWARE-SPECIFIC', 'target': 'GAME'},
    'fn-027': {'status': 'HARDWARE-SPECIFIC', 'target': 'GAME'},
    'fn-028': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-029': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-030': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-031': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-032': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-033': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-034': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-035': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-036': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-037': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-038': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-039': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fps-001': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fps-002': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fps-003': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fps-004': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fps-005': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fps-006': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fps-007': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fps-008': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fps-009': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fps-010': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fps-011': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'fps-012': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ft-001': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ft-002': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ft-003': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ft-004': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ft-005': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ft-006': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ft-007': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ft-008': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ft-009': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ft-010': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ft-011': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ft-012': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'game-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'game-002': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'GAME'},
    'game-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'game-004': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'game-005': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'game-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'game-007': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'game-008': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'game-009': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'game-010': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'game-011': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'game-012': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'game-013': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'game-014': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'game-015': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'game-016': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gp-001': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gp-002': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gp-003': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gp-004': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gp-005': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gp-006': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gp-007': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gp-008': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gp-009': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gp-010': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gp-011': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gp-012': {'status': 'VALID', 'target': 'GAME', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gpu-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GPU'},
    'gpu-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GPU'},
    'gpu-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GPU'},
    'gpu-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GPU'},
    'gpu-005': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gpu-006': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gpu-007': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gpu-008': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gpu-009': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gpu-010': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gpu-011': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gpu-012': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gpu-013': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gpu-014': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gpu-015': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'gpu-016': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'il-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'il-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'il-003': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'INPUT'},
    'il-004': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'INPUT'},
    'il-005': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'il-006': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'il-007': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'il-008': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'il-009': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'INPUT'},
    'il-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'il-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'il-012': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'int-001': {'status': 'VALID', 'target': 'CPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'int-002': {'status': 'VALID', 'target': 'CPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'int-003': {'status': 'VALID', 'target': 'CPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'int-004': {'status': 'VALID', 'target': 'CPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'int-005': {'status': 'VALID', 'target': 'CPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'int-006': {'status': 'VALID', 'target': 'CPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'int-007': {'status': 'VALID', 'target': 'CPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'int-008': {'status': 'VALID', 'target': 'CPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'int-009': {'status': 'VALID', 'target': 'CPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'int-010': {'status': 'VALID', 'target': 'CPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'int-011': {'status': 'VALID', 'target': 'CPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'int-012': {'status': 'VALID', 'target': 'CPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'kbd-001': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'INPUT'},
    'kbd-002': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'INPUT'},
    'kbd-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'kbd-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'kbd-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'kbd-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'kbd-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'kbd-008': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'kbd-009': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'kbd-010': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'kbd-011': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'kbd-012': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'mon-001': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'DISPLAY'},
    'mon-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'mon-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'mon-004': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'mon-005': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'mon-006': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'DISPLAY'},
    'mon-007': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'mon-008': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'mon-009': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'mon-010': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'mon-011': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'mon-012': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'mon-013': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'mon-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'mouse-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'mouse-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'mouse-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'mouse-004': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'INPUT'},
    'mouse-005': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'mouse-006': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'mouse-007': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'mouse-008': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'mouse-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'mouse-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'mouse-011': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'mouse-012': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'net-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-007': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'NETWORK'},
    'net-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-009': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'NETWORK'},
    'net-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-012': {'status': 'VALID', 'target': 'NETWORK', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'net-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-015': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-016': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'nv-001': {'status': 'HARDWARE-SPECIFIC', 'target': 'GPU'},
    'nv-002': {'status': 'HARDWARE-SPECIFIC', 'target': 'GPU'},
    'nv-003': {'status': 'HARDWARE-SPECIFIC', 'target': 'GPU'},
    'nv-004': {'status': 'HARDWARE-SPECIFIC', 'target': 'GPU'},
    'nv-005': {'status': 'HARDWARE-SPECIFIC', 'target': 'GPU'},
    'nv-006': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'nv-007': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'nv-008': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'nv-009': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'nv-010': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'nv-011': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'nv-012': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'nv-013': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'nv-014': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'nv-015': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'nv-016': {'status': 'VALID', 'target': 'GPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'power-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-008': {'status': 'VALID', 'target': 'POWER', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'power-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-012': {'status': 'VALID', 'target': 'POWER', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'power-013': {'status': 'VALID', 'target': 'POWER', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'power-014': {'status': 'VALID', 'target': 'POWER', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'pp-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'pp-002': {'status': 'VALID', 'target': 'POWER', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'pp-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'pp-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'pp-005': {'status': 'VALID', 'target': 'POWER', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'pp-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'pp-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'pp-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'pp-009': {'status': 'VALID', 'target': 'POWER', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'pp-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'pp-011': {'status': 'VALID', 'target': 'POWER', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'pp-012': {'status': 'VALID', 'target': 'POWER', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'pre-001': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'pre-002': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'pre-003': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'pre-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'pre-005': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'pre-006': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'pre-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'pre-008': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'pre-009': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'priv-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'ram-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'RAM'},
    'ram-002': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'RAM'},
    'ram-003': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'RAM'},
    'ram-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'RAM'},
    'ram-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'RAM'},
    'ram-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'RAM'},
    'ram-007': {'status': 'VALID', 'target': 'RAM', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ram-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'RAM'},
    'ram-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'RAM'},
    'ram-010': {'status': 'VALID', 'target': 'RAM', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ram-011': {'status': 'VALID', 'target': 'RAM', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ram-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'RAM'},
    'ram-013': {'status': 'VALID', 'target': 'RAM', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ram-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'RAM'},
    'ram-015': {'status': 'VALID', 'target': 'RAM', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'ram-016': {'status': 'VALID', 'target': 'RAM', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'reg-001': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'reg-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-004': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'reg-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-006': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'reg-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-012': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'reg-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-015': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-016': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'rep-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-005': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'rep-006': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'rep-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-010': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'rep-011': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'rep-012': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'rep-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sched-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'SERVICES'},
    'sched-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'SERVICES'},
    'sched-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'SERVICES'},
    'sched-004': {'status': 'VALID', 'target': 'SERVICES', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'sched-005': {'status': 'VALID', 'target': 'SERVICES', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'sched-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'SERVICES'},
    'sched-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'SERVICES'},
    'sched-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'SERVICES'},
    'sched-009': {'status': 'VALID', 'target': 'SERVICES', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'sched-010': {'status': 'VALID', 'target': 'SERVICES', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'sched-011': {'status': 'VALID', 'target': 'SERVICES', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'sched-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'SERVICES'},
    'sec-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sec-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sec-003': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'sec-004': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'sec-005': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'sec-006': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'sec-007': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'sec-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sec-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sec-010': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'sec-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sec-012': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'start-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STARTUP'},
    'start-002': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'start-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STARTUP'},
    'start-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STARTUP'},
    'start-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STARTUP'},
    'start-006': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'start-007': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'start-008': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'start-009': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'start-010': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'start-011': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'start-012': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'start-013': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'start-014': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'stor-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STORAGE'},
    'stor-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STORAGE'},
    'stor-003': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'STORAGE'},
    'stor-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STORAGE'},
    'stor-005': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'STORAGE'},
    'stor-006': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'STORAGE'},
    'stor-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STORAGE'},
    'stor-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STORAGE'},
    'stor-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STORAGE'},
    'stor-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STORAGE'},
    'stor-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STORAGE'},
    'stor-012': {'status': 'VALID', 'target': 'STORAGE', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'stor-013': {'status': 'VALID', 'target': 'STORAGE', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'stor-014': {'status': 'VALID', 'target': 'STORAGE', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'svc-001': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-002': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-003': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-004': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-005': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-006': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-007': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-008': {'status': 'VALID', 'target': 'SERVICES', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'svc-009': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-010': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-011': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-012': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-013': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-014': {'status': 'VALID', 'target': 'SERVICES', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'svc-015': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-016': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'sys-001': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'sys-002': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'sys-003': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'sys-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-007': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'sys-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-011': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'sys-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-013': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'sys-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-015': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'sys-016': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-017': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-018': {'status': 'INVALID', 'verdict': 'REMOVE', 'evidence': 'LOW',
                'note': 'disables Spectre/Meltdown mitigations - serious security risk, not recommended'},
    'sys-019': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'tel-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'tel-002': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'TELEMETRY'},
    'tel-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'tel-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'tel-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'tel-006': {'status': 'OUTDATED', 'target': 'TELEMETRY'},
    'tel-007': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'TELEMETRY'},
    'tel-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'tel-009': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'TELEMETRY'},
    'tel-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'tel-011': {'status': 'VALID', 'target': 'TELEMETRY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'tel-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'tel-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'tel-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'tools-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'usb-001': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'INPUT'},
    'usb-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'usb-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'usb-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'usb-005': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'usb-006': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'usb-007': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'usb-008': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'usb-009': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'usb-010': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'usb-011': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'usb-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'wgr-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'wgr-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'wgr-003': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wgr-004': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wgr-005': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wgr-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'wgr-007': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wgr-008': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wgr-009': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wgr-010': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wgr-011': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wgr-012': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wifi-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'wifi-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'wifi-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'wifi-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'wifi-005': {'status': 'VALID', 'target': 'NETWORK', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wifi-006': {'status': 'VALID', 'target': 'NETWORK', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wifi-007': {'status': 'VALID', 'target': 'NETWORK', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wifi-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'wifi-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'wifi-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'wifi-011': {'status': 'VALID', 'target': 'NETWORK', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wifi-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'wifi-013': {'status': 'VALID', 'target': 'NETWORK', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wifi-014': {'status': 'VALID', 'target': 'NETWORK', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'win-001': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'win-002': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'win-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'win-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'win-005': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'win-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'win-007': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'win-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'win-009': {'status': 'OUTDATED'},
    'win-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'win-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'win-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'win-013': {'status': 'OUTDATED'},
    'win-014': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'win-015': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'win-016': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'win-017': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'win-018': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
}

NOTES = {
    'adv-001': 'obscure registry write - evidence low',
    'adv-002': 'registry target is a known Windows key',
    'adv-003': 'obscure registry write - evidence low',
    'adv-004': 'informational guidance entry',
    'adv-005': 'informational guidance entry',
    'adv-006': 'registry target is a known Windows key',
    'adv-007': 'verifiable via live system state',
    'adv-008': 'informational guidance entry',
    'adv-009': 'verifiable via live system state',
    'adv-010': 'informational guidance entry',
    'adv-011': 'informational guidance entry',
    'adv-012': 'obscure registry write - evidence low',
    'aim-001': 'obscure registry write - evidence low',
    'aim-002': 'obscure registry write - evidence low',
    'aim-003': 'obscure registry write - evidence low',
    'aim-004': 'verifiable via live system state',
    'aim-005': 'obscure registry write - evidence low',
    'aim-006': 'obscure registry write - evidence low',
    'amd-001': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'amd-002': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'amd-003': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'amd-004': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'amd-005': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'amd-006': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'amd-007': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'amd-008': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'amd-009': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'amd-010': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'amd-011': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'amd-012': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'amd-013': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'amd-014': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'audio-001': 'obscure registry write - evidence low',
    'audio-002': 'obscure registry write - evidence low',
    'audio-003': 'obscure registry write - evidence low',
    'audio-004': 'obscure registry write - evidence low',
    'audio-005': 'verifiable via live system state',
    'audio-006': 'informational guidance entry',
    'audio-007': 'informational guidance entry',
    'audio-008': 'informational guidance entry',
    'audio-009': 'informational guidance entry',
    'audio-010': 'informational guidance entry',
    'audio-011': 'informational guidance entry',
    'audio-012': 'obscure registry write - evidence low',
    'bg-001': 'obscure registry write - evidence low',
    'bg-002': 'verifiable via live system state',
    'bg-003': 'informational guidance entry',
    'bg-004': 'informational guidance entry',
    'bg-005': 'informational guidance entry',
    'bg-006': 'informational guidance entry',
    'bg-007': 'obscure registry write - evidence low',
    'bg-008': 'informational guidance entry',
    'bg-009': "targets dead Win10-era feature: 'tips and suggestions'",
    'bg-010': 'informational guidance entry',
    'bios-001': 'obscure registry write - evidence low',
    'bios-002': 'informational guidance entry',
    'bios-003': 'informational guidance entry',
    'bios-004': 'informational guidance entry',
    'bios-005': 'informational guidance entry',
    'bios-006': 'informational guidance entry',
    'bios-007': 'informational guidance entry',
    'bios-008': 'informational guidance entry',
    'bios-009': 'informational guidance entry',
    'bios-010': 'informational guidance entry',
    'bios-011': 'informational guidance entry',
    'bios-012': 'informational guidance entry',
    'cpu-001': 'verifiable via live system state',
    'cpu-002': 'verifiable via live system state',
    'cpu-003': 'verifiable via live system state',
    'cpu-004': 'verifiable via live system state',
    'cpu-005': 'verifiable via live system state',
    'cpu-006': 'applies only to specific GPU/CPU vendor',
    'cpu-007': 'obscure registry write - evidence low',
    'cpu-008': 'obscure registry write - evidence low',
    'cpu-009': 'obscure registry write - evidence low',
    'cpu-010': 'obscure registry write - evidence low',
    'cpu-011': 'obscure registry write - evidence low',
    'cpu-012': 'obscure registry write - evidence low',
    'cpu-013': 'registry target is a known Windows key',
    'cpu-014': 'verifiable via live system state',
    'cpu-015': 'verifiable via live system state',
    'cpu-016': 'registry target is a known Windows key',
    'cpu-017': 'registry target is a known Windows key',
    'cpu-018': 'obscure registry write - evidence low',
    'cpu-020': 'no-op: apply equals revert, cannot be undone',
    'cpu-023': 'no-op: apply equals revert, cannot be undone',
    'db-001': 'obscure registry write - evidence low',
    'db-002': 'obscure registry write - evidence low',
    'db-003': 'obscure registry write - evidence low',
    'db-004': 'obscure registry write - evidence low',
    'db-005': 'obscure registry write - evidence low',
    'db-006': 'obscure registry write - evidence low',
    'db-007': 'obscure registry write - evidence low',
    'db-008': 'obscure registry write - evidence low',
    'db-009': 'obscure registry write - evidence low',
    'db-010': "targets dead Win10-era feature: 'tips and suggestions'",
    'db-011': 'registry target is a known Windows key',
    'db-012': 'informational guidance entry',
    'db-013': 'obscure registry write - evidence low',
    'db-014': 'obscure registry write - evidence low',
    'diag-001': 'obscure registry write - evidence low',
    'diag-002': 'obscure registry write - evidence low',
    'diag-003': 'obscure registry write - evidence low',
    'diag-004': 'obscure registry write - evidence low',
    'diag-005': 'obscure registry write - evidence low',
    'diag-006': 'obscure registry write - evidence low',
    'diag-007': 'obscure registry write - evidence low',
    'diag-008': 'obscure registry write - evidence low',
    'diag-009': 'obscure registry write - evidence low',
    'diag-010': 'obscure registry write - evidence low',
    'diag-011': 'obscure registry write - evidence low',
    'diag-012': 'obscure registry write - evidence low',
    'diag-013': 'informational guidance entry',
    'diag-014': 'obscure registry write - evidence low',
    'disp-001': 'obscure registry write - evidence low',
    'disp-002': 'obscure registry write - evidence low',
    'disp-003': 'obscure registry write - evidence low',
    'disp-004': 'obscure registry write - evidence low',
    'disp-005': 'obscure registry write - evidence low',
    'disp-006': 'informational guidance entry',
    'disp-007': 'informational guidance entry',
    'disp-008': 'informational guidance entry',
    'disp-009': 'obscure registry write - evidence low',
    'disp-010': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'disp-011': 'informational guidance entry',
    'disp-012': 'informational guidance entry',
    'dx-001': 'obscure registry write - evidence low',
    'dx-002': 'informational guidance entry',
    'dx-003': 'obscure registry write - evidence low',
    'dx-004': 'informational guidance entry',
    'dx-005': 'informational guidance entry',
    'dx-006': 'informational guidance entry',
    'dx-007': 'informational guidance entry',
    'dx-008': 'informational guidance entry',
    'dx-009': 'informational guidance entry',
    'dx-010': 'informational guidance entry',
    'dx12-001': 'obscure registry write - evidence low',
    'dx12-002': 'informational guidance entry',
    'dx12-003': 'informational guidance entry',
    'dx12-004': 'informational guidance entry',
    'dx12-005': 'informational guidance entry',
    'dx12-006': 'informational guidance entry',
    'dx12-007': 'informational guidance entry',
    'dx12-008': 'informational guidance entry',
    'dx12-009': 'informational guidance entry',
    'dx12-010': 'informational guidance entry',
    'eth-001': 'obscure registry write - evidence low',
    'eth-002': 'obscure registry write - evidence low',
    'eth-003': 'obscure registry write - evidence low',
    'eth-004': 'obscure registry write - evidence low',
    'eth-005': 'obscure registry write - evidence low',
    'eth-006': 'obscure registry write - evidence low',
    'eth-007': 'obscure registry write - evidence low',
    'eth-008': 'obscure registry write - evidence low',
    'eth-009': 'obscure registry write - evidence low',
    'eth-010': 'obscure registry write - evidence low',
    'eth-011': 'obscure registry write - evidence low',
    'eth-012': 'obscure registry write - evidence low',
    'eth-013': 'obscure registry write - evidence low',
    'eth-014': 'obscure registry write - evidence low',
    'exp-001': 'obscure registry write - evidence low',
    'exp-002': 'obscure registry write - evidence low',
    'exp-003': 'obscure registry write - evidence low',
    'exp-004': 'obscure registry write - evidence low',
    'exp-005': 'obscure registry write - evidence low',
    'exp-006': 'informational guidance entry',
    'exp-007': 'informational guidance entry',
    'exp-008': 'obscure registry write - evidence low',
    'exp-009': 'informational guidance entry',
    'exp-010': 'informational guidance entry',
    'expl-001': 'obscure registry write - evidence low',
    'expl-002': 'obscure registry write - evidence low',
    'expl-003': 'obscure registry write - evidence low',
    'expl-004': 'registry target is a known Windows key',
    'expl-005': 'obscure registry write - evidence low',
    'expl-006': 'obscure registry write - evidence low',
    'expl-007': 'obscure registry write - evidence low',
    'expl-008': 'registry target is a known Windows key',
    'expl-009': 'obscure registry write - evidence low',
    'expl-010': 'obscure registry write - evidence low',
    'expl-011': 'obscure registry write - evidence low',
    'expl-012': 'obscure registry write - evidence low',
    'expl-013': 'obscure registry write - evidence low',
    'expl-014': 'obscure registry write - evidence low',
    'fn-001': 'informational guidance entry',
    'fn-002': 'informational guidance entry',
    'fn-003': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'fn-004': 'informational guidance entry',
    'fn-005': 'informational guidance entry',
    'fn-006': 'informational guidance entry',
    'fn-007': 'informational guidance entry',
    'fn-008': 'informational guidance entry',
    'fn-009': 'informational guidance entry',
    'fn-010': 'informational guidance entry',
    'fn-011': 'obscure registry write - evidence low',
    'fn-012': 'obscure registry write - evidence low',
    'fn-013': 'obscure registry write - evidence low',
    'fn-014': 'obscure registry write - evidence low',
    'fn-015': 'obscure registry write - evidence low',
    'fn-016': 'obscure registry write - evidence low',
    'fn-017': 'obscure registry write - evidence low',
    'fn-018': 'obscure registry write - evidence low',
    'fn-019': 'obscure registry write - evidence low',
    'fn-020': 'obscure registry write - evidence low',
    'fn-021': 'obscure registry write - evidence low',
    'fn-022': 'obscure registry write - evidence low',
    'fn-023': 'obscure registry write - evidence low',
    'fn-024': 'applies only to specific GPU/CPU vendor',
    'fn-025': 'obscure registry write - evidence low',
    'fn-026': 'applies only to specific GPU/CPU vendor',
    'fn-027': 'applies only to specific GPU/CPU vendor',
    'fn-028': 'obscure registry write - evidence low',
    'fn-029': 'obscure registry write - evidence low',
    'fn-030': 'obscure registry write - evidence low',
    'fn-031': 'obscure registry write - evidence low',
    'fn-032': 'obscure registry write - evidence low',
    'fn-033': 'obscure registry write - evidence low',
    'fn-034': 'obscure registry write - evidence low',
    'fn-035': 'obscure registry write - evidence low',
    'fn-036': 'obscure registry write - evidence low',
    'fn-037': 'obscure registry write - evidence low',
    'fn-038': 'obscure registry write - evidence low',
    'fn-039': 'obscure registry write - evidence low',
    'fps-001': 'informational guidance entry',
    'fps-002': 'informational guidance entry',
    'fps-003': 'informational guidance entry',
    'fps-004': 'informational guidance entry',
    'fps-005': 'informational guidance entry',
    'fps-006': 'informational guidance entry',
    'fps-007': 'informational guidance entry',
    'fps-008': 'informational guidance entry',
    'fps-009': 'informational guidance entry',
    'fps-010': 'informational guidance entry',
    'fps-011': 'informational guidance entry',
    'fps-012': 'informational guidance entry',
    'ft-001': 'informational guidance entry',
    'ft-002': 'informational guidance entry',
    'ft-003': 'informational guidance entry',
    'ft-004': 'informational guidance entry',
    'ft-005': 'informational guidance entry',
    'ft-006': 'informational guidance entry',
    'ft-007': 'informational guidance entry',
    'ft-008': 'informational guidance entry',
    'ft-009': 'informational guidance entry',
    'ft-010': 'informational guidance entry',
    'ft-011': 'informational guidance entry',
    'ft-012': 'informational guidance entry',
    'game-001': 'obscure registry write - evidence low',
    'game-002': 'registry target is a known Windows key',
    'game-003': 'obscure registry write - evidence low',
    'game-004': 'informational guidance entry',
    'game-005': 'informational guidance entry',
    'game-006': 'obscure registry write - evidence low',
    'game-007': 'informational guidance entry',
    'game-008': 'informational guidance entry',
    'game-009': 'informational guidance entry',
    'game-010': 'informational guidance entry',
    'game-011': 'informational guidance entry',
    'game-012': 'informational guidance entry',
    'game-013': 'informational guidance entry',
    'game-014': 'informational guidance entry',
    'game-015': 'informational guidance entry',
    'game-016': 'informational guidance entry',
    'gp-001': 'informational guidance entry',
    'gp-002': 'informational guidance entry',
    'gp-003': 'informational guidance entry',
    'gp-004': 'informational guidance entry',
    'gp-005': 'informational guidance entry',
    'gp-006': 'informational guidance entry',
    'gp-007': 'informational guidance entry',
    'gp-008': 'informational guidance entry',
    'gp-009': 'informational guidance entry',
    'gp-010': 'informational guidance entry',
    'gp-011': 'informational guidance entry',
    'gp-012': 'informational guidance entry',
    'gpu-001': 'obscure registry write - evidence low',
    'gpu-002': 'obscure registry write - evidence low',
    'gpu-003': 'obscure registry write - evidence low',
    'gpu-004': 'obscure registry write - evidence low',
    'gpu-005': 'informational guidance entry',
    'gpu-006': 'informational guidance entry',
    'gpu-007': 'informational guidance entry',
    'gpu-008': 'informational guidance entry',
    'gpu-009': 'informational guidance entry',
    'gpu-010': 'informational guidance entry',
    'gpu-011': 'informational guidance entry',
    'gpu-012': 'informational guidance entry',
    'gpu-013': 'informational guidance entry',
    'gpu-014': 'informational guidance entry',
    'gpu-015': 'informational guidance entry',
    'gpu-016': 'informational guidance entry',
    'il-001': 'obscure registry write - evidence low',
    'il-002': 'obscure registry write - evidence low',
    'il-003': 'registry target is a known Windows key',
    'il-004': 'registry target is a known Windows key',
    'il-005': 'informational guidance entry',
    'il-006': 'informational guidance entry',
    'il-007': 'informational guidance entry',
    'il-008': 'informational guidance entry',
    'il-009': 'registry target is a known Windows key',
    'il-010': 'obscure registry write - evidence low',
    'il-011': 'obscure registry write - evidence low',
    'il-012': 'informational guidance entry',
    'int-001': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'int-002': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'int-003': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'int-004': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'int-005': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'int-006': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'int-007': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'int-008': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'int-009': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'int-010': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'int-011': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'int-012': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'kbd-001': 'registry target is a known Windows key',
    'kbd-002': 'registry target is a known Windows key',
    'kbd-003': 'obscure registry write - evidence low',
    'kbd-004': 'obscure registry write - evidence low',
    'kbd-005': 'obscure registry write - evidence low',
    'kbd-006': 'obscure registry write - evidence low',
    'kbd-007': 'obscure registry write - evidence low',
    'kbd-008': 'informational guidance entry',
    'kbd-009': 'informational guidance entry',
    'kbd-010': 'informational guidance entry',
    'kbd-011': 'informational guidance entry',
    'kbd-012': 'informational guidance entry',
    'mon-001': 'verifiable via live system state',
    'mon-002': 'obscure registry write - evidence low',
    'mon-003': 'obscure registry write - evidence low',
    'mon-004': 'informational guidance entry',
    'mon-005': 'informational guidance entry',
    'mon-006': 'verifiable via live system state',
    'mon-007': 'informational guidance entry',
    'mon-008': 'informational guidance entry',
    'mon-009': 'informational guidance entry',
    'mon-010': 'informational guidance entry',
    'mon-011': 'informational guidance entry',
    'mon-012': 'informational guidance entry',
    'mon-013': 'informational guidance entry',
    'mon-014': 'obscure registry write - evidence low',
    'mouse-001': 'obscure registry write - evidence low',
    'mouse-002': 'obscure registry write - evidence low',
    'mouse-003': 'obscure registry write - evidence low',
    'mouse-004': 'registry target is a known Windows key',
    'mouse-005': 'informational guidance entry',
    'mouse-006': 'informational guidance entry',
    'mouse-007': 'informational guidance entry',
    'mouse-008': 'informational guidance entry',
    'mouse-009': 'obscure registry write - evidence low',
    'mouse-010': 'obscure registry write - evidence low',
    'mouse-011': 'informational guidance entry',
    'mouse-012': 'informational guidance entry',
    'net-001': 'obscure registry write - evidence low',
    'net-002': 'obscure registry write - evidence low',
    'net-003': 'obscure registry write - evidence low',
    'net-004': 'obscure registry write - evidence low',
    'net-005': 'obscure registry write - evidence low',
    'net-006': 'obscure registry write - evidence low',
    'net-007': 'registry target is a known Windows key',
    'net-008': 'obscure registry write - evidence low',
    'net-009': 'registry target is a known Windows key',
    'net-010': 'obscure registry write - evidence low',
    'net-011': 'obscure registry write - evidence low',
    'net-012': 'informational guidance entry',
    'net-013': 'obscure registry write - evidence low',
    'net-014': 'obscure registry write - evidence low',
    'net-015': 'obscure registry write - evidence low',
    'net-016': 'obscure registry write - evidence low',
    'nv-001': 'applies only to specific GPU/CPU vendor',
    'nv-002': 'applies only to specific GPU/CPU vendor',
    'nv-003': 'applies only to specific GPU/CPU vendor',
    'nv-004': 'applies only to specific GPU/CPU vendor',
    'nv-005': 'applies only to specific GPU/CPU vendor',
    'nv-006': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'nv-007': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'nv-008': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'nv-009': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'nv-010': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'nv-011': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'nv-012': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'nv-013': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'nv-014': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'nv-015': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'nv-016': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'power-001': 'obscure registry write - evidence low',
    'power-002': 'obscure registry write - evidence low',
    'power-003': 'obscure registry write - evidence low',
    'power-004': 'obscure registry write - evidence low',
    'power-005': 'obscure registry write - evidence low',
    'power-006': 'obscure registry write - evidence low',
    'power-007': 'obscure registry write - evidence low',
    'power-008': 'informational guidance entry',
    'power-009': 'obscure registry write - evidence low',
    'power-010': 'obscure registry write - evidence low',
    'power-011': 'obscure registry write - evidence low',
    'power-012': 'informational guidance entry',
    'power-013': 'informational guidance entry',
    'power-014': 'informational guidance entry',
    'pp-001': 'obscure registry write - evidence low',
    'pp-002': 'informational guidance entry',
    'pp-003': 'obscure registry write - evidence low',
    'pp-004': 'obscure registry write - evidence low',
    'pp-005': 'informational guidance entry',
    'pp-006': 'obscure registry write - evidence low',
    'pp-007': 'obscure registry write - evidence low',
    'pp-008': 'obscure registry write - evidence low',
    'pp-009': 'informational guidance entry',
    'pp-010': 'obscure registry write - evidence low',
    'pp-011': 'informational guidance entry',
    'pp-012': 'informational guidance entry',
    'pre-001': 'registry target is a known Windows key',
    'pre-002': 'registry target is a known Windows key',
    'pre-003': 'registry target is a known Windows key',
    'pre-004': 'obscure registry write - evidence low',
    'pre-005': 'registry target is a known Windows key',
    'pre-006': 'registry target is a known Windows key',
    'pre-007': 'obscure registry write - evidence low',
    'pre-008': 'informational guidance entry',
    'pre-009': 'registry target is a known Windows key',
    'priv-001': 'obscure registry write - evidence low',
    'priv-002': 'obscure registry write - evidence low',
    'priv-003': 'obscure registry write - evidence low',
    'priv-004': 'obscure registry write - evidence low',
    'priv-005': 'obscure registry write - evidence low',
    'priv-006': 'obscure registry write - evidence low',
    'priv-007': 'obscure registry write - evidence low',
    'priv-008': 'obscure registry write - evidence low',
    'priv-009': 'obscure registry write - evidence low',
    'priv-010': 'obscure registry write - evidence low',
    'priv-011': 'obscure registry write - evidence low',
    'priv-012': 'obscure registry write - evidence low',
    'ram-001': 'obscure registry write - evidence low',
    'ram-002': 'verifiable via live system state',
    'ram-003': 'verifiable via live system state',
    'ram-004': 'obscure registry write - evidence low',
    'ram-005': 'obscure registry write - evidence low',
    'ram-006': 'obscure registry write - evidence low',
    'ram-007': 'informational guidance entry',
    'ram-008': 'obscure registry write - evidence low',
    'ram-009': 'obscure registry write - evidence low',
    'ram-010': 'informational guidance entry',
    'ram-011': 'informational guidance entry',
    'ram-012': 'obscure registry write - evidence low',
    'ram-013': 'informational guidance entry',
    'ram-014': 'obscure registry write - evidence low',
    'ram-015': 'informational guidance entry',
    'ram-016': 'informational guidance entry',
    'reg-001': 'registry target is a known Windows key',
    'reg-002': 'obscure registry write - evidence low',
    'reg-003': 'obscure registry write - evidence low',
    'reg-004': 'registry target is a known Windows key',
    'reg-005': 'obscure registry write - evidence low',
    'reg-006': 'registry target is a known Windows key',
    'reg-007': 'obscure registry write - evidence low',
    'reg-008': 'obscure registry write - evidence low',
    'reg-009': 'obscure registry write - evidence low',
    'reg-010': 'obscure registry write - evidence low',
    'reg-011': 'obscure registry write - evidence low',
    'reg-012': 'registry target is a known Windows key',
    'reg-013': 'obscure registry write - evidence low',
    'reg-014': 'obscure registry write - evidence low',
    'reg-015': 'obscure registry write - evidence low',
    'reg-016': 'registry target is a known Windows key',
    'rep-001': 'obscure registry write - evidence low',
    'rep-002': 'obscure registry write - evidence low',
    'rep-003': 'obscure registry write - evidence low',
    'rep-004': 'obscure registry write - evidence low',
    'rep-005': 'informational guidance entry',
    'rep-006': 'informational guidance entry',
    'rep-007': 'obscure registry write - evidence low',
    'rep-008': 'obscure registry write - evidence low',
    'rep-009': 'obscure registry write - evidence low',
    'rep-010': 'informational guidance entry',
    'rep-011': 'informational guidance entry',
    'rep-012': 'informational guidance entry',
    'rep-013': 'obscure registry write - evidence low',
    'rep-014': 'obscure registry write - evidence low',
    'sched-001': 'obscure registry write - evidence low',
    'sched-002': 'obscure registry write - evidence low',
    'sched-003': 'obscure registry write - evidence low',
    'sched-004': 'informational guidance entry',
    'sched-005': 'informational guidance entry',
    'sched-006': 'obscure registry write - evidence low',
    'sched-007': 'obscure registry write - evidence low',
    'sched-008': 'obscure registry write - evidence low',
    'sched-009': 'informational guidance entry',
    'sched-010': 'informational guidance entry',
    'sched-011': 'informational guidance entry',
    'sched-012': 'obscure registry write - evidence low',
    'sec-001': 'obscure registry write - evidence low',
    'sec-002': 'obscure registry write - evidence low',
    'sec-003': 'informational guidance entry',
    'sec-004': 'informational guidance entry',
    'sec-005': 'informational guidance entry',
    'sec-006': 'informational guidance entry',
    'sec-007': 'informational guidance entry',
    'sec-008': 'obscure registry write - evidence low',
    'sec-009': 'obscure registry write - evidence low',
    'sec-010': 'informational guidance entry',
    'sec-011': 'obscure registry write - evidence low',
    'sec-012': 'informational guidance entry',
    'start-001': 'obscure registry write - evidence low',
    'start-002': 'informational guidance entry',
    'start-003': 'obscure registry write - evidence low',
    'start-004': 'obscure registry write - evidence low',
    'start-005': 'obscure registry write - evidence low',
    'start-006': 'informational guidance entry',
    'start-007': 'informational guidance entry',
    'start-008': 'informational guidance entry',
    'start-009': 'informational guidance entry',
    'start-010': 'informational guidance entry',
    'start-011': 'informational guidance entry',
    'start-012': 'informational guidance entry',
    'start-013': 'informational guidance entry',
    'start-014': 'informational guidance entry',
    'stor-001': 'obscure registry write - evidence low',
    'stor-002': 'obscure registry write - evidence low',
    'stor-003': 'registry target is a known Windows key',
    'stor-004': 'obscure registry write - evidence low',
    'stor-005': 'verifiable via live system state',
    'stor-006': 'verifiable via live system state',
    'stor-007': 'obscure registry write - evidence low',
    'stor-008': 'obscure registry write - evidence low',
    'stor-009': 'obscure registry write - evidence low',
    'stor-010': 'obscure registry write - evidence low',
    'stor-011': 'obscure registry write - evidence low',
    'stor-012': 'informational guidance entry',
    'stor-013': 'informational guidance entry',
    'stor-014': 'informational guidance entry',
    'svc-001': 'verifiable via live system state',
    'svc-002': 'verifiable via live system state',
    'svc-003': 'verifiable via live system state',
    'svc-004': 'verifiable via live system state',
    'svc-005': 'verifiable via live system state',
    'svc-006': 'verifiable via live system state',
    'svc-007': 'verifiable via live system state',
    'svc-008': 'informational guidance entry',
    'svc-009': 'verifiable via live system state',
    'svc-010': 'verifiable via live system state',
    'svc-011': 'verifiable via live system state',
    'svc-012': 'verifiable via live system state',
    'svc-013': 'verifiable via live system state',
    'svc-014': 'informational guidance entry',
    'svc-015': 'verifiable via live system state',
    'svc-016': 'verifiable via live system state',
    'sys-001': 'registry target is a known Windows key',
    'sys-002': 'registry target is a known Windows key',
    'sys-003': 'registry target is a known Windows key',
    'sys-004': 'obscure registry write - evidence low',
    'sys-005': 'obscure registry write - evidence low',
    'sys-006': 'obscure registry write - evidence low',
    'sys-007': 'registry target is a known Windows key',
    'sys-008': 'obscure registry write - evidence low',
    'sys-009': 'obscure registry write - evidence low',
    'sys-010': 'obscure registry write - evidence low',
    'sys-011': 'informational guidance entry',
    'sys-012': 'obscure registry write - evidence low',
    'sys-013': 'registry target is a known Windows key',
    'sys-014': 'obscure registry write - evidence low',
    'sys-015': 'registry target is a known Windows key',
    'sys-016': 'obscure registry write - evidence low',
    'sys-017': 'obscure registry write - evidence low',
    'sys-018': 'disables Spectre/Meltdown mitigations - serious security risk',
    'sys-019': 'obscure registry write - evidence low',
    'tel-001': 'obscure registry write - evidence low',
    'tel-002': 'verifiable via live system state',
    'tel-003': 'obscure registry write - evidence low',
    'tel-004': 'obscure registry write - evidence low',
    'tel-005': 'obscure registry write - evidence low',
    'tel-006': "targets dead Win10-era feature: 'cortana'",
    'tel-007': 'registry target is a known Windows key',
    'tel-008': 'obscure registry write - evidence low',
    'tel-009': 'verifiable via live system state',
    'tel-010': 'obscure registry write - evidence low',
    'tel-011': 'informational guidance entry',
    'tel-012': 'obscure registry write - evidence low',
    'tel-013': 'obscure registry write - evidence low',
    'tel-014': 'obscure registry write - evidence low',
    'tools-001': 'obscure registry write - evidence low',
    'tools-002': 'obscure registry write - evidence low',
    'tools-003': 'obscure registry write - evidence low',
    'tools-004': 'obscure registry write - evidence low',
    'tools-005': 'obscure registry write - evidence low',
    'tools-006': 'obscure registry write - evidence low',
    'tools-007': 'obscure registry write - evidence low',
    'tools-008': 'obscure registry write - evidence low',
    'tools-009': 'obscure registry write - evidence low',
    'tools-010': 'obscure registry write - evidence low',
    'tools-011': 'obscure registry write - evidence low',
    'tools-012': 'obscure registry write - evidence low',
    'tools-013': 'obscure registry write - evidence low',
    'tools-014': 'obscure registry write - evidence low',
    'usb-001': 'verifiable via live system state',
    'usb-002': 'obscure registry write - evidence low',
    'usb-003': 'obscure registry write - evidence low',
    'usb-004': 'obscure registry write - evidence low',
    'usb-005': 'informational guidance entry',
    'usb-006': 'informational guidance entry',
    'usb-007': 'informational guidance entry',
    'usb-008': 'informational guidance entry',
    'usb-009': 'informational guidance entry',
    'usb-010': 'informational guidance entry',
    'usb-011': 'informational guidance entry',
    'usb-012': 'obscure registry write - evidence low',
    'wgr-001': 'obscure registry write - evidence low',
    'wgr-002': 'obscure registry write - evidence low',
    'wgr-003': 'informational guidance entry',
    'wgr-004': 'informational guidance entry',
    'wgr-005': 'informational guidance entry',
    'wgr-006': 'obscure registry write - evidence low',
    'wgr-007': 'informational guidance entry',
    'wgr-008': 'informational guidance entry',
    'wgr-009': 'informational guidance entry',
    'wgr-010': 'informational guidance entry',
    'wgr-011': 'informational guidance entry',
    'wgr-012': 'informational guidance entry',
    'wifi-001': 'obscure registry write - evidence low',
    'wifi-002': 'obscure registry write - evidence low',
    'wifi-003': 'obscure registry write - evidence low',
    'wifi-004': 'obscure registry write - evidence low',
    'wifi-005': 'informational guidance entry',
    'wifi-006': 'informational guidance entry',
    'wifi-007': 'informational guidance entry',
    'wifi-008': 'obscure registry write - evidence low',
    'wifi-009': 'obscure registry write - evidence low',
    'wifi-010': 'obscure registry write - evidence low',
    'wifi-011': 'informational guidance entry',
    'wifi-012': 'obscure registry write - evidence low',
    'wifi-013': 'informational guidance entry',
    'wifi-014': 'informational guidance entry',
    'win-001': 'registry target is a known Windows key',
    'win-002': 'registry target is a known Windows key',
    'win-003': 'obscure registry write - evidence low',
    'win-004': 'obscure registry write - evidence low',
    'win-005': 'registry target is a known Windows key',
    'win-006': 'obscure registry write - evidence low',
    'win-007': 'registry target is a known Windows key',
    'win-008': 'obscure registry write - evidence low',
    'win-009': "targets dead Win10-era feature: 'tips and suggestions'",
    'win-010': 'obscure registry write - evidence low',
    'win-011': 'obscure registry write - evidence low',
    'win-012': 'obscure registry write - evidence low',
    'win-013': "targets dead Win10-era feature: 'cortana'",
    'win-014': 'registry target is a known Windows key',
    'win-015': 'obscure registry write - evidence low',
    'win-016': 'obscure registry write - evidence low',
    'win-017': 'obscure registry write - evidence low',
    'win-018': 'obscure registry write - evidence low',
}
