"""Tweak validation metadata + conflict detection + apply gating.

Every tweak carries a small validation record so the UI and Apply-All logic
can reason about correctness, not just execution success:

  status    VALID | INVALID | PLACEBO | OUTDATED | DUPLICATE | CONFLICTING |
            HARDWARE-SPECIFIC | UNKNOWN
  evidence  HIGH | MEDIUM | LOW | UNKNOWN
  target    CPU | GPU | RAM | STORAGE | NETWORK | INPUT | AUDIO | DISPLAY |
            WINDOWS | GAME | SERVICES | POWER | STARTUP | SECURITY |
            TELEMETRY | DEBLOAT | DIAGNOSTICS | BIOS | INFORMATIONAL
  verdict   SHIP | FIX | REMOVE | REVIEW

The per-tweak records live in :mod:`database.validation_data` (generated by
the audit script, ``_dev/audit_gen.py``) and are merged into every loaded
tweak dict by :func:`apply`.  Conflicts (two tweaks writing the same registry
value with different targets) are computed live from the action lists so the
data can never drift from the code.
"""
from __future__ import annotations

from collections import defaultdict

from .validation_data import OVERRIDES, NOTES

STATUSES = ("VALID", "INVALID", "PLACEBO", "OUTDATED", "DUPLICATE",
            "CONFLICTING", "HARDWARE-SPECIFIC", "UNKNOWN")
EVIDENCES = ("HIGH", "MEDIUM", "LOW", "UNKNOWN")
TARGETS = ("CPU", "GPU", "RAM", "STORAGE", "NETWORK", "INPUT", "AUDIO",
           "DISPLAY", "WINDOWS", "GAME", "SERVICES", "POWER", "STARTUP",
           "SECURITY", "TELEMETRY", "DEBLOAT", "DIAGNOSTICS", "BIOS",
           "INFORMATIONAL")
VERDICTS = ("SHIP", "FIX", "REMOVE", "REVIEW")

# Apply-All and per-card gating: which statuses block automatic application.
BLOCKED_STATUSES = {"INVALID", "PLACEBO", "OUTDATED", "CONFLICTING"}
# Conflicts are one-way flagged: when a conflicting tweak is applied, the
# other party is downgraded so Apply-All does not silently fight itself.
_CONFLICT_MARK = "CONFLICTING"


def _norm(v):
    if isinstance(v, bool):
        return v
    try:
        return int(v)
    except Exception:  # noqa: BLE001
        return str(v)


def _target(action) -> tuple:
    """Return (target_key, normalized_value) for an action, or (None, None).

    Target keys cover every *mutable* destination so that two tweaks fighting
    over the same setting are flagged regardless of how they express it:

      ("reg",   hive, path, name)   registry value
      ("svc",   service_name)       service start mode (sc / svc / start / stop)
      ("ini",   path, section, key) ini/game-config value
      ("power", setting, scheme)    power setting under a scheme
    """
    if not isinstance(action, (tuple, list)) or not action:
        return None, None
    kind = action[0]
    try:
        if kind == "reg" and len(action) >= 5:
            return (("reg", str(action[1]).lower(), str(action[2]).lower(),
                     str(action[3]).lower()), _norm(action[4]))
        if kind == "regdel" and len(action) >= 3:
            return (("reg", str(action[1]).lower(), str(action[2]).lower(),
                     str(action[3]).lower()), "<delete>")
        if kind == "sc" and len(action) >= 3:
            # ("sc", "disable"/"enable"/"start"/"stop", service)
            return (("svc", str(action[2]).lower()), str(action[1]).lower())
        if kind == "svc" and len(action) >= 3:
            # ("svc", service, "disabled"/"auto"/"demand"/...)
            return (("svc", str(action[1]).lower()), str(action[2]).lower())
        if kind in ("svcstart", "svcstop") and len(action) >= 2:
            return (("svc", str(action[1]).lower()), kind[3:].upper())
        if kind == "power" and len(action) >= 3:
            scheme = str(action[3]).lower() if len(action) > 3 else "AC"
            return (("power", str(action[1]).lower(), scheme), _norm(action[2]))
        if kind == "ini" and len(action) >= 5:
            return (("ini", str(action[1]).lower(), str(action[2]).lower(),
                     str(action[3]).lower()), _norm(action[4]))
        if kind == "inidel" and len(action) >= 4:
            return (("ini", str(action[1]).lower(), str(action[2]).lower(),
                     str(action[3]).lower()), "<delete>")
    except Exception:  # noqa: BLE001
        return None, None
    return None, None


def _conflicts(tweaks) -> dict:
    """Map tweak id -> [(other_id, target, reason)].

    Two tweaks conflict when they target the *same* mutable setting (registry
    value, service start mode, ini/game-config value, or power setting) but
    disagree on the target value — or when one writes it and the other deletes
    it. Same-value writes are not a conflict (idempotent, e.g. two tweaks that
    both disable the same service).
    """
    owner: dict = {}       # target -> (tweak_id, target_value_normalized)
    deletes: defaultdict = defaultdict(list)  # target -> [tweak_id]
    result: defaultdict = defaultdict(list)

    for t in tweaks:
        tid = t["id"]
        for a in t.get("actions", []):
            target, value = _target(a)
            if target is None:
                continue
            if value == "<delete>":
                deletes[target].append(tid)
                continue
            if target in owner:
                oid, ovalue = owner[target]
                if ovalue != value and oid != tid:
                    kind = _target_kind(target)
                    reason = (f"same {kind} set to {value!r} by {tid} and "
                              f"{ovalue!r} by {oid}")
                    result[tid].append((oid, target, reason))
                    result[oid].append((tid, target, reason))
            else:
                owner[target] = (tid, value)

    # A delete of a setting another tweak writes (or vice-versa) is a conflict.
    for target, deleters in deletes.items():
        if target in owner:
            owner_id, _ = owner[target]
            for d in deleters:
                if d != owner_id:
                    reason = "one tweak writes this setting, the other deletes it"
                    result[d].append((owner_id, target, reason))
                    result[owner_id].append((d, target, reason))
        elif len(deletes[target]) > 1:
            for a in deletes[target]:
                for b in deletes[target]:
                    if a < b:
                        reason = "two tweaks delete the same setting"
                        result[a].append((b, target, reason))
                        result[b].append((a, target, reason))
    return dict(result)


def _target_kind(target: tuple) -> str:
    return {
        "reg": "registry value",
        "svc": "service setting",
        "ini": "game/config file value",
        "power": "power setting",
    }.get(target[0], "setting")


def apply(tweaks: list[dict]) -> None:
    """Merge validation metadata into every loaded tweak dict (in place)."""
    conflicts = _conflicts(tweaks)
    for t in tweaks:
        tid = t["id"]
        rec = OVERRIDES.get(tid, {})
        t["status"] = str(rec.get("status") or t.get("status") or "UNKNOWN")
        t["evidence"] = str(rec.get("evidence") or t.get("evidence") or "UNKNOWN")
        t["target"] = str(rec.get("target") or t.get("target") or "WINDOWS")
        t["verdict"] = str(rec.get("verdict") or t.get("verdict") or "REVIEW")
        t["validation_note"] = rec.get("note") or NOTES.get(tid) or ""
        if conflicts.get(tid):
            t["status"] = _CONFLICT_MARK
            t["validation_note"] = ("Conflicts with: " +
                                    ", ".join(oid for oid, _, _ in conflicts[tid]))
        t["conflicts"] = [{"with": oid, "target": _fmt_target(target), "reason": reason}
                          for oid, target, reason in conflicts.get(tid, [])]


def _fmt_target(target: tuple) -> str:
    kind = target[0]
    if kind == "reg" and len(target) == 4:
        return f"{target[1].upper()}\\{target[2]}\\{target[3]}"
    if kind == "svc" and len(target) == 2:
        return f"service '{target[1]}'"
    if kind == "ini" and len(target) == 4:
        return f"{target[1]} [{target[2]}] {target[3]}"
    if kind == "power" and len(target) == 3:
        return f"power '{target[1]}' ({target[2]})"
    return "\\".join(str(x) for x in target)


def conflicts_for(tweak_id: str) -> list[dict]:
    """Return the conflict records attached to a tweak (empty when none)."""
    from . import BY_ID  # deferred to avoid import cycle at module scope
    t = BY_ID.get(tweak_id)
    return list((t or {}).get("conflicts", []))


def gate(tweak: dict) -> tuple[bool, str]:
    """Can this tweak be applied automatically right now?

    Returns (allowed, reason).  Placebos, invalid and outdated tweaks are
    blocked from one-click Apply-All but remain visible (with a label) so the
    user can still inspect or force them.
    """
    status = tweak.get("status", "UNKNOWN")
    if status in BLOCKED_STATUSES:
        return False, f"Status {status.lower()}: {tweak.get('validation_note') or 'not safe to auto-apply'}"
    return True, ""


def report(tweaks: list[dict]) -> dict:
    """Summary counts grouped by status / verdict / evidence / target."""
    by_status: dict = defaultdict(int)
    by_verdict: dict = defaultdict(int)
    by_evidence: dict = defaultdict(int)
    by_target: dict = defaultdict(int)
    for t in tweaks:
        by_status[t.get("status", "UNKNOWN")] += 1
        by_verdict[t.get("verdict", "REVIEW")] += 1
        by_evidence[t.get("evidence", "UNKNOWN")] += 1
        by_target[t.get("target", "WINDOWS")] += 1
    return {
        "total": len(tweaks),
        "by_status": dict(by_status),
        "by_verdict": dict(by_verdict),
        "by_evidence": dict(by_evidence),
        "by_target": dict(by_target),
    }
