"""Tweak validation metadata + conflict detection + apply gating.

Every tweak carries a small validation record so the UI and Apply-All logic
can reason about correctness, not just execution success:

  status    VALID | INVALID | PLACEBO | OUTDATED | DUPLICATE | CONFLICTING |
            HARDWARE-SPECIFIC | UNKNOWN
  evidence  HIGH | MEDIUM | LOW | UNKNOWN
  target    CPU | GPU | RAM | STORAGE | NETWORK | INPUT | AUDIO | DISPLAY |
            WINDOWS | GAME | SERVICES | POWER | STARTUP | SECURITY |
            TELEMETRY | DEBLOAT | DIAGNOSTICS | BIOS | INFORMATIONAL
  verdict   SHIP | FIX | REMOVE | REVIEW

The per-tweak records live in :mod:`database.validation_data` (generated by
the audit script, ``_dev/audit_gen.py``) and are merged into every loaded
tweak dict by :func:`apply`.  Conflicts (two tweaks writing the same registry
value with different targets) are computed live from the action lists so the
data can never drift from the code.
"""
from __future__ import annotations

from collections import defaultdict

from .validation_data import OVERRIDES, NOTES

STATUSES = ("VALID", "INVALID", "PLACEBO", "OUTDATED", "DUPLICATE",
            "CONFLICTING", "HARDWARE-SPECIFIC", "UNKNOWN")
EVIDENCES = ("HIGH", "MEDIUM", "LOW", "UNKNOWN")
TARGETS = ("CPU", "GPU", "RAM", "STORAGE", "NETWORK", "INPUT", "AUDIO",
           "DISPLAY", "WINDOWS", "GAME", "SERVICES", "POWER", "STARTUP",
           "SECURITY", "TELEMETRY", "DEBLOAT", "DIAGNOSTICS", "BIOS",
           "INFORMATIONAL")
VERDICTS = ("SHIP", "FIX", "REMOVE", "REVIEW")

# Apply-All and per-card gating: which statuses block automatic application.
BLOCKED_STATUSES = {"INVALID", "PLACEBO", "OUTDATED", "CONFLICTING"}
# Conflicts are one-way flagged: when a conflicting tweak is applied, the
# other party is downgraded so Apply-All does not silently fight itself.
_CONFLICT_MARK = "CONFLICTING"


def _reg_key(action) -> tuple | None:
    """Registry target (hive, path, value) for an action, lowercased."""
    if not isinstance(action, (tuple, list)) or not action:
        return None
    kind = action[0]
    if kind in ("reg",):
        try:
            return (str(action[1]).lower(), str(action[2]).lower(),
                    str(action[3]).lower())
        except Exception:  # noqa: BLE001
            return None
    if kind in ("regdel",):
        try:
            return (str(action[1]).lower(), str(action[2]).lower(),
                    str(action[3]).lower())
        except Exception:  # noqa: BLE001
            return None
    return None


def _conflicts(tweaks) -> dict:
    """Map tweak id -> [(other_id, target, reason)].

    Two tweaks conflict when they write the *same* registry value but their
    action tuples disagree on the target value (or one writes while the other
    deletes it).
    """
    owner: dict = {}       # target -> (tweak_id, target_value_normalized)
    deletes: defaultdict = defaultdict(list)  # target -> [tweak_id]
    result: defaultdict = defaultdict(list)

    def norm(v):
        if isinstance(v, bool):
            return v
        try:
            return int(v)
        except Exception:  # noqa: BLE001
            return str(v)

    for t in tweaks:
        tid = t["id"]
        for a in t.get("actions", []):
            target = _reg_key(a)
            if not target:
                continue
            if a[0] == "reg":
                value = norm(a[4])
                if target in owner:
                    oid, ovalue = owner[target]
                    if ovalue != value and oid != tid:
                        reason = f"same registry value set to {value!r} by {tid} and {ovalue!r} by {oid}"
                        result[tid].append((oid, target, reason))
                        result[oid].append((tid, target, reason))
                else:
                    owner[target] = (tid, value)
            elif a[0] == "regdel":
                deletes[target].append(tid)

    # A delete of a value another tweak writes (or vice-versa) is a conflict.
    for target, deleters in deletes.items():
        if target in owner:
            owner_id, _ = owner[target]
            for d in deleters:
                if d != owner_id:
                    reason = "one tweak writes this value, the other deletes it"
                    result[d].append((owner_id, target, reason))
                    result[owner_id].append((d, target, reason))
        elif len(deletes[target]) > 1:
            for a in deletes[target]:
                for b in deletes[target]:
                    if a < b:
                        reason = "two tweaks delete the same registry value"
                        result[a].append((b, target, reason))
                        result[b].append((a, target, reason))
    return dict(result)


def apply(tweaks: list[dict]) -> None:
    """Merge validation metadata into every loaded tweak dict (in place)."""
    conflicts = _conflicts(tweaks)
    for t in tweaks:
        tid = t["id"]
        rec = OVERRIDES.get(tid, {})
        t["status"] = str(rec.get("status") or t.get("status") or "UNKNOWN")
        t["evidence"] = str(rec.get("evidence") or t.get("evidence") or "UNKNOWN")
        t["target"] = str(rec.get("target") or t.get("target") or "WINDOWS")
        t["verdict"] = str(rec.get("verdict") or t.get("verdict") or "REVIEW")
        t["validation_note"] = rec.get("note") or NOTES.get(tid) or ""
        if conflicts.get(tid):
            t["status"] = _CONFLICT_MARK
            t["validation_note"] = ("Conflicts with: " +
                                    ", ".join(oid for oid, _, _ in conflicts[tid]))
        t["conflicts"] = [{"with": oid, "target": _fmt_target(target), "reason": reason}
                          for oid, target, reason in conflicts.get(tid, [])]


def _fmt_target(target: tuple) -> str:
    if len(target) == 3:
        hive, path, name = target
        return f"{hive.upper()}\\{path}\\{name}"
    return "\\".join(str(x) for x in target)


def conflicts_for(tweak_id: str) -> list[dict]:
    """Return the conflict records attached to a tweak (empty when none)."""
    from . import BY_ID  # deferred to avoid import cycle at module scope
    t = BY_ID.get(tweak_id)
    return list((t or {}).get("conflicts", []))


def gate(tweak: dict) -> tuple[bool, str]:
    """Can this tweak be applied automatically right now?

    Returns (allowed, reason).  Placebos, invalid and outdated tweaks are
    blocked from one-click Apply-All but remain visible (with a label) so the
    user can still inspect or force them.
    """
    status = tweak.get("status", "UNKNOWN")
    if status in BLOCKED_STATUSES:
        return False, f"Status {status.lower()}: {tweak.get('validation_note') or 'not safe to auto-apply'}"
    return True, ""


def report(tweaks: list[dict]) -> dict:
    """Summary counts grouped by status / verdict / evidence / target."""
    by_status: dict = defaultdict(int)
    by_verdict: dict = defaultdict(int)
    by_evidence: dict = defaultdict(int)
    by_target: dict = defaultdict(int)
    for t in tweaks:
        by_status[t.get("status", "UNKNOWN")] += 1
        by_verdict[t.get("verdict", "REVIEW")] += 1
        by_evidence[t.get("evidence", "UNKNOWN")] += 1
        by_target[t.get("target", "WINDOWS")] += 1
    return {
        "total": len(tweaks),
        "by_status": dict(by_status),
        "by_verdict": dict(by_verdict),
        "by_evidence": dict(by_evidence),
        "by_target": dict(by_target),
    }
